(function(C,root){
  'use strict';
  // Pure, bounded authoring helpers. No clock, canvas or listener lives here.
  var S=C.studioScenes,copy=S.clone;
  var easings=['linear','step','ease-in','ease-out','ease-in-out','cubic-in','cubic-out','cubic-in-out','back','elastic','bounce','spring','bezier'];
  function bezier(t,h){h=h||[.25,.1,.25,1];function curve(x,a,b){return 3*(1-x)*(1-x)*x*a+3*(1-x)*x*x*b+x*x*x;}var lo=0,hi=1;for(var i=0;i<24;i++){var mid=(lo+hi)/2;if(curve(mid,h[0],h[2])<t)lo=mid;else hi=mid;}return curve((lo+hi)/2,h[1],h[3]);}
  function ease(t,kind,handles){t=Math.max(0,Math.min(1,t));if(t===0||t===1)return t;switch(kind){case 'linear':return t;case 'step':return 0;case 'ease-in':return t*t;case 'ease-out':return 1-(1-t)*(1-t);case 'cubic-in':return t*t*t;case 'cubic-out':return 1-Math.pow(1-t,3);case 'cubic-in-out':return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;case 'back':return 1+2.70158*Math.pow(t-1,3)+1.70158*Math.pow(t-1,2);case 'elastic':return Math.pow(2,-10*t)*Math.sin((t*10-.75)*2*Math.PI/3)+1;case 'bounce':var n=7.5625,d=2.75;if(t<1/d)return n*t*t;if(t<2/d){t-=1.5/d;return n*t*t+.75;}if(t<2.5/d){t-=2.25/d;return n*t*t+.9375;}t-=2.625/d;return n*t*t+.984375;case 'spring':var f=function(x){return 1-Math.exp(-6*x)*Math.cos(10*x);};return f(t)/f(1);case 'bezier':return bezier(t,handles);default:return t*t*(3-2*t);}}
  function mix(a,b,t){if(Array.isArray(a)&&Array.isArray(b))return a.map(function(v,i){return v+(b[i]-v)*t;});return typeof a==='number'&&typeof b==='number'?a+(b-a)*t:t>=1?copy(b):copy(a);}
  function value(keys,time,base,light){if(!keys.length)return copy(base);var a=keys[0],b=a;for(var i=0;i<keys.length;i++){if(time===keys[i].time)return copy(keys[i].value);if(keys[i].time<time)a=keys[i];if(keys[i].time>time){b=keys[i];break;}b=a;}if(a===b||time<a.time)return copy(a.value);var kind=light?'ease-in-out':b.easing,p=ease((time-a.time)/(b.time-a.time),kind,b.bezier);return mix(a.value,b.value,p);}
  function object(scene,id){return S.objects(scene).concat(scene.animation.cameras||[],scene.animation.titles||[]).find(function(o){return o.id===id;});}
  function properties(scene,o){if(!o)return [];var p;if(o===scene.card)p=['position','tilt','rotationZ','scale','side','visible'];else if(o===scene.camera||scene.animation.cameras.indexOf(o)>=0)p=['position','rotation','yaw','pitch','distance','target','fov','roll','focus','focusDistance','aperture','orthoScale'];else if(o===scene.post)p=['exposure','contrast','saturation','temperature','tint','lift','gamma','gain','bloom','halation','vignette','grain','aberration','flare','tiltShift'];else if(o===scene.backdrop)p=['color'];else if(scene.animation.titles.indexOf(o)>=0)p=['position','opacity','size','visible'];else if(scene.groups.indexOf(o)>=0)p=['position','rotation','scale'];else if(scene.lights.indexOf(o)>=0)p=['position','rotation','intensity','color','bottom','size','angle','falloff','softness','shadowSoftness','visible'];else p=['position','rotation','scale','color','gradient','density','speed','visible'];return p;}
  function baseValue(scene,o,property){if(property==='focusDistance'){var basis=C.studioCamera.basis(o),eye=o.position||basis.back.map(function(v,i){return o.target[i]+v*o.distance;});return o.focusDistance==null?Math.max(.05,C.studioCamera.dot(eye.map(function(v,i){return v-o.focus[i];}),basis.back)):o.focusDistance;}if(property==='position'&&(o===scene.camera||scene.animation.cameras.indexOf(o)>=0))return o.position||C.studioCamera.basis(o).back.map(function(v,i){return o.target[i]+v*o.distance;});if(property==='rotation'&&(o===scene.camera||scene.animation.cameras.indexOf(o)>=0))return o.rotation||[o.pitch,o.yaw,o.roll];return o[property];}
  function group(scene,target){var o=object(scene,target);return !o?'Props':o===scene.camera||scene.animation.cameras.indexOf(o)>=0?'Camera':o===scene.card?'Card':scene.lights.indexOf(o)>=0?'Lights':o===scene.post?'Look':scene.animation.titles.indexOf(o)>=0?'Titles':o===scene.backdrop||C.studioProps.isEffect(o)?'FX':'Props';}
  function keyCount(scene){return scene.keyframes.length+scene.animation.tracks.reduce(function(n,t){return n+t.keys.length;},0);}
  function upsert(scene,target,property,time,v){var o=object(scene,target);if(!o||S.locked(scene,o)||properties(scene,o).indexOf(property)<0)throw Error('Choose an unlocked, animatable property.');if(v===undefined||v===null||Array.isArray(v)&&v.some(function(n){return !Number.isFinite(n);})||typeof v==='number'&&!Number.isFinite(v))throw Error('A finite property value is required.');var a=scene.animation,time=Math.max(0,Math.min(scene.director.duration,S.snap(time,1/a.fps))),track=a.tracks.find(function(t){return t.target===target&&t.property===property;});if(!track){if(a.tracks.length>=256)throw Error('Track limit reached: 256.');track={id:'track-'+root.crypto.randomUUID(),target:target,property:property,enabled:true,keys:[]};a.tracks.push(track);}var k=track.keys.find(function(k){return Math.abs(k.time-time)<.5/a.fps;});if(!k){if(track.keys.length>=96||keyCount(scene)>=1024)throw Error('Key limit reached.');k={id:'key-'+root.crypto.randomUUID(),time:time,easing:'ease-in-out',bezier:[.25,.1,.25,1]};track.keys.push(k);}k.value=copy(v);track.keys.sort(function(a,b){return a.time-b.time;});return {track:track,key:k};}
  function autoKey(scene,before,time){var edits=[];S.objects(scene).concat(scene.animation.cameras,scene.animation.titles).forEach(function(o){var old=object(before,o.id);if(!old||S.locked(scene,o))return;properties(scene,o).forEach(function(p){if((o===scene.camera||scene.animation.cameras.indexOf(o)>=0)&&(p==='position'||p==='rotation'||p==='focusDistance')&&o[p]===null&&old[p]===null)return;var a=baseValue(before,old,p),b=baseValue(scene,o,p);if(a!==undefined&&b!==undefined&&JSON.stringify(a)!==JSON.stringify(b))edits.push({o:o,p:p,a:a,b:b});});});var authored=copy(scene.animation.tracks);try{edits.forEach(function(e){var track=scene.animation.tracks.find(function(t){return t.target===e.o.id&&t.property===e.p;});if(time>0&&(!track||!track.keys.length))upsert(scene,e.o.id,e.p,0,e.a);upsert(scene,e.o.id,e.p,time,e.b);});return edits.length;}catch(error){scene.animation.tracks=authored;throw error;}}
  function editable(scene,t){var o=object(scene,t.target);return o&&!S.locked(scene,o);}
  function migratePoses(scene){scene.keyframes.forEach(function(f){var o=object(scene,f.target),data=f.camera||f.light;if(!o||!data)return;properties(scene,o).forEach(function(p){if(data[p]!==undefined&&data[p]!==null){var result=upsert(scene,o.id,p,f.time,data[p]);result.key.easing=f.easing;result.key.bezier=f.bezier||[.25,.1,.25,1];}});});scene.keyframes=[];return scene;}
  function refs(scene,ids){var set=new Set(ids);return scene.animation.tracks.flatMap(function(t){return t.keys.filter(function(k){return set.has(k.id);}).map(function(k){return {track:t,key:k};});});}
  function retime(scene,ids,offset,scale,pivot){var all=refs(scene,ids).filter(function(r){return editable(scene,r.track);});if(!all.length)return;var a=scene.animation,lo=Math.min.apply(Math,all.map(function(r){return r.key.time;})),hi=Math.max.apply(Math,all.map(function(r){return r.key.time;}));scale=Math.max(.1,Math.min(10,scale||1));pivot=pivot==null?lo:pivot;var times=all.map(function(r){return pivot+(r.key.time-pivot)*scale+(offset||0);});if(Math.min.apply(Math,times)<0||Math.max.apply(Math,times)>scene.director.duration)throw Error('Selected keys would leave the timeline.');all.forEach(function(r,i){r.key.time=Math.max(0,Math.min(scene.director.duration,S.snap(times[i],1/a.fps)));});a.tracks.forEach(function(t){t.keys.sort(function(a,b){return a.time-b.time;});});}
  function loop(scene,ids){var set=new Set(ids),area=scene.animation.workArea;scene.animation.tracks.filter(function(t){return !ids.length||t.keys.some(function(k){return set.has(k.id);});}).forEach(function(t){if(!editable(scene,t)||!t.keys.length)return;var v=value(t.keys,area.in,baseValue(scene,object(scene,t.target),t.property));upsert(scene,t.target,t.property,area.in,v);upsert(scene,t.target,t.property,area.out,v);});}
  function clamp(o,p,v){var ranges={position:[-20,20],target:[-10,10],focus:[-20,20],scale:[.05,6],distance:[1.3,9],focusDistance:[.05,30],fov:[15,90],pitch:[-Math.PI/2,Math.PI/2],aperture:[0,10],orthoScale:[.2,20],intensity:[0,20],color:[0,1],bottom:[0,1],gradient:[0,1],size:[.02,4],angle:[5,120],falloff:[0,4],softness:[0,1],shadowSoftness:[0,1],density:[.05,1],speed:[.1,5],opacity:[0,1],bloom:[0,1],halation:[0,1],vignette:[0,1],grain:[0,.3],aberration:[0,1],flare:[0,1],tiltShift:[0,1],exposure:[-2,2],contrast:[.25,2],saturation:[0,2],temperature:[-1,1],tint:[-1,1],lift:[-.2,.2],gamma:[.5,2],gain:[.5,2]};var r=ranges[p];if(o.font){if(p==='position')r=[0,1];if(p==='size')r=[.01,.15];}function n(x){return Number.isFinite(x)?r?Math.max(r[0],Math.min(r[1],x)):x:0;}return Array.isArray(v)?v.map(n):typeof v==='number'?n(v):copy(v);}
  function sample(scene,next,time){next.animation=Object.assign({},scene.animation,{cameras:scene.animation.cameras.map(copy),titles:scene.animation.titles.map(copy)});next.groups=scene.groups.map(copy);var visibilityFactors=new Map(),sampledObjects=new Map(S.objects(next).concat(next.animation.cameras,next.animation.titles).map(function(o){return [o.id,o];}));scene.animation.tracks.forEach(function(t){if(!t.enabled||!t.keys.length)return;var o=sampledObjects.get(t.target);if(!o||properties(next,o).indexOf(t.property)<0)return;var base=baseValue(next,o,t.property),isLight=next.lights.indexOf(o)>=0,keys=t.keys;if(base===undefined)return;var valid=keys.every(function(k){return Array.isArray(base)?Array.isArray(k.value)&&k.value.length===base.length:typeof k.value===typeof base;});if(!valid)return;if(isLight){var gap=(C.cutscenes.profile()==='full'?.24:.6)*scene.animation.speed,last=-100;keys=keys.filter(function(k){if(k.time-last<gap)return false;last=k.time;return true;});}var visibility=isLight&&t.property==='visible';if(visibility)keys=keys.map(function(k){return Object.assign({},k,{value:k.value?1:0});});var area=scene.animation.workArea,span=area.out-area.in,lightTime=isLight&&!C.motion.reduced&&scene.director.repeat!=='once'&&span<gap?area.in:time,closure=Math.min(.8,span/2),v=value(keys,lightTime,visibility?(base?1:0):base,isLight);if(isLight&&scene.director.repeat==='loop'&&closure>0&&lightTime>area.out-closure)v=mix(v,value(keys,area.in,base,true),ease((lightTime-area.out+closure)/closure,'ease-in-out'));if(visibility){o.visible=v>.001;visibilityFactors.set(o.id,Math.max(0,Math.min(1,v)));}else o[t.property]=clamp(o,t.property,v);if(o===next.camera||next.animation.cameras.indexOf(o)>=0)o.autoFrame=false;});
    next.lights.forEach(function(l){if(visibilityFactors.has(l.id))l.intensity*=visibilityFactors.get(l.id);});
    // Groups remain world-space containers: apply only their animated delta once.
    var byId=new Map(next.groups.map(function(g){return [g.id,g];}));[next.card].concat(next.lights,next.props).forEach(function(o){var parent=o.parentId,seen=new Set();while(parent&&!seen.has(parent)){seen.add(parent);var g=byId.get(parent),base=scene.groups.find(function(x){return x.id===parent;});if(!g||!base)break;var delta=g.rotation.map(function(v,i){return v-base.rotation[i];}),factors=g.scale.map(function(v,i){return v/base.scale[i];}),m=C.studioProps.model(g.position,delta,factors),p=o.position.map(function(v,i){return v-base.position[i];});o.position=C.studioCamera.transform(m,p).slice(0,3);if(o.scale)o.scale=o.scale.map(function(v,i){return Math.max(.05,Math.min(6,v*factors[i]));});if(o===next.card){o.tilt=o.tilt.map(function(v,i){return v+delta[i];});o.rotationZ+=delta[2];}else o.rotation=o.rotation.map(function(v,i){return v+delta[i];});parent=g.parentId;}});
    function camera(c){if(c.shake&&c.shake.amount)c.autoFrame=false;if(c.position){var d=c.position.map(function(v,i){return v-c.target[i];});c.distance=Math.max(.05,Math.hypot.apply(Math,d));c.yaw=Math.atan2(d[0],d[2]);c.pitch=Math.asin(Math.max(-1,Math.min(1,d[1]/c.distance)));}if(c.rotation){c.pitch=c.rotation[0];c.yaw=c.rotation[1];c.roll=c.rotation[2];if(c.position){var b=C.studioCamera.basis(c);c.target=c.position.map(function(v,i){return v-b.back[i]*c.distance;});}}if(c.focusDistance!=null){var basis=C.studioCamera.basis(c),eye=c.position||basis.back.map(function(v,i){return c.target[i]+v*c.distance;});c.focus=eye.map(function(v,i){return v-basis.back[i]*c.focusDistance;});}return c;}camera(next.camera);next.animation.cameras.forEach(camera);return next;
  }
  function shake(c,time){var sh=c.shake;if(!sh||!sh.amount||C.motion.reduced)return c;var seed=String(sh.seed).split('').reduce(function(n,c){return (n*31+c.charCodeAt(0))>>>0;},17),t=time*sh.frequency;function wave(i){return Math.sin(t*1.37+i+seed%37)*.65+Math.sin(t*.71+i*2+seed%19)*.35;}c.yaw+=wave(1)*sh.amount*.02;c.pitch+=wave(2)*sh.amount*.016;c.roll+=wave(3)*sh.amount*.007;c.target=c.target.map(function(v,i){return v+wave(i+4)*sh.amount*.012;});return c;}
  function shots(scene,time){var shots=scene.animation.shots.slice().sort(function(a,b){return a.start-b.start;}),current=null,previous=null;shots.forEach(function(s){if(time>=s.start&&time<s.start+s.duration){previous=current;current=s;}else if(time>=s.start+s.duration&&!current)previous=s;});if(!current)return {camera:shake(copy(scene.camera),time),black:0};var index=shots.indexOf(current);previous=index>0?shots[index-1]:null;function cam(s){return shake(copy(!s||s.cameraId==='camera'?scene.camera:scene.animation.cameras.find(function(c){return c.id===s.cameraId;})||scene.camera),time);}var to=cam(current),from=cam(previous),span=Math.min(current.blend||.4,current.duration/2),k=Math.max(0,Math.min(1,(time-current.start)/Math.max(.01,span))),transition=current.transition;if(!previous||transition==='cut'||k>=1)return {camera:to,black:0};if(transition==='dissolve')return {camera:to,from:from,blend:ease(k,'ease-in-out'),black:0};if(transition==='dip')return {camera:k<.5?from:to,black:1-Math.abs(2*k-1)};var c=k<.5?from:to;c.yaw+=(k<.5?1:-1)*Math.sin(k*Math.PI)*.35;return {camera:c,black:0};}
  var titles=[['Lower Third',[.12,.8],.033,'left','Inter','name'],['Name Plate',[.5,.82],.036,'center','Inter','name'],['Museum Label',[.12,.84],.025,'left','Inter','tier'],['Minimal Caption',[.5,.9],.026,'center','Inter','name'],['Big Reveal',[.5,.5],.072,'center','Inter','name'],['Serial Stamp',[.83,.12],.02,'right','JetBrains Mono','serial'],['Variant Banner',[.5,.13],.026,'center','JetBrains Mono','variant'],['Credits',[.5,.78],.03,'center','Inter','custom']];
  function addTitle(scene,name,identity,time){if(scene.animation.titles.length>=16)throw Error('Title limit reached: 16.');var p=titles.find(function(p){return p[0]===name;})||titles[0],text=p[5]==='serial'?identity.serial:p[5]==='tier'?identity.name+'\n'+identity.tier:p[5]==='variant'?identity.variant||'Original finish':p[5]==='custom'?'Directed in Cardable':identity.name,t={id:'title-'+root.crypto.randomUUID(),preset:p[0],text:text,font:p[4],position:p[1].slice(),opacity:1,size:p[2],align:p[3],visible:true,locked:false,start:Math.min(time,scene.director.duration-.01),duration:Math.max(.01,Math.min(3,scene.director.duration-time)),fade:.35};scene.animation.titles.push(t);return t;}
  function titlePose(t,time){var duration=t.duration,age=time-t.start,fade=Math.min(t.fade||0,duration/2),alpha=t.visible&&age>=0&&age<=duration?t.opacity*(fade?Math.min(1,age/fade,(duration-age)/fade):1):0;return {alpha:Math.max(0,alpha),y:t.position[1]+(!C.motion.reduced?.018*(1-Math.min(1,Math.max(0,age)/Math.max(.01,fade))):0)};}
  C.studioAnimation={easings:easings,ease:ease,mix:mix,value:value,object:object,properties:properties,baseValue:baseValue,group:group,keyCount:keyCount,upsert:upsert,autoKey:autoKey,migratePoses:migratePoses,refs:refs,retime:retime,loop:loop,sample:sample,shots:shots,titles:titles,addTitle:addTitle,titlePose:titlePose,editable:editable};
})(window.Cardable,window);
