(function(C,root){
  'use strict';
  function ease(t,kind){t=Math.max(0,Math.min(1,t));return kind==='ease-in'?t*t:kind==='ease-out'?1-(1-t)*(1-t):kind==='linear'?t:t*t*(3-2*t);}
  function mix(a,b,t){if(Array.isArray(a))return a.map(function(v,i){return v+(b[i]-v)*t;});return a+(b-a)*t;}
  function pose(frames,time,kind,base){if(!frames.length)return base;frames=frames.slice().sort(function(a,b){return a.time-b.time;});var a=frames[0],b=a;for(var i=0;i<frames.length;i++){if(frames[i].time<=time)a=frames[i];if(frames[i].time>=time){b=frames[i];break;}b=a;}var p=b.time>a.time?ease((time-a.time)/(b.time-a.time),b.easing):0,result=C.studioScenes.clone(a[kind]);Object.keys(result).forEach(function(k){if(typeof result[k]==='number'||Array.isArray(result[k]))result[k]=mix(a[kind][k],b[kind][k],p);});return result;}
  function sample(scene,time,turn,preview){
    // Render copies omit authored tracks: never clone 96 keyframes per frame.
    var next=Object.assign({},scene,{card:C.studioScenes.clone(scene.card),camera:C.studioScenes.clone(scene.camera),lights:scene.lights.map(C.studioScenes.clone),props:scene.props.map(C.studioScenes.clone),post:C.studioScenes.clone(scene.post),keyframes:[]}),d=scene.director||{duration:8,repeat:'once'},frames=scene.keyframes||[];time=Math.max(0,Math.min(d.duration,time||0));
    if(preview!==false&&frames.length){next.camera=Object.assign({},next.camera,pose(frames.filter(function(f){return f.track==='camera';}),time,'camera',next.camera));
      next.lights.forEach(function(l){var all=frames.filter(function(f){return f.track==='light'&&f.target===l.id;}).sort(function(a,b){return a.time-b.time;}),gap=C.cutscenes.profile()==='full'?.24:.6,track=[];all.forEach(function(f){if(!track.length||f.time-track[track.length-1].time>=gap)track.push(f);});var value=pose(track,time,'light',l);
        // Loop closure is a soft ramp too, even with different authored endpoints.
        if(d.repeat==='loop'&&track.length&&time>d.duration-.8){var start=track[0].light,k=ease((time-d.duration+.8)/.8,'ease-in-out');['position','intensity','color'].forEach(function(key){value[key]=mix(value[key],start[key],k);});}
        ['position','intensity','color'].forEach(function(key){l[key]=C.studioScenes.clone(value[key]);});
      });
    }
    if(preview!==false&&scene.animation)scene.animation.tracks.forEach(function(track){if(!track.enabled||!track.keys.length)return;var object=[next.card,next.camera,next.post].concat(next.lights,next.props).find(function(o){return o.id===track.target;});if(!object)return;var allowed=object===next.card?['tilt','position','scale','rotationZ']:object===next.camera?['yaw','pitch','distance','fov','roll','target','focus','aperture']:object===next.post?['exposure','bloom','contrast','saturation','temperature','tint','lift','gamma','gain','halation','vignette','grain','aberration','flare']:object.scale?['position','rotation','scale']:['position','intensity','color','size','angle'];if(allowed.indexOf(track.property)<0)return;var keys=track.keys,base=object[track.property];if(base===undefined)return;if(next.lights.indexOf(object)>=0){var gap=C.cutscenes.profile()==='full'?.24:.6,last=-100;keys=keys.filter(function(k){if(k.time-last<gap)return false;last=k.time;return true;});}var values=keys.filter(function(k){return Array.isArray(base)?Array.isArray(k.value)&&k.value.length===base.length:typeof k.value==='number';}).map(function(k){return {time:k.time,easing:k.easing,value:{channel:k.value}};});if(!values.length)return;var value=pose(values,time,'value',{channel:base}).channel,range=track.property==='scale'?[.05,6]:track.property==='distance'?[1.3,9]:track.property==='fov'?[15,90]:track.property==='intensity'?[0,20]:track.property==='bloom'||track.property==='halation'||track.property==='vignette'||track.property==='color'?[0,1]:track.property==='grain'?[0,.3]:track.property==='contrast'?[.25,2]:track.property==='saturation'?[0,2]:track.property==='temperature'||track.property==='tint'?[-1,1]:track.property==='exposure'?[-2,2]:track.property==='aperture'?[0,10]:track.property==='size'?[.02,4]:track.property==='angle'?[5,120]:track.property==='gamma'||track.property==='gain'?[.5,2]:track.property==='lift'?[-.2,.2]:track.property==='position'||track.property==='target'||track.property==='focus'?[-20,20]:null;function clamp(v){return range?Math.max(range[0],Math.min(range[1],v)):v;}if(next.lights.indexOf(object)>=0&&d.repeat==='loop'&&time>d.duration-.8){value=mix(value,values[0].value.channel,ease((time-d.duration+.8)/.8,'ease-in-out'));}object[track.property]=Array.isArray(value)?value.map(clamp):clamp(value);});
    if(turn&&!C.motion.reduced)next.card.tilt[1]+=turn*360;return next;
  }
  function create(s){var state={time:s.scene.director.playhead,playing:false,preview:!!(s.scene.keyframes.length||s.scene.animation.tracks.some(function(t){return t.enabled&&t.keys.length;}))&&s.scene.director.preview!==false,turntable:false,turn:0,direction:1};
    function changed(){s.api.dirty();}
    state.seek=function(time){state.time=Math.max(0,Math.min(s.scene.director.duration,time));state.playing=false;state.preview=true;state.turntable=false;state.turn=0;changed();};
    state.pause=function(edit){state.playing=false;state.turntable=false;state.turn=0;if(edit){state.preview=false;}changed();};
    state.play=function(){if(C.motion.reduced)return s.api.status('Reduced motion: scrub the timeline to choose a still pose.');if(s.renderer.kind==='Simple')return s.api.status('Director playback requires WebGL2. You can still scrub and author keyframes.');if(!s.scene.keyframes.length&&!s.scene.animation.tracks.some(function(t){return t.enabled&&t.keys.length;}))return s.api.status('Add keyframes or use Auto-director first.');if(state.time>=s.scene.animation.workArea.out||state.time<s.scene.animation.workArea.in)state.time=s.scene.animation.workArea.in;state.preview=true;state.playing=!state.playing;state.turntable=false;state.direction=1;changed();};
    state.toggleTurntable=function(){if(C.motion.reduced||s.renderer.kind==='Simple')return s.api.status('Turntable needs WebGL2 and motion enabled.');state.playing=false;state.turntable=!state.turntable;if(!state.turntable)state.turn=0;changed();if(s.selected==='director')C.studioDirectorPanel(s);};
    state.advance=function(seconds){var d=s.scene.director;if(C.motion.reduced){state.playing=state.turntable=false;return;}if(state.turntable)state.turn=(state.turn+seconds/d.duration)%1;if(!state.playing)return;var area=s.scene.animation.workArea,lo=area.in,hi=Math.max(lo+.001,area.out);state.time+=seconds*state.direction*s.scene.animation.speed;if(state.time>hi||state.time<lo){if(d.repeat==='ping-pong'){state.time=state.time<lo?2*lo-state.time:2*hi-state.time;state.direction*=-1;}else if(d.repeat==='loop')state.time=lo+((state.time-lo)%(hi-lo)+(hi-lo))%(hi-lo);else{state.time=state.direction<0?lo:hi;state.playing=false;}}state.time=Math.max(0,Math.min(d.duration,state.time));};
    state.active=function(){return state.playing||state.turntable;};state.scene=function(){return sample(s.scene,state.time,state.turn,state.preview);};
    state.capture=function(target){if(s.scene.keyframes.length>=96)return s.api.status('Keyframe limit reached: 96 per scene.');var scene=state.scene(),track=target==='camera'?'camera':'light',light=scene.lights.find(function(l){return l.id===target;});if(track==='light'&&!light)return;var frame={id:'frame-'+root.crypto.randomUUID(),time:Number(state.time.toFixed(2)),track:track,target:target,easing:'ease-in-out'};if(light)frame.light={position:light.position.slice(),intensity:light.intensity,color:light.color.slice()};else frame.camera=C.studioScenes.clone(scene.camera);
      s.api.mutate(function(){s.scene.keyframes=s.scene.keyframes.filter(function(f){return !(f.target===target&&Math.abs(f.time-frame.time)<.01);});s.scene.keyframes.push(frame);Object.assign(s.scene,C.studioScenes.parse(s.scene));},'Capture '+track+' key');state.preview=true;state.playing=false;s.directorKeyId=frame.id;if(s.workspace)s.workspace.page('Animate');else C.studioDirectorPanel(s);changed();};
    state.editPose=function(){var current=state.scene();s.api.mutate(function(){s.scene.camera=current.camera;current.lights.forEach(function(l){var base=s.scene.lights.find(function(v){return v.id===l.id;});if(base)['position','intensity','color'].forEach(function(k){base[k]=C.studioScenes.clone(l[k]);});});},'Load displayed pose');state.pause(true);s.api.status('Pose loaded into Camera and Light controls. Edit it, then capture keyframes at this time.');};
    state.auto=function(rig){state.pause(true);s.api.mutate(function(){s.scene.lights=C.studioPresets.lights(rig,s.tier);s.scene.keyframes=[];var duration=s.scene.director.duration,base=C.studioScenes.clone(s.scene.camera);base.autoFrame=false;[-.7,0,.7].forEach(function(yaw,i){var camera=C.studioScenes.clone(base);camera.yaw=yaw;camera.pitch=.08+(i===1?.09:0);camera.distance=base.distance*(i===1?.92:1);s.scene.keyframes.push({id:'auto-camera-'+i,time:duration*i/2,track:'camera',target:'camera',easing:'ease-in-out',camera:camera});});s.scene.lights.forEach(function(l,i){[0,1,2].forEach(function(k){var p=l.position.slice();p[0]+=Math.sin(k*Math.PI/2+i)*.35;s.scene.keyframes.push({id:'auto-light-'+i+'-'+k,time:duration*k/2,track:'light',target:l.id,easing:'ease-in-out',light:{position:p,intensity:l.intensity*(k===1?.88:1),color:l.color.slice()}});});});},'Auto-director: '+rig);state.time=0;state.preview=true;s.directorKeyId='auto-camera-0';s.directorTarget='camera';C.studioDirectorPanel(s);s.api.status('Orbit and '+rig+' rig ready. Press Preview to play.');changed();};
    state.titleAlpha=function(){return s.scene.director.title?(state.playing||state.preview?Math.max(0,Math.min(1,(1.8-state.time)/.6)):1):0;};
    state.paintTitle=function(g,w,h){var alpha=state.titleAlpha();if(!alpha)return;var unit=Math.min(w,h);g.save();g.globalAlpha=alpha;g.fillStyle='#08080CCC';g.fillRect(0,h*.76,w,h*.24);g.textAlign='center';g.fillStyle='#F5F5F7';g.font='600 '+unit*.038+'px Inter';g.fillText(s.view.card.name,w*.5,h*.85,w*.88);g.fillStyle='#BEBEC7';g.font=unit*.02+'px "JetBrains Mono"';g.fillText(C.rarity(s.view.card.rarity).name+' · '+s.view.instance.serial,w*.5,h*.9,w*.88);g.restore();};
    state.sync=function(){if(s.titleOverlay){s.titleOverlay.style.opacity=state.titleAlpha();s.titleOverlay.hidden=!s.scene.director.title;}if(s.timelineUI&&s.timelineUI.update)s.timelineUI.update(state);};
    return state;
  }
  C.studioDirector={sample:sample,ease:ease,pose:pose,create:create};
})(window.Cardable,window);
