(function(C,root){
  'use strict';
  var A=C.studioAnimation;
  function ease(t,kind,handles){return A.ease(t,kind,handles);}
  function mix(a,b,t){return A.mix(a,b,t);}
  function pose(frames,time,kind,base){if(!frames.length)return base;frames=frames.slice().sort(function(a,b){return a.time-b.time;});var result=C.studioScenes.clone(base);Object.keys(frames[0][kind]).forEach(function(k){var keys=frames.map(function(f){return {time:f.time,value:f[kind][k],easing:f.easing,bezier:f.bezier};});result[k]=A.value(keys,time,base[k]);});return result;}
  function sample(scene,time,turn,preview){
    // Render copies omit authored tracks: never clone 96 keyframes per frame.
    var next=Object.assign({},scene,{card:C.studioScenes.clone(scene.card),camera:C.studioScenes.clone(scene.camera),lights:scene.lights.map(C.studioScenes.clone),props:scene.props.map(C.studioScenes.clone),post:C.studioScenes.clone(scene.post),backdrop:C.studioScenes.clone(scene.backdrop),keyframes:[]}),d=scene.director||{duration:8,repeat:'once'},frames=scene.keyframes||[];time=Math.max(0,Math.min(d.duration,time||0));
    if(preview!==false&&frames.length){next.camera=Object.assign({},next.camera,pose(frames.filter(function(f){return f.track==='camera';}),time,'camera',next.camera));
      next.lights.forEach(function(l){var all=frames.filter(function(f){return f.track==='light'&&f.target===l.id;}).sort(function(a,b){return a.time-b.time;}),gap=(C.cutscenes.profile()==='full'?.24:.6)*scene.animation.speed,track=[];all.forEach(function(f){if(!track.length||f.time-track[track.length-1].time>=gap)track.push(f);});var area=scene.animation.workArea,span=area.out-area.in,lightTime=!C.motion.reduced&&d.repeat!=='once'&&span<gap?area.in:time,value=pose(track.map(function(f){return Object.assign({},f,{easing:'ease-in-out'});}),lightTime,'light',l),closure=Math.min(.8,span/2);
        // Loop closure is a soft ramp too, even with different authored endpoints.
        if(d.repeat==='loop'&&track.length&&closure>0&&lightTime>area.out-closure){var start=pose(track,area.in,'light',l),k=ease((lightTime-area.out+closure)/closure,'ease-in-out');['position','intensity','color'].forEach(function(key){value[key]=mix(value[key],start[key],k);});}
        ['position','intensity','color'].forEach(function(key){l[key]=C.studioScenes.clone(value[key]);});
      });
    }
    if(preview!==false&&scene.animation){A.sample(scene,next,time);var shot=A.shots(next,time);next.camera=Object.assign(next.camera,C.studioScenes.camera(shot.camera));next.transitionBlack=shot.black;if(shot.from)next.shotBlend={camera:shot.from,blend:shot.blend};}
    if(turn&&!C.motion.reduced)next.card.tilt[1]+=turn*360;return next;
  }
  function create(s){var state={time:s.scene.director.playhead,playing:false,preview:!!(s.scene.keyframes.length||s.scene.animation.shots.length||s.scene.animation.titles.length||s.scene.camera.shake.amount||s.scene.animation.tracks.some(function(t){return t.enabled&&t.keys.length;}))&&s.scene.director.preview!==false,turntable:false,turn:0,direction:1};
    function changed(){s.api.dirty();}
    state.seek=function(time){state.time=Math.max(0,Math.min(s.scene.director.duration,time));state.playing=false;state.preview=true;state.turntable=false;state.turn=0;changed();};
    state.pause=function(edit){state.playing=false;state.turntable=false;state.turn=0;if(edit){state.preview=false;}changed();};
    state.play=function(){if(C.motion.reduced)return s.api.status('Reduced motion: scrub the timeline to choose a still pose.');if(s.renderer.kind==='Simple')return s.api.status('Director playback requires WebGL2. You can still scrub and author keyframes.');if(!state.hasAnimation())return s.api.status('Add keyframes or use Auto-director first.');if(state.time>=s.scene.animation.workArea.out||state.time<s.scene.animation.workArea.in)state.time=s.scene.animation.workArea.in;state.preview=true;state.playing=!state.playing;state.turntable=false;state.direction=1;changed();};
    state.toggleTurntable=function(){if(C.motion.reduced||s.renderer.kind==='Simple')return s.api.status('Turntable needs WebGL2 and motion enabled.');state.playing=false;state.turntable=!state.turntable;if(!state.turntable)state.turn=0;changed();if(s.selected==='director')C.studioDirectorPanel(s);};
    state.advance=function(seconds){var d=s.scene.director;if(C.motion.reduced){state.playing=state.turntable=false;return;}if(state.turntable)state.turn=(state.turn+seconds/d.duration)%1;if(!state.playing)return;var area=s.scene.animation.workArea,lo=area.in,hi=Math.max(lo+.001,area.out);state.time+=seconds*state.direction*s.scene.animation.speed;if(state.time>hi||state.time<lo){if(d.repeat==='ping-pong'){state.time=state.time<lo?2*lo-state.time:2*hi-state.time;state.direction*=-1;}else if(d.repeat==='loop')state.time=lo+((state.time-lo)%(hi-lo)+(hi-lo))%(hi-lo);else{state.time=state.direction<0?lo:hi;state.playing=false;}}state.time=Math.max(0,Math.min(d.duration,state.time));};
    state.hasAnimation=function(){return !!(s.scene.keyframes.length||s.scene.animation.shots.length||s.scene.animation.titles.length||s.scene.camera.shake.amount||s.scene.animation.tracks.some(function(t){return t.enabled&&t.keys.length;}));};
    state.active=function(){return state.playing||state.turntable;};state.scene=function(){return sample(s.scene,state.time,state.turn,state.preview);};
    state.capture=function(target){if(s.scene.animation.autoKey||s.root.dataset.page==='Animate'){var o=A.object(s.scene,target),properties=A.properties(s.scene,o);if(!o)return;var shown=state.scene(),pose=A.object(shown,target);s.api.mutate(function(){properties.forEach(function(p){if((p==='position'||p==='rotation'||p==='focusDistance')&&pose[p]===null)return;var v=A.baseValue(shown,pose,p);if(v!==undefined&&v!==null)A.upsert(s.scene,target,p,state.time,v);});},'Key object pose');state.preview=true;state.playing=false;if(s.workspace)s.workspace.page('Animate');return;} if(s.scene.keyframes.length>=96)return s.api.status('Keyframe limit reached: 96 per scene.');var scene=state.scene(),track=target==='camera'?'camera':'light',light=scene.lights.find(function(l){return l.id===target;});if(track==='light'&&!light)return;var frame={id:'frame-'+root.crypto.randomUUID(),time:Number(state.time.toFixed(2)),track:track,target:target,easing:'ease-in-out'};if(light)frame.light={position:light.position.slice(),intensity:light.intensity,color:light.color.slice()};else frame.camera=C.studioScenes.clone(scene.camera);
      s.api.mutate(function(){s.scene.keyframes=s.scene.keyframes.filter(function(f){return !(f.target===target&&Math.abs(f.time-frame.time)<.01);});s.scene.keyframes.push(frame);Object.assign(s.scene,C.studioScenes.parse(s.scene));},'Capture '+track+' key');state.preview=true;state.playing=false;s.directorKeyId=frame.id;if(s.workspace)s.workspace.page('Animate');else C.studioDirectorPanel(s);changed();};
    state.editPose=function(){var current=state.scene();s.api.mutate(function(){['card','camera','post','backdrop'].forEach(function(k){Object.assign(s.scene[k],current[k]);});['lights','props','groups'].forEach(function(k){current[k].forEach(function(o){var base=s.scene[k].find(function(v){return v.id===o.id;});if(base)Object.assign(base,o);});});current.animation.cameras.concat(current.animation.titles).forEach(function(o){var base=A.object(s.scene,o.id);if(base)Object.assign(base,o);});},'Load displayed pose');state.pause(true);s.api.status('Displayed pose loaded into scene controls. Edit it, then capture keyframes at this time.');};
    state.auto=function(rig){state.pause(true);s.api.mutate(function(){var oldLights=s.scene.lights.map(function(l){return l.id;});s.scene.animation.tracks=s.scene.animation.tracks.filter(function(t){return oldLights.indexOf(t.target)<0&&t.target!=='camera';});s.scene.lights=C.studioPresets.lights(rig,s.tier);s.scene.keyframes=[];var duration=s.scene.director.duration,base=C.studioScenes.clone(s.scene.camera);base.autoFrame=false;[-.7,0,.7].forEach(function(yaw,i){var camera=C.studioScenes.clone(base);camera.yaw=yaw;camera.pitch=.08+(i===1?.09:0);camera.distance=base.distance*(i===1?.92:1);s.scene.keyframes.push({id:'auto-camera-'+i,time:duration*i/2,track:'camera',target:'camera',easing:'ease-in-out',camera:camera});});s.scene.lights.forEach(function(l,i){[0,1,2].forEach(function(k){var p=l.position.slice();p[0]+=Math.sin(k*Math.PI/2+i)*.35;s.scene.keyframes.push({id:'auto-light-'+i+'-'+k,time:duration*k/2,track:'light',target:l.id,easing:'ease-in-out',light:{position:p,intensity:l.intensity*(k===1?.88:1),color:l.color.slice()}});});});},'Auto-director: '+rig);state.time=0;state.preview=true;s.directorKeyId='auto-camera-0';s.directorTarget='camera';C.studioDirectorPanel(s);s.api.status('Orbit and '+rig+' rig ready. Press Preview to play.');changed();};
    state.titleAlpha=function(){return s.scene.director.title?(state.playing||state.preview?Math.max(0,Math.min(1,(1.8-state.time)/.6)):1):0;};
    state.paintTitle=function(g,w,h,sceneOverride,timeOverride){var shown=sceneOverride||state.scene(),titleTime=timeOverride==null?state.time:timeOverride,black=shown.transitionBlack||0;/* Scene transitions are already composited by the renderer. */var alpha=sceneOverride?shown.director.title?Math.min(1,Math.max(0,(titleTime-shown.animation.workArea.in-.5)/.6)):0:state.titleAlpha();if(alpha){var unit=Math.min(w,h);g.save();g.globalAlpha=alpha;g.fillStyle='#08080CCC';g.fillRect(0,h*.76,w,h*.24);g.textAlign='center';g.fillStyle='#F5F5F7';g.font='600 '+unit*.038+'px Inter';g.fillText(s.view.card.name,w*.5,h*.85,w*.88);g.fillStyle='#BEBEC7';g.font=unit*.02+'px "JetBrains Mono"';g.fillText(C.rarity(s.view.card.rarity).name+' · '+s.view.instance.serial,w*.5,h*.9,w*.88);g.restore();}shown.animation.titles.forEach(function(t){var p=A.titlePose(t,titleTime);if(!p.alpha)return;var unit=Math.min(w,h),size=unit*t.size,x=w*t.position[0],y=h*p.y;g.save();g.globalAlpha=p.alpha*(1-black);g.textAlign=t.align;g.textBaseline='middle';g.font='500 '+size+'px "'+t.font+'"';var lines=t.text.split('\n').slice(0,5),width=Math.min(w*.9,Math.max.apply(Math,lines.map(function(l){return g.measureText(l).width;})))+size;g.fillStyle='#08080acc';if(['Lower Third','Name Plate','Museum Label','Variant Banner','Credits'].indexOf(t.preset)>=0)g.fillRect(x-(t.align==='center'?width/2:t.align==='right'?width:0)-size*.25,y-size*.8,width+size*.5,size*(lines.length*1.25+.4));g.fillStyle='#F5F5F7';lines.forEach(function(line,i){g.fillText(line,x,y+i*size*1.25,w*.86);});g.restore();});};
    state.sync=function(){if(s.titleOverlay)s.titleOverlay.hidden=true;if(s.titleCanvas){var rect=s.viewport.getBoundingClientRect(),ratio=C.studioCamera.aspect(s.scene.camera.aspect),w=ratio?Math.min(rect.width,rect.height*ratio)*.9:rect.width,h=ratio?w/ratio:rect.height,dpr=Math.min(2,root.devicePixelRatio||1);if(s.titleCanvas.width!==Math.round(w*dpr)||s.titleCanvas.height!==Math.round(h*dpr)){s.titleCanvas.width=Math.max(1,Math.round(w*dpr));s.titleCanvas.height=Math.max(1,Math.round(h*dpr));}s.titleCanvas.style.width=w+'px';s.titleCanvas.style.height=h+'px';var g=s.titleCanvas.getContext('2d');g.clearRect(0,0,s.titleCanvas.width,s.titleCanvas.height);state.paintTitle(g,s.titleCanvas.width,s.titleCanvas.height);}if(s.timelineUI&&s.timelineUI.update)s.timelineUI.update(state);};
    return state;
  }
  C.studioDirector={sample:sample,ease:ease,pose:pose,create:create};
})(window.Cardable,window);
