(function(C,root){
  'use strict';
  var S=C.studioScenes, K=C.studioCamera, P=C.studioProps;
  function get(scene,id){return S.objects(scene).find(function(o){return o.id===id;});}
  function kind(scene,o){return o===scene.card?'card':scene.lights.indexOf(o)>=0?'light':scene.props.indexOf(o)>=0?'prop':scene.groups.indexOf(o)>=0?'group':o===scene.camera?'camera':o===scene.post?'look':'backdrop';}
  function members(scene,ids){var wanted=new Set(ids),all=S.objects(scene);return all.filter(function(o){var p=o,seen=new Set();while(p&&!seen.has(p.id)){if(wanted.has(p.id))return !!o.position;seen.add(p.id);p=get(scene,p.parentId);}return false;});}
  function model(scene,o){return o===scene.card?K.matrices(scene.camera,1,o).model:P.model(o.position,o.rotation||[0,0,0],o.scale||[o.size||.4,o.size||.4,o.size||.4]);}
  function corners(scene,o){var box=o===scene.card?{min:[-.5,-.7,-.025],max:[.5,.7,.025]}:kind(scene,o)==='light'?{min:[-.3,-.3,-.3],max:[.3,.3,.3]}:P.isEffect(o)?{min:[-1.5,-1,-1],max:[1.5,1,1]}:P.bounds(o.type), transforms=o.type==='collection'&&o.instances.length?P.placements(o).map(function(t){return t.model;}):[model(scene,o)],out=[];transforms.forEach(function(m){for(var i=0;i<8;i++)out.push(K.transform(m,[i&1?box.max[0]:box.min[0],i&2?box.max[1]:box.min[1],i&4?box.max[2]:box.min[2]]).slice(0,3));});return out;}
  function bounds(scene,ids){var points=[].concat.apply([],members(scene,ids).map(function(o){return corners(scene,o);})),min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];points.forEach(function(v){v.forEach(function(n,i){min[i]=Math.min(min[i],n);max[i]=Math.max(max[i],n);});});return points.length?{min:min,max:max,center:min.map(function(v,i){return (v+max[i])/2;}),size:min.map(function(v,i){return max[i]-v;})}:null;}
  function roots(scene,ids){var set=new Set(ids);return ids.filter(function(id){var o=get(scene,id),seen=new Set();if(!o)return false;while(o&&o.parentId&&!seen.has(o.id)){seen.add(o.id);if(set.has(o.parentId))return false;o=get(scene,o.parentId);}return true;});}
  function canEdit(scene,ids){return members(scene,ids).filter(function(o){return !S.locked(scene,o);});}
  function rotate(v,axis,angle){var c=Math.cos(angle),s=Math.sin(angle),dot=K.dot(v,axis),cross=[axis[1]*v[2]-axis[2]*v[1],axis[2]*v[0]-axis[0]*v[2],axis[0]*v[1]-axis[1]*v[0]];return v.map(function(n,i){return n*c+cross[i]*s+axis[i]*dot*(1-c);});}
  function rotation(before,axis,delta,card){var r=card?[before.tilt[0],before.tilt[1],before.rotationZ||0]:before.rotation,a=delta*Math.PI/180,c=Math.cos(a),s=Math.sin(a),q=1-c,x=axis[0],y=axis[1],z=axis[2],matrix=new Float32Array([c+x*x*q,y*x*q+z*s,z*x*q-y*s,0,x*y*q-z*s,c+y*y*q,z*y*q+x*s,0,x*z*q+y*s,y*z*q-x*s,c+z*z*q,0,0,0,0,1]),m=K.multiply(matrix,P.model([0,0,0],r,[1,1,1])),ry=Math.asin(Math.max(-1,Math.min(1,m[8]))),rx,rz;if(Math.abs(Math.cos(ry))>.00001){rx=Math.atan2(-m[9],m[10]);rz=Math.atan2(-m[4],m[0]);}else{rx=Math.atan2(m[6],m[5]);rz=0;}return [rx,ry,rz].map(function(v){return v*180/Math.PI;});}
  function transform(scene,ids,original,mode,delta,axis,pivot){canEdit(scene,ids).forEach(function(o){var before=original.get(o.id);if(!before)return;if(mode==='move')o.position=before.position.map(function(n,i){return Math.max(-20,Math.min(20,n+delta[i]));});else if(mode==='rotate'){var r=rotate(before.position.map(function(v,i){return v-pivot[i];}),axis,delta*Math.PI/180);o.position=r.map(function(v,i){return Math.max(-20,Math.min(20,v+pivot[i]));});var r=rotation(before,axis,delta,o===scene.card);if(o===scene.card){o.tilt=r.slice(0,2);o.rotationZ=r[2];}else o.rotation=r;}else{var factors=Array.isArray(delta)?delta:[delta,delta,delta];if(o.scale)o.scale=before.scale.map(function(v,i){return Math.max(.05,Math.min(6,v*factors[i]));});else o.size=Math.max(.02,Math.min(4,before.size*Math.max.apply(Math,factors)));o.position=before.position.map(function(v,i){return Math.max(-20,Math.min(20,pivot[i]+(v-pivot[i])*factors[i]));});}});}
  function snapFloor(scene,ids){canEdit(scene,ids).forEach(function(o){var b=bounds(scene,[o.id]);if(b)o.position[1]+=-.9-b.min[1];});}
  function group(scene,ids){var list=roots(scene,ids).filter(function(id){var o=get(scene,id);return o&&!S.locked(scene,o);});if(!list.length||scene.groups.length>=64)throw Error('Select unlocked objects; a scene supports 64 groups.');var parent=get(scene,list[0]).parentId;if(!list.every(function(id){return get(scene,id).parentId===parent;}))parent=null;var g={id:'group-'+root.crypto.randomUUID(),name:'Group '+(scene.groups.length+1),parentId:parent,visible:true,locked:false,children:list};scene.groups.push(g);list.forEach(function(id){get(scene,id).parentId=g.id;});S.syncGroups(scene);return g.id;}
  function ungroup(scene,ids){scene.groups.slice().forEach(function(g){if(ids.indexOf(g.id)<0||S.locked(scene,g))return;S.objects(scene).forEach(function(o){if(o.parentId===g.id)o.parentId=g.parentId;});scene.groups.splice(scene.groups.indexOf(g),1);});S.syncGroups(scene);}
  function duplicate(scene,ids,tier){var selected=roots(scene,ids),all=S.objects(scene),source=all.filter(function(o){if(selected.indexOf(o.id)>=0)return true;var p=o,seen=new Set();while(p&&!seen.has(p.id)){seen.add(p.id);if(selected.indexOf(p.parentId)>=0)return true;p=get(scene,p.parentId);}return false;}).filter(function(o){return !S.locked(scene,o)&&['card','light','prop','group'].indexOf(kind(scene,o))>=0;}),copies=[],map=new Map(),limit=S.limits(tier),lights=source.filter(function(o){return kind(scene,o)==='light';}).length,props=source.filter(function(o){return ['prop','card'].indexOf(kind(scene,o))>=0;}).length,groups=source.filter(function(o){return kind(scene,o)==='group';}).length,cards=source.reduce(function(n,o){return n+(o===scene.card?1:o.type==='collection'?o.instances.length:0);},0)+scene.props.reduce(function(n,o){return n+(o.type==='collection'?o.instances.length:0);},0);
    if(scene.lights.length+lights>limit.lights||scene.props.length+props>limit.props||scene.groups.length+groups>64||cards>10)throw Error('Duplicate would exceed this quality tier or the ten collection-card limit.');
    source.forEach(function(o){var k=kind(scene,o),n;if(k==='card'){n=P.create('collection');n.instances=scene.card.source?[scene.card.source.instanceId]:[];n.scale=o.scale.map(function(v){return v*2;});n.position=o.position.slice();n.rotation=[o.tilt[0],o.tilt[1],o.rotationZ];}else n=S.clone(o);n.id=k+'-'+root.crypto.randomUUID();n.name=(o.name||'Card')+' copy';if(n.position)n.position[0]=Math.min(20,n.position[0]+.15);n.parentId=o.parentId;copies.push({kind:k,object:n,old:o.id});map.set(o.id,n.id);});
    copies.forEach(function(c){c.object.parentId=map.get(c.object.parentId)||c.object.parentId;if(c.kind==='group'){c.object.children=[];scene.groups.push(c.object);}else scene[c.kind==='light'?'lights':'props'].push(c.object);});S.syncGroups(scene);return selected.map(function(id){return map.get(id);}).filter(Boolean);
  }
  function remove(scene,ids){var selected=roots(scene,ids),all=S.objects(scene);all.forEach(function(o){if(selected.indexOf(o.id)<0||S.locked(scene,o))return;var k=kind(scene,o);if(k==='card')o.visible=false;else if(k==='group')ungroup(scene,[o.id]);else if(k==='prop'||k==='light'){scene[k==='prop'?'props':'lights']=scene[k==='prop'?'props':'lights'].filter(function(v){return v!==o;});scene.keyframes=scene.keyframes.filter(function(f){return f.target!==o.id;});scene.animation.tracks=scene.animation.tracks.filter(function(t){return t.target!==o.id;});}});}
  function arrange(scene,ids,method,axis,spacing){var all=canEdit(scene,ids),center=bounds(scene,ids);if(!all.length||!center)return;axis=axis==null?0:axis;spacing=spacing||1.2;if(method==='align')all.forEach(function(o){o.position[axis]=center.center[axis];});else if(method==='distribute'){all.sort(function(a,b){return a.position[axis]-b.position[axis];});var first=all[0].position[axis],last=all[all.length-1].position[axis];all.forEach(function(o,i){o.position[axis]=all.length<2?first:first+(last-first)*i/(all.length-1);});}else if(method==='mirror')all.forEach(function(o){o.position[axis]=2*center.center[axis]-o.position[axis];if(o===scene.card)o.tilt[1]=-o.tilt[1];else o.rotation[axis===0?1:0]=-o.rotation[axis===0?1:0];});else all.forEach(function(o,i){if(method==='circle'){var a=2*Math.PI*i/all.length;o.position[0]=center.center[0]+Math.cos(a)*spacing;o.position[2]=center.center[2]+Math.sin(a)*spacing;}else{var cols=Math.ceil(Math.sqrt(all.length));o.position[0]=center.center[0]+(i%cols-(cols-1)/2)*spacing;o.position[1]=center.center[1]+(Math.floor(i/cols)-(Math.ceil(all.length/cols)-1)/2)*spacing;}});all.forEach(function(o){o.position=o.position.map(function(v){return Math.max(-20,Math.min(20,v));});});}
  function array(scene,ids,method,count,spacing,tier){var selected=roots(scene,ids),result=selected.slice();if(!selected.length)throw Error('Select an object for the array.');if(!Number.isFinite(count)||!Number.isFinite(spacing)||spacing<.1||spacing>5)throw Error('Use an array count from 2 to 16 and spacing from 0.1 to 5.');count=Math.max(2,Math.min(16,Math.floor(count)));for(var i=1;i<count;i++)result=result.concat(duplicate(scene,selected,tier));arrange(scene,result,method,0,spacing);return result;}
  function pick(scene,m,x,y){var ray=K.ray(m,x,y),hits=[];members(scene,S.objects(scene).filter(function(o){return o.visible!==false;}).map(function(o){return o.id;})).forEach(function(o){if(kind(scene,o)==='light'){var p=K.project(m,o.position);if(p.front&&Math.hypot(p.x-x,p.y-y)<.032)hits.push({id:o.id,d:Math.hypot.apply(Math,o.position.map(function(v,i){return v-ray.origin[i];}))});return;}var transforms=o.type==='collection'&&o.instances.length?P.placements(o).map(function(t){return t.model;}):[model(scene,o)],box=o===scene.card?{min:[-.5,-.7,-.025],max:[.5,.7,.025]}:P.isEffect(o)?{min:[-1.5,-1,-1],max:[1.5,1,1]}:P.bounds(o.type),nearest=Infinity;transforms.forEach(function(model){var inv=K.inverse(model),a=K.transform(inv,ray.origin),d=K.transform(inv,ray.direction.concat(0)),near=0,far=Infinity;for(var i=0;i<3;i++){if(Math.abs(d[i])<1e-8){if(a[i]<box.min[i]||a[i]>box.max[i])return;}else{var lo=(box.min[i]-a[i])/d[i],hi=(box.max[i]-a[i])/d[i];near=Math.max(near,Math.min(lo,hi));far=Math.min(far,Math.max(lo,hi));}}if(far>=near)nearest=Math.min(nearest,near);});if(Number.isFinite(nearest))hits.push({id:o.id,d:nearest});});return hits.sort(function(a,b){return a.d-b.d;}).map(function(o){return o.id;});}
  C.studioEditing={get:get,kind:kind,members:members,roots:roots,bounds:bounds,corners:corners,model:model,transform:transform,snapFloor:snapFloor,group:group,ungroup:ungroup,duplicate:duplicate,remove:remove,arrange:arrange,array:array,pick:pick};
})(window.Cardable,window);
