(function (C) {
  'use strict';
  function lamp(type, position, color, intensity, extras) { return Object.assign(C.studioScenes.light({ type: type, position: position, color: color, intensity: intensity }), extras || {}); }
  var rigs = {
    Studio: function () { return [lamp('area', [-1.6, 2, 2.6], [1, .97, .93], 2.8, { rotation: [-30, -30, 0], size: 1 }), lamp('area', [1.4, .4, 2], [.8, .88, 1], 1.2, { rotation: [-10, 35, 0] }), lamp('strip', [0, 1, -1], [1, 1, 1], 2.2, { rotation: [-25, 180, 0] })]; },
    Rim: function () { return [lamp('strip', [-1.1, .6, -.8], [.75, .86, 1], 4, { rotation: [-10, -125, 0], size: .9 }), lamp('point', [1.3, .2, 1.7], [1, .94, .83], .9)]; },
    Noir: function () { return [lamp('spot', [-1.2, 2.2, 2.3], [1, 1, 1], 5, { rotation: [-40, -28, 0], angle: 35, gobo: 'blinds', softness: .18 })]; },
    'Neon Alley': function () { return [lamp('strip', [-1.2, .7, 1.3], [1, .08, .5], 3, { rotation: [-20, -42, 0] }), lamp('strip', [1.3, .3, 1.7], [.06, .8, 1], 3, { rotation: [-10, 38, 0] }), lamp('ambient', [0, 0, 0], [.18, .13, .25], .25)]; },
    Sunset: function () { return [lamp('directional', [-2, 1, 2], [1, .45, .15], 1.3, { rotation: [-18, -55, 0] }), lamp('ambient', [0, 0, 0], [.42, .35, .62], .6, { bottom: [.2, .1, .08] })]; },
    Moonlight: function () { return [lamp('directional', [1.5, 2, 2], [.4, .6, 1], 1.6, { rotation: [-45, 35, 0] }), lamp('area', [-1, .2, 2], [.78, .86, 1], .5)]; },
    Showroom: function () { return [lamp('area', [-1.3, 1.6, 2.2], [1, 1, 1], 3, { size: 1.2, rotation: [-30, -30, 0] }), lamp('area', [1.2, 1, 1.8], [1, .98, .92], 2, { size: .9, rotation: [-25, 30, 0] }), lamp('ambient', [0, 0, 0], [.8, .85, 1], .35)]; },
    Vault: function () { return [lamp('spot', [0, 2.5, 2], [1, .8, .36], 4, { rotation: [-50, 0, 0], angle: 40 }), lamp('strip', [1.1, .1, -1], [.5, .72, 1], 2.5, { rotation: [0, 140, 0] })]; }
  };
  function arrangement(name,scene,tier){
    var props=[];function add(type,position,options){var p=C.studioProps.create(type);p.position=position;if(options)Object.keys(options).forEach(function(k){p[k]=options[k];});props.push(p);return p;}
    if(name==='Void'){add('haze',[0,0,-.5],{color:[.12,.16,.25],density:.2});}
    else {
      add('floor',[0,-.88,0],{color:name==='Sunset Desk'?[.24,.13,.075]:[.13,.14,.16],surface:name==='Showroom'?'mirror':name==='Vault'?'glossy':'matte'});
      if(name==='Museum'){add('plinth-square',[0,-.81,0],{scale:[1.1,.3,1],material:'metal'});add('glass-case',[0,-.05,0],{scale:[1,1.3,1],color:[.75,.82,.9],castShadow:false});add('spotlight-can',[1.15,.7,-.9],{rotation:[90,0,0]});}
      else if(name==='Neon Alley'){add('neon-tube',[-1,.55,-.7],{color:[1,.08,.5],text:'CARDABLE',rotation:[0,15,0]});add('led-strip',[1,.2,-.5],{color:[.06,.8,1],rotation:[0,0,90]});add('haze',[0,0,0],{density:.3});add('rain',[0,0,.2],{density:.25});}
      else if(name==='Sunset Desk'){add('plant',[1,-.32,-.15]);add('pack',[-1,-.35,-.15],{packId:scene.card.source&&scene.card.source.packId||'standard',rotation:[0,15,0],material:'gloss'});add('easel',[0,-.13,-.1]);}
      else if(name==='Vault'){add('plinth-round',[0,-.8,0],{scale:[1,.45,1],color:[.3,.24,.12],material:'metal'});add('crown',[-.95,-.53,0]);add('trophy',[1,-.4,-.1]);add('dust',[0,.1,0],{color:[.75,.6,.3],density:.3});}
      else if(name==='Showroom'){add('turntable',[0,-.76,0],{scale:[1,.55,1],material:'metal'});add('softbox',[-1.4,.4,-.3],{rotation:[0,30,0]});add('ring-light',[1.3,.4,-.3],{rotation:[0,-30,0]});}
      else {add('easel',[0,-.13,-.15]);add('softbox',[-1.4,.45,-.3],{rotation:[0,25,0]});}
    }
    return props.slice(0,C.studioScenes.limits(tier).props);
  }
  C.studioPresets = { serialize:function(preset){return JSON.stringify({id:String(preset.id||'user-scene').slice(0,80),kind:'scene',name:String(preset.name||'Scene').slice(0,60),scene:JSON.parse(C.studioScenes.serialize(preset.scene)),version:1});},parse:function(value){if(typeof value==='string')value=JSON.parse(value);if(!value||value.version!==1||value.kind!=='scene')throw new Error('Unsupported studio preset.');return {id:String(value.id||'user-scene').slice(0,80),kind:'scene',name:String(value.name||'Scene').slice(0,60),scene:C.studioScenes.parse(value.scene),version:1};},rigs: Object.keys(rigs), scenes: ['Studio', 'Museum', 'Neon Alley', 'Sunset Desk', 'Void', 'Vault', 'Showroom', 'Surprise me'],
    lights: function (name, tier) { return (rigs[name] || rigs.Studio)().slice(0, C.studioScenes.limits(tier).lights).map(function (l, i) { l.id = i === 0 ? 'key' : 'rig-' + i; l.name = i === 0 ? 'Key light' : 'Fill ' + i; return l; }); },
    apply: function (name, scene, tier) { if (name === 'Surprise me') name = 'Studio'; var rig = { Museum: 'Studio', 'Sunset Desk': 'Sunset', Void: 'Rim' }[name] || name, next = C.studioScenes.defaults(); next.card = C.studioScenes.clone(scene.card); next.lights = this.lights(rig, tier); next.backdrop.color = name === 'Showroom' ? [.16, .16, .17] : name === 'Museum' ? [.07, .07, .075] : name === 'Sunset Desk' ? [.05, .025, .02] : name === 'Void' ? [.004, .004, .006] : [.025, .025, .033]; next.props=arrangement(name,next,tier);next.camera.yaw = name === 'Museum' ? 0 : -.12; next.camera.pitch = name === 'Sunset Desk' ? .18 : .04; next.post.bloom = name === 'Neon Alley' ? .35 : .12; return C.studioScenes.parse(next); }
  };
})(window.Cardable);

(function(C){
  'use strict';
  var S=C.studioScenes,P=C.studioPresets,D=C.studioPresetCatalog,copy=S.clone;
  function random(seed){var n=2166136261;String(seed).split('').forEach(function(c){n=Math.imul(n^c.charCodeAt(0),16777619);});return function(){n+=0x6D2B79F5;var t=Math.imul(n^n>>>15,1|n);t^=t+Math.imul(t^t>>>7,61|t);return ((t^t>>>14)>>>0)/4294967296;};}
  function rgb(hex){if(Array.isArray(hex))return hex.slice(0,3);if(typeof hex!=='string'||!/^#[0-9a-f]{6}$/i.test(hex))return [.7,.72,.8];return [1,3,5].map(function(i){return parseInt(hex.slice(i,i+2),16)/255;});}
  function profile(card,instance,faces){var rarity=C.rarity(card.rarity),variant=C.variant(instance.variantId),finish=C.finishes.registry[rarity.finish],palette=variant&&variant.studio&&variant.studio.palette||({'rainbow-holo':['#EDACDA','#76CDD8'],'vertical-holo':['#D6E4F3'],'aurora':['#55C8A1','#8582DC'],'galaxy-holo':['#799BCF','#AD80CC'],'beam':['#DDE3E8'],'matte':['#9DAAB8'],'gold-foil':['#EBC16A']})[instance.variantId]||finish&&finish.studio&&finish.studio.palette||[rarity.accent||rarity.color||'#B0B4C0'];return {accent:rgb(palette[0]),brightness:faces&&faces.artProfile?faces.artProfile.brightness:.5,matte:instance.variantId==='matte',foil:!!instance.variantId&&instance.variantId!=='matte'||/gold|foil|chrome/i.test(rarity.finish||''),classic:instance.cardSkinId==='classic'};}
  function adapt(lights,rules,card){if(!card)return lights;var accent=card.accent,complement=accent.map(function(v){return .35+(1-v)*.65;});lights.forEach(function(l,i){var isRim=l.position[2]<0,k=rules.accent*(isRim?1:.4),color=isRim?complement:accent;l.color=l.color.map(function(v,j){var out=v*(1-k)+color[j]*k;if(card.classic)out=out*(1-rules.warm)+[1,.83,.61][j]*rules.warm;return Math.max(0,Math.min(1,out));});if(isRim)l.intensity*=1+(.5-card.brightness)*rules.rim;if(card.foil&&l.type!=='ambient')l.intensity*=rules.foil;if(card.matte){l.size=Math.min(4,l.size*1.25);l.intensity*=1.08;}if(card.classic)l.size=Math.min(4,l.size*1.2);});return lights;}
  function rig(name){return (D.rigs[name]||D.rigs['Three-point']).map(function(l,i){return Object.assign(copy(l),{id:i?'rig-'+i:'key',name:name+' · '+(i?'Fill '+i:'Key'),parentId:null});});}
  function look(name){var x=D.looks.find(function(x){return x[0]===name;});return Object.assign(S.defaults().post,copy(x?x[1]:{}));}
  function components(data,base){var owned=C.state.current.inventory||[],left=10;return data.map(function(raw,i){var p=S.prop(Object.assign({id:'component-'+i},copy(raw)),i);if(p.type==='collection'){var ids=base.props.filter(function(p){return p.type==='collection';}).flatMap(function(p){return p.instances;}).concat(base.card.source?[base.card.source.instanceId]:[],owned.map(function(x){return x.instanceId;}));p.instances=Array.from(new Set(ids)).filter(function(id){return owned.some(function(x){return x.instanceId===id;});}).slice(0,Math.min(left,p.arrangement==='stack'?4:6));left-=p.instances.length;}if(p.type==='pack')p.packId=base.card.source&&base.card.source.packId||'standard';return p;});}
  function channel(scene,target,property,values){var id='preset-'+target+'-'+property;scene.animation.tracks.push({id:id,target:target,property:property,enabled:true,keys:values.map(function(x,i){return {id:id+'-'+i,time:x[0],value:copy(x[1]),easing:x[2]||'ease-in-out'};})});}
  function cameraKeys(scene,name,seed){var c=copy(scene.camera),p=scene.card.position.slice(),d=scene.director.duration;scene.keyframes=[];scene.animation.tracks=[];scene.animation.shots=[];scene.animation.markers=[];c.target=p.slice();c.focus=p.slice();c.autoFrame=c.lockToCard=false;c.projection='perspective';c.roll=0;function key(t,values,ease){scene.keyframes.push({id:'move-'+D.slug(name)+'-'+scene.keyframes.length,time:t*d,track:'camera',target:'camera',easing:ease||'ease-in-out',camera:Object.assign(copy(c),values)});}function target(y){return p.map(function(v,i){return v+(i===1?y:0);});}
    if(name==='Hero'){key(0,{yaw:-.18,pitch:.07,distance:3.2});key(1,{yaw:.1,pitch:.085,distance:2.7});}
    else if(name==='Close-up'){key(0,{yaw:-.065,pitch:.035,distance:1.6,target:target(.22),aperture:2.2});key(1,{yaw:.05,pitch:.03,distance:1.45,target:target(.18),aperture:2.2});}
    else if(name==='Reveal'){key(0,{yaw:.2,pitch:.05,distance:1.4,target:target(-.26)});key(.28,{yaw:.14,pitch:.06,distance:1.6,target:target(-.12)});key(1,{yaw:0,pitch:.06,distance:3.15});}
    else if(name==='Turntable'){key(0,{yaw:0,pitch:.055,distance:3.1});key(1,{yaw:0,pitch:.055,distance:3.1});channel(scene,'card','tilt',[[0,scene.card.tilt],[d,[scene.card.tilt[0],scene.card.tilt[1]+360],'linear']]);}
    else if(name==='Crane Up'){key(0,{yaw:-.1,pitch:-.12,distance:3,target:target(-.2)});key(1,{yaw:.08,pitch:.27,distance:3.35,target:target(.16)});}
    else if(name==='Whip Pan Settle'){key(0,{yaw:-.8,pitch:.03,distance:3.35});key(.12,{yaw:.22,pitch:.055,distance:3.1},'ease-out');key(.24,{yaw:-.08,pitch:.055,distance:3.05});key(1,{yaw:-.035,pitch:.06,distance:2.9});}
    else if(name==='Dolly Zoom'){[0,.25,.5,.75,1].forEach(function(t){var distance=3.7-t*1.7;key(t,{yaw:.04,pitch:.045,distance:distance,fov:2*Math.atan(3.7*Math.tan(25*Math.PI/360)/distance)*180/Math.PI},'linear');});}
    else if(name==='Orbit Left'||name==='Orbit Right'){var sign=name==='Orbit Left'?-1:1;key(0,{yaw:-sign*.38,pitch:.075,distance:3.3});key(.5,{yaw:0,pitch:.09,distance:3.05});key(1,{yaw:sign*.38,pitch:.075,distance:3.3});}
    else if(name==='Handheld'){var r=random(seed);for(var i=0;i<=16;i++)key(i/16,{yaw:(r()-.5)*.03,pitch:.07+(r()-.5)*.022,distance:3.05+(r()-.5)*.04,roll:(r()-.5)*.007,target:target((r()-.5)*.025)});}
    else if(name==='Slow Float'){key(0,{yaw:-.07,pitch:.065,distance:3.1,target:target(-.035)});key(.5,{yaw:.06,pitch:.09,distance:3,target:target(.04)});key(1,{yaw:-.07,pitch:.065,distance:3.1,target:target(-.035)});}
    else if(name==='Spec Sweep'){key(0,{yaw:-.11,pitch:.04,distance:1.65,target:[p[0]-.16,p[1]-.34,p[2]],aperture:1.1});key(1,{yaw:.1,pitch:.04,distance:1.65,target:[p[0]+.16,p[1]-.34,p[2]],aperture:1.1});}
    else if(name==='Orbit Reveal'){key(0,{yaw:-.62,pitch:.1,distance:3.6});key(.55,{yaw:-.12,pitch:.08,distance:3.05});key(1,{yaw:.18,pitch:.08,distance:2.95});}
    else if(name==='Spiral Push'){key(0,{yaw:-.42,pitch:.25,distance:3.9});key(.35,{yaw:-.15,pitch:.14,distance:3.25});key(.7,{yaw:.15,pitch:.08,distance:2.85});key(1,{yaw:.27,pitch:.055,distance:2.55});}
    else if(name==='Rack Focus Pair'){key(0,{yaw:-.1,pitch:.06,distance:2.7,focus:target(.3),aperture:1.2});key(.4,{yaw:-.045,pitch:.06,distance:2.65,focus:target(.3),aperture:1.2});key(.65,{yaw:.02,pitch:.06,distance:2.65,focus:target(-.3),aperture:1.2});key(1,{yaw:.08,pitch:.06,distance:2.7,focus:target(-.3),aperture:1.2});}
    else if(name==='Slow Crane Down'){key(0,{yaw:-.12,pitch:.3,distance:3.6,target:target(.2)});key(.5,{yaw:0,pitch:.14,distance:3.2});key(1,{yaw:.08,pitch:.025,distance:3.05,target:target(-.08)});}
    else if(name==='Detail Crawl'){key(0,{yaw:-.055,pitch:.04,distance:1.75,target:[p[0]-.19,p[1]-.29,p[2]],focus:target(-.28),aperture:.7});key(.5,{yaw:0,pitch:.03,distance:1.7,target:[p[0],p[1]-.19,p[2]],focus:target(-.18),aperture:.7});key(1,{yaw:.055,pitch:.035,distance:1.75,target:[p[0]+.19,p[1]-.08,p[2]],focus:target(-.08),aperture:.7});}
    else if(name==='Pendulum'){key(0,{yaw:-.24,pitch:.075,distance:3.2});key(.5,{yaw:.24,pitch:.075,distance:3.2});key(1,{yaw:-.24,pitch:.075,distance:3.2});}
    else if(name==='Beauty Pass'){key(0,{yaw:-.18,pitch:.07,distance:3.1});key(.32,{yaw:.06,pitch:.08,distance:2.7});key(.34,{yaw:-.055,pitch:.025,distance:1.55,target:target(.18),aperture:2.1},'linear');key(.65,{yaw:.065,pitch:.03,distance:1.45,target:target(.12),aperture:2.1});key(.67,{yaw:.25,pitch:.12,distance:3.15},'linear');key(1,{yaw:-.12,pitch:.07,distance:3.05});scene.animation.shots=[{id:'beauty-hero',cameraId:'camera',start:0,duration:d*.34,transition:'cut'},{id:'beauty-art',cameraId:'camera',start:d*.34,duration:d*.33,transition:'cut'},{id:'beauty-finish',cameraId:'camera',start:d*.67,duration:d*.33,transition:'cut'}];scene.animation.markers=[{id:'beauty-art-marker',name:'Art close-up',time:d*.34,color:[.7,.7,.8]},{id:'beauty-finish-marker',name:'Finish',time:d*.67,color:[.7,.7,.8]}];}
    Object.assign(scene.camera,scene.keyframes[0].camera);scene.director.preview=true;scene.animation.workArea={in:0,out:d};return scene;
  }
  function animate(scene,name){var d=scene.director.duration,c=scene.card,p=c.position,t=c.tilt;scene.animation.tracks=[];scene.animation.shots=[];scene.animation.markers=[];scene.keyframes=[];scene.director.preview=true;scene.animation.workArea={in:0,out:d};
    if(name==='Float')channel(scene,'card','position',[[0,p],[d*.5,[p[0],p[1]+.07,p[2]]],[d,p]]);
    else if(name==='Pulse Glow')channel(scene,'look','bloom',[[0,scene.post.bloom],[d*.5,Math.min(.6,scene.post.bloom+.09)],[d,scene.post.bloom]]);
    else if(name==='Slow Tilt Reveal')channel(scene,'card','tilt',[[0,[t[0]+8,t[1]-22]],[d*.65,[t[0]-2,t[1]+8]],[d,t]]);
    else if(name==='Showcase Spin')channel(scene,'card','tilt',[[0,t],[d,[t[0],t[1]+360],'linear']]);
    else if(name==='Light Sweep'||name==='Flicker (safe)'){var l=scene.lights.find(function(l){return l.type!=='ambient';});if(!l)throw Error('Add a spatial light before applying this animation.');if(name==='Light Sweep'){channel(scene,l.id,'position',[[0,[l.position[0]-1,l.position[1],l.position[2]]],[d*.5,[l.position[0]+1,l.position[1],l.position[2]]],[d,[l.position[0]-1,l.position[1],l.position[2]]]]);}else{for(var i=0,values=[];i<=8;i++)values.push([d*i/8,l.intensity*(i%2?.95:1)]);channel(scene,l.id,'intensity',values);}}
    else if(name==='Breathing Camera')channel(scene,'camera','distance',[[0,scene.camera.distance],[d*.5,Math.max(1.3,scene.camera.distance*.975)],[d,scene.camera.distance]]);
    else if(name==='Prop Orbit'){var props=scene.props.filter(function(p){return p.type!=='floor'&&p.type!=='backdrop'&&!C.studioProps.isEffect(p);}).slice(0,8);if(!props.length)throw Error('Add a prop set before applying Prop Orbit.');props.forEach(function(p){var values=[];for(var i=0;i<=8;i++){var a=i*Math.PI/4,dx=p.position[0]-c.position[0],dz=p.position[2]-c.position[2];values.push([d*i/8,[c.position[0]+dx*Math.cos(a)+dz*Math.sin(a),p.position[1],c.position[2]-dx*Math.sin(a)+dz*Math.cos(a)]]);}channel(scene,p.id,'position',values);});}
    else if(name==='Variant Glint'){channel(scene,'card','tilt',[[0,t],[d*.45,[t[0]+3,t[1]+13]],[d,t]]);channel(scene,'look','bloom',[[0,scene.post.bloom],[d*.45,Math.min(.6,scene.post.bloom+.05)],[d,scene.post.bloom]]);}
    return scene;
  }
  function find(id){return D.entries.find(function(e){return e.id===id||e.name===id;})||(C.state.current.studio.presets||[]).find(function(e){return e.id===id;});}
  function build(entry,base,card,seed){if(typeof entry==='string')entry=find(entry);if(!entry)throw Error('Preset unavailable.');if(entry.scene)return S.preset(entry).scene;var next=S.parse(base),data=entry.data;
    if(entry.kind==='scene'){next=S.defaults();next.card.source=copy(base.card.source);next.card.plate=base.card.plate;next.card.side=base.card.side;next.backdrop.color=data.backdrop.slice();next.lights=adapt(rig(data.rig),entry.adapt,card);next.props=components(data.props,base);Object.assign(next.camera,{yaw:data.camera[0],pitch:data.camera[1],distance:data.camera[2],fov:data.camera[3]});next.post=look(data.look);if(card&&card.foil)next.post.bloom*=.75;}
    else if(entry.kind==='rig'){var oldLightIds=next.lights.map(function(l){return l.id;});next.keyframes=next.keyframes.filter(function(f){return f.track!=='light';});next.animation.tracks=next.animation.tracks.filter(function(t){return oldLightIds.indexOf(t.target)<0;});next.lights=adapt(rig(entry.name),entry.adapt,card);}
    else if(entry.kind==='look')next.post=look(entry.name);
    else if(entry.kind==='props'){var oldPropIds=next.props.map(function(p){return p.id;});next.animation.tracks=next.animation.tracks.filter(function(t){return oldPropIds.indexOf(t.target)<0;});next.props=components(data,base);}
    else if(entry.kind==='move')cameraKeys(next,entry.name,seed||'cardable');
    else if(entry.kind==='animation')animate(next,entry.name);
    return S.parse(next);
  }
  function combine(base,preset,next,add,tier){var kind=preset.kind,out=S.parse(base),touched=kind==='scene'?S.objects(base):kind==='rig'?base.lights:kind==='props'?base.props:kind==='look'?[base.post]:kind==='move'?[base.camera,base.card]:next.animation.tracks.map(function(t){return S.objects(base).find(function(o){return o.id===t.target;});}).filter(Boolean);
    if(touched.some(function(o){return S.locked(base,o);}))throw Error('Unlock the affected objects before applying this preset.');
    function clear(ids){out.keyframes=out.keyframes.filter(function(f){return ids.indexOf(f.target)<0;});out.animation.tracks=out.animation.tracks.filter(function(t){return ids.indexOf(t.target)<0;});out.groups.forEach(function(g){g.children=g.children.filter(function(id){return ids.indexOf(id)<0;});});}
    function list(key){var old=out[key];if(!add)clear(old.map(function(x){return x.id;}));var ids=new Set(S.objects(out).map(function(o){return o.id;})),map=new Map(),items=next[key].map(function(x,i){var o=copy(x),id=o.id,n=0;if(add)id='preset-'+key+'-'+i;while(ids.has(id))id='preset-'+key+'-'+i+'-'+n++;ids.add(id);map.set(o.id,id);o.id=id;o.parentId=null;return o;});out[key]=(add?old:[]).concat(items);next.keyframes.filter(function(f){return map.has(f.target);}).forEach(function(f){f=copy(f);f.target=map.get(f.target);f.id+='-'+out.keyframes.length;out.keyframes.push(f);});next.animation.tracks.filter(function(t){return map.has(t.target);}).forEach(function(t){t=copy(t);t.target=map.get(t.target);t.id+='-'+out.animation.tracks.length;out.animation.tracks.push(t);});if(add&&out[key].length>S.limits(tier)[key])throw Error('This preset exceeds the current '+key+' limit. Increase studio quality or replace objects.');return map;}
    if(kind==='scene'&&!add){out=next;}
    else if(kind==='scene'){list('lights');list('props');}
    else if(kind==='rig')list('lights');
    else if(kind==='props')list('props');
    else if(kind==='look'){var meta={id:out.post.id,parentId:out.post.parentId,visible:out.post.visible,locked:out.post.locked};out.post=Object.assign(copy(next.post),meta);clear(['look']);}
    else if(kind==='move'||kind==='animation'){var offset=add&&kind==='move'?out.director.duration:0,duration=next.director.duration;if(offset){duration=Math.min(duration,15-offset);if(duration<1)throw Error('Timeline is full. Replace the move or shorten it first.');out.director.duration=offset+duration;}if(!add){if(kind==='move'){out.director.duration=next.director.duration;out.animation.shots=[];out.keyframes=out.keyframes.filter(function(f){return f.track!=='camera';});out.animation.tracks=out.animation.tracks.filter(function(t){return !(t.target==='camera'||t.target==='card'&&t.property==='tilt');});}else out.animation.tracks=out.animation.tracks.filter(function(t){return !next.animation.tracks.some(function(n){return n.target===t.target&&n.property===t.property;});});}if(kind==='move'){out.keyframes=out.keyframes.concat(next.keyframes.map(function(f){f=copy(f);f.id+='-'+out.keyframes.length;f.time=offset+f.time*duration/next.director.duration;return f;}));if(!offset)out.camera=Object.assign(out.camera,copy(next.camera));}var animationMap=new Map(),taken=new Set(S.objects(out).concat(out.animation.cameras,out.animation.titles).map(function(o){return o.id;}));['cameras','titles'].forEach(function(kind){next.animation[kind].forEach(function(o){if(out.animation[kind].length>=(kind==='cameras'?8:16))throw Error('Preset exceeds the '+kind+' limit.');var object=copy(o),id=object.id,n=0;while(taken.has(id))id=object.id.slice(0,60)+'-preset-'+n++;taken.add(id);animationMap.set(object.id,id);object.id=id;if(kind==='titles'){object.start=offset+object.start*duration/next.director.duration;object.duration*=duration/next.director.duration;}out.animation[kind].push(object);});});next.animation.tracks.forEach(function(t){t=copy(t);t.target=animationMap.get(t.target)||t.target;t.id+='-'+out.animation.tracks.length;t.keys.forEach(function(k){k.id+='-'+out.animation.tracks.length;k.time=offset+k.time*duration/next.director.duration;});out.animation.tracks.push(t);});if(next.animation.shots.length)out.animation.shots=out.animation.shots.concat(next.animation.shots.map(function(x){x=copy(x);x.cameraId=animationMap.get(x.cameraId)||x.cameraId;x.start=offset+x.start*duration/next.director.duration;x.duration*=duration/next.director.duration;return x;}));var marks=next.animation.markers.map(function(m){m=copy(m);m.id+='-'+out.animation.markers.length;m.time=offset+m.time*duration/next.director.duration;return m;});out.animation.markers=out.animation.markers.concat(marks);out.director.preview=true;out.animation.workArea={in:0,out:out.director.duration};}
    out.card.source=copy(base.card.source);var owned=C.state.current.inventory;out.props.forEach(function(p){if(p.type==='collection')p.instances=p.instances.filter(function(id){return owned.some(function(x){return x.instanceId===id;});});});return S.parse(out);
  }
  function snapshot(kind,name,scene,id){return S.preset({version:2,id:id||'user-'+Date.now().toString(36),kind:kind,name:name,scene:scene,tags:['User']});}
  function surprise(seed,previous){var family=previous&&previous.tags[0],pool=D.entries.filter(function(e){return e.kind==='scene'&&(!family||e.tags[0]===family);}),r=random(seed);return pool[Math.floor(r()*pool.length)];}
  function remix(entry,base,card,seed){var next=build(entry,base,card,seed),r=random(seed);next.camera.yaw+= (r()-.5)*.14;next.camera.pitch+=(r()-.5)*.06;next.lights.forEach(function(l){l.position[0]+=(r()-.5)*.22;l.intensity*=.94+r()*.12;});next.post.exposure=Math.max(-2,Math.min(2,next.post.exposure+(r()-.5)*.12));return S.parse(next);}
  Object.assign(P,{catalog:D.entries,find:find,build:build,combine:combine,profile:profile,random:random,surprise:surprise,remix:remix,snapshot:snapshot,parse:S.preset,serialize:function(p){return JSON.stringify(S.ordered(S.preset(p)));},scenes:D.styles.map(function(x){return x[0];}),rigs:Object.keys(D.rigs),lights:function(name,tier){var aliases={Studio:'Three-point',Rim:'Rim and Fill',Noir:'Split Light','Neon Alley':'Practical Neon',Sunset:'Sunset Window',Showroom:'Butterfly',Vault:'Rembrandt'};return rig(aliases[name]||name).slice(0,S.limits(tier).lights);},apply:function(name,scene,tier,card,seed){name={Studio:'Dark Seamless','Sunset Desk':'Workbench',Void:'Eclipse'}[name]||name;var e=name==='Surprise me'?surprise(seed||'cardable'):find(name);return build(e,scene,card,seed);}});
})(window.Cardable);
