(function(C,root){
  'use strict';
  function mime(){if(!root.MediaRecorder||!root.HTMLCanvasElement.prototype.captureStream)return null;return ['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(function(type){return root.MediaRecorder.isTypeSupported(type);})||null;}
  function download(s){if(s.clip)return C.studioFiles.save(s.clip,'cardable-'+s.view.instance.serial+'-director').catch(function(e){s.api.status(e.message);});}
  function controls(s){if(!mime())return;C.studioUI.section(s,'Record a clip');C.studioUI.node('p','studio-copy',s.panel,'WebM · work area · current quality · up to 1080p / 60 fps · no audio.');if(s.recordJob)C.studioUI.button('Stop recording',s.panel,function(){s.recordJob.stop(false);});else C.studioUI.button('Record WebM',s.panel,function(){start(s);}).disabled=!!s.photoBusy||!s.faces;if(s.clip)C.studioUI.button('Download clip',s.panel,function(){download(s);});}
  function start(s,preset){var type=mime();if(!type||s.closing||s.photoBusy||s.recordJob||!s.renderer)return;
    preset=preset||{w:1920,h:1080,fps:30};var fps=preset.fps===60?60:30;var canvas=root.document.createElement('canvas'),ratio=preset.w/preset.h||C.studioCamera.aspect(s.scene.camera.aspect)||s.canvas.width/s.canvas.height,w=preset.w||Math.min(1920,Math.round(1080*ratio)),h=preset.h||Math.min(1080,Math.round(w/ratio));canvas.width=Math.max(2,w);canvas.height=Math.max(2,h);var g=canvas.getContext('2d',{alpha:false}),stream,recorder,job,buttons=[],chunks=[],bytes=0,deadline=null;
    try{stream=canvas.captureStream(0);var track=stream.getVideoTracks()[0];if(!track||typeof track.requestFrame!=='function'){stream.getTracks().forEach(function(t){t.stop();});stream=canvas.captureStream(fps);track=stream.getVideoTracks()[0];}recorder=new root.MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:6000000});
      job=s.recordJob={elapsed:0,started:root.performance.now(),last:-Infinity,duration:(s.scene.animation.workArea.out-s.scene.animation.workArea.in)/s.scene.animation.speed,done:false,cancelled:false};
      function release(){if(s.recordStop){s.recordStop.remove();s.recordStop=null;}root.clearTimeout(deadline);deadline=null;stream.getTracks().forEach(function(t){t.stop();});canvas.width=canvas.height=1;buttons.forEach(function(b){if(b.el.isConnected)b.el.disabled=b.disabled;});buttons.length=0;}
      function detach(){recorder.ondataavailable=recorder.onstop=recorder.onerror=null;chunks.length=0;}
      function finish(){release();if(s.recordJob===job)s.recordJob=null;if(!job.cancelled&&!s.closing&&s.root.isConnected&&chunks.length){s.clip=new root.Blob(chunks,{type:'video/webm'});C.events.emit('studio:clip',{cardId:s.view.card.id,instanceId:s.view.instance.instanceId,duration:job.elapsed,fps:fps,w:w,h:h,stepped:false,bytes:s.clip.size,at:Date.now()});s.api.status('Clip ready · '+job.elapsed.toFixed(1)+' seconds. Save it from Deliver.');}detach();if(!s.closing&&s.root.isConnected){s.director.pause();if(s.selected==='director')C.studioDirectorPanel(s);else if(s.selected==='photo')s.api.select('photo');s.api.dirty();}}
      job.stop=function(cancel){if(job.done){if(cancel)job.cancelled=true;return;}job.done=true;job.cancelled=!!cancel;s.director.pause();try{if(recorder.state!=='inactive')recorder.stop();else finish();}catch(_){job.cancelled=true;finish();}release();};
      job.frame=function(now,seconds){if(job.done)return;job.elapsed=(root.performance.now()-job.started)/1000;if(now-job.last>=1000/fps-.5){job.last=now;var cw=s.canvas.width,ch=s.canvas.height,sourceW=Math.min(cw,ch*ratio)*.9,sourceH=sourceW/ratio;g.drawImage(s.canvas,(cw-sourceW)/2,(ch-sourceH)/2,sourceW,sourceH,0,0,canvas.width,canvas.height);s.director.paintTitle(g,canvas.width,canvas.height);if(track.requestFrame)track.requestFrame();}s.api.status('Recording · '+job.elapsed.toFixed(1)+' / '+job.duration.toFixed(1)+' s');if(job.elapsed>=job.duration)job.stop(false);};
      recorder.ondataavailable=function(event){if(job.cancelled)return;if(event.data.size){bytes+=event.data.size;if(bytes>32000000){s.api.status('Recording stopped: clip memory limit reached.');job.stop(true);}else chunks.push(event.data);}};recorder.onstop=finish;recorder.onerror=function(){s.api.status('WebM recording is unavailable on this device.');job.stop(true);};
      s.clip=null;s.director.time=s.scene.animation.workArea.in;s.director.direction=1;if(!C.motion.reduced&&s.renderer.kind!=='Simple'&&!s.director.turntable&&s.director.hasAnimation()){s.director.preview=true;s.director.playing=true;}
      if(s.workspace&&s.root.dataset.mode==='simple'){s.recordStop=C.studioUI.button('Stop recording',s.root.querySelector('.studio-simple-captures'),function(){job.stop(false);});}else {s.recordStop=C.studioUI.button('Stop recording',s.root,function(){job.stop(false);});s.recordStop.classList.add('studio-record-stop');}s.root.querySelectorAll('button,input,select,textarea').forEach(function(el){if(el===s.exit||el.textContent==='Stop recording')return;buttons.push({el:el,disabled:el.disabled});el.disabled=true;});recorder.start(1000);deadline=root.setTimeout(function(){job.elapsed=job.duration;job.stop(false);},job.duration*1000);s.lastFrame=null;s.api.dirty();
    }catch(error){if(stream)stream.getTracks().forEach(function(t){t.stop();});canvas.width=canvas.height=1;buttons.forEach(function(b){b.el.disabled=b.disabled;});if(s.recordJob===job)s.recordJob=null;s.api.status('This browser could not start a WebM clip.');}
  }
  C.studioRecording={supported:function(){return !!mime();},controls:controls,start:start,download:download};
})(window.Cardable,window);
