(function (C, root) {
  'use strict';
  // Studio-owned WebGL utilities. No cutscene helper or shared GPU state is used.
  function slab() {
    var points = [], vertices = [];
    [[0.42, 0.62, 0], [-0.42, 0.62, Math.PI / 2], [-0.42, -0.62, Math.PI], [0.42, -0.62, Math.PI * 1.5]].forEach(function (corner) { for (var i = 0; i <= 10; i++) { var angle = corner[2] + i / 10 * Math.PI / 2; points.push([corner[0] + Math.cos(angle) * 0.08, corner[1] + Math.sin(angle) * 0.08]); } });
    function push(p, z, normal, face) { vertices.push(p[0], p[1], z, normal[0], normal[1], normal[2], p[0] + 0.5, p[1] / 1.4 + 0.5, face); }
    function tri(a, az, an, b, bz, bn, c, cz, cn, face) { push(a, az, an, face); push(b, bz, bn, face); push(c, cz, cn, face); }
    points.forEach(function (a, index) { var b = points[(index + 1) % points.length], ia = [a[0] * 0.985, a[1] * 0.989], ib = [b[0] * 0.985, b[1] * 0.989];
      tri([0, 0], 0.025, [0, 0, 1], ia, 0.025, [0, 0, 1], ib, 0.025, [0, 0, 1], 1);
      tri([0, 0], -0.025, [0, 0, -1], ib, -0.025, [0, 0, -1], ia, -0.025, [0, 0, -1], 0);
      var dx = b[0] - a[0], dy = b[1] - a[1], length = Math.hypot(dx, dy) || 1, n = [dy / length, -dx / length, 0];
      tri(a, 0, n, b, 0, n, ib, 0.025, [n[0] * 0.7, n[1] * 0.7, 0.7], 2); tri(a, 0, n, ib, 0.025, [n[0] * 0.7, n[1] * 0.7, 0.7], ia, 0.025, [n[0] * 0.7, n[1] * 0.7, 0.7], 2);
      tri(b, 0, n, a, 0, n, ia, -0.025, [n[0] * 0.7, n[1] * 0.7, -0.7], 2); tri(b, 0, n, ia, -0.025, [n[0] * 0.7, n[1] * 0.7, -0.7], ib, -0.025, [n[0] * 0.7, n[1] * 0.7, -0.7], 2);
    }); return new Float32Array(vertices);
  }
  var vertex = '#version 300 es\nprecision highp float;layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;layout(location=3)in float aFace;uniform mat4 uModel,uVP;out vec3 vWorld,vNormal;out vec2 vUV;flat out int vFace;void main(){vec4 world=uModel*vec4(aPosition,1.);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;vUV=aUV;vFace=int(aFace+.1);gl_Position=uVP*world;}';
  var fragment = '#version 300 es\nprecision highp float;in vec3 vWorld,vNormal;in vec2 vUV;flat in int vFace;out vec4 result;uniform sampler2D uFront,uBack,uNormal,uTags;uniform vec3 uEye,uLight,uColor;uniform float uIntensity;uniform mat4 uModel;void main(){if(vFace==3){vec4 tag=texture(uTags,vUV);if(tag.a<.1)discard;result=tag;return;}vec4 base=vFace==2?vec4(.25,.27,.3,1.):vFace==1?texture(uFront,vUV):texture(uBack,vec2(1.-vUV.x,vUV.y));if(base.a<.2)discard;vec3 n=normalize(vNormal);vec4 map=texture(uNormal,vUV);if(vFace==1)n=normalize(n+mat3(uModel)*vec3((map.xy*2.-1.)*.28,0.));vec3 l=normalize(uLight-vWorld),v=normalize(uEye-vWorld),h=normalize(l+v);float diffuse=max(dot(n,l),0.);float rough=vFace==2?.19:vFace==0?.34:mix(.21,.52,map.a);float spec=pow(max(dot(n,h),0.),mix(170.,18.,rough))*uIntensity;vec3 color=base.rgb*(.62+diffuse*uIntensity*.4*uColor)+uColor*spec*(vFace==2?.62:.16);float rim=pow(1.-max(dot(n,v),0.),3.)*diffuse;result=vec4(color+uColor*rim*.12,base.a);}';
  var backgroundVertex = '#version 300 es\nprecision highp float;out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}';
  var backgroundFragment = '#version 300 es\nprecision highp float;in vec2 uv;uniform vec3 uBackdrop;out vec4 result;void main(){float light=exp(-length((uv-vec2(.5,.55))*vec2(1.,.7))*3.);float floor=exp(-length((uv-vec2(.5,.12))*vec2(2.,5.))*6.);result=vec4(uBackdrop*(.65+light*1.5)+floor*.01,1.);}';
  function shader(gl, type, source) { var s = gl.createShader(type); gl.shaderSource(s, source); gl.compileShader(s); if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) { var reason = gl.getShaderInfoLog(s); gl.deleteShader(s); throw new Error(reason); } return s; }
  function program(gl, vs, fs) { var v, f, p; try { v = shader(gl, gl.VERTEX_SHADER, vs); f = shader(gl, gl.FRAGMENT_SHADER, fs); p = gl.createProgram(); gl.attachShader(p, v); gl.attachShader(p, f); gl.linkProgram(p); if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p)); return p; } catch (error) { if (p) gl.deleteProgram(p); throw error; } finally { if (v) gl.deleteShader(v); if (f) gl.deleteShader(f); } }
  C.studioRenderer = {
    create: function (canvas, faces, tier) {
      var gl = canvas.getContext('webgl2', { alpha: false, antialias: tier === 'high' || tier === 'medium', preserveDrawingBuffer: false, powerPreference: 'default' });
      if (!gl) return this.simple(canvas, faces);
      var material, backdrop, mesh, tags, textures = [], uniforms = {}, vertices = slab(), destroyed = false;
      function destroy() { if (destroyed) return; destroyed = true; textures.forEach(function (t) { gl.deleteTexture(t); }); if (material) gl.deleteProgram(material); if (backdrop) gl.deleteProgram(backdrop); if (mesh) gl.deleteBuffer(mesh); if (tags) gl.deleteBuffer(tags); var extension = gl.getExtension('WEBGL_lose_context'); if (extension) extension.loseContext(); canvas.width = canvas.height = 1; }
      try {
        material = program(gl, vertex, fragment); backdrop = program(gl, backgroundVertex, backgroundFragment);
        ['uModel', 'uVP', 'uEye', 'uLight', 'uColor', 'uIntensity', 'uFront', 'uBack', 'uNormal', 'uTags'].forEach(function (name) { uniforms[name] = gl.getUniformLocation(material, name); }); var backdropColor = gl.getUniformLocation(backdrop, 'uBackdrop');
        mesh = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, mesh); gl.bufferData(gl.ARRAY_BUFFER, vertices, gl.STATIC_DRAW);
        // Tags are a camera-facing label above the slab, like the detail tags.
        tags = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, tags); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-.5,.76,0,0,0,1,0,0,3, .5,.76,0,0,0,1,1,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.76,0,0,0,1,0,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.846,0,0,0,1,0,1,3]), gl.STATIC_DRAW);
        [faces.front, faces.back, faces.normal, faces.tags].forEach(function (face, unit) { var t = gl.createTexture(); textures.push(t); gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t); gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, face); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR); });
        function bind(buffer) { gl.bindBuffer(gl.ARRAY_BUFFER, buffer); [3, 3, 2, 1].forEach(function (size, index) { gl.enableVertexAttribArray(index); gl.vertexAttribPointer(index, size, gl.FLOAT, false, 36, [0, 12, 24, 32][index]); }); }
        return { canvas: canvas, kind: 'WebGL2', maxSize: Math.min(gl.getParameter(gl.MAX_TEXTURE_SIZE), gl.getParameter(gl.MAX_RENDERBUFFER_SIZE)),
          draw: function (scene, width, height) { if (destroyed) return; var ratios = { high: 2, medium: 1.5, low: 1.25, 'very-low': 1 }, dpr = Math.min(root.devicePixelRatio || 1, ratios[tier] || 1.5), pixels = { high: 2600000, medium: 1700000, low: 1100000, 'very-low': 800000 }; var scale = Math.min(dpr, Math.sqrt((pixels[tier] || 1700000) / Math.max(1, width * height))), w = Math.max(1, Math.round(width * scale)), h = Math.max(1, Math.round(height * scale)); if (canvas.width !== w || canvas.height !== h) { canvas.width = w; canvas.height = h; } gl.viewport(0, 0, w, h); gl.clearColor(0.03, 0.03, 0.04, 1); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT); gl.disable(gl.DEPTH_TEST); [0, 1, 2, 3].forEach(function (index) { gl.disableVertexAttribArray(index); }); gl.useProgram(backdrop); gl.uniform3fv(backdropColor, scene.backdrop.color); gl.drawArrays(gl.TRIANGLES, 0, 3);
            gl.enable(gl.DEPTH_TEST); gl.useProgram(material); var matrices = C.studioCamera.matrices(scene.camera, w / h, scene.card), light = scene.lights[0] || C.studioScenes.defaults().lights[0]; gl.uniformMatrix4fv(uniforms.uModel, false, matrices.model); gl.uniformMatrix4fv(uniforms.uVP, false, matrices.vp); gl.uniform3fv(uniforms.uEye, matrices.eye); gl.uniform3fv(uniforms.uLight, light.position); gl.uniform3fv(uniforms.uColor, light.color); gl.uniform1f(uniforms.uIntensity, light.intensity); ['uFront', 'uBack', 'uNormal', 'uTags'].forEach(function (name, index) { gl.uniform1i(uniforms[name], index); }); bind(mesh); gl.drawArrays(gl.TRIANGLES, 0, vertices.length / 9);
            var label = C.studioCamera.matrices(scene.camera, w / h, { tilt: [-scene.camera.pitch * 180 / Math.PI, scene.camera.yaw * 180 / Math.PI], side: 'front' }); gl.uniformMatrix4fv(uniforms.uModel, false, label.model); bind(tags); gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA); gl.drawArrays(gl.TRIANGLES, 0, 6); gl.disable(gl.BLEND);
          }, destroy: destroy };
      } catch (error) { destroy(); throw error; }
    },
    simple: function (canvas, faces) { var context = canvas.getContext('2d', { alpha: false }); if (!context) throw new Error('A canvas renderer is unavailable.'); return { canvas: canvas, kind: 'Simple', maxSize: 1920,
      draw: function (scene, width, height) { canvas.width = Math.max(1, Math.round(width)); canvas.height = Math.max(1, Math.round(height)); context.fillStyle = 'rgb(' + scene.backdrop.color.map(function (n) { return Math.round(n * 255); }).join(',') + ')'; context.fillRect(0, 0, width, height); var h = Math.min(height * .7 * 3 / scene.camera.distance, width * 1.12), w = h * 5 / 7; context.drawImage(scene.card.side === 'back' ? faces.back : faces.front, (width - w) / 2, (height - h) / 2, w, h); context.drawImage(faces.tags, (width - w) / 2, (height - h) / 2 - w * .1, w, w * .086); }, destroy: function () { canvas.width = canvas.height = 1; } }; }
  };
})(window.Cardable, window);
