(function (C, root) {
  'use strict';
  // All GPU objects belong to the open studio. No shared cutscene helpers/state.
  function slab() {
    var points = [], vertices = [];
    [[.42, .62, 0], [-.42, .62, Math.PI / 2], [-.42, -.62, Math.PI], [.42, -.62, Math.PI * 1.5]].forEach(function (corner) { for (var i = 0; i <= 10; i++) { var angle = corner[2] + i / 10 * Math.PI / 2; points.push([corner[0] + Math.cos(angle) * .08, corner[1] + Math.sin(angle) * .08]); } });
    function push(p, z, n, face) { vertices.push(p[0], p[1], z, n[0], n[1], n[2], p[0] + .5, p[1] / 1.4 + .5, face); }
    function tri(a, az, an, b, bz, bn, c, cz, cn, face) { push(a, az, an, face); push(b, bz, bn, face); push(c, cz, cn, face); }
    points.forEach(function (a, index) { var b = points[(index + 1) % points.length], ia = [a[0] * .985, a[1] * .989], ib = [b[0] * .985, b[1] * .989];
      tri([0, 0], .025, [0, 0, 1], ia, .025, [0, 0, 1], ib, .025, [0, 0, 1], 1); tri([0, 0], -.025, [0, 0, -1], ib, -.025, [0, 0, -1], ia, -.025, [0, 0, -1], 0);
      var dx = b[0] - a[0], dy = b[1] - a[1], len = Math.hypot(dx, dy) || 1, n = [dy / len, -dx / len, 0];
      tri(a, 0, n, b, 0, n, ib, .025, [n[0] * .7, n[1] * .7, .7], 2); tri(a, 0, n, ib, .025, [n[0] * .7, n[1] * .7, .7], ia, .025, [n[0] * .7, n[1] * .7, .7], 2);
      tri(b, 0, n, a, 0, n, ia, -.025, [n[0] * .7, n[1] * .7, -.7], 2); tri(b, 0, n, ia, -.025, [n[0] * .7, n[1] * .7, -.7], ib, -.025, [n[0] * .7, n[1] * .7, -.7], 2);
    }); return new Float32Array(vertices);
  }
  var header = '#version 300 es\nprecision highp float;\n';
  var vertex = header + 'layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;layout(location=3)in float aFace;uniform mat4 uModel,uVP;out vec3 vWorld,vNormal;out vec2 vUV;flat out int vFace;void main(){vec4 world=uModel*vec4(aPosition,1.);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;vUV=aUV;vFace=int(aFace+.1);gl_Position=uVP*world;}';
  var screen = header + 'out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}';
  var lighting = `
uniform int uCount,uShadowQuality; uniform vec4 uPos[8],uDir[8],uColor[8],uExtra[8],uBottom[8],uShadow[8]; uniform mat4 uInverseModel; uniform vec3 uEye;
vec3 rightOf(vec3 d){return normalize(cross(abs(d.y)>.95?vec3(1,0,0):vec3(0,1,0),d));}
float obstruction(vec3 p,vec3 l,float distance){vec3 a=(uInverseModel*vec4(p,1)).xyz,b=mat3(uInverseModel)*l;if(abs(b.z)<.00001)return 1.;float t=-a.z/b.z;if(t<.001||t>distance)return 1.;vec2 q=abs((a+b*t).xy)-vec2(.42,.62);float edge=length(max(q,0.))+min(max(q.x,q.y),0.)-.08;return smoothstep(-.003,.003,edge);}
float maskGobo(vec2 q,float pattern,float soft){float aa=max(.02,soft*.08);if(pattern<.5)return 1.;if(pattern<1.5)return mix(.12,1.,smoothstep(.25-aa,.25+aa,abs(sin(q.y*22.))));if(pattern<2.5)return mix(.12,1.,smoothstep(.22-aa,.22+aa,min(abs(sin(q.x*18.)),abs(sin(q.y*18.)))));vec2 cell=fract(q*5.)-.5;if(pattern<3.5){cell=mat2(.8,-.6,.6,.8)*cell;return mix(.12,1.,1.-smoothstep(.85-aa,.85+aa,length(cell/vec2(.38,.17))));}float a=atan(cell.y,cell.x),radius=.22+.1*cos(a*5.);return mix(.12,1.,1.-smoothstep(radius-aa,radius+aa,length(cell)));}
void illuminate(vec3 p,vec3 n,float rough,bool receiver,out vec3 diffuse,out vec3 specular){diffuse=vec3(.18);specular=vec3(0);vec3 v=normalize(uEye-p);
 for(int i=0;i<8;i++){if(i>=uCount)break;int kind=int(uPos[i].w+.1);vec3 color=uColor[i].rgb*uColor[i].a;
 if(kind==5){diffuse+=mix(uBottom[i].rgb,uColor[i].rgb,n.y*.5+.5)*uColor[i].a;continue;}
 vec3 direction=normalize(uDir[i].xyz),right=rightOf(direction),up=cross(direction,right);float cs=cos(uShadow[i].y),sn=sin(uShadow[i].y);vec3 axis=right*cs+up*sn;up=up*cs-right*sn;right=axis;
 int samples=(kind==3||kind==4||receiver&&uShadowQuality==2)?4:1;
 for(int s=0;s<4;s++){if(s>=samples)break;vec2 offsets=vec2((s==0||s==2)?-.5:.5,(s<2)?-.5:.5);float size=(kind==3||kind==4)?uExtra[i].x*(receiver?.25+uShadow[i].x*.75:1.):receiver?uShadow[i].x*.35:0.;vec3 source=uPos[i].xyz+right*offsets.x*size+up*offsets.y*size*(kind==4?.12:.6);
 vec3 delta=kind==2?-direction+(receiver&&uShadowQuality==2?(right*offsets.x+up*offsets.y)*uShadow[i].x*.08:vec3(0)):source-p;float distance=kind==2?100.:length(delta);vec3 l=normalize(delta);float attenuation=kind==2?1.:4./(1.+(abs(uExtra[i].y-2.)<.001?distance*distance:pow(max(distance,.1),uExtra[i].y)));
 if(kind==1){float cone=dot(-l,direction),outer=uDir[i].w,inner=mix(outer,1.,max(uExtra[i].z,.01));attenuation*=smoothstep(outer,inner,cone);vec3 d=p-source;vec2 q=vec2(dot(d,right),dot(d,up))/max(.1,dot(d,direction));attenuation*=maskGobo(q,uExtra[i].w,uExtra[i].z);}
 if(kind==3||kind==4)attenuation*=max(.05,dot(-l,direction));float shadow=receiver&&uShadowQuality>0&&uBottom[i].w>.5?obstruction(p,l,distance):1.;float lambert=max(dot(n,l),0.);diffuse+=color*lambert*attenuation*shadow/float(samples);if(!receiver){vec3 h=normalize(l+v);float spec=pow(max(dot(n,h),0.),mix(180.,12.,clamp(rough+uExtra[i].x*.04,0.,1.)));specular+=color*spec*attenuation*shadow/float(samples);}
 }} }
`;
  var fragment = header + lighting + `
in vec3 vWorld,vNormal;in vec2 vUV;flat in int vFace;out vec4 result;uniform sampler2D uFront,uBack,uNormal,uTags;uniform mat4 uModel;
void main(){if(vFace==3){vec4 tag=texture(uTags,vUV);if(tag.a<.1)discard;result=tag;return;}vec4 base=vFace==2?vec4(.25,.27,.3,1.):vFace==1?texture(uFront,vUV):texture(uBack,vec2(1.-vUV.x,vUV.y));if(base.a<.2)discard;vec3 n=normalize(vNormal);vec4 map=texture(uNormal,vUV);if(vFace==1)n=normalize(n+mat3(uModel)*vec3((map.xy*2.-1.)*.28,0.));float rough=vFace==2?.16:vFace==0?.34:mix(.2,.58,map.a);vec3 d,s;illuminate(vWorld,n,rough,false,d,s);float fresnel=pow(1.-max(dot(n,normalize(uEye-vWorld)),0.),3.);result=vec4(base.rgb*(.35+d*.6)+s*(vFace==2?.65:.26)+d*fresnel*.06,base.a);}`;
  var background = header + lighting + `
in vec2 uv;uniform vec3 uBackdrop;uniform mat4 uInverseVP,uVP;out vec4 result;
void main(){vec4 farPoint=uInverseVP*vec4(uv*2.-1.,1,1);vec3 ray=normalize(farPoint.xyz/farPoint.w-uEye);float floorT=abs(ray.y)>.00001?(-.9-uEye.y)/ray.y:1000.;float wallT=abs(ray.z)>.00001?(-1.6-uEye.z)/ray.z:1000.;if(floorT<0.)floorT=1000.;if(wallT<0.)wallT=1000.;bool floorPlane=floorT<wallT;float t=min(floorT,wallT);vec3 p=uEye+ray*min(t,100.),n=floorPlane?vec3(0,1,0):vec3(0,0,1);vec3 d,s;illuminate(p,n,.9,true,d,s);float gradient=exp(-length((uv-vec2(.5,.55))*vec2(1.,.7))*3.);result=vec4(uBackdrop*(.4+gradient*.8+d*.65)+s*.008,1.);vec4 clip=uVP*vec4(p,1.);gl_FragDepth=t<60.?clamp(clip.z/clip.w*.5+.5,0.,1.):1.;}`;
  var filter = header + `in vec2 uv;out vec4 result;uniform sampler2D uImage;uniform vec2 uStep;uniform int uThreshold;void main(){vec3 c=texture(uImage,uv).rgb*.227027;for(int i=1;i<5;i++){float weight=i==1?.1945946:i==2?.1216216:i==3?.054054:.016216;vec2 d=uStep*float(i);c+=(texture(uImage,uv+d).rgb+texture(uImage,uv-d).rgb)*weight;}if(uThreshold==1)c=max(c-vec3(.62),0.);result=vec4(c,1.);}`;
  var composite = header + `
in vec2 uv;out vec4 result;uniform sampler2D uImage,uDepth,uBloom;uniform vec2 uPixel,uFlareAt;uniform vec3 uFlareColor;uniform vec4 uPost,uLens;uniform float uFocus,uAperture;uniform int uDOF;
float distanceAt(vec2 p){float z=texture(uDepth,p).r*2.-1.;return 6./(60.05-z*59.95);}
void main(){vec2 radial=uv-.5,shift=radial*uLens.y*.006;vec3 base=vec3(texture(uImage,uv+shift).r,texture(uImage,uv).g,texture(uImage,uv-shift).b);float radius=0.;if(uDOF==1){radius=clamp(abs(distanceAt(uv)-uFocus)/max(.1,distanceAt(uv))*uAperture*5.,0.,14.);radius=max(radius,abs(uv.y-.5)*uLens.w*16.);}
if(radius>.2){vec3 sum=base;float weight=1.;for(int i=0;i<12;i++){float angle=float(i)*2.399963;vec2 p=clamp(uv+vec2(cos(angle),sin(angle))*sqrt((float(i)+.5)/12.)*radius*uPixel,vec2(0),vec2(1));float w=smoothstep(.03,.25,distanceAt(p)-distanceAt(uv)+.25);sum+=texture(uImage,p).rgb*w;weight+=w;}base=sum/weight;}
base+=texture(uBloom,uv).rgb*uPost.y;float flare=0.;vec2 axis=.5-uFlareAt;for(int i=0;i<3;i++){vec2 at=uFlareAt+axis*(1.3+float(i)*.8);flare+=exp(-length(uv-at)*(26.+float(i)*9.))*.035;}base+=uFlareColor*flare*uLens.z;base*=exp2(uPost.x);base=base/(1.+max(base-1.,0.));base*=1.-uPost.z*smoothstep(.1,.7,length(radial));float noise=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453)-.5;base+=noise*uPost.w*.16;result=vec4(clamp(base,0.,1.),1.);}`;
  function shader(gl, type, source) { var s = gl.createShader(type); gl.shaderSource(s, source); gl.compileShader(s); if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) { var reason = gl.getShaderInfoLog(s); gl.deleteShader(s); throw new Error(reason); } return s; }
  function program(gl, vs, fs) { var v, f, p; try { v = shader(gl, gl.VERTEX_SHADER, vs); f = shader(gl, gl.FRAGMENT_SHADER, fs); p = gl.createProgram(); gl.attachShader(p, v); gl.attachShader(p, f); gl.linkProgram(p); if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p)); return p; } catch (error) { if (p) gl.deleteProgram(p); throw error; } finally { if (v) gl.deleteShader(v); if (f) gl.deleteShader(f); } }
  C.studioRenderer = {
    create: function (canvas, faces, tier) {
      var gl = canvas.getContext('webgl2', { alpha: false, antialias: false, preserveDrawingBuffer: false, powerPreference: 'default' }); if (!gl) return this.simple(canvas, faces);
      var textures = [], programs = [], buffers = [], arrays = [], targets = [], destroyed = false, size = '', vertices = slab(), full = tier === 'high', bloomEnabled = full || tier === 'medium', maxSize = Math.min(gl.getParameter(gl.MAX_TEXTURE_SIZE), gl.getParameter(gl.MAX_RENDERBUFFER_SIZE));
      function destroy() { if (destroyed) return; destroyed = true; textures.forEach(function (t) { gl.deleteTexture(t); }); programs.forEach(function (p) { gl.deleteProgram(p.id); }); buffers.forEach(function (b) { gl.deleteBuffer(b); }); arrays.forEach(function (a) { gl.deleteVertexArray(a); }); targets.forEach(function (t) { gl.deleteFramebuffer(t.fbo); }); var extension = gl.getExtension('WEBGL_lose_context'); if (extension) extension.loseContext(); canvas.width = canvas.height = 1; }
      function makeProgram(vs, fs) { var p = { id: program(gl, vs, fs), locations: {} }; programs.push(p); return p; }
      function location(p, name) { if (!(name in p.locations)) p.locations[name] = gl.getUniformLocation(p.id, name); return p.locations[name]; }
      function uniform(p, name, method, value) { gl[method](location(p, name), value); }
      function matrix(p, name, value) { gl.uniformMatrix4fv(location(p, name), false, value); }
      function texture(source, unit, depth) { var t = gl.createTexture(); textures.push(t); gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, depth ? gl.NEAREST : gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, depth ? gl.NEAREST : gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); if (source) { gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, source); gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false); } return t; }
      function target(depth) { var t = { fbo: gl.createFramebuffer(), color: texture(null, 4), depth: depth ? texture(null, 5, true) : null }; targets.push(t); return t; }
      function resize(t, w, h) { t.w = w; t.h = h; gl.bindTexture(gl.TEXTURE_2D, t.color); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, w, h, 0, gl.RGBA, gl.UNSIGNED_BYTE, null); gl.bindFramebuffer(gl.FRAMEBUFFER, t.fbo); gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, t.color, 0); if (t.depth) { gl.bindTexture(gl.TEXTURE_2D, t.depth); gl.texImage2D(gl.TEXTURE_2D, 0, gl.DEPTH_COMPONENT24, w, h, 0, gl.DEPTH_COMPONENT, gl.UNSIGNED_INT, null); gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, gl.TEXTURE_2D, t.depth, 0); } if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.FRAMEBUFFER_COMPLETE) throw new Error('Studio render target unavailable.'); }
      function bindTexture(t, unit) { gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t); }
      function geometry(data) { var array = gl.createVertexArray(), buffer = gl.createBuffer(); arrays.push(array); buffers.push(buffer); gl.bindVertexArray(array); gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW); [3, 3, 2, 1].forEach(function (n, i) { gl.enableVertexAttribArray(i); gl.vertexAttribPointer(i, n, gl.FLOAT, false, 36, [0, 12, 24, 32][i]); }); return array; }
      function lights(p, scene, m) { var positions = [], directions = [], colors = [], extras = [], bottoms = [], shadows = []; scene.lights.forEach(function (l) { positions.push.apply(positions, l.position.concat(C.studioLights.types.indexOf(l.type))); directions.push.apply(directions, C.studioLights.direction(l).concat(Math.cos(l.angle * Math.PI / 360))); colors.push.apply(colors, l.color.concat(l.intensity)); extras.push(l.size, l.falloff, l.softness, ['none', 'blinds', 'grid', 'leaves', 'stars'].indexOf(l.gobo)); bottoms.push.apply(bottoms, l.bottom.concat(l.shadows ? 1 : 0)); shadows.push(l.shadowSoftness, l.rotation[2] * Math.PI / 180, 0, 0); });
        uniform(p, 'uCount', 'uniform1i', scene.lights.length); uniform(p, 'uShadowQuality', 'uniform1i', full ? 2 : tier === 'medium' ? 1 : 0); if (positions.length) { [['uPos[0]', positions], ['uDir[0]', directions], ['uColor[0]', colors], ['uExtra[0]', extras], ['uBottom[0]', bottoms], ['uShadow[0]', shadows]].forEach(function (v) { uniform(p, v[0], 'uniform4fv', v[1]); }); } matrix(p, 'uInverseModel', m.inverseModel); uniform(p, 'uEye', 'uniform3fv', m.eye);
      }
      try {
        var material = makeProgram(vertex, fragment), stage = makeProgram(screen, background), blur = makeProgram(screen, filter), post = makeProgram(screen, composite), mesh = geometry(vertices), tags = geometry(new Float32Array([-.5,.76,0,0,0,1,0,0,3, .5,.76,0,0,0,1,1,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.76,0,0,0,1,0,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.846,0,0,0,1,0,1,3]));
        var facesGPU = [faces.front, faces.back, faces.normal, faces.tags].map(function (source, i) { return texture(source, i); }), sceneTarget = target(true), bloomA = target(false), bloomB = target(false), empty = texture(null, 6); gl.bindTexture(gl.TEXTURE_2D, empty); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array([0, 0, 0, 255]));
        function filterPass(from, to, step, threshold) { gl.bindFramebuffer(gl.FRAMEBUFFER, to.fbo); gl.viewport(0, 0, to.w, to.h); gl.useProgram(blur.id); bindTexture(from.color, 4); uniform(blur, 'uImage', 'uniform1i', 4); uniform(blur, 'uStep', 'uniform2fv', step); uniform(blur, 'uThreshold', 'uniform1i', threshold); gl.drawArrays(gl.TRIANGLES, 0, 3); }
        return { canvas: canvas, kind: 'WebGL2', maxSize: maxSize,
          draw: function (scene, width, height) { if (destroyed) return; var dpr = Math.min(root.devicePixelRatio || 1, { high: 2, medium: 1.5, low: 1.25 }[tier] || 1), scale = Math.min(dpr, Math.sqrt(({ high: 2600000, medium: 1700000, low: 1100000 }[tier] || 1100000) / Math.max(1, width * height)), maxSize / Math.max(width, height)), w = Math.max(1, Math.round(width * scale)), h = Math.max(1, Math.round(height * scale));
            if (size !== w + ':' + h) { size = w + ':' + h; canvas.width = w; canvas.height = h; resize(sceneTarget, w, h); if (bloomEnabled) { resize(bloomA, Math.max(1, Math.ceil(w / 4)), Math.max(1, Math.ceil(h / 4))); resize(bloomB, bloomA.w, bloomA.h); } }
            var m = C.studioCamera.matrices(scene.camera, w / h, scene.card); gl.bindFramebuffer(gl.FRAMEBUFFER, sceneTarget.fbo); gl.viewport(0, 0, w, h); gl.clearColor(.03, .03, .04, 1); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT); gl.bindVertexArray(null); gl.enable(gl.DEPTH_TEST); gl.useProgram(stage.id); lights(stage, scene, m); uniform(stage, 'uBackdrop', 'uniform3fv', scene.backdrop.color); matrix(stage, 'uInverseVP', m.inverseVP); matrix(stage, 'uVP', m.vp); gl.drawArrays(gl.TRIANGLES, 0, 3);
            gl.useProgram(material.id); lights(material, scene, m); matrix(material, 'uModel', m.model); matrix(material, 'uVP', m.vp); facesGPU.forEach(bindTexture); ['uFront', 'uBack', 'uNormal', 'uTags'].forEach(function (name, i) { uniform(material, name, 'uniform1i', i); }); gl.bindVertexArray(mesh); gl.drawArrays(gl.TRIANGLES, 0, vertices.length / 9);
            var label = C.studioCamera.matrices(scene.camera, w / h, { tilt: [-scene.camera.pitch * 180 / Math.PI, scene.camera.yaw * 180 / Math.PI], side: 'front' }); matrix(material, 'uModel', label.model); gl.bindVertexArray(tags); gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA); gl.drawArrays(gl.TRIANGLES, 0, 6); gl.disable(gl.BLEND); gl.disable(gl.DEPTH_TEST); gl.bindVertexArray(null);
            var hasBloom = bloomEnabled && scene.post.bloom > 0; if (hasBloom) { filterPass(sceneTarget, bloomA, [1 / w, 1 / h], 1); filterPass(bloomA, bloomB, [1 / bloomA.w, 0], 0); filterPass(bloomB, bloomA, [0, 1 / bloomA.h], 0); }
            gl.bindFramebuffer(gl.FRAMEBUFFER, null); gl.viewport(0, 0, w, h); gl.useProgram(post.id); bindTexture(sceneTarget.color, 4); bindTexture(sceneTarget.depth, 5); bindTexture(hasBloom ? bloomA.color : empty, 6); uniform(post, 'uImage', 'uniform1i', 4); uniform(post, 'uDepth', 'uniform1i', 5); uniform(post, 'uBloom', 'uniform1i', 6); uniform(post, 'uPixel', 'uniform2fv', [1 / w, 1 / h]); uniform(post, 'uPost', 'uniform4fv', [scene.post.exposure, hasBloom ? scene.post.bloom : 0, scene.post.vignette, scene.post.grain]); uniform(post, 'uLens', 'uniform4fv', [0, scene.post.aberration, scene.post.flare, full ? scene.post.tiltShift : 0]); uniform(post, 'uDOF', 'uniform1i', full ? 1 : 0); uniform(post, 'uAperture', 'uniform1f', full ? scene.camera.aperture : 0); var focus = scene.camera.focus.map(function (n, i) { return m.eye[i] - n; }); uniform(post, 'uFocus', 'uniform1f', Math.max(.05, C.studioCamera.dot(focus, m.basis.back))); var key = scene.lights.find(function (l) { return l.type !== 'ambient'; }), flareAt = key && C.studioCamera.project(m, key.position); uniform(post, 'uFlareAt', 'uniform2fv', flareAt && flareAt.front ? [flareAt.x, 1 - flareAt.y] : [-4, -4]); uniform(post, 'uFlareColor', 'uniform3fv', key ? key.color.map(function (n) { return n * Math.min(key.intensity, 3); }) : [0, 0, 0]); gl.drawArrays(gl.TRIANGLES, 0, 3);
          }, destroy: destroy };
      } catch (error) { destroy(); throw error; }
    },
    simple: function (canvas, faces) { var context = canvas.getContext('2d', { alpha: false }); if (!context) throw new Error('A canvas renderer is unavailable.'); return { canvas: canvas, kind: 'Simple', maxSize: 1920,
      draw: function (scene, width, height) { canvas.width = Math.max(1, Math.round(width)); canvas.height = Math.max(1, Math.round(height)); context.fillStyle = 'rgb(' + scene.backdrop.color.map(function (n) { return Math.round(n * 255); }).join(',') + ')'; context.fillRect(0, 0, width, height); var h = Math.min(height * .7 * 3 / scene.camera.distance, width * 1.12), w = h * 5 / 7, x = (width - w) / 2, y = (height - h) / 2, l = scene.lights[0]; context.save(); context.translate(width / 2, height / 2); context.rotate(-scene.camera.roll); context.translate(-width / 2, -height / 2); context.save(); context.beginPath(); context.roundRect(x, y, w, h, w * .045); context.clip(); context.filter = 'brightness(' + Math.max(.2, Math.min(2, l ? .45 + l.intensity * .4 : .45)) * Math.pow(2, scene.post.exposure) + ')'; context.drawImage(scene.card.side === 'back' ? faces.back : faces.front, x, y, w, h); context.filter = 'none'; if (l) { context.globalCompositeOperation = 'source-atop'; context.fillStyle = 'rgba(' + l.color.map(function (n) { return Math.round(n * 255); }).join(',') + ',.1)'; context.fillRect(x, y, w, h); context.globalCompositeOperation = 'source-over'; } context.restore(); context.drawImage(faces.tags, x, y - w * .1, w, w * .086); context.restore(); }, destroy: function () { canvas.width = canvas.height = 1; } };
    }
  };
})(window.Cardable, window);
