(function (C, root) {
  'use strict';
  // All GPU objects belong to the open studio. No shared cutscene helpers/state.
  function slab() {
    var points = [], vertices = [];
    [[.42, .62, 0], [-.42, .62, Math.PI / 2], [-.42, -.62, Math.PI], [.42, -.62, Math.PI * 1.5]].forEach(function (corner) { for (var i = 0; i <= 10; i++) { var angle = corner[2] + i / 10 * Math.PI / 2; points.push([corner[0] + Math.cos(angle) * .08, corner[1] + Math.sin(angle) * .08]); } });
    function push(p, z, n, face) { vertices.push(p[0], p[1], z, n[0], n[1], n[2], p[0] + .5, p[1] / 1.4 + .5, face); }
    function tri(a, az, an, b, bz, bn, c, cz, cn, face) { push(a, az, an, face); push(b, bz, bn, face); push(c, cz, cn, face); }
    points.forEach(function (a, index) { var b = points[(index + 1) % points.length], ia = [a[0] * .985, a[1] * .989], ib = [b[0] * .985, b[1] * .989];
      tri([0, 0], .025, [0, 0, 1], ia, .025, [0, 0, 1], ib, .025, [0, 0, 1], 1); tri([0, 0], -.025, [0, 0, -1], ib, -.025, [0, 0, -1], ia, -.025, [0, 0, -1], 0);
      var dx = b[0] - a[0], dy = b[1] - a[1], len = Math.hypot(dx, dy) || 1, n = [dy / len, -dx / len, 0];
      tri(a, 0, n, b, 0, n, ib, .025, [n[0] * .7, n[1] * .7, .7], 2); tri(a, 0, n, ib, .025, [n[0] * .7, n[1] * .7, .7], ia, .025, [n[0] * .7, n[1] * .7, .7], 2);
      tri(b, 0, n, a, 0, n, ia, -.025, [n[0] * .7, n[1] * .7, -.7], 2); tri(b, 0, n, ia, -.025, [n[0] * .7, n[1] * .7, -.7], ib, -.025, [n[0] * .7, n[1] * .7, -.7], 2);
    }); return new Float32Array(vertices);
  }
  var header = '#version 300 es\nprecision highp float;\nprecision highp int;\n';
  var vertex = header + 'layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;layout(location=3)in float aFace;uniform mat4 uModel,uVP;out vec3 vWorld,vNormal;out vec2 vUV;flat out int vFace;void main(){vec4 world=uModel*vec4(aPosition,1.);vWorld=world.xyz;vNormal=transpose(inverse(mat3(uModel)))*aNormal;vUV=aUV;vFace=int(aFace+.1);gl_Position=uVP*world;}';
  var screen = header + 'out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}';
  var lighting = `
uniform int uShadowQuality;uniform highp sampler2D uKeyDepth;uniform mat4 uLightVP;uniform int uKeyShadow,uKeyIndex,uCardVisible;uniform vec2 uShadowPixel;
float keyShadow(vec3 p){if(uKeyShadow==0)return 1.;vec4 q=uLightVP*vec4(p,1.);vec3 v=q.xyz/q.w*.5+.5;if(any(lessThan(v,vec3(0)))||any(greaterThan(v,vec3(1))))return 1.;float sum=0.;for(int j=0;j<4;j++){if(j>0&&uShadowQuality<2)break;vec2 d=vec2(j%2==0?-.6:.6,j<2?-.6:.6)*uShadowPixel;sum+=v.z-.002<texture(uKeyDepth,v.xy+d).r?1.:.18;}return sum/(uShadowQuality==2?4.:1.);}
uniform int uCount; uniform vec4 uPos[8],uDir[8],uColor[8],uExtra[8],uBottom[8],uShadow[8]; uniform mat4 uInverseModel; uniform vec3 uEye;
vec3 rightOf(vec3 d){return normalize(cross(abs(d.y)>.95?vec3(1,0,0):vec3(0,1,0),d));}
float obstruction(vec3 p,vec3 l,float distance){if(uCardVisible==0)return 1.;vec3 a=(uInverseModel*vec4(p,1)).xyz,b=mat3(uInverseModel)*l;if(abs(b.z)<.00001)return 1.;float t=-a.z/b.z;if(t<.001||t>distance)return 1.;vec2 q=abs((a+b*t).xy)-vec2(.42,.62);float edge=length(max(q,0.))+min(max(q.x,q.y),0.)-.08;return smoothstep(-.003,.003,edge);}
float maskGobo(vec2 q,float pattern,float soft){float aa=max(.02,soft*.08);if(pattern<.5)return 1.;if(pattern<1.5)return mix(.12,1.,smoothstep(.25-aa,.25+aa,abs(sin(q.y*22.))));if(pattern<2.5)return mix(.12,1.,smoothstep(.22-aa,.22+aa,min(abs(sin(q.x*18.)),abs(sin(q.y*18.)))));vec2 cell=fract(q*5.)-.5;if(pattern<3.5){cell=mat2(.8,-.6,.6,.8)*cell;return mix(.12,1.,1.-smoothstep(.85-aa,.85+aa,length(cell/vec2(.38,.17))));}float a=atan(cell.y,cell.x),radius=.22+.1*cos(a*5.);return mix(.12,1.,1.-smoothstep(radius-aa,radius+aa,length(cell)));}
void illuminate(vec3 p,vec3 n,float rough,bool receiver,out vec3 diffuse,out vec3 specular){diffuse=vec3(.18);specular=vec3(0);vec3 v=normalize(uEye-p);
 for(int i=0;i<8;i++){if(i>=uCount)break;int kind=int(uPos[i].w+.1);vec3 color=uColor[i].rgb*uColor[i].a;
 if(kind==5){diffuse+=mix(uBottom[i].rgb,uColor[i].rgb,n.y*.5+.5)*uColor[i].a;continue;}
 vec3 direction=normalize(uDir[i].xyz),right=rightOf(direction),up=cross(direction,right);float cs=cos(uShadow[i].y),sn=sin(uShadow[i].y);vec3 axis=right*cs+up*sn;up=up*cs-right*sn;right=axis;
 int samples=(kind==3||kind==4||receiver&&uShadowQuality==2)?4:1;
 for(int s=0;s<4;s++){if(s>=samples)break;vec2 offsets=vec2((s==0||s==2)?-.5:.5,(s<2)?-.5:.5);float size=(kind==3||kind==4)?uExtra[i].x*(receiver?.25+uShadow[i].x*.75:1.):receiver?uShadow[i].x*.35:0.;vec3 source=uPos[i].xyz+right*offsets.x*size+up*offsets.y*size*(kind==4?.12:.6);
 vec3 delta=kind==2?-direction+(receiver&&uShadowQuality==2?(right*offsets.x+up*offsets.y)*uShadow[i].x*.08:vec3(0)):source-p;float distance=kind==2?100.:length(delta);vec3 l=normalize(delta);float attenuation=kind==2?1.:4./(1.+(abs(uExtra[i].y-2.)<.001?distance*distance:pow(max(distance,.1),uExtra[i].y)));
 if(kind==1){float cone=dot(-l,direction),outer=uDir[i].w,inner=mix(outer,1.,max(uExtra[i].z,.01));attenuation*=smoothstep(outer,inner,cone);vec3 d=p-source;vec2 q=vec2(dot(d,right),dot(d,up))/max(.1,dot(d,direction));attenuation*=maskGobo(q,uExtra[i].w,uExtra[i].z);}
 if(kind==3||kind==4)attenuation*=max(.05,dot(-l,direction));float shadow=receiver&&uShadowQuality>0&&uBottom[i].w>.5?obstruction(p,l,distance):1.;if(i==uKeyIndex)shadow*=keyShadow(p);float lambert=max(dot(n,l),0.);diffuse+=color*lambert*attenuation*shadow/float(samples);if(!receiver){vec3 h=normalize(l+v);float spec=pow(max(dot(n,h),0.),mix(180.,12.,clamp(rough+uExtra[i].x*.04,0.,1.)));specular+=color*spec*attenuation*shadow/float(samples);}
 }} }
`;
  var fragment = header + lighting + C.studioMaterials.shader() + `
in vec3 vWorld,vNormal;in vec2 vUV;flat in int vFace;out vec4 result;uniform sampler2D uFront,uBack,uNormal,uTags;uniform mat4 uModel;
void main(){if(vFace==3){vec4 tag=texture(uTags,vUV);if(tag.a<.1)discard;result=tag;return;}vec4 base=vFace==2?vec4(.25,.27,.3,1.):vFace==1?texture(uFront,vUV):texture(uBack,vec2(1.-vUV.x,vUV.y));if(base.a<.2)discard;vec3 n=normalize(vNormal);vec4 map=texture(uNormal,vUV);if(vFace==1)n=normalize(n+mat3(uModel)*vec3((map.xy*2.-1.)*.28,0.));float rough=vFace==2?.16:vFace==0?.34:mix(.2,.58,map.a);if(vFace==1&&uVariant==4)rough=mix(rough,.94,innerMask(vUV));vec3 d,s;illuminate(vWorld,n,rough,false,d,s);if(vFace==1){base.rgb=studioSurface(base.rgb,vUV,n,normalize(uEye-vWorld),d,s);if(uVariant==4)s*=1.-innerMask(vUV);}float fresnel=pow(1.-max(dot(n,normalize(uEye-vWorld)),0.),3.);result=vec4(base.rgb*(.35+d*.6)+s*(vFace==2?.65:.26)+d*fresnel*.06,base.a);}`;
  var background = header + lighting + `
in vec2 uv;uniform vec4 uView;uniform vec3 uBackdrop;uniform mat4 uInverseVP,uVP;out vec4 result;
void main(){vec4 farPoint=uInverseVP*vec4(uv*2.-1.,1,1);vec4 nearPoint=uInverseVP*vec4(uv*2.-1.,-1,1);vec3 origin=nearPoint.xyz/nearPoint.w;vec3 ray=normalize(farPoint.xyz/farPoint.w-origin);float floorT=abs(ray.y)>.00001?(-.9-origin.y)/ray.y:1000.;float wallT=abs(ray.z)>.00001?(-1.6-origin.z)/ray.z:1000.;if(floorT<0.)floorT=1000.;if(wallT<0.)wallT=1000.;bool floorPlane=floorT<wallT;float t=min(floorT,wallT);vec3 p=origin+ray*min(t,100.),n=floorPlane?vec3(0,1,0):vec3(0,0,1);vec3 d,s;illuminate(p,n,.9,true,d,s);float gradient=exp(-length((uView.xy+uv*uView.zw-vec2(.5,.55))*vec2(1.,.7))*3.);result=vec4(uBackdrop*(.4+gradient*.8+d*.65)+s*.008,1.);vec4 clip=uVP*vec4(p,1.);gl_FragDepth=t<60.?clamp(clip.z/clip.w*.5+.5,0.,1.):1.;}`;
  var propVertex = header + 'layout(location=0)in vec3 aPosition;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;layout(location=3)in float aFace;uniform mat4 uModel,uVP;uniform float uTime;uniform int uEffect,uSpin;uniform vec3 uRight,uUp;out vec3 vWorld,vNormal;out vec2 vUV;flat out int vFace;void main(){vec3 p=aPosition,n=aNormal;vUV=aUV;vFace=int(aFace+.1);if(uSpin>0&&vFace==9){float a=uTime*3.,c=cos(a),s=sin(a);if(uSpin==1){p.xy=mat2(c,s,-s,c)*p.xy;n.xy=mat2(c,s,-s,c)*n.xy;}else{p.xz=mat2(c,s,-s,c)*p.xz;n.xz=mat2(c,s,-s,c)*n.xz;}}if(uEffect>0){vUV=p.xy*.5+.5;vec3 seed=aNormal;float t=uTime;vec3 center=(seed-.5)*vec3(3.,2.,2.);float size=.018;if(uEffect==1||uEffect==8){center.y+=.18*sin(t*.2+seed.x*6.);size=uEffect==1?1.1:.42;center.y+=uEffect==8?mod(t*.2+seed.y,1.)-.5:0.;}else if(uEffect==3){float age=fract(t*.5+seed.y);center=vec3((seed.x-.5)*age,age*1.7-.8-age*age*.7,(seed.z-.5)*age);size=.012;}else if(uEffect==4){center.y=.9-mod(t*.3+seed.y*2.,2.);center.x+=.16*sin(t+seed.z*10.);size=.025;}else if(uEffect==5){center.y=1.-mod(t*.22+seed.y*2.,2.);center.x+=.14*sin(t*.7+seed.z*10.);size=.016;}else if(uEffect==6){center.y=1.-mod(t*1.6+seed.y*2.,2.);size=.009;p.y*=7.;}else if(uEffect==7){center+=vec3(sin(t*.6+seed.x*9.),cos(t*.4+seed.y*10.),sin(t*.3+seed.z*11.))*.13;size=.015;}else if(uEffect==9){center=(seed-.5)*vec3(.8,.6,0.);size=.12;}else {center+=vec3(sin(t*.2+seed.x*9.),cos(t*.3+seed.y*10.),0.)*.1;size=.008;}vec4 world=uModel*vec4(center,1);vWorld=world.xyz+(uRight*p.x+uUp*p.y)*size;vNormal=normalize(cross(uRight,uUp));gl_Position=uVP*vec4(vWorld,1);}else{vec4 world=uModel*vec4(p,1);vWorld=world.xyz;vNormal=transpose(inverse(mat3(uModel)))*n;gl_Position=uVP*world;}}';
  var propFragment = header + lighting + C.studioMaterials.shader() + `
in vec3 vWorld,vNormal;in vec2 vUV;flat in int vFace;out vec4 result;
uniform vec3 uTint,uGradient;uniform vec4 uSurface;uniform sampler2D uPaint,uRefraction,uReflection;uniform vec2 uViewport,uViewScale;uniform int uHasPaint,uPhase,uEffect,uGrid,uBackdrop,uMirror;
void main(){if(vFace==4&&uPhase!=1||vFace!=4&&uPhase==1&&uEffect==0)discard;vec3 base=uTint,n=normalize(vNormal);float alpha=1.;
if(uBackdrop==1)base=mix(uTint,uGradient,clamp(vUV.y,0.,1.));if(vFace==1)base*=.5;if(uGrid==1){vec2 line=abs(fract(vWorld.xz*2.-.5)-.5);base*=mix(.35,1.,smoothstep(.01,.025,min(line.x,line.y)));}
if(vFace==3&&uHasPaint==1){vec4 paint=texture(uPaint,vUV);if(paint.a<.1)discard;base*=paint.rgb;}
if(uEffect>0){float radius=length(vUV*2.-1.);alpha=1.-smoothstep(.15,1.,radius);alpha*=uSurface.w;if(uEffect==1||uEffect==8)alpha*=.075;if(uEffect==7)alpha*=.65+.35*sin(vUV.x*18.);if(uEffect==4)base=mix(base,vec3(fract(vUV.x*7.),fract(vUV.x*13.),fract(vUV.x*23.)),.6);if(alpha<.002)discard;}
vec3 d,s;illuminate(vWorld,n,vFace==3&&uVariant==4?.94:uSurface.x,false,d,s);if(vFace==3&&uHasPaint==1){base=studioSurface(base,vUV,n,normalize(uEye-vWorld),d,s);if(uVariant==4)s*=1.-innerMask(vUV);}
vec3 c=base*(.24+d*.62)*(1.-uSurface.y*.35)+s*mix(.2,.9,uSurface.y);
if(uSurface.z>.5||vFace==2)c+=base*(1.2+d*.18);
if(vFace==4){vec2 at=gl_FragCoord.xy/uViewport;c=mix(texture(uRefraction,clamp(at+n.xy*.014/uViewScale,vec2(0),vec2(1))).rgb,c,.18)+s*.15;alpha=.38;}
if(uMirror==1){float f=.55+.3*pow(1.-abs(dot(n,normalize(uEye-vWorld))),3.);c=mix(c,texture(uReflection,gl_FragCoord.xy/uViewport).rgb,f);}
result=vec4(c,alpha);
}`;
  var shadowFragment=header+'void main(){}';
  var filter = header + `in vec2 uv;out vec4 result;uniform sampler2D uImage;uniform vec2 uStep;uniform int uThreshold;void main(){vec3 c=texture(uImage,uv).rgb*.227027;for(int i=1;i<5;i++){float weight=i==1?.1945946:i==2?.1216216:i==3?.054054:.016216;vec2 d=uStep*float(i);c+=(texture(uImage,uv+d).rgb+texture(uImage,uv-d).rgb)*weight;}if(uThreshold==1)c=max(c-vec3(.62),0.);result=vec4(c,1.);}`;
  var composite = header + `
in vec2 uv;out vec4 result;uniform sampler2D uImage,uDepth,uBloom;uniform vec2 uPixel,uFlareAt;uniform vec3 uFlareColor;uniform vec4 uPost,uLens;uniform vec4 uView;uniform float uResolution,uFocus,uAperture;uniform int uDOF,uOrtho;
float distanceAt(vec2 p){float z=texture(uDepth,p).r*2.-1.;return uOrtho==1?.05+(z*.5+.5)*59.95:6./(60.05-z*59.95);}
void main(){vec2 globalUV=uView.xy+uv*uView.zw,radial=globalUV-.5,shift=radial*uLens.y*.006/uView.zw;vec3 base=vec3(texture(uImage,uv+shift).r,texture(uImage,uv).g,texture(uImage,uv-shift).b);float radius=0.;if(uDOF==1){radius=clamp(abs(distanceAt(uv)-uFocus)/max(.1,distanceAt(uv))*uAperture*5.,0.,14.);radius=max(radius,abs(globalUV.y-.5)*uLens.w*16.);}
radius*=uResolution;if(radius>.2){vec3 sum=base;float weight=1.;for(int i=0;i<12;i++){float angle=float(i)*2.399963;vec2 p=clamp(uv+vec2(cos(angle),sin(angle))*sqrt((float(i)+.5)/12.)*radius*uPixel,vec2(0),vec2(1));float w=smoothstep(.03,.25,distanceAt(p)-distanceAt(uv)+.25);sum+=texture(uImage,p).rgb*w;weight+=w;}base=sum/weight;}
base+=texture(uBloom,uv).rgb*uPost.y;float flare=0.;vec2 axis=.5-uFlareAt;for(int i=0;i<3;i++){vec2 at=uFlareAt+axis*(1.3+float(i)*.8);flare+=exp(-length(globalUV-at)*(26.+float(i)*9.))*.035;}base+=uFlareColor*flare*uLens.z;base*=exp2(uPost.x);base=base/(1.+max(base-1.,0.));base*=1.-uPost.z*smoothstep(.1,.7,length(radial));float noise=fract(sin(dot(globalUV/(uPixel*uView.zw),vec2(12.9898,78.233)))*43758.5453)-.5;base+=noise*uPost.w*.16;result=vec4(clamp(base,0.,1.),1.);}`;
  function shader(gl, type, source) { var s = gl.createShader(type); gl.shaderSource(s, source); gl.compileShader(s); if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) { var reason = gl.getShaderInfoLog(s); gl.deleteShader(s); throw new Error(reason); } return s; }
  function program(gl, vs, fs) { var v, f, p; try { v = shader(gl, gl.VERTEX_SHADER, vs); f = shader(gl, gl.FRAGMENT_SHADER, fs); p = gl.createProgram(); gl.attachShader(p, v); gl.attachShader(p, f); gl.linkProgram(p); if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p)); return p; } catch (error) { if (p) gl.deleteProgram(p); throw error; } finally { if (v) gl.deleteShader(v); if (f) gl.deleteShader(f); } }
  C.studioRenderer = {
    create: function (canvas, faces, tier) {
      var gl = canvas.getContext('webgl2', { alpha: false, antialias: false, preserveDrawingBuffer: false, powerPreference: 'default' }); if (!gl) throw new Error('WebGL2 unavailable');
      var textures = [], programs = [], buffers = [], arrays = [], targets = [], destroyed = false, size = '', propTextures = new Map(), meshCache = new Map(), shadowSignature = '', shadowMatrix = new Float32Array(16), keyIndex = -1, vertices = slab(), full = tier === 'high', bloomEnabled = full || tier === 'medium', maxSize = Math.min(gl.getParameter(gl.MAX_TEXTURE_SIZE), gl.getParameter(gl.MAX_RENDERBUFFER_SIZE));
      function destroy() { if (destroyed) return; destroyed = true; propTextures.forEach(function(r,key){if(key.indexOf('card:')!==0)r.source.width=r.source.height=1;});propTextures.clear();meshCache.clear(); textures.forEach(function (t) { gl.deleteTexture(t); }); programs.forEach(function (p) { gl.deleteProgram(p.id); }); buffers.forEach(function (b) { gl.deleteBuffer(b); }); arrays.forEach(function (a) { gl.deleteVertexArray(a); }); targets.forEach(function (t) { gl.deleteFramebuffer(t.fbo); }); var extension = gl.getExtension('WEBGL_lose_context'); if (extension) extension.loseContext(); canvas.width = canvas.height = 1; }
      function makeProgram(vs, fs) { var p = { id: program(gl, vs, fs), locations: {} }; programs.push(p); return p; }
      function location(p, name) { if (!(name in p.locations)) p.locations[name] = gl.getUniformLocation(p.id, name); return p.locations[name]; }
      function uniform(p, name, method, value) { gl[method](location(p, name), value); }
      function matrix(p, name, value) { gl.uniformMatrix4fv(location(p, name), false, value); }
      function texture(source, unit, depth) { var t = gl.createTexture(); textures.push(t); gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, depth ? gl.NEAREST : gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, depth ? gl.NEAREST : gl.LINEAR); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE); gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE); if (source) { var cap=Math.min(maxSize,C.studioScenes.limits(tier).texture),temporary=null;if(Math.max(source.width,source.height)>cap){temporary=root.document.createElement('canvas');var ratio=cap/Math.max(source.width,source.height);temporary.width=Math.max(1,Math.floor(source.width*ratio));temporary.height=Math.max(1,Math.floor(source.height*ratio));temporary.getContext('2d').drawImage(source,0,0,temporary.width,temporary.height);source=temporary;} gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, source); gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false);if(temporary)temporary.width=temporary.height=1; } return t; }
      function target(depth) { var t = { fbo: gl.createFramebuffer(), color: texture(null, 4), depth: depth ? texture(null, 5, true) : null }; targets.push(t); return t; }
      function resize(t, w, h) { t.w = w; t.h = h; gl.bindTexture(gl.TEXTURE_2D, t.color); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA8, w, h, 0, gl.RGBA, gl.UNSIGNED_BYTE, null); gl.bindFramebuffer(gl.FRAMEBUFFER, t.fbo); gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, t.color, 0); if (t.depth) { gl.bindTexture(gl.TEXTURE_2D, t.depth); gl.texImage2D(gl.TEXTURE_2D, 0, gl.DEPTH_COMPONENT24, w, h, 0, gl.DEPTH_COMPONENT, gl.UNSIGNED_INT, null); gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.DEPTH_ATTACHMENT, gl.TEXTURE_2D, t.depth, 0); } if (gl.checkFramebufferStatus(gl.FRAMEBUFFER) !== gl.FRAMEBUFFER_COMPLETE) throw new Error('Studio render target unavailable.'); }
      function bindTexture(t, unit) { gl.activeTexture(gl.TEXTURE0 + unit); gl.bindTexture(gl.TEXTURE_2D, t); }
      function geometry(data) { var array = gl.createVertexArray(), buffer = gl.createBuffer(); arrays.push(array); buffers.push(buffer); gl.bindVertexArray(array); gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, data, gl.STATIC_DRAW); [3, 3, 2, 1].forEach(function (n, i) { gl.enableVertexAttribArray(i); gl.vertexAttribPointer(i, n, gl.FLOAT, false, 36, [0, 12, 24, 32][i]); }); return array; }
      function coating(p,scene,info){info=info||{};uniform(p,'uVariant','uniform1i',info.variant||0);uniform(p,'uFinish','uniform1i',info.finish||0);uniform(p,'uClassic','uniform1i',info.classic?1:0);uniform(p,'uPlate','uniform1i',info.plate?1:0);uniform(p,'uMono','uniform1i',C.config.rarityColorMode==='mono'?1:0);uniform(p,'uSeed','uniform1f',info.seed||0);uniform(p,'uMaterialTime','uniform1f',!C.motion.reduced&&(tier==='high'||tier==='medium')?scene.materialTime||0:0);}
      function lights(p, scene, m) { var positions = [], directions = [], colors = [], extras = [], bottoms = [], shadows = []; scene.lights.forEach(function (l) { positions.push.apply(positions, l.position.concat(C.studioLights.types.indexOf(l.type))); directions.push.apply(directions, C.studioLights.direction(l).concat(Math.cos(l.angle * Math.PI / 360))); colors.push.apply(colors, l.color.concat(l.intensity)); extras.push(l.size, l.falloff, l.softness, ['none', 'blinds', 'grid', 'leaves', 'stars'].indexOf(l.gobo)); bottoms.push.apply(bottoms, l.bottom.concat(l.shadows ? 1 : 0)); shadows.push(l.shadowSoftness, l.rotation[2] * Math.PI / 180, 0, 0); });
        uniform(p,'uCardVisible','uniform1i',scene.card.visible===false?0:1);uniform(p,'uKeyIndex','uniform1i',keyIndex);uniform(p,'uKeyShadow','uniform1i',keyIndex>=0&&(full||tier==='medium')?1:0);matrix(p,'uLightVP',shadowMatrix);uniform(p,'uShadowPixel','uniform2fv',[(1+(scene.lights[keyIndex]?scene.lights[keyIndex].shadowSoftness:0)*4)/(full?1024:512),(1+(scene.lights[keyIndex]?scene.lights[keyIndex].shadowSoftness:0)*4)/(full?1024:512)]);if(keyMap){bindTexture(keyMap.depth,7);uniform(p,'uKeyDepth','uniform1i',7);}uniform(p, 'uCount', 'uniform1i', scene.lights.length); uniform(p, 'uShadowQuality', 'uniform1i', full ? 2 : tier === 'medium' ? 1 : 0); if (positions.length) { [['uPos[0]', positions], ['uDir[0]', directions], ['uColor[0]', colors], ['uExtra[0]', extras], ['uBottom[0]', bottoms], ['uShadow[0]', shadows]].forEach(function (v) { uniform(p, v[0], 'uniform4fv', v[1]); }); } matrix(p, 'uInverseModel', m.inverseModel); uniform(p, 'uEye', 'uniform3fv', m.eye);
      }
      try {
        var viewScale=[1,1];var material = makeProgram(vertex, fragment), stage = makeProgram(screen, background), blur = makeProgram(screen, filter), post = makeProgram(screen, composite), propMaterial=makeProgram(propVertex,propFragment),shadowProgram=makeProgram(propVertex,shadowFragment),mesh = geometry(vertices), tags = geometry(new Float32Array([-.5,.76,0,0,0,1,0,0,3, .5,.76,0,0,0,1,1,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.76,0,0,0,1,0,0,3, .5,.846,0,0,0,1,1,1,3, -.5,.846,0,0,0,1,0,1,3]));
        var facesGPU = [faces.front, faces.back, faces.normal, faces.tags].map(function (source, i) { return texture(source, i); }), keyMap=target(true),reflectTarget=target(true),refractTarget=target(false),sceneTarget = target(true), bloomA = target(false), bloomB = target(false), empty = texture(null, 6); gl.bindTexture(gl.TEXTURE_2D, empty); gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, new Uint8Array([0, 0, 0, 255]));
        resize(keyMap,full?1024:tier==='medium'?512:1,full?1024:tier==='medium'?512:1);
        var accumulation=null,accumProgram=null;
        function halton(n,base){var f=1,value=0;while(n>0){f/=base;value+=f*(n%base);n=Math.floor(n/base);}return value;}
        function refineTargets(w,h){if(!accumulation){accumProgram=makeProgram(screen,'#version 300 es\nprecision highp float;in vec2 uv;out vec4 outColor;uniform sampler2D uPrevious,uSample;uniform float uWeight;void main(){outColor=mix(texture(uPrevious,uv),texture(uSample,uv),uWeight);}');accumulation=[target(false),target(false),target(false)];}accumulation.forEach(function(t){if(t.w!==w||t.h!==h)resize(t,w,h);});}
        function relax(t){if(t.w>1||t.h>1)resize(t,1,1);}

        function cachedMesh(type){if(!meshCache.has(type)){var data=C.studioProps.mesh(type,tier);meshCache.set(type,{array:geometry(data),count:data.length/9});}return meshCache.get(type);}
        function paintTexture(key,source){var r=propTextures.get(key);if(r&&r.source!==source){gl.deleteTexture(r.texture);textures.splice(textures.indexOf(r.texture),1);propTextures.delete(key);r=null;}if(!r&&source){r={source:source,texture:texture(source,8)};propTextures.set(key,r);}return r&&r.texture;}
        function configure(p,model,m,prop,effect){matrix(p,'uModel',model);matrix(p,'uVP',m.vp);uniform(p,'uTime','uniform1f',prop.time||0);uniform(p,'uSpin','uniform1i',prop.type==='fan'?1:prop.type==='turntable'?2:0);uniform(p,'uEffect','uniform1i',effect);uniform(p,'uRight','uniform3fv',m.basis.right);uniform(p,'uUp','uniform3fv',m.basis.up);}
        function drawProps(scene,m,p,phase,assets,used){gl.useProgram(p.id);if(p===propMaterial){lights(p,scene,m);uniform(p,'uPhase','uniform1i',phase===2?0:phase);uniform(p,'uViewport','uniform2fv',[canvas.width,canvas.height]);uniform(p,'uViewScale','uniform2fv',viewScale);bindTexture(refractTarget.w?refractTarget.color:empty,9);uniform(p,'uRefraction','uniform1i',9);bindTexture(phase!==2&&reflectTarget.w?reflectTarget.color:empty,10);uniform(p,'uReflection','uniform1i',10);}
          var effectProps=scene.props.filter(C.studioProps.isEffect),perEffect=Math.max(1,Math.floor(({high:512,medium:192,low:48}[tier]||48)/Math.max(1,effectProps.length)));
          scene.props.forEach(function(prop){var effect=C.studioProps.effects.indexOf(prop.type)+1;if(p===shadowProgram&&(effect||!prop.castShadow||prop.type==='floor'||prop.type==='grid-floor'||prop.type==='backdrop'))return;if(phase===0&&effect)return;if(phase===1&&!effect&&prop.type!=='glass-case')return;if(phase===2&&(effect||prop.type==='glass-case'||prop.type==='floor'||prop.type==='grid-floor'))return;
            var geo=cachedMesh(prop.type),draws=prop.type==='collection'?C.studioProps.placements(prop):[{model:C.studioProps.model(prop.position,prop.rotation,prop.scale)}];
            if(p===propMaterial){uniform(p,'uTint','uniform3fv',prop.color);uniform(p,'uGradient','uniform3fv',prop.gradient);uniform(p,'uSurface','uniform4fv',[prop.material==='matte'?.8:prop.material==='gloss'?.2:.12,prop.material==='metal'?1:0,prop.material==='emissive'?1:0,prop.density]);uniform(p,'uGrid','uniform1i',prop.type==='grid-floor'?1:0);uniform(p,'uBackdrop','uniform1i',prop.type==='backdrop'?1:0);uniform(p,'uMirror','uniform1i',phase!==2&&prop.type==='floor'&&prop.surface==='mirror'?1:0);if(prop.type==='floor')uniform(p,'uSurface','uniform4fv',[prop.surface==='matte'?.85:.08,0,0,1]);}
            draws.forEach(function(draw){configure(p,draw.model,m,prop,effect);if(p===propMaterial){coating(p,scene,draw.id&&assets&&assets.material?assets.material(draw.id):null);var key=prop.type==='collection'?'card:'+draw.id:prop.type==='pack'?'pack:'+prop.packId:prop.type==='neon-tube'?'text:'+prop.text:null,source=draw.id&&assets?assets.get(draw.id):null,r=key&&propTextures.get(key);if(key&&!source&&!draw.id&&!r)source=C.studioProps.surface(prop);var t=key&&paintTexture(key,source||r&&r.source);if(key)used.add(key);bindTexture(t||empty,8);uniform(p,'uPaint','uniform1i',8);uniform(p,'uHasPaint','uniform1i',t?1:0);}gl.bindVertexArray(geo.array);gl.drawArrays(gl.TRIANGLES,0,effect?Math.min(geo.count,Math.max(1,Math.ceil(perEffect*prop.density))*6):geo.count);});
          });}
        function drawCard(scene,m,p){if(scene.card.visible===false)return;gl.useProgram(p.id);if(p===material){coating(p,scene,faces.material);lights(p,scene,m);facesGPU.forEach(bindTexture);['uFront','uBack','uNormal','uTags'].forEach(function(name,i){uniform(p,name,'uniform1i',i);});}else{uniform(p,'uEffect','uniform1i',0);uniform(p,'uSpin','uniform1i',0);}matrix(p,'uModel',m.model);matrix(p,'uVP',m.vp);gl.bindVertexArray(mesh);gl.drawArrays(gl.TRIANGLES,0,vertices.length/9);}
        function shadows(scene,m){keyIndex=scene.lights.findIndex(function(l){return l.type!=='ambient'&&l.shadows;});if(!(full||tier==='medium')||keyIndex<0)return;var key=scene.lights[keyIndex],signature=JSON.stringify([[scene.card.visible,scene.card.tilt,scene.card.side,scene.card.position,scene.card.scale,scene.card.rotationZ],scene.props.filter(function(p){return p.castShadow&&!C.studioProps.isEffect(p);}).map(function(p){return [p.id,p.type,p.position,p.rotation,p.scale,p.instances,p.arrangement,p.type==='fan'||p.type==='turntable'?p.time:0];}),key]);if(signature===shadowSignature)return;shadowSignature=signature;
          var aim=key.type==='spot'||key.type==='directional'?C.studioLights.direction(key):C.studioCamera.unit(key.position.map(function(v){return -v;})),eye=key.type==='directional'?aim.map(function(v){return -v*12;}):key.position,back=aim.map(function(v){return -v;}),right=C.studioCamera.unit(Math.abs(back[1])>.95?[1,0,0]:[back[2],0,-back[0]]),up=[back[1]*right[2]-back[2]*right[1],back[2]*right[0]-back[0]*right[2],back[0]*right[1]-back[1]*right[0]],extent=6;scene.props.forEach(function(p){extent=Math.min(24,Math.max(extent,Math.hypot.apply(Math,p.position)+Math.max.apply(Math,p.scale)));});
          var view=new Float32Array([right[0],up[0],back[0],0,right[1],up[1],back[1],0,right[2],up[2],back[2],0,-C.studioCamera.dot(right,eye),-C.studioCamera.dot(up,eye),-C.studioCamera.dot(back,eye),1]),projection=new Float32Array([1/extent,0,0,0,0,1/extent,0,0,0,0,-2/60,0,0,0,-1,1]);shadowMatrix=C.studioCamera.multiply(projection,view);
          gl.bindFramebuffer(gl.FRAMEBUFFER,keyMap.fbo);gl.viewport(0,0,keyMap.w,keyMap.h);gl.clear(gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.colorMask(false,false,false,false);gl.enable(gl.POLYGON_OFFSET_FILL);gl.polygonOffset(1,2);var shadowView={vp:shadowMatrix,model:m.model,basis:m.basis};drawCard(scene,shadowView,shadowProgram);drawProps(scene,shadowView,shadowProgram,0,null,new Set());gl.disable(gl.POLYGON_OFFSET_FILL);gl.colorMask(true,true,true,true);
        }
        function filterPass(from, to, step, threshold) { gl.bindFramebuffer(gl.FRAMEBUFFER, to.fbo); gl.viewport(0, 0, to.w, to.h); gl.useProgram(blur.id); bindTexture(from.color, 4); uniform(blur, 'uImage', 'uniform1i', 4); uniform(blur, 'uStep', 'uniform2fv', step); uniform(blur, 'uThreshold', 'uniform1i', threshold); gl.drawArrays(gl.TRIANGLES, 0, 3); }
        return { canvas: canvas, kind: 'WebGL2', maxSize: maxSize,
          draw: function (scene, width, height, assets, tile, refinement) { if (destroyed) return; var dpr = Math.min(root.devicePixelRatio || 1, { high: 2, medium: 1.5, low: 1.25 }[tier] || 1), scale = Math.min(dpr, Math.sqrt(({ high: 2600000, medium: 1700000, low: 1100000 }[tier] || 1100000) / Math.max(1, width * height)), maxSize / Math.max(width, height)), w = Math.max(1, Math.round(width * scale)), h = Math.max(1, Math.round(height * scale));if(tile){w=tile.w;h=tile.h;}
            if (size !== w + ':' + h) { size = w + ':' + h; canvas.width = w; canvas.height = h; resize(sceneTarget, w, h); if (bloomEnabled) { resize(bloomA, Math.max(1, Math.ceil(w / 4)), Math.max(1, Math.ceil(h / 4))); resize(bloomB, bloomA.w, bloomA.h); } }
            if(refinement){refineTargets(w,h);scene=Object.assign({},scene,{lights:scene.lights.map(function(l,i){var next=Object.assign({},l,{position:l.position.slice()});if(full&&l.type!=='ambient'){next.position[0]+=(halton(refinement.index+1+i,2)-.5)*l.size*.05;next.position[1]+=(halton(refinement.index+1+i,3)-.5)*l.size*.05;}return next;})});}else if(accumulation)accumulation.forEach(relax);
            var fullW=tile?tile.fullW:w,fullH=tile?tile.fullH:h,view=tile?[tile.x/fullW,1-(tile.y+h)/fullH,w/fullW,h/fullH]:[0,0,1,1];viewScale=view.slice(2);var m = C.studioCamera.matrices(scene.camera, fullW / fullH, scene.card),fullVP=m.vp,used=new Set();if(refinement){var jitter=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,(halton(refinement.index+1,2)-.5)*2/w,(halton(refinement.index+1,3)-.5)*2/h,0,1]);m.vp=C.studioCamera.multiply(jitter,m.vp);m.inverseVP=C.studioCamera.inverse(m.vp);}if(tile){var crop=new Float32Array([fullW/w,0,0,0,0,fullH/h,0,0,0,0,1,0,(fullW-2*tile.x-w)/w,(2*tile.y+h-fullH)/h,0,1]);m.vp=C.studioCamera.multiply(crop,m.vp);m.inverseVP=C.studioCamera.inverse(m.vp);}shadows(scene,m);
            var hasGlass=scene.props.some(function(p){return p.type==='glass-case';});if(!hasGlass)relax(refractTarget);var mirror=scene.props.find(function(p){return p.type==='floor'&&p.surface==='mirror';});
            if(!mirror)relax(reflectTarget);
            if(mirror){var rw=Math.max(1,Math.ceil(w/2)),rh=Math.max(1,Math.ceil(h/2));if(reflectTarget.w!==rw||reflectTarget.h!==rh)resize(reflectTarget,rw,rh);var reflection=new Float32Array([1,0,0,0,0,-1,0,0,0,0,1,0,0,2*mirror.position[1],0,1]),rm={vp:C.studioCamera.multiply(m.vp,reflection),model:m.model,inverseModel:m.inverseModel,eye:[m.eye[0],2*mirror.position[1]-m.eye[1],m.eye[2]],basis:m.basis};gl.bindFramebuffer(gl.FRAMEBUFFER,reflectTarget.fbo);gl.viewport(0,0,rw,rh);gl.clearColor.apply(gl,scene.backdrop.color.concat(1));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);drawCard(scene,rm,material);drawProps(scene,rm,propMaterial,2,assets,used);}
            gl.bindFramebuffer(gl.FRAMEBUFFER, sceneTarget.fbo); gl.viewport(0, 0, w, h); gl.clearColor(.03, .03, .04, 1); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT); gl.bindVertexArray(null); gl.enable(gl.DEPTH_TEST); gl.useProgram(stage.id); lights(stage, scene, m); uniform(stage,'uView','uniform4fv',view);uniform(stage, 'uBackdrop', 'uniform3fv', scene.backdrop.color); matrix(stage, 'uInverseVP', m.inverseVP); matrix(stage, 'uVP', m.vp); gl.drawArrays(gl.TRIANGLES, 0, 3);
            drawCard(scene,m,material); drawProps(scene,m,propMaterial,0,assets,used);
            if(hasGlass){if(refractTarget.w!==w||refractTarget.h!==h)resize(refractTarget,w,h);gl.bindFramebuffer(gl.READ_FRAMEBUFFER,sceneTarget.fbo);gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,refractTarget.fbo);gl.blitFramebuffer(0,0,w,h,0,0,w,h,gl.COLOR_BUFFER_BIT,gl.NEAREST);gl.bindFramebuffer(gl.FRAMEBUFFER,sceneTarget.fbo);}
            gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);drawProps(scene,m,propMaterial,1,assets,used);gl.depthMask(true);gl.disable(gl.BLEND);
            gl.useProgram(material.id);lights(material,scene,m);matrix(material,'uVP',m.vp);facesGPU.forEach(bindTexture);
            var label = C.studioCamera.matrices(scene.camera, fullW / fullH, { tilt: [-scene.camera.pitch * 180 / Math.PI, scene.camera.yaw * 180 / Math.PI], side: 'front' }); matrix(material, 'uModel', label.model); gl.bindVertexArray(tags); gl.enable(gl.BLEND); gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA); if(scene.card.visible!==false)gl.drawArrays(gl.TRIANGLES, 0, 6); gl.disable(gl.BLEND); gl.disable(gl.DEPTH_TEST); gl.bindVertexArray(null);
            var hasBloom = bloomEnabled && scene.post.bloom > 0; if (hasBloom) { filterPass(sceneTarget, bloomA, [1 / w, 1 / h], 1); filterPass(bloomA, bloomB, [1 / bloomA.w, 0], 0); filterPass(bloomB, bloomA, [0, 1 / bloomA.h], 0); }
            gl.bindFramebuffer(gl.FRAMEBUFFER, refinement?accumulation[0].fbo:null); gl.viewport(0, 0, w, h); gl.useProgram(post.id); bindTexture(sceneTarget.color, 4); bindTexture(sceneTarget.depth, 5); bindTexture(hasBloom ? bloomA.color : empty, 6); uniform(post,'uView','uniform4fv',view);uniform(post,'uResolution','uniform1f',tile?fullH/1080:1);uniform(post, 'uImage', 'uniform1i', 4); uniform(post, 'uDepth', 'uniform1i', 5); uniform(post, 'uBloom', 'uniform1i', 6); uniform(post, 'uPixel', 'uniform2fv', [1 / w, 1 / h]); uniform(post, 'uPost', 'uniform4fv', [scene.post.exposure, hasBloom ? scene.post.bloom : 0, scene.post.vignette, scene.post.grain]); uniform(post, 'uLens', 'uniform4fv', [0, scene.post.aberration, scene.post.flare, full ? scene.post.tiltShift : 0]); uniform(post,'uOrtho','uniform1i',scene.camera.projection==='ortho'?1:0);uniform(post, 'uDOF', 'uniform1i', full ? 1 : 0); uniform(post, 'uAperture', 'uniform1f', full ? scene.camera.aperture : 0); var focus = scene.camera.focus.map(function (n, i) { return m.eye[i] - n; }); uniform(post, 'uFocus', 'uniform1f', Math.max(.05, C.studioCamera.dot(focus, m.basis.back))); var key = scene.lights.find(function (l) { return l.type !== 'ambient'; }), flareAt = key && C.studioCamera.project({vp:fullVP}, key.position); uniform(post, 'uFlareAt', 'uniform2fv', flareAt && flareAt.front ? [flareAt.x, 1 - flareAt.y] : [-4, -4]); uniform(post, 'uFlareColor', 'uniform3fv', key ? key.color.map(function (n) { return n * Math.min(key.intensity, 3); }) : [0, 0, 0]); gl.drawArrays(gl.TRIANGLES, 0, 3);
            if(refinement){var previous=accumulation[1],destination=accumulation[2];gl.bindFramebuffer(gl.FRAMEBUFFER,destination.fbo);gl.useProgram(accumProgram.id);bindTexture(previous.color,4);bindTexture(accumulation[0].color,5);uniform(accumProgram,'uPrevious','uniform1i',4);uniform(accumProgram,'uSample','uniform1i',5);uniform(accumProgram,'uWeight','uniform1f',1/(refinement.index+1));gl.drawArrays(gl.TRIANGLES,0,3);gl.bindFramebuffer(gl.READ_FRAMEBUFFER,destination.fbo);gl.bindFramebuffer(gl.DRAW_FRAMEBUFFER,null);gl.blitFramebuffer(0,0,w,h,0,0,w,h,gl.COLOR_BUFFER_BIT,gl.NEAREST);accumulation[1]=destination;accumulation[2]=previous;}
            propTextures.forEach(function(r,key){if(!used.has(key)){gl.deleteTexture(r.texture);textures.splice(textures.indexOf(r.texture),1);if(key.indexOf('card:')!==0)r.source.width=r.source.height=1;propTextures.delete(key);}});
          }, pixels:function(){var data=new Uint8Array(canvas.width*canvas.height*4);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.readPixels(0,0,canvas.width,canvas.height,gl.RGBA,gl.UNSIGNED_BYTE,data);if(gl.getError()!==gl.NO_ERROR)throw new Error('Photo readback failed. Choose a smaller resolution.');return data;}, destroy: destroy };
      } catch (error) { destroy(); throw error; }
    },
    simple: function (canvas, faces) { var context = canvas.getContext('2d', { alpha: false }); if (!context) throw new Error('A canvas renderer is unavailable.'); return { canvas: canvas, kind: 'Simple', maxSize: 1920,
      draw: function (scene, width, height, assets, crop) { var scale=crop?1:Math.min(1,1920/Math.max(width,height)),w=Math.max(1,Math.round(width*scale)),h=Math.max(1,Math.round(height*scale));if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;context.setTransform(scale,0,0,scale,0,0);if(crop){context.setTransform(canvas.width/crop.w,0,0,canvas.height/crop.h,-crop.x*canvas.width/crop.w,-crop.y*canvas.height/crop.h);width=crop.fullW;height=crop.fullH;} context.fillStyle = 'rgb(' + scene.backdrop.color.map(function (n) { return Math.round(n * 255); }).join(',') + ')'; context.fillRect(0, 0, width, height); var h = Math.min(height * .7 * 3 / scene.camera.distance, width * 1.12), w = h * 5 / 7, x = (width - w) / 2, y = (height - h) / 2, l = scene.lights[0]; context.save(); context.translate(width / 2, height / 2); context.rotate(-scene.camera.roll); context.translate(-width / 2, -height / 2); context.save(); context.beginPath(); context.roundRect(x, y, w, h, w * .045); context.clip(); context.filter = 'brightness(' + Math.max(.2, Math.min(2, l ? .45 + l.intensity * .4 : .45)) * Math.pow(2, scene.post.exposure) + ')'; if(scene.card.visible!==false)context.drawImage(scene.card.side === 'back' ? faces.back : faces.front, x, y, w, h); context.filter = 'none'; if (l) { context.globalCompositeOperation = 'source-atop'; context.fillStyle = 'rgba(' + l.color.map(function (n) { return Math.round(n * 255); }).join(',') + ',.1)'; context.fillRect(x, y, w, h); context.globalCompositeOperation = 'source-over'; } context.restore(); if(scene.card.visible!==false)context.drawImage(faces.tags, x, y - w * .1, w, w * .086); context.restore(); }, destroy: function () { canvas.width = canvas.height = 1; } };
    }
  };
})(window.Cardable, window);
