(function (C, root) {
  'use strict';
  var session = null, generation = 0;
  function node(tag, name, parent, value) { var el = root.document.createElement(tag); el.className = name; if (value != null) el.textContent = value; if (parent) parent.appendChild(el); return el; }
  function button(label, parent, run, title) { var el = node('button', 'studio-button', parent, label); el.type = 'button'; el.title = title || label; if (run) el.addEventListener('click', run); else { el.disabled = true; el.title = title || 'Available in a later milestone'; } return el; }
  function dirty() { if (!session) return; session.dirty = true; C.fx.wake(); }
  function status(message) { if (session) session.status.textContent = message; }
  function inspector(kind) {
    var s = session; if (!s) return; s.selected = kind; s.panel.replaceChildren(); s.root.querySelectorAll('[data-studio-tool]').forEach(function (tool) { tool.setAttribute('aria-pressed', String(tool.dataset.studioTool === kind)); });
    node('p', 'studio-kicker', s.panel, kind === 'camera' ? 'ORBIT CAMERA' : kind === 'backdrop' ? 'BACKDROP' : 'SELECTED CARD');
    node('h2', 'studio-panel-title', s.panel, kind === 'camera' ? 'Find the angle.' : kind === 'backdrop' ? 'A quiet stage.' : s.view.card.name);
    if (kind === 'camera') {
      node('p', 'studio-copy', s.panel, s.renderer && s.renderer.kind === 'Simple' ? 'Simple preview. Orbit needs WebGL2.' : 'Drag the stage to orbit. Scroll to move closer. Arrow keys also orbit the camera.');
      field('Distance', 'range', s.scene.camera.distance, 1.3, 9, .05, function (value) { s.scene.camera.distance = value; dirty(); });
      button('Frame card', s.panel, function () { C.studioCamera.frame(s.scene); inspector('camera'); dirty(); }, 'Frame card · F');
    } else if (kind === 'backdrop') { field('Brightness', 'range', s.scene.backdrop.color[0], 0, .25, .005, function (value) { s.scene.backdrop.color = [value, value, value * 1.08]; dirty(); }); }
    else { var line = node('dl', 'studio-identity', s.panel); [['Serial', s.view.instance.serial], ['Rarity', C.rarity(s.view.card.rarity).name], ['Finish', C.variant(s.view.instance.variantId)?.name || 'Normal'], ['Skin', C.cardSkin(s.view.instance.cardSkinId)?.name || 'Standard']].forEach(function (pair) { node('dt', '', line, pair[0]); node('dd', '', line, pair[1]); });
      var faces = node('div', 'studio-segment', s.panel); ['front', 'back'].forEach(function (side) { var b = button(side === 'front' ? 'Front' : 'Back', faces, function () { s.scene.card.side = side; inspector('card'); dirty(); }); b.setAttribute('aria-pressed', String(s.scene.card.side === side)); });
      field('Info plate', 'checkbox', s.scene.card.plate, null, null, null, function (value) { s.scene.card.plate = value; repaint(); });
      if (s.view.instance.variantId) node('p', 'studio-limited', s.panel, 'Studio preview limited · this coating is not ported yet.');
      node('p', 'studio-copy', s.panel, 'Your scene is saved as Last scene for this exact instance when you leave.');
    }
  }
  function field(label, type, value, min, max, step, changed) { var wrapper = node('label', 'studio-field', session.panel), caption = node('span', '', wrapper, label), input = node('input', '', wrapper); input.type = type; if (type === 'checkbox') input.checked = value; else { input.min = min; input.max = max; input.step = step; input.value = value; } input.setAttribute('aria-label', label); input.addEventListener('input', function () { changed(type === 'checkbox' ? input.checked : Number(input.value)); }); return input; }
  function stop(event) { event.stopPropagation(); }
  function shell(s) {
    var el = s.root = node('section', 'studio-shell', root.document.body); el.setAttribute('role', 'dialog'); el.setAttribute('aria-modal', 'true'); el.setAttribute('aria-label', 'Card studio'); el.setAttribute('data-tool-surface', 'studio');
    var top = node('header', 'studio-topbar', el), identity = node('div', 'studio-topbar-identity', top); node('span', 'studio-kicker', identity, 'INSPECT / STUDIO'); node('h1', '', identity, s.view.card.name);
    var actions = node('div', 'studio-topbar-actions', top); button('Undo', actions, null, 'Undo begins in milestone B'); button('Redo', actions, null, 'Redo begins in milestone B'); button('Presets', actions, null, 'Scene rigs begin in milestone B'); button('Reset', actions, function () { s.scene = C.studioScenes.defaults(s.view.instance, s.pose); inspector('card'); repaint(); }); node('span', 'studio-quality', actions, s.tier === 'very-low' ? 'VERY LOW / SIMPLE' : s.tier.toUpperCase()); s.exit = button('Exit', actions, function () { C.studioController.exit(); }, 'Return to card detail · Esc');
    var stage = node('div', 'studio-layout', el), outliner = node('aside', 'studio-outliner glass', stage); node('p', 'studio-kicker', outliner, 'SCENE');
    var row = button('Card', outliner, function () { inspector('card'); }); row.classList.add('studio-object'); row.setAttribute('aria-label', 'Select card'); node('span', 'studio-object-note', outliner, 'Visible · locked');
    var key = button('Key light', outliner, function () { status('The foundation key light is fixed. Light editing begins in milestone B.'); }); key.classList.add('studio-object'); node('span', 'studio-object-note', outliner, 'Point · fixed rig');
    s.viewport = node('div', 'studio-viewport', stage); s.viewport.tabIndex = 0; s.viewport.setAttribute('role', 'group'); s.viewport.setAttribute('aria-label', 'Card stage. Drag or use arrows to orbit; scroll or plus/minus to dolly. F frames the card.'); s.canvas = node('canvas', 'studio-canvas', s.viewport); s.canvas.setAttribute('aria-hidden', 'true'); s.loading = node('div', 'studio-loading', s.viewport, 'Preparing your card…');
    var right = node('aside', 'studio-inspector glass', stage); s.panel = node('div', '', right);
    var bottom = node('footer', 'studio-bottom', el), tools = node('nav', 'studio-tools glass', bottom); tools.setAttribute('aria-label', 'Studio tools');
    [['Select', 'card'], ['Lights', null], ['Props', null], ['Camera', 'camera'], ['Backdrop', 'backdrop'], ['Card', 'card'], ['Photo', null]].forEach(function (pair) { var b = button(pair[0], tools, pair[1] ? function () { inspector(pair[1]); } : null, pair[1] ? pair[0] : pair[0] + ' begins in milestone ' + (pair[0] === 'Lights' ? 'B' : pair[0] === 'Props' ? 'C' : 'D')); if (pair[1]) b.dataset.studioTool = pair[1]; });
    s.status = node('p', 'studio-status', bottom); s.status.setAttribute('role', 'status'); node('span', 'studio-hint', bottom, 'DRAG TO ORBIT · SCROLL TO DOLLY · F TO FRAME · ESC TO RETURN');
    el.addEventListener('keydown', function (event) { stop(event); if (event.key === 'Tab') { var list = C.accessibility.focusables(el), index = list.indexOf(root.document.activeElement), next = event.shiftKey ? (index <= 0 ? list.length - 1 : index - 1) : (index + 1) % list.length; if (list.length) { event.preventDefault(); list[next].focus(); } return; } if (event.key === 'Escape') { event.preventDefault(); if (s.selected) { s.selected = null; s.panel.replaceChildren(); node('p', 'studio-copy', s.panel, 'Nothing selected. Press Esc again to return to the card.'); } else C.studioController.exit(); return; } var target = event.target; if (target.matches('input,select,textarea') || event.ctrlKey || event.metaKey || event.altKey) return;
      var key = String(event.key).toLowerCase(); if (key === ' ' || key === 'spacebar') { event.preventDefault(); status('Turntable controls begin in milestone E.'); return; } if (key === 'f') { event.preventDefault(); C.studioCamera.frame(s.scene); dirty(); } else if (key === 'c') inspector('camera'); else if (key === 'arrowleft' || key === 'arrowright' || key === 'arrowup' || key === 'arrowdown') { event.preventDefault(); C.studioCamera.orbit(s.scene.camera, key === 'arrowleft' ? -8 : key === 'arrowright' ? 8 : 0, key === 'arrowup' ? -8 : key === 'arrowdown' ? 8 : 0); dirty(); } else if (key === '+' || key === '=' || key === '-') { event.preventDefault(); C.studioCamera.dolly(s.scene.camera, key === '-' ? 80 : -80); dirty(); }
    });
    ['pointerdown', 'pointerup', 'pointermove', 'pointercancel', 'click', 'contextmenu', 'wheel', 'keyup'].forEach(function (name) { el.addEventListener(name, function (event) { stop(event); if (name === 'contextmenu') event.preventDefault(); }); });
    s.viewport.addEventListener('pointerdown', function (event) { if (event.button !== 0 || s.closing || !s.renderer || s.renderer.kind === 'Simple') return; s.drag = { id: event.pointerId, x: event.clientX, y: event.clientY }; s.viewport.setPointerCapture(event.pointerId); s.viewport.focus(); });
    s.viewport.addEventListener('pointermove', function (event) { if (!s.drag || s.drag.id !== event.pointerId) return; C.studioCamera.orbit(s.scene.camera, event.clientX - s.drag.x, event.clientY - s.drag.y); s.drag.x = event.clientX; s.drag.y = event.clientY; dirty(); });
    function end() { if (s.drag && s.viewport.hasPointerCapture(s.drag.id)) s.viewport.releasePointerCapture(s.drag.id); s.drag = null; } s.viewport.addEventListener('pointerup', end); s.viewport.addEventListener('pointercancel', end); s.viewport.addEventListener('lostpointercapture', function () { s.drag = null; });
    s.viewport.addEventListener('wheel', function (event) { event.preventDefault(); if (s.closing) return; C.studioCamera.dolly(s.scene.camera, event.deltaY); dirty(); }, { passive: false });
    s.cleanups.push(C.events.on('fx:visibility', function (visible) { end(); if (visible) dirty(); }));
    s.cleanups.push(C.events.on('motion:changed', dirty));
    if (root.ResizeObserver) { s.observer = new root.ResizeObserver(dirty); s.observer.observe(s.viewport); } else { root.addEventListener('resize', dirty); s.cleanups.push(function () { root.removeEventListener('resize', dirty); }); }
  }
  function ghost(s) { var rect = s.view.el.getBoundingClientRect(); s.source = { left: rect.left, top: rect.top, width: rect.width, height: rect.height }; if (!s.template) s.template = s.view.el.cloneNode(true); var copy = s.template.cloneNode(true); copy.classList.add('studio-card-ghost'); copy.setAttribute('aria-hidden', 'true'); copy.inert = true; copy.removeAttribute('tabindex'); copy.style.width = rect.width + 'px'; copy.style.height = rect.height + 'px'; copy.style.margin = '0'; copy.querySelectorAll('[id]').forEach(function (el) { var id = el.id, next = id + '-studio-' + generation; el.id = next; copy.querySelectorAll('*').forEach(function (part) { Array.from(part.attributes).forEach(function (attr) { if (attr.value.indexOf('#' + id) >= 0) part.setAttribute(attr.name, attr.value.split('#' + id).join('#' + next)); }); }); }); copy.querySelectorAll('[tabindex]').forEach(function (el) { el.removeAttribute('tabindex'); }); s.ghost = copy; s.root.appendChild(copy); }
  function drawTransition(s, progress) { var r = s.viewport.getBoundingClientRect(), h = r.height * 1.4 / (2 * s.scene.camera.distance * Math.tan(s.scene.camera.fov * Math.PI / 360)), target = { width: h * 5 / 7, height: h, left: r.left + (r.width - h * 5 / 7) / 2, top: r.top + (r.height - h) / 2 }, p = 1 - Math.pow(1 - progress, 3), k = s.closing ? 1 - p : p; if (s.ghost) { s.ghost.style.transform = 'translate3d(' + (s.source.left + (target.left - s.source.left) * k) + 'px,' + (s.source.top + (target.top - s.source.top) * k) + 'px,0) scale(' + (1 + (target.width / s.source.width - 1) * k) + ')'; s.ghost.style.opacity = C.motion.reduced ? 0 : s.closing ? p : 1 - Math.max(0, (p - .65) / .35); } s.root.style.setProperty('--studio-enter', s.closing ? 1 - p : p); s.canvas.style.opacity = s.closing ? 1 - p : p; }
  function update(now, dt) { var s = session; if (!s) return false; if (s.transition) { s.age += Math.min(dt, 50); var p = Math.min(1, s.age / (C.motion.reduced ? 180 : 450)); drawTransition(s, p); if (p === 1) { s.transition = false; if (s.closing) { cleanup(s); return false; } if (s.ghost) { s.ghost.remove(); s.ghost = null; } s.root.classList.add('is-ready'); } }
    if (s.dirty && s.renderer && !s.closing) { s.dirty = false; var r = s.viewport.getBoundingClientRect(); s.renderer.draw(C.studioScenes.effective(s.scene, s.tier), r.width, r.height); }
    return s.transition;
  }
  async function repaint() { var s = session; if (!s || s.closing) return; var revision = ++s.revision; status('Preparing printed face…'); var faces;
    try { faces = await C.studioFace.paint(s.view.card, s.view.instance, s.scene, s.tier, s.view.el, s.entry, function () { return session === s && !s.closing && revision === s.revision; }); if (!faces) return false; if (session !== s || s.closing || revision !== s.revision) { faces.destroy(); return; } if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy();
      // A lost old context cannot be reused; use a fresh canvas when repainting.
      if (s.faces) { var next = node('canvas', 'studio-canvas', s.viewport); next.setAttribute('aria-hidden', 'true'); s.canvas.replaceWith(next); s.canvas = next; }
      s.faces = faces;
      try { s.renderer = s.tier === 'very-low' ? C.studioRenderer.simple(s.canvas, faces) : C.studioRenderer.create(s.canvas, faces, s.tier); } catch (_) { var fallback = node('canvas', 'studio-canvas', s.viewport); s.canvas.replaceWith(fallback); s.canvas = fallback; s.renderer = C.studioRenderer.simple(fallback, faces); }
      s.loading.hidden = true; status(s.renderer.kind === 'Simple' ? 'Simple preview · one light · no props · photo tools arrive in milestone D.' : 'Last scene autosaves on exit · ' + (faces.source === 'embedded' ? 'original artwork' : 'procedural art fallback')); dirty();
      if (!s.entered) { s.entered = true; s.age = 0; s.transition = true; C.events.emit('studio:enter', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake(); } return true;
    } catch (error) { if (faces) faces.destroy(); if (session === s) { status('The studio could not prepare this card. Return to detail and try again.'); C.studioController.exit(); } return false; }
  }
  function cleanup(s) { if (session !== s) return; session = null; generation++; s.cleanups.forEach(function (fn) { fn(); }); if (s.observer) s.observer.disconnect(); if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy(); C.art.releaseStudioData(); C.accessibility.release(s.root); s.root.remove(); root.document.body.classList.remove('studio-active'); s.hidden.forEach(function (record) { if (record.el.isConnected) { record.el.inert = record.inert; record.el.style.visibility = record.visibility; } });
    if (!s.view.destroyed && s.view.el.isConnected && C.detail.phase === 'detail') { s.view.setVisible(true); s.view.setFace(s.pose.side); s.view.setMode('full'); s.view.setTiltLock({ x: s.pose.x, y: s.pose.y }); var releaseTilt = function () { if (!s.view.destroyed) s.view.setTiltLock(null); s.view.el.removeEventListener('pointermove', releaseTilt); }; s.view.el.addEventListener('pointermove', releaseTilt, { once: true }); }
    s.releaseMenu(); s.releaseScope(); if (s.timersRunning) C.timers.start(); if (s.focus && s.focus.isConnected) s.focus.focus({ preventScroll: true }); else if (C.detail.closeButton) C.detail.closeButton.focus({ preventScroll: true }); if (s.entered) C.events.emit('studio:exit', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake();
  }
  C.studioController = {
    get active() { return !!session; }, get scene() { return session && session.scene; },
    enter: async function (context, view) { if (session) return false; var styles = root.getComputedStyle(view.el), pose = { x: parseFloat(styles.getPropertyValue('--rx')) || 0, y: parseFloat(styles.getPropertyValue('--ry')) || 0, side: view.side }, s = session = { view: view, entry: context.entry, pose: pose, scene: C.studioScenes.last(view.instance) || C.studioScenes.defaults(view.instance, pose), tier: C.settings.get('quality'), selected: 'card', cleanups: [], hidden: [], focus: root.document.activeElement, revision: 0, dirty: true, age: 0, transition: false, entered: false, closing: false };
      s.timersRunning = C.timers.running; C.timers.stop(); s.releaseMenu = C.menu.suspendActivity(); s.releaseScope = C.fx.scope('studio'); shell(s); ghost(s); drawTransition(s, 0); view.setMode('lite'); view.setVisible(false);
      Array.from(root.document.body.children).forEach(function (el) { if (el === s.root || el.tagName === 'SCRIPT') return; s.hidden.push({ el: el, inert: el.inert, visibility: el.style.visibility }); el.inert = true; el.style.visibility = 'hidden'; }); root.document.body.classList.add('studio-active'); C.accessibility.trap(s.root); s.cleanups.push(C.fx.subscribe(update, 'studio')); s.cleanups.push(C.events.on('save:willReplace', function () { if (session === s) cleanup(s); })); s.cleanups.push(C.events.on('detail:reset', function () { if (session === s) cleanup(s); })); inspector('card'); s.exit.focus({ preventScroll: true }); return await repaint();
    },
    exit: function () { var s = session; if (!s || s.closing) return; s.closing = true; s.revision++; if (s.entered) C.studioScenes.saveLast(s.view.instance, s.scene); if (!s.entered || root.document.hidden) return cleanup(s);
      // Returning uses the detail card's original pose, not the orbit angle.
      s.view.setFace(s.pose.side); ghost(s); s.transition = true; s.age = 0; s.root.classList.remove('is-ready'); C.fx.wake();
    }
  };
})(window.Cardable, window);
