(function (C, root) {
  'use strict';
  var session = null, generation = 0;
  function node(tag, name, parent, value) { return C.studioUI.node(tag, name, parent, value); }
  function dirty() { if (!session) return; session.dirty = true; C.fx.wake(); }
  function status(message) { if (session) session.status.textContent = message; }
  function inspector(kind, id) { if (session && !session.recordJob) C.studioUI.inspect(session, kind, id); }
  function begin() { if (session && !session.closing && !session.photoBusy && !session.recordJob) session.history.begin(session.scene); }
  function commit() { if (!session || session.closing) return; session.history.commit(session.scene); C.studioUI.history(session); C.studioUI.outliner(session); }
  function mutate(run) { if (!session || session.closing || session.photoBusy || session.recordJob) return; commit(); begin(); var beforeScene=session.scene,plate = session.scene.card.plate; run();if(session.scene!==beforeScene)session.director=C.studioDirector.create(session); commit(); C.studioUI.outliner(session); if (plate !== session.scene.card.plate) repaint(); dirty(); }
  function frame() { if (!session) return; var r = session.viewport.getBoundingClientRect(); C.studioCamera.frame(session.scene, r.width / Math.max(1, r.height)); }
  function restore(redo) { var s = session; if (!s || s.closing || s.photoBusy || s.recordJob) return; commit(); if(s.director)s.director.pause(true);var next = redo ? s.history.redo() : s.history.undo(); if (!next) return; var plate = s.scene.card.plate; s.scene = next;s.director=C.studioDirector.create(s); inspector(s.selected || 'card', s.selectedId); C.studioUI.history(s); if (plate !== next.card.plate) repaint(); dirty(); }
  function addLight(type) { var s = session; if (!s || s.closing) return; if (s.scene.lights.length >= (s.renderer&&s.renderer.kind==='Simple'?1:C.studioScenes.limits(s.tier).lights)) return status('Light limit reached for ' + s.tier + '. Delete a light or choose a smaller rig.'); var light = C.studioLights.create(type); mutate(function () { s.scene.lights.push(light); }); inspector('light', light.id); if (s.scene.lights.length >= C.studioScenes.limits(s.tier).lights - 1) status('Near the light limit: ' + s.scene.lights.length + ' / ' + C.studioScenes.limits(s.tier).lights + '.'); }
  function addProp(type){var s=session;if(!s||s.closing)return;var limit=C.studioScenes.limits(s.tier).props;if(s.scene.props.length>=limit||s.renderer.kind==='Simple')return status('Prop limit reached for '+s.tier+'.');var p=C.studioProps.create(type);if(type==='collection'){var instance=C.state.current.inventory.find(function(i){return i.instanceId!==s.view.instance.instanceId;});var total=s.scene.props.reduce(function(n,v){return n+(v.type==='collection'?v.instances.length:0);},0);if(instance&&total<10)p.instances=[instance.instanceId];}mutate(function(){s.scene.props.push(p);});inspector('prop',p.id);if(s.scene.props.length>=limit-2)status('Near the prop limit: '+s.scene.props.length+' / '+limit+'.');}
  function remove(id,kind){var s=session;if(!s)return;kind=kind||s.selected;var object=kind==='card'?s.scene.card:s.scene.lights.concat(s.scene.props).find(function(v){return v.id===(id||s.selectedId);});if(!object)return;if(object.locked)return status('Unlock this object before deleting it.');mutate(function(){if(kind==='card')s.scene.card.visible=false;else if(s.scene.props.indexOf(object)>=0)s.scene.props=s.scene.props.filter(function(p){return p!==object;});else s.scene.lights=s.scene.lights.filter(function(l){return l!==object;});});inspector(kind==='prop'?'props':kind==='card'?'card':'lights');}
  function duplicate(){var s=session,object=s&&s.scene.lights.concat(s.scene.props).find(function(v){return v.id===s.selectedId;});if(!object||object.locked)return;var isProp=!!object.scale,limit=C.studioScenes.limits(s.tier)[isProp?'props':'lights'];if(s.scene[isProp?'props':'lights'].length>=limit)return status('Object limit reached.');if(object.type==='collection'&&s.scene.props.reduce(function(n,p){return n+(p.type==='collection'?p.instances.length:0);},0)+object.instances.length>10)return status('Collection-card limit reached: ten per scene.');var next;if(isProp){next=C.studioScenes.clone(object);next.id=C.studioProps.create(object.type).id;next.name=(object.name+' copy').slice(0,60);next.position[0]+=.15;}else next=C.studioLights.duplicate(object);mutate(function(){s.scene[isProp?'props':'lights'].push(next);});inspector(isProp?'prop':'light',next.id);}
  function loadScene(value){var s=session;if(!s)return;var next=C.studioScenes.parse(value);next.card.source=C.studioScenes.clone(s.scene.card.source);next.props.forEach(function(p){if(p.type==='collection')p.instances=p.instances.filter(function(id){return C.state.current.inventory.some(function(i){return i.instanceId===id;});});});mutate(function(){s.scene=next;});s.selectedId=null;s.lightTime=next.presentationTime||0;s.director=C.studioDirector.create(s);s.lastFrame=null;dirty();}
  function presented(s){var r=s.viewport.getBoundingClientRect(),scene=C.studioScenes.effective(s.director?s.director.scene():s.scene,s.tier);scene.materialTime=s.lightTime;if(scene.camera.autoFrame)C.studioCamera.frame(scene,r.width/Math.max(1,r.height));scene.lights=C.studioLights.sample(scene.lights,s.lightTime,s.tier);scene.props=C.studioProps.sample(scene.props,s.lightTime,s.tier);return {scene:scene,width:r.width,height:r.height};}
  function saveSlot(index,name){var s=session;if(!s||!s.renderer)return;s.scene.director.playhead=s.director.time;s.scene.presentationTime=s.lightTime;commit();var display=presented(s);s.renderer.draw(display.scene,display.width,display.height,s.propAssets);var thumbnail=root.document.createElement('canvas');thumbnail.width=160;thumbnail.height=100;var g=thumbnail.getContext('2d');g.fillStyle='#09090B';g.fillRect(0,0,160,100);var scale=Math.min(160/s.canvas.width,100/s.canvas.height),w=s.canvas.width*scale,h=s.canvas.height*scale;g.drawImage(s.canvas,(160-w)/2,(100-h)/2,w,h);var store=C.state.current.studio||(C.state.current.studio={slots:[],last:{}});store.slots[index]={name:String(name||'Scene '+(index+1)).slice(0,60),thumbnail:thumbnail.toDataURL('image/jpeg',.65),scene:C.studioScenes.parse(s.scene)};thumbnail.width=thumbnail.height=1;C.state.save();status('Scene saved in slot '+(index+1)+'.');}
  function selectAt(s,event){var display=presented(s),m=C.studioCamera.matrices(display.scene.camera,display.width/display.height,display.scene.card),r=s.viewport.getBoundingClientRect(),ray=C.studioCamera.ray(m,(event.clientX-r.left)/r.width,(event.clientY-r.top)/r.height),prop=C.studioProps.pick(display.scene.props,ray);if(prop)inspector('prop',prop.id);else inspector('card');}
  function focusAt(s, event) { var r = s.viewport.getBoundingClientRect(), display = C.studioScenes.clone(s.scene); if (display.camera.autoFrame) C.studioCamera.frame(display, r.width / r.height); var m = C.studioCamera.matrices(display.camera, r.width / r.height, display.card), ray = C.studioCamera.ray(m, (event.clientX - r.left) / r.width, (event.clientY - r.top) / r.height), normal = C.studioCamera.transform(m.model, [0, 0, 1, 0]).slice(0, 3), point = C.studioCamera.plane(ray, [0, 0, 0], normal), local = point && C.studioCamera.transform(m.inverseModel, point);
    if (!local || Math.abs(local[0]) > .5 || Math.abs(local[1]) > .7) point = C.studioCamera.plane(ray, [0, -.9, 0], [0, 1, 0]); if (!point || point.some(function (v) { return !Number.isFinite(v) || Math.abs(v) > 20; })) point = [0, 0, 0]; mutate(function () { s.scene.camera.focus = point; if (!s.scene.camera.aperture) s.scene.camera.aperture = 2; }); s.focusPick = false; inspector('camera'); status('Focus point set.'); }
  function shell(s) {
    C.studioUI.build(s, { begin: begin, commit: commit, mutate: mutate, restore: restore, dirty: dirty, status: status, frame: frame, repaint: repaint, select: inspector, addLight: addLight, addProp:addProp,loadScene:loadScene,saveSlot:saveSlot, capture:function(){C.studioPhotoPanel.capture(s);}, remove: remove, duplicate: duplicate }); s.gizmos = C.studioGizmos.create(s);s.director=C.studioDirector.create(s);
    function end(event) { var click=s.drag&&event&&event.type==='pointerup'&&!s.drag.pan&&Math.hypot(event.clientX-s.drag.startX,event.clientY-s.drag.startY)<4; if (s.drag && s.viewport.hasPointerCapture(s.drag.id)) s.viewport.releasePointerCapture(s.drag.id); s.drag = null; commit();if(click)selectAt(s,event); }
    s.root.addEventListener('keydown', function (event) { event.stopPropagation(); var key = String(event.key).toLowerCase(), target = event.target;
      if (event.key === 'Tab') { var list = C.accessibility.focusables(s.root), index = list.indexOf(root.document.activeElement), next = event.shiftKey ? (index <= 0 ? list.length - 1 : index - 1) : (index + 1) % list.length; if (list.length) { event.preventDefault(); list[next].focus(); } return; }
      if (event.key === 'Escape') { event.preventDefault();if(s.recordJob){s.recordJob.stop(true);status('Recording cancelled.');return;}if(s.photoBusy){s.photoJob.cancel();status('Capture cancelled.');return;} if (s.focusPick) { s.focusPick = false; status('Focus selection cancelled.'); } else if (s.selected) { commit(); s.selected = s.selectedId = null; C.studioUI.closeDirector(s);s.root.querySelectorAll('[data-studio-mode]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.studioMode==='inspect'));});s.panel.replaceChildren(); node('p', 'studio-copy', s.panel, 'Nothing selected. Press Esc again to return to the card.'); dirty(); } else C.studioController.exit(); return; }
      if(s.photoBusy||s.recordJob){event.preventDefault();return;}if ((event.ctrlKey || event.metaKey) && !event.altKey && !target.matches('input[type=text],textarea,[contenteditable]')) { if (key === 'z') { event.preventDefault(); restore(event.shiftKey); } else if (key === 'd') { event.preventDefault(); duplicate(); } return; }
      if (target.matches('input,select,textarea,[contenteditable]') || target.closest('[data-studio-handle]') || event.ctrlKey || event.metaKey || event.altKey) return;
      if (key === ' ' || key === 'spacebar') { event.preventDefault(); if(!event.repeat)s.director.toggleTurntable(); return; }
      if (key === 'l') { event.preventDefault(); addLight('point'); } else if (key === 'p') { event.preventDefault(); inspector('props'); } else if (key === 'c') inspector('camera'); else if (key === 'delete' || key === 'backspace') { event.preventDefault(); remove(); } else if (key === 'f') { event.preventDefault(); mutate(frame); } else if (/^arrow/.test(key) && s.renderer && s.renderer.kind !== 'Simple') { event.preventDefault(); mutate(function () { if (event.shiftKey) C.studioCamera.pan(s.scene.camera, key === 'arrowleft' ? -12 : key === 'arrowright' ? 12 : 0, key === 'arrowup' ? -12 : key === 'arrowdown' ? 12 : 0, s.viewport.clientHeight); else C.studioCamera.orbit(s.scene.camera, key === 'arrowleft' ? -8 : key === 'arrowright' ? 8 : 0, key === 'arrowup' ? -8 : key === 'arrowdown' ? 8 : 0); }); } else if (key === '+' || key === '=' || key === '-') { event.preventDefault(); mutate(function () { C.studioCamera.dolly(s.scene.camera, key === '-' ? 80 : -80); }); }
    });
    ['pointerdown', 'pointerup', 'pointermove', 'pointercancel', 'click', 'contextmenu', 'wheel', 'keyup'].forEach(function (name) { s.root.addEventListener(name, function (event) { event.stopPropagation(); if (name === 'contextmenu') event.preventDefault(); }); });
    s.viewport.addEventListener('pointerdown', function (event) { if (event.target.closest('[data-studio-handle]') || s.closing || s.photoBusy || s.recordJob || !s.renderer || s.renderer.kind === 'Simple') return; if (s.focusPick) { event.preventDefault(); return focusAt(s, event); } if (event.button !== 0 && event.button !== 2) return; s.director.pause(true);commit(); begin(); if (s.scene.camera.autoFrame) frame(); s.drag = { id: event.pointerId, x: event.clientX, y: event.clientY,startX:event.clientX,startY:event.clientY, pan: event.button === 2 || event.shiftKey }; s.viewport.setPointerCapture(event.pointerId); s.viewport.focus(); });
    s.viewport.addEventListener('pointermove', function (event) { if (!s.drag || s.drag.id !== event.pointerId) return; var dx = event.clientX - s.drag.x, dy = event.clientY - s.drag.y; if (s.drag.pan) C.studioCamera.pan(s.scene.camera, dx, dy, s.viewport.clientHeight); else C.studioCamera.orbit(s.scene.camera, dx, dy); s.drag.x = event.clientX; s.drag.y = event.clientY; dirty(); });
    s.viewport.addEventListener('pointerup', end); s.viewport.addEventListener('pointercancel', end); s.viewport.addEventListener('lostpointercapture', end);
    s.viewport.addEventListener('wheel', function (event) { event.preventDefault(); if (s.closing || s.photoBusy || s.recordJob) return; // One wheel gesture is coalesced until the next action/exit, with no timer.
      s.director.pause(true);begin(); if (s.scene.camera.autoFrame) frame(); C.studioCamera.dolly(s.scene.camera, event.deltaY); dirty();
    }, { passive: false });
    s.cleanups.push(C.events.on('studio:albumContext',function(e){if(e.active&&s.recordJob)s.recordJob.stop(true);s.lastFrame=null;dirty();}));s.cleanups.push(C.events.on('fx:visibility', function (visible) { end(); s.gizmos.cancel();if(!visible&&s.photoJob)s.photoJob.cancel();if(!visible&&s.recordJob)s.recordJob.stop(true); s.lastFrame = null; if (visible) dirty(); }));
    s.cleanups.push(C.events.on('motion:changed', function () { if(C.motion.reduced)s.director.pause();dirty(); if (s.selected) inspector(s.selected, s.selectedId); }));
    s.cleanups.push(C.events.on('settings:changed', function (change) { if (change.key === 'strobing') dirty(); }));
    if (root.ResizeObserver) { s.observer = new root.ResizeObserver(dirty); s.observer.observe(s.viewport); }
    s.cleanups.push(C.viewport.onResize(dirty));
  }
  function ghost(s) { var rect = C.viewport.rect(s.view.el.getBoundingClientRect()); s.source = { left: rect.left, top: rect.top, width: rect.width, height: rect.height }; if (!s.template) s.template = s.view.el.cloneNode(true); var copy = s.template.cloneNode(true); copy.classList.add('studio-card-ghost'); copy.setAttribute('aria-hidden', 'true'); copy.inert = true; copy.removeAttribute('tabindex'); copy.style.width = rect.width + 'px'; copy.style.height = rect.height + 'px'; copy.style.margin = '0'; copy.querySelectorAll('[id]').forEach(function (el) { var id = el.id, next = id + '-studio-' + generation; el.id = next; copy.querySelectorAll('*').forEach(function (part) { Array.from(part.attributes).forEach(function (attr) { if (attr.value.indexOf('#' + id) >= 0) part.setAttribute(attr.name, attr.value.split('#' + id).join('#' + next)); }); }); }); copy.querySelectorAll('[tabindex]').forEach(function (el) { el.removeAttribute('tabindex'); }); s.ghost = copy; s.root.appendChild(copy); }
  function drawTransition(s, progress) { var r = C.viewport.rect(s.viewport.getBoundingClientRect()), h = r.height * 1.4 / (2 * s.scene.camera.distance * Math.tan(s.scene.camera.fov * Math.PI / 360)), target = { width: h * 5 / 7, height: h, left: r.left + (r.width - h * 5 / 7) / 2, top: r.top + (r.height - h) / 2 }, p = 1 - Math.pow(1 - progress, 3), k = s.closing ? 1 - p : p; if (s.ghost) { s.ghost.style.transform = 'translate3d(' + (s.source.left + (target.left - s.source.left) * k) + 'px,' + (s.source.top + (target.top - s.source.top) * k) + 'px,0) scale(' + (1 + (target.width / s.source.width - 1) * k) + ')'; s.ghost.style.opacity = C.motion.reduced ? 0 : s.closing ? p : 1 - Math.max(0, (p - .65) / .35); } s.root.style.setProperty('--studio-enter', s.closing ? 1 - p : p); s.canvas.style.opacity = s.closing ? 1 - p : p; }
  function update(now, dt) { var s = session; if (!s) return false; if (s.transition) { s.age += Math.min(dt, 50); var p = Math.min(1, s.age / (C.motion.reduced ? 180 : 450)); drawTransition(s, p); if (p === 1) { s.transition = false; if (s.closing) { cleanup(s); return false; } if (s.ghost) { s.ghost.remove(); s.ghost = null; } s.root.classList.add('is-ready'); s.dirty = true; } }
    var limits=C.studioScenes.limits(s.tier),effectiveForAnimation={lights:s.scene.lights.filter(function(l){return l.visible;}).slice(0,limits.lights),props:s.scene.props.filter(function(p){return p.visible;}).slice(0,limits.props)},canAnimate=!s.closing&&!s.photoBusy&&s.renderer&&s.renderer.kind!=='Simple',animated=canAnimate&&(s.director.active()||C.studioMaterials.active(s.faces,s.tier)||C.studioLights.active(effectiveForAnimation.lights,s.tier)||C.studioProps.active(effectiveForAnimation.props,s.tier)),running=animated||!!(s.recordJob&&!s.recordJob.done),seconds=running&&s.lastFrame!==null?Math.min(80,now-s.lastFrame)/1000:0;
    if(running){if(animated)s.lightTime+=seconds;s.director.advance(seconds);s.dirty=true;}s.lastFrame=running?now:null;
    if(s.dirty&&s.renderer&&!s.closing){s.dirty=false;var display=presented(s),effective=display.scene;s.propAssets.sync(s.renderer.kind==='Simple'?[]:effective.props);s.renderer.draw(effective,display.width,display.height,s.propAssets);C.studioUI.guide(s,display.width,display.height);s.gizmos.draw(effective,display.width,display.height);s.director.sync();if(s.recordJob&&!s.recordJob.done)s.recordJob.frame(now,seconds);}
    var shutter=false;if(s.shutter){s.shutter.age+=Math.min(dt,50);var p=Math.min(1,s.shutter.age/420);s.shutter.el.style.setProperty('--shutter',String(p));s.shutter.el.style.opacity=String(Math.sin(p*Math.PI));if(s.shutter.fly){s.shutter.fly.style.transform=C.motion.reduced?'none':'translate('+(s.shutter.dx*p)+'px,'+(s.shutter.dy*p)+'px) scale('+(1-.75*p)+')';s.shutter.fly.style.opacity=String(1-p);}if(p===1){URL.revokeObjectURL(s.shutter.url);s.shutter.el.remove();if(s.shutter.fly)s.shutter.fly.remove();s.shutter=null;}else shutter=true;}return s.transition || running || shutter;
  }
  async function repaint() { var s = session; if (!s || s.closing) return; var revision = ++s.revision; status('Preparing printed face…'); var faces;
    try { faces = await C.studioFace.paint(s.view.card, s.view.instance, s.scene, s.tier, s.view.el, s.entry, function () { return session === s && !s.closing && revision === s.revision; }); if (!faces) return false; if (session !== s || s.closing || revision !== s.revision) { faces.destroy(); return; } if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy();
      // A lost old context cannot be reused; use a fresh canvas when repainting.
      if (s.faces) { var next = node('canvas', 'studio-canvas', s.viewport); next.setAttribute('aria-hidden', 'true'); s.canvas.replaceWith(next); s.canvas = next; }
      s.faces = faces;
      try { s.renderer = s.tier === 'very-low' ? C.studioRenderer.simple(s.canvas, faces) : C.studioRenderer.create(s.canvas, faces, s.tier); } catch (_) { var fallback = node('canvas', 'studio-canvas', s.viewport); s.canvas.replaceWith(fallback); s.canvas = fallback; s.renderer = C.studioRenderer.simple(fallback, faces); }
      if (!s.entered || s.renderer.kind === 'Simple') inspector(s.selected || 'card', s.selectedId); s.loading.hidden = true; status(s.renderer.kind === 'Simple' ? 'Simple preview · one static light · no spatial gizmos or lens passes.' : 'Last scene autosaves on exit · ' + (faces.source === 'embedded' ? 'original artwork' : 'procedural art fallback')); dirty();
      if (!s.entered) { s.entered = true; s.age = 0; s.transition = true; C.events.emit('studio:enter', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake(); } return true;
    } catch (error) { if (faces) faces.destroy(); if (session === s) { status('The studio could not prepare this card. Return to detail and try again.'); C.studioController.exit(); } return false; }
  }
  function releaseDetailTilt(view){var release=function(){if(!view.destroyed)view.setTiltLock(null);view.el.removeEventListener('pointermove',release);};view.el.addEventListener('pointermove',release,{once:true});}
  function cleanup(s) { if (session !== s) return; session = null; generation++;if(s.recordJob)s.recordJob.stop(true);if(s.photoJob)s.photoJob.cancel();if(C.studioAlbumUI&&C.studioAlbumUI.active)C.studioAlbumUI.close();if(s.photoFilm)s.photoFilm.destroy();if(s.shutter&&s.shutter.url)URL.revokeObjectURL(s.shutter.url); s.cleanups.forEach(function (fn) { fn(); }); if (s.observer) s.observer.disconnect(); if (s.gizmos) s.gizmos.destroy(); if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy();if(s.propAssets)s.propAssets.destroy(); C.art.releaseStudioData(); C.accessibility.release(s.root); s.root.remove(); root.document.body.classList.remove('studio-active'); s.hidden.forEach(function (record) { if (record.el.isConnected) { record.el.inert = record.inert; record.el.style.visibility = record.visibility; } });
    if (!s.view.destroyed && s.view.el.isConnected && C.detail.phase === 'detail') { s.view.setVisible(true); s.view.setFace(s.pose.side); s.view.setMode('full'); s.view.setTiltLock({ x: s.pose.x, y: s.pose.y }); releaseDetailTilt(s.view); }
    s.releaseMenu(); s.releaseScope(); if (s.timersRunning) C.timers.start(); if (s.focus && s.focus.isConnected) s.focus.focus({ preventScroll: true }); else if (C.detail.closeButton) C.detail.closeButton.focus({ preventScroll: true }); if (s.entered) C.events.emit('studio:exit', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake();
  }
  C.studioController = {
    get active() { return !!session; }, get scene() { return session && session.scene; },get capturing(){return !!(session&&session.photoBusy);},get instanceId(){return session&&session.view.instance.instanceId;},loadPhoto:function(value){if(!session||session.photoBusy||session.closing)return false;loadScene(value);inspector('photo');return true;},
    enter: async function (context, view) { if (session) return false; var styles = root.getComputedStyle(view.el), pose = { x: parseFloat(styles.getPropertyValue('--rx')) || 0, y: parseFloat(styles.getPropertyValue('--ry')) || 0, side: view.side }, s = session = { view: view, entry: context.entry, pose: pose, scene: context.sceneJson?C.studioScenes.parse(context.sceneJson):C.studioScenes.last(view.instance) || C.studioScenes.defaults(view.instance, pose), tier: C.settings.get('quality'), selected: 'card', cleanups: [], hidden: [], focus: root.document.activeElement, revision: 0, dirty: true, age: 0, lightTime: 0, lastFrame: null, transition: false, entered: false, closing: false }; s.scene.card.source=C.studioScenes.defaults(view.instance).card.source;s.lightTime=s.scene.presentationTime||0;s.history = C.studioScenes.history(s.scene);s.propAssets=C.studioProps.assets(s,dirty);
      s.timersRunning = C.timers.running; C.timers.stop(); s.releaseMenu = C.menu.suspendActivity(); s.releaseScope = C.fx.scope('studio'); shell(s); ghost(s); drawTransition(s, 0); view.setMode('lite'); view.setVisible(false);
      C.viewport.layers().forEach(function (el) { if (el === s.root || el.tagName === 'SCRIPT') return; s.hidden.push({ el: el, inert: el.inert, visibility: el.style.visibility }); el.inert = true; el.style.visibility = 'hidden'; }); root.document.body.classList.add('studio-active'); C.accessibility.trap(s.root); s.cleanups.push(C.fx.subscribe(update, 'studio')); s.cleanups.push(C.events.on('save:willReplace', function () { if (session === s) cleanup(s); })); s.cleanups.push(C.events.on('detail:reset', function () { if (session === s) cleanup(s); })); inspector('card'); s.exit.focus({ preventScroll: true }); return await repaint();
    },
    exit: function () { var s = session; if (!s || s.closing) return; commit();if(s.recordJob)s.recordJob.stop(true);if(s.photoJob)s.photoJob.cancel();s.scene.presentationTime=s.lightTime;s.scene.director.playhead=s.director.time;s.scene.director.preview=s.director.preview;s.gizmos.cancel(); s.closing = true; s.revision++; if (s.entered) C.studioScenes.saveLast(s.view.instance, s.scene); if (!s.entered || root.document.hidden) return cleanup(s);
      // Returning uses the detail card's original pose, not the orbit angle.
      s.view.setFace(s.pose.side); ghost(s); s.transition = true; s.age = 0; s.root.classList.remove('is-ready'); C.fx.wake();
    }
  };
})(window.Cardable, window);
