(function (C, root) {
  'use strict';
  var session = null, generation = 0;
  function node(tag, name, parent, value) { return C.studioUI.node(tag, name, parent, value); }
  function dirty() { if (!session) return; session.dirty = true; C.fx.wake(); }
  function status(message) { if (session) session.status.textContent = message; }
  function inspector(kind, id) { if (session) C.studioUI.inspect(session, kind, id); }
  function begin() { if (session && !session.closing) session.history.begin(session.scene); }
  function commit() { if (!session || session.closing) return; session.history.commit(session.scene); C.studioUI.history(session); C.studioUI.outliner(session); }
  function mutate(run) { if (!session || session.closing) return; commit(); begin(); var plate = session.scene.card.plate; run(); commit(); C.studioUI.outliner(session); if (plate !== session.scene.card.plate) repaint(); dirty(); }
  function frame() { if (!session) return; var r = session.viewport.getBoundingClientRect(); C.studioCamera.frame(session.scene, r.width / Math.max(1, r.height)); }
  function restore(redo) { var s = session; if (!s || s.closing) return; commit(); var next = redo ? s.history.redo() : s.history.undo(); if (!next) return; var plate = s.scene.card.plate; s.scene = next; inspector(s.selected || 'card', s.selectedId); C.studioUI.history(s); if (plate !== next.card.plate) repaint(); dirty(); }
  function addLight(type) { var s = session; if (!s || s.closing) return; if (s.scene.lights.length >= C.studioScenes.limits(s.tier).lights) return status('Light limit reached for ' + s.tier + '. Delete a light or choose a smaller rig.'); var light = C.studioLights.create(type); mutate(function () { s.scene.lights.push(light); }); inspector('light', light.id); if (s.scene.lights.length >= C.studioScenes.limits(s.tier).lights - 1) status('Near the light limit: ' + s.scene.lights.length + ' / ' + C.studioScenes.limits(s.tier).lights + '.'); }
  function remove(id) { var s = session, light = s && s.scene.lights.find(function (l) { return l.id === (id || s.selectedId); }); if (!light) return; if (light.locked) return status('Unlock this light before deleting it.'); mutate(function () { s.scene.lights = s.scene.lights.filter(function (l) { return l !== light; }); }); inspector('lights'); }
  function duplicate() { var s = session, light = s && s.scene.lights.find(function (l) { return l.id === s.selectedId; }); if (!light || light.locked) return; if (s.scene.lights.length >= C.studioScenes.limits(s.tier).lights) return status('Light limit reached.'); var next = C.studioLights.duplicate(light); mutate(function () { s.scene.lights.push(next); }); inspector('light', next.id); }
  function focusAt(s, event) { var r = s.viewport.getBoundingClientRect(), display = C.studioScenes.clone(s.scene); if (display.camera.autoFrame) C.studioCamera.frame(display, r.width / r.height); var m = C.studioCamera.matrices(display.camera, r.width / r.height, display.card), ray = C.studioCamera.ray(m, (event.clientX - r.left) / r.width, (event.clientY - r.top) / r.height), normal = C.studioCamera.transform(m.model, [0, 0, 1, 0]).slice(0, 3), point = C.studioCamera.plane(ray, [0, 0, 0], normal), local = point && C.studioCamera.transform(m.inverseModel, point);
    if (!local || Math.abs(local[0]) > .5 || Math.abs(local[1]) > .7) point = C.studioCamera.plane(ray, [0, -.9, 0], [0, 1, 0]); if (!point || point.some(function (v) { return !Number.isFinite(v) || Math.abs(v) > 20; })) point = [0, 0, 0]; mutate(function () { s.scene.camera.focus = point; if (!s.scene.camera.aperture) s.scene.camera.aperture = 2; }); s.focusPick = false; inspector('camera'); status('Focus point set.'); }
  function shell(s) {
    C.studioUI.build(s, { begin: begin, commit: commit, mutate: mutate, restore: restore, dirty: dirty, status: status, frame: frame, repaint: repaint, select: inspector, addLight: addLight, remove: remove, duplicate: duplicate }); s.gizmos = C.studioGizmos.create(s);
    function end() { if (s.drag && s.viewport.hasPointerCapture(s.drag.id)) s.viewport.releasePointerCapture(s.drag.id); s.drag = null; commit(); }
    s.root.addEventListener('keydown', function (event) { event.stopPropagation(); var key = String(event.key).toLowerCase(), target = event.target;
      if (event.key === 'Tab') { var list = C.accessibility.focusables(s.root), index = list.indexOf(root.document.activeElement), next = event.shiftKey ? (index <= 0 ? list.length - 1 : index - 1) : (index + 1) % list.length; if (list.length) { event.preventDefault(); list[next].focus(); } return; }
      if (event.key === 'Escape') { event.preventDefault(); if (s.focusPick) { s.focusPick = false; status('Focus selection cancelled.'); } else if (s.selected) { commit(); s.selected = s.selectedId = null; s.panel.replaceChildren(); node('p', 'studio-copy', s.panel, 'Nothing selected. Press Esc again to return to the card.'); dirty(); } else C.studioController.exit(); return; }
      if ((event.ctrlKey || event.metaKey) && !event.altKey && !target.matches('input[type=text],textarea,[contenteditable]')) { if (key === 'z') { event.preventDefault(); restore(event.shiftKey); } else if (key === 'd') { event.preventDefault(); duplicate(); } return; }
      if (target.matches('input,select,textarea,[contenteditable]') || target.closest('[data-studio-handle]') || event.ctrlKey || event.metaKey || event.altKey) return;
      if (key === ' ' || key === 'spacebar') { event.preventDefault(); status('Turntable controls begin in milestone E.'); return; }
      if (key === 'l') { event.preventDefault(); addLight('point'); } else if (key === 'p') { event.preventDefault(); status('Procedural props begin in milestone C.'); } else if (key === 'c') inspector('camera'); else if (key === 'delete' || key === 'backspace') { event.preventDefault(); remove(); } else if (key === 'f') { event.preventDefault(); mutate(frame); } else if (/^arrow/.test(key) && s.renderer && s.renderer.kind !== 'Simple') { event.preventDefault(); mutate(function () { if (event.shiftKey) C.studioCamera.pan(s.scene.camera, key === 'arrowleft' ? -12 : key === 'arrowright' ? 12 : 0, key === 'arrowup' ? -12 : key === 'arrowdown' ? 12 : 0, s.viewport.clientHeight); else C.studioCamera.orbit(s.scene.camera, key === 'arrowleft' ? -8 : key === 'arrowright' ? 8 : 0, key === 'arrowup' ? -8 : key === 'arrowdown' ? 8 : 0); }); } else if (key === '+' || key === '=' || key === '-') { event.preventDefault(); mutate(function () { C.studioCamera.dolly(s.scene.camera, key === '-' ? 80 : -80); }); }
    });
    ['pointerdown', 'pointerup', 'pointermove', 'pointercancel', 'click', 'contextmenu', 'wheel', 'keyup'].forEach(function (name) { s.root.addEventListener(name, function (event) { event.stopPropagation(); if (name === 'contextmenu') event.preventDefault(); }); });
    s.viewport.addEventListener('pointerdown', function (event) { if (event.target.closest('[data-studio-handle]') || s.closing || !s.renderer || s.renderer.kind === 'Simple') return; if (s.focusPick) { event.preventDefault(); return focusAt(s, event); } if (event.button !== 0 && event.button !== 2) return; commit(); begin(); if (s.scene.camera.autoFrame) frame(); s.drag = { id: event.pointerId, x: event.clientX, y: event.clientY, pan: event.button === 2 || event.shiftKey }; s.viewport.setPointerCapture(event.pointerId); s.viewport.focus(); });
    s.viewport.addEventListener('pointermove', function (event) { if (!s.drag || s.drag.id !== event.pointerId) return; var dx = event.clientX - s.drag.x, dy = event.clientY - s.drag.y; if (s.drag.pan) C.studioCamera.pan(s.scene.camera, dx, dy, s.viewport.clientHeight); else C.studioCamera.orbit(s.scene.camera, dx, dy); s.drag.x = event.clientX; s.drag.y = event.clientY; dirty(); });
    s.viewport.addEventListener('pointerup', end); s.viewport.addEventListener('pointercancel', end); s.viewport.addEventListener('lostpointercapture', end);
    s.viewport.addEventListener('wheel', function (event) { event.preventDefault(); if (s.closing) return; // One wheel gesture is coalesced until the next action/exit, with no timer.
      begin(); if (s.scene.camera.autoFrame) frame(); C.studioCamera.dolly(s.scene.camera, event.deltaY); dirty();
    }, { passive: false });
    s.cleanups.push(C.events.on('fx:visibility', function (visible) { end(); s.gizmos.cancel(); s.lastFrame = null; if (visible) dirty(); }));
    s.cleanups.push(C.events.on('motion:changed', function () { dirty(); if (s.selected) inspector(s.selected, s.selectedId); }));
    s.cleanups.push(C.events.on('settings:changed', function (change) { if (change.key === 'strobing') dirty(); }));
    if (root.ResizeObserver) { s.observer = new root.ResizeObserver(dirty); s.observer.observe(s.viewport); } else { root.addEventListener('resize', dirty); s.cleanups.push(function () { root.removeEventListener('resize', dirty); }); }
  }
  function ghost(s) { var rect = s.view.el.getBoundingClientRect(); s.source = { left: rect.left, top: rect.top, width: rect.width, height: rect.height }; if (!s.template) s.template = s.view.el.cloneNode(true); var copy = s.template.cloneNode(true); copy.classList.add('studio-card-ghost'); copy.setAttribute('aria-hidden', 'true'); copy.inert = true; copy.removeAttribute('tabindex'); copy.style.width = rect.width + 'px'; copy.style.height = rect.height + 'px'; copy.style.margin = '0'; copy.querySelectorAll('[id]').forEach(function (el) { var id = el.id, next = id + '-studio-' + generation; el.id = next; copy.querySelectorAll('*').forEach(function (part) { Array.from(part.attributes).forEach(function (attr) { if (attr.value.indexOf('#' + id) >= 0) part.setAttribute(attr.name, attr.value.split('#' + id).join('#' + next)); }); }); }); copy.querySelectorAll('[tabindex]').forEach(function (el) { el.removeAttribute('tabindex'); }); s.ghost = copy; s.root.appendChild(copy); }
  function drawTransition(s, progress) { var r = s.viewport.getBoundingClientRect(), h = r.height * 1.4 / (2 * s.scene.camera.distance * Math.tan(s.scene.camera.fov * Math.PI / 360)), target = { width: h * 5 / 7, height: h, left: r.left + (r.width - h * 5 / 7) / 2, top: r.top + (r.height - h) / 2 }, p = 1 - Math.pow(1 - progress, 3), k = s.closing ? 1 - p : p; if (s.ghost) { s.ghost.style.transform = 'translate3d(' + (s.source.left + (target.left - s.source.left) * k) + 'px,' + (s.source.top + (target.top - s.source.top) * k) + 'px,0) scale(' + (1 + (target.width / s.source.width - 1) * k) + ')'; s.ghost.style.opacity = C.motion.reduced ? 0 : s.closing ? p : 1 - Math.max(0, (p - .65) / .35); } s.root.style.setProperty('--studio-enter', s.closing ? 1 - p : p); s.canvas.style.opacity = s.closing ? 1 - p : p; }
  function update(now, dt) { var s = session; if (!s) return false; if (s.transition) { s.age += Math.min(dt, 50); var p = Math.min(1, s.age / (C.motion.reduced ? 180 : 450)); drawTransition(s, p); if (p === 1) { s.transition = false; if (s.closing) { cleanup(s); return false; } if (s.ghost) { s.ghost.remove(); s.ghost = null; } s.root.classList.add('is-ready'); s.dirty = true; } }
    var animated = !s.closing && C.studioLights.active(C.studioScenes.effective(s.scene, s.tier).lights, s.tier);
    if (animated) { s.lightTime += s.lastFrame === null ? 0 : Math.min(80, now - s.lastFrame) / 1000; s.dirty = true; } s.lastFrame = animated ? now : null;
    if (s.dirty && s.renderer && !s.closing) { s.dirty = false; var r = s.viewport.getBoundingClientRect(); var effective = C.studioScenes.effective(s.scene, s.tier); if (effective.camera.autoFrame) C.studioCamera.frame(effective, r.width / Math.max(1, r.height)); effective.lights = C.studioLights.sample(effective.lights, s.lightTime, s.tier); s.renderer.draw(effective, r.width, r.height); C.studioUI.guide(s, r.width, r.height); s.gizmos.draw(effective, r.width, r.height); }
    return s.transition || animated;
  }
  async function repaint() { var s = session; if (!s || s.closing) return; var revision = ++s.revision; status('Preparing printed face…'); var faces;
    try { faces = await C.studioFace.paint(s.view.card, s.view.instance, s.scene, s.tier, s.view.el, s.entry, function () { return session === s && !s.closing && revision === s.revision; }); if (!faces) return false; if (session !== s || s.closing || revision !== s.revision) { faces.destroy(); return; } if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy();
      // A lost old context cannot be reused; use a fresh canvas when repainting.
      if (s.faces) { var next = node('canvas', 'studio-canvas', s.viewport); next.setAttribute('aria-hidden', 'true'); s.canvas.replaceWith(next); s.canvas = next; }
      s.faces = faces;
      try { s.renderer = s.tier === 'very-low' ? C.studioRenderer.simple(s.canvas, faces) : C.studioRenderer.create(s.canvas, faces, s.tier); } catch (_) { var fallback = node('canvas', 'studio-canvas', s.viewport); s.canvas.replaceWith(fallback); s.canvas = fallback; s.renderer = C.studioRenderer.simple(fallback, faces); }
      if (!s.entered || s.renderer.kind === 'Simple') inspector(s.selected || 'card', s.selectedId); s.loading.hidden = true; status(s.renderer.kind === 'Simple' ? 'Simple preview · one static light · no spatial gizmos or lens passes.' : 'Last scene autosaves on exit · ' + (faces.source === 'embedded' ? 'original artwork' : 'procedural art fallback')); dirty();
      if (!s.entered) { s.entered = true; s.age = 0; s.transition = true; C.events.emit('studio:enter', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake(); } return true;
    } catch (error) { if (faces) faces.destroy(); if (session === s) { status('The studio could not prepare this card. Return to detail and try again.'); C.studioController.exit(); } return false; }
  }
  function cleanup(s) { if (session !== s) return; session = null; generation++; s.cleanups.forEach(function (fn) { fn(); }); if (s.observer) s.observer.disconnect(); if (s.gizmos) s.gizmos.destroy(); if (s.renderer) s.renderer.destroy(); if (s.faces) s.faces.destroy(); C.art.releaseStudioData(); C.accessibility.release(s.root); s.root.remove(); root.document.body.classList.remove('studio-active'); s.hidden.forEach(function (record) { if (record.el.isConnected) { record.el.inert = record.inert; record.el.style.visibility = record.visibility; } });
    if (!s.view.destroyed && s.view.el.isConnected && C.detail.phase === 'detail') { s.view.setVisible(true); s.view.setFace(s.pose.side); s.view.setMode('full'); s.view.setTiltLock({ x: s.pose.x, y: s.pose.y }); var releaseTilt = function () { if (!s.view.destroyed) s.view.setTiltLock(null); s.view.el.removeEventListener('pointermove', releaseTilt); }; s.view.el.addEventListener('pointermove', releaseTilt, { once: true }); }
    s.releaseMenu(); s.releaseScope(); if (s.timersRunning) C.timers.start(); if (s.focus && s.focus.isConnected) s.focus.focus({ preventScroll: true }); else if (C.detail.closeButton) C.detail.closeButton.focus({ preventScroll: true }); if (s.entered) C.events.emit('studio:exit', { cardId: s.view.card.id, instanceId: s.view.instance.instanceId, at: Date.now() }); C.fx.wake();
  }
  C.studioController = {
    get active() { return !!session; }, get scene() { return session && session.scene; },
    enter: async function (context, view) { if (session) return false; var styles = root.getComputedStyle(view.el), pose = { x: parseFloat(styles.getPropertyValue('--rx')) || 0, y: parseFloat(styles.getPropertyValue('--ry')) || 0, side: view.side }, s = session = { view: view, entry: context.entry, pose: pose, scene: C.studioScenes.last(view.instance) || C.studioScenes.defaults(view.instance, pose), tier: C.settings.get('quality'), selected: 'card', cleanups: [], hidden: [], focus: root.document.activeElement, revision: 0, dirty: true, age: 0, lightTime: 0, lastFrame: null, transition: false, entered: false, closing: false }; s.history = C.studioScenes.history(s.scene);
      s.timersRunning = C.timers.running; C.timers.stop(); s.releaseMenu = C.menu.suspendActivity(); s.releaseScope = C.fx.scope('studio'); shell(s); ghost(s); drawTransition(s, 0); view.setMode('lite'); view.setVisible(false);
      Array.from(root.document.body.children).forEach(function (el) { if (el === s.root || el.tagName === 'SCRIPT') return; s.hidden.push({ el: el, inert: el.inert, visibility: el.style.visibility }); el.inert = true; el.style.visibility = 'hidden'; }); root.document.body.classList.add('studio-active'); C.accessibility.trap(s.root); s.cleanups.push(C.fx.subscribe(update, 'studio')); s.cleanups.push(C.events.on('save:willReplace', function () { if (session === s) cleanup(s); })); s.cleanups.push(C.events.on('detail:reset', function () { if (session === s) cleanup(s); })); inspector('card'); s.exit.focus({ preventScroll: true }); return await repaint();
    },
    exit: function () { var s = session; if (!s || s.closing) return; commit(); s.gizmos.cancel(); s.closing = true; s.revision++; if (s.entered) C.studioScenes.saveLast(s.view.instance, s.scene); if (!s.entered || root.document.hidden) return cleanup(s);
      // Returning uses the detail card's original pose, not the orbit angle.
      s.view.setFace(s.pose.side); ghost(s); s.transition = true; s.age = 0; s.root.classList.remove('is-ready'); C.fx.wake();
    }
  };
})(window.Cardable, window);
