(function(C,root){'use strict';
  C.settingsShell={create:function(panel){
    var groups={},rows={},navButtons={},current='Graphics',query='',confirmations=[],search,rail,content,preview;
    var body=C.packMarkup.node('div','cb-settings-body',panel);rail=C.packMarkup.node('nav','cb-settings-rail cb-scroll',body);rail.setAttribute('aria-label','Settings groups');
    var column=C.packMarkup.node('div','cb-settings-column',body), tools=C.packMarkup.node('div','cb-settings-tools',column);
    search=C.ui.create('search-field',{label:'Search settings',placeholder:'Search settings…',onChange:function(value){query=value.toLowerCase().trim();refresh();}});tools.appendChild(search);
    var mode=C.ui.create('segmented-control',{label:'Settings mode',options:['Simple','Advanced'],value:C.settings.get('settingsMode')==='advanced'?1:0,onChange:function(v){C.settings.set('settingsMode',v.toLowerCase());refresh();}});tools.appendChild(mode);
    var work=C.packMarkup.node('div','cb-settings-work',column);content=C.packMarkup.node('div','settings-scroll cb-scroll',work);preview=C.packMarkup.node('aside','cb-settings-preview',work);preview.setAttribute('aria-label','Live card preview');var empty=C.ui.create('empty-state',{label:'No matching settings. Try another search.'});empty.hidden=true;content.appendChild(empty);var advancedButton=C.ui.create('button',{label:'Show Advanced',onClick:function(){C.settings.set('settingsMode','advanced');}});empty.appendChild(advancedButton);
    function group(name){if(groups[name])return groups[name];var section=C.packMarkup.node('section','settings-group',content);section.dataset.group=name;var heading=C.packMarkup.node('header','cb-section-header',section);C.packMarkup.node('h3','',heading,name);heading.appendChild(C.ui.create('help',{help:name==='Data'?'data':name==='About'?'welcome':'settings',label:'Help with '+name.toLowerCase()}));
      var b=C.ui.create('button',{label:'Restore defaults',title:'Restore defaults for '+name.toLowerCase(),variant:'ghost'});var hasSettings=Object.values(C.settingsSchema.entries).some(function(d){return d.group===name;});if(hasSettings)heading.appendChild(b);var confirm=C.settingsControls.confirmation(b,function(){var before=C.settings.snapshot,next=Object.assign({},before);Object.keys(C.settingsSchema.entries).forEach(function(k){if(C.settingsSchema.entries[k].group===name)next[k]=C.settingsSchema.entries[k].defaultValue;});C.settings.restore(next);C.ui.toast(name+' restored.',{label:'Undo',run:function(){C.settings.restore(before);}});},{announce:function(text){C.preferences.status.textContent=text;}});if(hasSettings)confirmations.push(confirm);else confirm.destroy();
      var nav=C.ui.create('button',{label:name,icon:/Graphic/.test(name)?'eye':/Performance/.test(name)?'clock':/Data/.test(name)?'folder':/About/.test(name)?'help':/Card/.test(name)?'card':'settings',variant:'ghost',onClick:function(){current=name;query='';search.value='';refresh();}});nav.setAttribute('aria-controls','settings-group-'+name.replace(/\W+/g,'-'));section.id=nav.getAttribute('aria-controls');rail.appendChild(nav);navButtons[name]=nav;groups[name]=section;return section;}
    function highlight(label,text){label.replaceChildren();var at=query?text.toLowerCase().indexOf(query):-1;if(at<0){label.textContent=text;return;}label.append(root.document.createTextNode(text.slice(0,at)));var mark=root.document.createElement('mark');mark.textContent=text.slice(at,at+query.length);label.append(mark,root.document.createTextNode(text.slice(at+query.length)));}
    function refresh(){var advanced=C.settings.get('settingsMode')==='advanced',snapshot=C.settings.snapshot;if(!advanced&&groups[current]&&Array.from(groups[current].querySelectorAll('.settings-row')).length&&Array.from(groups[current].querySelectorAll('.settings-row')).every(function(r){return C.settingsSchema.entries[r.dataset.setting].advanced;}))current='Graphics';Object.keys(rows).forEach(function(k){var r=rows[k],d=C.settingsSchema.entries[k],matches=!query||[d.label,d.helper,k].concat(d.aliases||[]).join(' ').toLowerCase().includes(query);r.row.hidden=!matches||!!d.advanced&&!advanced;r.row.dataset.changed=String(snapshot[k]!==d.defaultValue);r.reset.hidden=snapshot[k]===d.defaultValue;highlight(r.label,d.label);});Object.keys(groups).forEach(function(name){var children=Array.from(groups[name].querySelectorAll('.settings-row'));var bindingMatch=name==='Controls'&&C.controlsSettings&&C.controlsSettings.filter(query);var active=query?(bindingMatch||children.length?bindingMatch||children.some(function(r){return !r.hidden;}):groups[name].textContent.toLowerCase().includes(query)):name===current;groups[name].hidden=!active;navButtons[name].hidden=!advanced&&!query&&Array.from(groups[name].querySelectorAll('.settings-row')).length>0&&Array.from(groups[name].querySelectorAll('.settings-row')).every(function(r){return C.settingsSchema.entries[r.dataset.setting].advanced;});navButtons[name].setAttribute('aria-current',String(name===current));});empty.hidden=!query||Object.values(groups).some(function(g){return !g.hidden;});var hiddenAdvanced=!advanced&&Object.keys(rows).some(function(k){var d=C.settingsSchema.entries[k];return d.advanced&&[d.label,d.helper,k].join(' ').toLowerCase().includes(query);});empty.childNodes[0].textContent=hiddenAdvanced?'This setting is in Advanced. Show Advanced to continue.':'No matching settings. Try another search.';advancedButton.hidden=!hiddenAdvanced;mode.style.setProperty('--selected',advanced?1:0);mode.querySelectorAll('button').forEach(function(b,i){b.setAttribute('aria-checked',String(i===(advanced?1:0)));b.tabIndex=i===(advanced?1:0)?0:-1;});}
    function add(row,d){row.dataset.setting=d.key;var label=row.querySelector('.settings-label'),reset=C.ui.create('icon-button',{label:'Reset '+d.label,icon:'reset',onClick:function(){C.settings.set(d.key,d.defaultValue);}});reset.classList.add('cb-setting-reset');row.appendChild(reset);row.appendChild(C.packMarkup.node('span','cb-changed-dot',null));rows[d.key]={row:row,label:label,reset:reset};}
    function focus(id){query='';search.value='';var item=C.settingsSchema.entries[id];if(!item||!rows[id]){if(id&&groups[id])current=id;refresh();return;}if(item.advanced&&C.settings.get('settingsMode')!=='advanced')C.settings.set('settingsMode','advanced');current=item.group;query='';search.value='';refresh();var r=rows[id].row;r.scrollIntoView({block:'center'});r.querySelector('button,input,select')?.focus({preventScroll:true});}
    C.settings.onChange('*',refresh);
    return {body:body,content:content,preview:preview,groups:groups,group:group,add:add,refresh:refresh,focus:focus,update:function(now,dt){var active=false;confirmations.forEach(function(c){active=c.update(now,dt)||active;});return active;}};
  }};
  C.openSettings=function(id){if(C.commands&&C.commands.active)C.commands.close();return C.preferences.show(id);};
})(window.Cardable,window);
