(function (C, root) {
  'use strict';
  var toolBlocked=[];var node=C.packMarkup.node, commands=new Map(), recent=[], palette, sheet, matches=[], selected=0, origin=null, focusMode=false, busy=false;
  function editable(target){return target&&target.closest&&target.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"])');}
  function idle(){return C.opening.phase==='idle'&&!C.tutorial.active&&!C.studio?.active&&!C.studio?.pending&&!C.studioAlbumUI?.active&&!C.dev?.immersive&&!root.document.hidden&&!C.friendly?.modal;}
  function allowed(item){return !item.when||item.when();}
  function context(active){if(active&&!toolBlocked.length){C.viewport.layers().filter(function(el){return el!==palette.backdrop&&el!==sheet&&el.tagName!=='SCRIPT'&&el.tagName!=='CANVAS';}).forEach(function(el){toolBlocked.push({el:el,before:el.inert});el.inert=true;});}else if(!active){toolBlocked.forEach(function(r){if(r.el.isConnected)r.el.inert=r.before;});toolBlocked=[];}C.events.emit('qol:context',{active:active});C.events.emit('menu:visibilityHold',{reason:'qol-tools',active:active});}
  function hide(){if(palette&&!palette.backdrop.hidden)C.paletteUI.hide(palette.backdrop);if(sheet){if(!sheet.hidden)C.paletteUI.hide(sheet);C.accessibility.release(sheet);}context(false);if(origin&&origin.isConnected)origin.focus({preventScroll:true});}
  function run(id){var item=commands.get(id);if(!item||!allowed(item))return;recent=[id].concat(recent.filter(function(x){return x!==id;})).slice(0,12);try{root.localStorage.setItem('cardable.qol.recent',JSON.stringify(recent.filter(function(id){return id.indexOf('card:')!==0;})));}catch(_){}hide();Promise.resolve().then(item.run).catch(function(){C.qol.toast('Could not complete that action.');});}
  function render(){palette.matches.replaceChildren();matches.slice(0,80).forEach(function(match,index){var item=match.item,b=node('button','dev-palette-result',palette.matches);b.type='button';b.id='game-command-'+index;b.tabIndex=-1;b.setAttribute('role','option');b.setAttribute('aria-selected',index===selected);b.classList.toggle('is-selected',index===selected);node('span','',b,item.label);node('small','',b,item.group+(item.hotkey?' · '+item.hotkey:''));b.addEventListener('click',function(){run(item.id);});});if(!matches.length)node('p','qol-empty',palette.matches,'No matching commands or collected cards.');palette.input.setAttribute('aria-activedescendant',matches.length?'game-command-'+selected:'');var current=palette.matches.children[selected];if(current)current.scrollIntoView({block:'nearest'});}
  function search(){var query=palette.input.value;matches=Array.from(commands.values()).filter(allowed).map(function(item){return {item:item,score:C.qol.fuzzyScore(query,[item.label,item.group].concat(item.aliases||[]).join(' ')),recent:recent.indexOf(item.id)};}).filter(function(r){return r.score>0;}).sort(function(a,b){var ar=a.recent<0?999:a.recent,br=b.recent<0?999:b.recent;return (!query?ar-br:0)||b.score-a.score||a.item.label.localeCompare(b.item.label);});selected=0;render();}
  function cards(){Array.from(commands.keys()).filter(function(id){return id.indexOf('card:')===0;}).forEach(function(id){commands.delete(id);});var seen=new Set();C.state.current.inventory.forEach(function(instance){var key=C.stacks.key(instance.cardId,instance.variantId);if(seen.has(key))return;seen.add(key);var card=C.card(instance.cardId);if(!card)return;var variant=instance.variantId&&C.variant(instance.variantId),rarity=C.rarity(card.rarity);C.commands.register({id:'card:'+key,label:card.name+' · '+(rarity?rarity.name:card.rarity)+(variant?' · '+variant.name:''),group:'Cards',aliases:[card.generation,instance.variantId||'normal'],when:function(){return idle()&&C.detail.phase==='closed';},run:function(){if(C.preferences.open)C.preferences.close();if(!C.inventory.active)C.inventory.request(true);C.events.emit('inventory:showCard',{cardId:card.id,instanceId:instance.instanceId});}});});}
  function open(){if(!idle()||C.contextMenu.open)return;cards();origin=root.document.activeElement;C.paletteUI.show(palette.backdrop);palette.input.value='';context(true);search();palette.input.focus();}
  function help(){if(!idle())return;hide();origin=root.document.activeElement;sheet.replaceChildren();node('h2','',sheet,'Keyboard shortcuts');var close=node('button','quiet-button',sheet,'Close');close.type='button';close.addEventListener('click',hide);var groups=new Map();C.keybindings.entries.forEach(function(item){var group=item.context||'Desktop';if(!groups.has(group)){var section=node('section','qol-shortcut-group',sheet);node('h3','',section,group);groups.set(group,section);}var row=node('div','qol-shortcut-row',groups.get(group));node('span','',row,item.label);node('kbd','',row,item.binding.replace(/Mod/g,root.navigator.platform.indexOf('Mac')>=0?'Cmd':'Ctrl'));});C.paletteUI.show(sheet);context(true);C.accessibility.trap(sheet);close.focus();}
  function focus(value){focusMode=!!value;root.document.body.classList.toggle('qol-focus',focusMode);if(focusMode){try{if(!root.localStorage.getItem('cardable.qol.focusHint')){C.qol.toast('H to show the interface');root.localStorage.setItem('cardable.qol.focusHint','1');}}catch(_){}}}
  function data(action){if(C.detail.phase!=='closed')C.detail.close();if(C.inventory.active)C.inventory.request('peek');C.openSettings('Data');if(C.preferences.open)C.settingsData.current[action].click();else C.qol.toast('Finish the current interaction first.');}
  async function capture(copy){if(!C.native||busy)return;busy=true;try{var result;if(copy!=null){if(C.detail.phase!=='detail'||!C.detail.view)throw new Error('Not in detail');var el=C.detail.view.el;el.blur();await new Promise(function(resolve){root.requestAnimationFrame(function(){root.requestAnimationFrame(resolve);});});var r=el.getBoundingClientRect(),style=root.getComputedStyle(el);result=await C.native.capture.card({x:r.x,y:r.y,width:r.width,height:r.height,radius:parseFloat(style.borderTopLeftRadius)||0,squircle:style.cornerShape==='squircle'},copy);}else result=await C.native.capture.saveWindow();if(!result.success)throw new Error('Capture failed');C.events.emit('ui:screenshot',{kind:copy==null?'window':'card',copied:!!result.copied});root.document.body.classList.remove('qol-shutter');void root.document.body.offsetWidth;root.document.body.classList.add('qol-shutter');root.setTimeout(function(){root.document.body.classList.remove('qol-shutter');},300);C.qol.toast(result.copied?'Card image copied.':'Image saved to Pictures / Cardable.',result.id?{label:'Show in folder',run:function(){return C.native.capture.showInFolder(result.id);}}:null);}catch(_){C.qol.toast('Could not capture this view.');}finally{busy=false;}}
  function command(id,label,group,run,when,aliases,hotkey){C.commands.register({id:id,label:label,group:group,run:run,when:when||idle,aliases:aliases||[],hotkey:hotkey});}
  function binding(binding,label,context,run,external,selector){C.keybindings.register({binding:binding,label:label,context:context,run:run,external:!!external,selector:selector});}
  function developerBindings(){if(!C.dev)return;function add(key,label){if(!Array.from(C.keybindings.entries.keys()).some(function(k){return k.toLowerCase()===key.toLowerCase();}))binding(key,label,'Developer',null,true);}add('`','Toggle developer workspace');if(C.native){add('F12','Toggle native DevTools');add('Mod+Shift+I','Toggle native DevTools');}Array.from(C.dev.groups.keys()).slice(0,10).forEach(function(group,index){add('Alt+'+(index===9?'0':index+1),group);});Array.from(C.dev.tools.values()).forEach(function(tool){if(tool.hotkey)add(tool.hotkey,tool.label);});}
  C.commands={register:function(item){if(!item||typeof item.id!=='string'||typeof item.run!=='function')throw new Error('Invalid command');commands.set(item.id,item);return function(){commands.delete(item.id);};},entries:commands,open:open,close:hide,run:run,get active(){return !!palette&&!palette.backdrop.hidden&&!palette.backdrop.inert||!!sheet&&!sheet.hidden&&!sheet.inert;}};
  C.desktopTools={capture:capture,openData:data,showShortcuts:help,syncDevBindings:developerBindings,get focus(){return focusMode;},init:function(){
    try{recent=JSON.parse(root.localStorage.getItem('cardable.qol.recent')||'[]');if(!Array.isArray(recent))recent=[];}catch(_){recent=[];}
    palette=C.paletteUI.create({id:'game-command-matches',label:'Cardable command palette',placeholder:'Find a command or collected card…'});palette.input.addEventListener('input',search);palette.backdrop.addEventListener('pointerdown',function(e){if(e.target===palette.backdrop)hide();});
    sheet=node('section','qol-shortcuts glass glass--sheet',C.viewport.parent(root.document.body));sheet.hidden=true;sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','Keyboard shortcuts');
    command('pack','Open pack','Play',function(){C.input.chargeStart();},function(){return idle()&&!C.inventory.active&&!C.preferences.open&&C.state.current.packs.ready>0;},['charge'],'Space');
    command('inventory','Open inventory','Collections',function(){if(C.preferences.open)C.preferences.close();C.inventory.request(true);},idle,[],'I');
    command('achievements','Open achievements','Collections',function(){if(C.preferences.open)C.preferences.close();C.achievementView.show();});
    command('settings','Open settings','Settings',function(){C.preferences.show();},idle,[],'S');
    command('dots','Toggle dot grid','Settings',function(){C.settings.set('dots',C.settings.get('dots')==='off'?'on':'off');});
    command('mute','Mute (sound is not enabled)','Settings',function(){C.settings.set('muted',!C.settings.get('muted'));C.qol.toast('Mute preference saved; sound is not enabled.');});
    ['auto','90','100','110','125','150'].forEach(function(value){command('scale:'+value,'Interface size · '+(value==='auto'?'Auto':value+' %'),'Settings',function(){C.settings.set('interfaceSize',value);},function(){return idle()&&!!C.native;});});
    C.inventoryToolbar.sorts.forEach(function(pair){command('sort:'+pair[0],'Sort cards · '+pair[1],'Collections',function(){C.inventoryModel.update({sortMode:pair[0],groupMode:pair[0]==='custom'?'none':C.inventoryModel.current.groupMode});C.inventory.request(true);});});
    [['owned:true','Owned cards'],['favorite:true','Favorites'],['new:true','New cards'],['','Clear filters']].forEach(function(pair){command('filter:'+pair[0],'Filter · '+pair[1],'Collections',function(){C.inventory.request(true);C.inventory.setPage(null);C.inventory.toolbar.searchFor(pair[0]);});});
    [['exportButton','Export save'],['restore','Restore backup…'],['replay','Replay tutorial…']].forEach(function(pair){command('data:'+pair[0],pair[1],'Data',function(){data(pair[0]);});});
    command('focus','Toggle focus mode','Play',function(){focus(!focusMode);},idle,[],'H');command('shortcuts','Keyboard shortcuts','Help',help,idle);command('help-mode','Help mode','Help',function(){C.help.toggle();},idle,[],'F1');
    command('help','How to play','Help',function(){C.friendly.showHelp();},idle,['guide','saving','restore','quality','recovery']);
    if(C.native)command('desktop-help','Desktop help','Help',function(){C.friendly.showHelp('desktop');},idle,['install','update','photos','safe mode']);
    if(C.native){command('saves','Open saves folder','Desktop',function(){return C.native.storage.openSaveDir();});command('fullscreen','Toggle fullscreen','Desktop',function(){return C.native.window.toggleFullscreen();},idle,[],'F11');command('mini','Mini mode','Desktop',function(){return C.native.window.toggleMini();},function(){return idle()&&!C.inventory.active&&!C.preferences.open;},[],'Mod+M');command('updates','Check for updates','Help',function(){return C.friendly?C.friendly.checkUpdates():C.desktop.checkUpdates(true);});command('diagnostics','Copy diagnostics','Help',function(){return C.friendly?C.friendly.copyDiagnostics():C.desktop.copyDiagnostics();});command('bug','Report a bug','Help',function(){return C.friendly?C.friendly.reportBug():C.qol.toast('Bug reporting is not configured yet.');});binding('F11','Toggle fullscreen','Desktop',null,true);binding('F2','Save window image','Desktop',function(){capture();});
      C.detailActions.register('desktop-card-capture',function(host,ctx){if(!ctx.entry.owned||ctx.preview)return;['Copy card image','Save card image'].forEach(function(label,index){var b=node('button','detail-menu-item',host,label);b.type='button';b.addEventListener('click',function(){ctx.dismiss();capture(index===0);});});});}
    binding('Mod+K','Find commands and cards','Global',open,false);binding('/','Search commands and cards','Global',open,false);binding('F1','Help mode','Global',function(){C.help.toggle();},false);binding('?','Help mode','Global',function(){C.help.toggle();},false);binding('H','Focus mode','Menu / Card detail',function(){if(!C.inventory.active&&C.detail.phase==='closed')focus(!focusMode);},false);
    [['Space','Hold to charge / Keep / Turntable','Menu / Reveal / Studio','.opening-keep'],['Enter','Hold (when configured) / keyboard tear','Opening',null],['Escape','Cancel / Back / Close','Global',null],['I','Inventory / Inspect card','Menu / Card detail','#inventory-affordance button'],['ArrowUp','Open inventory','Menu',null],['S','Toggle settings','Menu','.preferences-entry'],['Mod+,','Open settings','Global',null],['R','Flip card','Card detail','[aria-keyshortcuts="R"]'],['F','Favorite card / Frame selection','Card detail / Studio','[aria-keyshortcuts="F"]'],['ArrowLeft','Previous card / copy / Orbit camera','Card detail / Studio',null],['ArrowRight','Next card / copy / Orbit camera','Card detail / Studio',null],['Mod+F','Search inventory or achievements','Inventory','.inventory-toolbar-buttons button[aria-label="Search cards"]']].forEach(function(p){binding(p[0],p[1],p[2],null,true,p[3]);});
    [['E','Enter Studio'],['L','Add point light'],['P','Props inspector'],['C','Camera inspector'],['Delete','Remove selection'],['Backspace','Remove selection'],['Mod+Z','Undo'],['Mod+Shift+Z','Redo'],['Mod+D','Duplicate selection'],['+','Zoom camera in'],['-','Zoom camera out']].forEach(function(p){binding(p[0],p[1],'Studio',null,true);});if(C.dev){Array.from(C.dev.tools.values()).forEach(function(t){if(t.hotkey&&!C.keybindings.entries.has(t.hotkey))binding(t.hotkey,t.label,'Developer',null,true);});}binding('Tab','Move keyboard focus','Menus',null,true);binding('Shift+Tab','Move focus backward','Menus',null,true);binding('ArrowDown','Navigate entries / heatmap','Collections',null,true);if(C.config.dev){binding('`','Toggle developer workspace','Developer',null,true);binding('F12','Toggle native DevTools','Developer',null,true);}
    C.keybindings.entries.forEach(function(item){if(item.selector)root.document.querySelectorAll(item.selector).forEach(function(el){el.title=item.label+' · '+item.binding;el.dataset.tooltip=el.title;});});
    root.document.addEventListener('keydown',function(e){if(C.friendly?.kind==='away')C.friendly.close();if(C.commands.active){if(!palette.backdrop.hidden){if(e.key==='ArrowDown'||e.key==='ArrowUp'){selected=(selected+(e.key==='ArrowDown'?1:-1)+Math.min(80,matches.length))%Math.max(1,Math.min(80,matches.length));render();}else if(e.key==='Enter'&&matches[selected])run(matches[selected].item.id);else if(e.key==='Escape')hide();else if(e.key==='Tab')palette.input.focus();else if(editable(e.target))return;}else if(e.key==='Escape')hide();else if(e.key==='Tab')return;e.preventDefault();e.stopImmediatePropagation();return;}if(e.key==='F2'&&C.native&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();capture();return;}if(e.repeat||editable(e.target)||C.dev?.opened||!idle())return;var key=e.key===' '? 'Space':e.key.length===1?e.key.toUpperCase():e.key;if((e.ctrlKey||e.metaKey))key='Mod+'+key;if(e.altKey)key='Alt+'+key;var item=C.keybindings.entries.get(key);if(item&&!item.external&&item.run&&!(key==='H'&&(C.inventory.active||C.detail.phase!=='closed'))){e.preventDefault();e.stopImmediatePropagation();item.run();}},true);
    root.document.addEventListener('dragover',function(e){if(e.dataTransfer)e.preventDefault();},true);
    root.document.addEventListener('drop',function(e){if(!e.dataTransfer)return;e.preventDefault();e.stopImmediatePropagation();if(!e.dataTransfer.files.length){C.qol.toast("Can't use that file");return;}var file=e.dataTransfer.files[0];if(e.dataTransfer.files.length!==1||!file.name.toLowerCase().endsWith('.json')||file.size>C.config.polish.maxSaveBytes){C.qol.toast("Can't use that file");return;}if(!idle()){C.qol.toast('Finish the current interaction before importing.');return;}if(C.detail.phase!=='closed')C.detail.close();if(C.inventory.active)C.inventory.request('peek');C.openSettings('Data');if(C.preferences.open)C.settingsData.current.read(file).then(function(ok){if(!ok)C.qol.toast("Can't use that file");});else C.qol.toast('Close the current view before importing.');},true);
    focus(C.settings.get('focusModeDefault'));C.settings.onChange('focusModeDefault',focus);C.events.on('save:willReplace',hide);
  }};
  C.events.on('app:ready',C.desktopTools.init);
})(window.Cardable,window);
