(function(C,root){
  'use strict';var node=C.packMarkup.node,icons=C.inventoryIcons;
  var sorts=[['catalog','Catalog order'],['custom','Custom'],['recent','Recently acquired'],['oldest','Oldest acquired'],['name-asc','Name A–Z'],['name-desc','Name Z–A'],['rarity-asc','Rarity low–high'],['rarity-desc','Rarity high–low'],['generation','Generation'],['vram-asc','VRAM low–high'],['vram-desc','VRAM high–low'],['quantity','Quantity'],['serial','First serial']];
  C.inventoryToolbar={sorts:sorts,create:function(host,actions){
    var header=node('header','inventory-header',host),collapse=icons.button('collapse','Collapse inventory',actions.collapse,header),title=node('div','inventory-title',header),heading=node('h2','',title,'Inventory'),count=node('div','inventory-count',title),numbers=C.numbers.create(count),progress=node('div','inventory-progress',title);node('i','inventory-progress-fill',progress);
    var summary=node('div','inventory-summary',title),newSummary=node('button','',summary),variantSummary=node('button','',summary),finishSummary=node('span','',summary);newSummary.type=variantSummary.type='button';newSummary.addEventListener('click',function(){filterPatch({newOnly:!filters.newOnly});});variantSummary.addEventListener('click',function(){filterPatch({variantOnly:!filters.variantOnly});});
    var buttons=node('div','inventory-toolbar-buttons',header),searchButton=icons.button('search','Search cards',function(){setSearchVisible(search.hidden);},buttons),filterButton=icons.button('filter','Filter cards',function(){popover('filter',filterButton);},buttons),sortButton=icons.button('sort','Sort cards',function(){popover('sort',sortButton);},buttons),viewButton=icons.button('grid','Switch to Grid',function(){actions.preference({viewMode:C.inventoryModel.current.viewMode==='shelf'?'grid':'shelf'});},buttons),moreButton=icons.button('more','Inventory options',function(){popover('more',moreButton);},buttons);
    var tabs=node('nav','inventory-tabs',host);tabs.setAttribute('aria-label','Collections');var unowned=node('label','inventory-unowned',tabs),toggle=node('input','',unowned);toggle.type='checkbox';node('span','',unowned,'Show Unowned');toggle.addEventListener('change',function(){actions.preference({showUnowned:toggle.checked});});
    var tabList=node('div','inventory-tab-list',tabs),add=icons.button('plus','Create collection',function(){popover('create',add);},tabs),search=node('div','inventory-search',host);search.hidden=true;search.id='inventory-search';searchButton.setAttribute('aria-controls',search.id);searchButton.setAttribute('aria-expanded','false');
    C.inventoryTabs.render(node('div','inventory-extension-tabs',tabs),{host:host,actions:actions});
    var input=node('input','inventory-search-input',search);input.type='search';input.placeholder='Search cards or type rarity:rare';input.setAttribute('aria-label','Search cards');input.setAttribute('aria-describedby','inventory-search-error');input.setAttribute('aria-invalid','false');input.autocomplete='off';
    var clear=icons.button('close','Clear search',function(){input.value='';actions.search('');suggest();input.focus();},search),suggestions=node('div','inventory-suggestions glass',search),error=node('p','inventory-search-error',search);error.id='inventory-search-error';error.setAttribute('role','status');error.hidden=true;suggestions.hidden=true;
    var chips=node('div','inventory-chips',host),popoverEl=node('div','inventory-popover glass',host);popoverEl.hidden=true;popoverEl.setAttribute('role','dialog');popoverEl.setAttribute('aria-label','Inventory options');
    var current=null,popKind=null,origin=null,lastTabs='',filters={},text='',tooltip=null,hoverAge=null,tooltipTarget=null,ownedValue=0,ownedFrom=0,ownedTarget=0,countAge=0,total=0,progressSpring=C.springs.create(0,{stiffness:100,damping:20,epsilon:.001});
    function empty(el){while(el.children.length)el.children[0].remove();}
    function setSearchVisible(visible){search.hidden=!visible;searchButton.setAttribute('aria-expanded',String(visible));if(!visible)suggestions.hidden=true;actions.layout();if(visible)input.focus();else searchButton.focus();}
    function button(label,fn,parent,selected){var b=node('button','inventory-menu-option',parent,label);b.type='button';if(selected)b.classList.add('is-selected');b.addEventListener('click',fn);return b;}
    function close(){if(!popKind)return false;popoverEl.hidden=true;popoverEl.inert=true;popKind=null;C.accessibility.release(popoverEl);host.appendChild(popoverEl);if(origin)origin.focus({preventScroll:true});return true;}
    function preference(patch){actions.preference(patch);close();}
    function filterPatch(patch){Object.assign(filters,patch);actions.filters(filters);}
    function check(parent,label,checked,fn){var wrapper=node('label','inventory-filter-check',parent),field=node('input','',wrapper);field.type='checkbox';field.checked=checked;node('span','',wrapper,label);field.addEventListener('change',function(){fn(field.checked);});return field;}
    function popover(kind,anchor,card){
      close();popKind=kind;origin=anchor;empty(popoverEl);popoverEl.hidden=false;popoverEl.inert=false;C.accessibility.trap(popoverEl);var bar=node('div','inventory-popover-heading',popoverEl);node('h3','',bar,kind==='filter'?'Filters':kind==='sort'?'Sort':kind==='membership'?'Add to collection':kind==='context'?'Card actions':kind==='create'?'New collection':'Collection options');icons.button('close','Close options',close,bar);
      var body=node('div','inventory-popover-body',popoverEl),ui=C.inventoryModel.current;
      if(kind==='sort'){sorts.forEach(function(item){button(item[1],function(){preference({sortMode:item[0],groupMode:item[0]==='custom'?'none':ui.groupMode});},body,ui.sortMode===item[0]);});}
      if(kind==='filter'){
        node('p','inventory-filter-preview',body,current.shown+' cards');var ownership=node('div','inventory-filter-options',body);['all','owned','unowned','duplicates'].forEach(function(value){button(value==='all'?'All ownership':value[0].toUpperCase()+value.slice(1),function(){filterPatch({ownership:value});popover('filter',filterButton);},ownership,(filters.ownership||'all')===value);});
        ['variant','rarity','generation','brand','memoryType'].forEach(function(key){if(!current.facets[key].length)return;var section=node('fieldset','inventory-filter-section',body);node('legend','',section,key==='memoryType'?'Memory type':key[0].toUpperCase()+key.slice(1));current.facets[key].forEach(function(value){var label=key==='variant'?(C.variant(value)?.name||'Normal'):key==='rarity'?C.rarity(value).name:key==='generation'?C.data.generations.find(function(g){return g.id===value;}).name:value;check(section,label,(filters[key]||[]).indexOf(value)>=0,function(enabled){var next=(filters[key]||[]).filter(function(v){return v!==value;});if(enabled)next.push(value);var patch={};patch[key]=next;filterPatch(patch);});});});
        var range=node('fieldset','inventory-filter-section',body);node('legend','',range,'VRAM · GB');['vramMin','vramMax'].forEach(function(key){var label=node('label','inventory-range',range,key==='vramMin'?'Minimum':'Maximum'),field=node('input','',label);field.type='number';field.min='0';field.step='any';field.value=filters[key]||'';field.addEventListener('input',function(){var patch={};patch[key]=field.value;filterPatch(patch);});});
        check(body,'New cards only',!!filters.newOnly,function(value){filterPatch({newOnly:value});});var quantity=node('label','inventory-range',body,'Minimum copies'),select=node('select','',quantity);[0,1,2,3].forEach(function(n){var option=node('option','',select,n?String(n):'Any');option.value=String(n);});select.value=String(filters.quantity||0);select.addEventListener('change',function(){filterPatch({quantity:select.value});});button('Clear all filters',function(){filters={};actions.filters(filters);popover('filter',filterButton);},body);
      }
      if(kind==='more'){
        node('p','inventory-menu-caption',body,'Group by');['none','rarity','generation','brand','ownership','new','variant'].forEach(function(mode){button(mode==='none'?'No grouping':mode[0].toUpperCase()+mode.slice(1),function(){preference({groupMode:mode,sortMode:mode!=='none'&&ui.sortMode==='custom'?'catalog':ui.sortMode});},body,ui.groupMode===mode);});
        button('Expand sheet',function(){close();actions.expand();},body);button('Clear filters and search',function(){filters={};input.value='';text='';actions.filters(filters);actions.search('');close();},body);
        var c=ui.collections.find(function(item){return item.id===ui.activeCollectionId;});if(c){var name=node('input','inventory-collection-name',body);name.value=c.name;name.setAttribute('aria-label','Collection name');button('Rename collection',function(){C.inventoryModel.rename(c.id,name.value);close();},body);button('Move tab earlier',function(){C.inventoryModel.moveCollection(c.id,-1);close();},body);button('Move tab later',function(){C.inventoryModel.moveCollection(c.id,1);close();},body);button('Delete collection',function(){popover('delete',moreButton,c);},body);}
      }
      if(kind==='delete'){node('p','',body,'Delete “'+card.name+'”? Your cards stay in All Cards.');button('Delete collection',function(){C.inventoryModel.remove(card.id);close();},body);}
      if(kind==='create'){var nameField=node('input','inventory-collection-name',body);nameField.placeholder='Collection name';nameField.maxLength=60;nameField.setAttribute('aria-label','Collection name');button('Create collection',function(){if(!nameField.value.trim())return;C.inventoryModel.create(nameField.value);close();},body);nameField.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.repeat&&nameField.value.trim()){C.inventoryModel.create(nameField.value);close();}});}
      if(kind==='membership'){if(!ui.collections.length)node('p','inventory-menu-caption',body,'Create a collection with the + button.');ui.collections.forEach(function(c){check(body,c.name,c.stackKeys.indexOf(card.stackKey)>=0,function(included){C.inventoryModel.membership(c.id,card.stackKey,included);});});}
      if(kind==='context'){
        button('View card',function(){close();actions.detail(card.stackKey);},body);
        if(card.owned){button(ui.favorites.indexOf(card.stackKey)>=0?'Unfavorite':'Favorite',function(){C.inventoryModel.favorite(card.stackKey);close();},body);button('Add to collection…',function(){popover('membership',anchor,card);},body);
          if(ui.collections.some(function(c){return c.id===ui.activeCollectionId;}))button('Remove from this collection',function(){C.inventoryModel.membership(ui.activeCollectionId,card.stackKey,false);close();},body);
          button('Delete a copy…',function(){close();C.cardDeletionView.show(card);},body);
          if(card.isNew)button('Mark as viewed',function(){C.collection.markSeen(card.stackKey,C.state.current.inventory);C.state.save();close();},body);
        }
        if(ui.sortMode==='custom'){button('Move earlier',function(){actions.move(card.stackKey,-1);close();},body);button('Move later',function(){actions.move(card.stackKey,1);close();},body);}else node('p','inventory-menu-caption',body,'Choose Custom sort to rearrange cards.');
      }
      var first=popoverEl.querySelector('input')||popoverEl.querySelector('button');if(first)first.focus({preventScroll:true});C.fx.wake();
    }
    function suggest(){empty(suggestions);var token=(input.value.match(/\S+$/)||[''])[0],parts=token.split(':'),key=parts[0].toLowerCase(),values=[];if(parts.length===1){values=['rarity:','generation:','brand:','vram:','memoryType:','owned:','new:','variant:','favorite:','type:','name:'].filter(function(v){return v.toLowerCase().startsWith(key);});}else if(current){var facet=key==='memorytype'?'memoryType':key;values=(current.facets[facet]|| (key==='owned'||key==='new'||key==='favorite'?['true','false']:[])).map(String).filter(function(v){return v.toLowerCase().startsWith(parts[1].toLowerCase());}).map(function(v){return parts[0]+':'+(v.includes(' ')?'"'+v+'"':v);});}values.slice(0,8).forEach(function(value){button(value,function(){input.value=input.value.slice(0,input.value.length-token.length)+value+(value.endsWith(':')?'':' ');text=input.value;actions.search(text);input.focus();suggest();},suggestions);});suggestions.hidden=!values.length||search.hidden;}
    input.addEventListener('input',function(){text=input.value;actions.search(text);suggest();});input.addEventListener('keydown',function(event){if(event.key==='ArrowDown'&&!suggestions.hidden){event.preventDefault();var first=suggestions.querySelector('button');if(first)first.focus();}});
    root.document.addEventListener('pointerdown',function(event){if(popKind&&!popoverEl.contains(event.target)&&event.target!==origin)close();});
    header.addEventListener('pointerover',function(event){var b=event.target.closest('.inventory-icon');if(b){tooltipTarget=b;hoverAge=0;C.fx.wake();}});header.addEventListener('pointerout',function(){hoverAge=null;if(tooltip){tooltip.remove();tooltip=null;}});
    return {el:header,controls:buttons,tabs:tabs,search:search,chips:chips,input:input,filters:filters,popover:popoverEl,count:numbers,buttons:{filter:filterButton,sort:sortButton,view:viewButton,more:moreButton},
      get modal(){return !!popKind;},get popKind(){return popKind;},
      render:function(model){current=model;newSummary.textContent=(model.newCopies||0)+' New';variantSummary.textContent=(model.variantCopies||0)+' variant copies';newSummary.setAttribute('aria-pressed',!!filters.newOnly);variantSummary.setAttribute('aria-pressed',!!filters.variantOnly);finishSummary.textContent=(model.stackCount||0)+' finishes';summary.title=(model.stackCount||0)+' owned finish stacks';var ui=C.inventoryModel.current;toggle.checked=ui.showUnowned;total=model.total;if(ownedTarget!==model.owned){ownedFrom=ownedValue;ownedTarget=model.owned;countAge=0;}numbers.set(Math.round(ownedValue)+' / '+total,false);title.setAttribute('aria-label',model.owned+' of '+model.total+' cards owned');progressSpring.target=model.total?model.owned/model.total:0;heading.textContent=ui.activeCollectionId==='favorites'?'Favorites':ui.collections.find(function(c){return c.id===ui.activeCollectionId;})?.name||'Inventory';viewButton.setAttribute('aria-label',ui.viewMode==='shelf'?'Switch to Grid':'Switch to Shelf');viewButton.dataset.tooltip=viewButton.getAttribute('aria-label');empty(viewButton);viewButton.appendChild(icons.create(ui.viewMode==='shelf'?'grid':'shelf'));error.textContent=model.errors.join(' · ');error.hidden=!model.errors.length;input.setAttribute('aria-invalid',String(!!model.errors.length));
        var collections=[{id:'all',name:'All Cards',count:model.collectionCounts.all},{id:'favorites',name:'Favorites',count:model.collectionCounts.favorites}].concat(ui.collections.map(function(c){return {id:c.id,name:c.name,count:model.collectionCounts[c.id]};})),signature=JSON.stringify([collections,ui.activeCollectionId]);if(signature!==lastTabs){lastTabs=signature;empty(tabList);collections.forEach(function(c){var b=button(c.name+' · '+c.count,function(){actions.preference({activeCollectionId:c.id});},tabList,c.id===ui.activeCollectionId);b.setAttribute('role','tab');b.setAttribute('aria-selected',c.id===ui.activeCollectionId);});}
        empty(chips);model.terms.filter(function(t){return t.key!=='text';}).forEach(function(term){button(term.token+' ×',function(){input.value=input.value.replace(term.token,'').trim();text=input.value;actions.search(text);},chips);});Object.keys(filters).forEach(function(key){var value=filters[key];if(!value||Array.isArray(value)&&!value.length||value==='all')return;button(key+': '+(Array.isArray(value)?value.join(', '):value)+' ×',function(){delete filters[key];actions.filters(filters);},chips);});chips.hidden=!chips.children.length;
        if(popKind==='filter'){var countText=popoverEl.querySelectorAll('.inventory-filter-preview')[0];if(countText)countText.textContent=model.shown+' cards';}
      },
      clearSearch:function(){input.value='';text='';filters={};suggestions.hidden=true;},searchFor:function(value){filters={};input.value=text=value;actions.filters(filters);actions.search(text);setSearchVisible(true);suggest();},openSearch:function(){setSearchVisible(true);},escape:function(){if(close())return true;if(!suggestions.hidden){suggestions.hidden=true;return true;}if(!search.hidden){setSearchVisible(false);return true;}return false;},
      context:function(tile,event){popover('context',tile.el,tile.entry);},membership:function(entry,anchor){popover('membership',anchor,entry);var detail=root.document.body.querySelectorAll('.inventory-detail')[0];if(detail){detail.appendChild(popoverEl);var first=popoverEl.querySelector('button');if(first)first.focus({preventScroll:true});}},
      close:close,reset:function(){close();if(tooltip)tooltip.remove();tooltip=null;hoverAge=null;suggestions.hidden=true;},
      update:function(now,dt){var active=false;if(ownedValue!==ownedTarget){countAge+=dt;var p=C.motion.reduced?1:Math.min(1,countAge/C.config.inventoryMotion.countMs);ownedValue=ownedFrom+(ownedTarget-ownedFrom)*(1-Math.pow(1-p,3));numbers.set(Math.round(ownedValue)+' / '+total,false);active=p<1;}if(!progressSpring.settled()){if(C.motion.reduced)progressSpring.reset(progressSpring.target);else progressSpring.step(dt,progressSpring.target);progress.style.setProperty('--inventory-progress',progressSpring.value);progress.style.setProperty('--inventory-progress-wave',(C.motion.reduced?0:progressSpring.velocity)+'px');active=active||!progressSpring.settled();}if(hoverAge!=null){hoverAge+=dt;if(hoverAge>=C.config.inventoryMotion.tooltipMs){hoverAge=null;if(tooltipTarget){tooltip=node('span','inventory-tooltip glass',header,tooltipTarget.dataset.tooltip);var r=tooltipTarget.getBoundingClientRect(),h=header.getBoundingClientRect();tooltip.style.transform='translate('+Math.max(0,r.left-h.left-40)+'px,0)';}}}return active||hoverAge!=null;}
    };
  }};
})(window.Cardable,window);
