(function(C,root){
  'use strict';
  var cfg,sheet,grip,body,toolbar,shelf,grid,arrow,empty,peek,peekView=null,spring,detents={},detent='peek',session=false,detailId=null,openingPhase='idle',preferences=false,drag=null,pendingClose=false,fixture=null,model={entries:[],groups:[],owned:0,total:0},query='',validQuery='',filters={},selected=null,signature='',dirty=true,mode=null,reorder=null,suppressClick=false,profile=null,lastProfile=null,selectionAge=0,deferredModel=false,selectedTags;
  var stats={updates:0,mounted:0,maxMounted:0,opens:0,closes:0,snaps:0};var node=C.packMarkup.node;
  function view(){return mode==='grid'?grid:shelf;}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
  function focus(el){if(el&&el.focus)el.focus({preventScroll:true});}
  function menuInert(value){['wordmark','pack-stage','currency-counter','inventory-affordance'].forEach(function(id){var el=root.document.getElementById(id);if(el)el.inert=value;});if(C.dev.panel)C.dev.panel.inert=value;}
  function context(){C.events.emit('inventory:context',{active:session,open:session,detail:!!detailId,detent:detent});arrow.setAttribute('aria-expanded',session);}
  function preference(patch){if(detailId)return;var before=session?C.inventoryTransition.capture(view().tiles):null;C.inventoryModel.update(patch);if(before&&session){view().update(root.performance.now(),0);C.inventoryTransition.morph(before,view().tiles);}}
  function select(entry){if(entry&&selectedTags)C.cardTags.render(selectedTags,entry,entry.instances.reduce(function(a,b){return !a||b.pulledAt>a.pulledAt?b:a;},null),'selected');if(entry&&selected!==entry.stackKey){selected=entry.stackKey;selectionAge=0;stats.snaps++;C.events.emit('inventory:selection',{cardId:entry.card.id,stackKey:selected});}}
  function refresh(force){
    if(!sheet||!toolbar)return;var ui=C.inventoryModel.current,base=C.collection.project(fixture?fixture.cards:C.data.cards,fixture?fixture.instances:C.state.current.inventory,'all'),parsed=C.inventoryQuery.parse(query);
    if(!parsed.errors.length)validQuery=query;var next=C.inventoryQuery.run(base,ui,validQuery,filters);next.errors=parsed.errors;
    var nextSignature=JSON.stringify([next.entries.map(function(e){return [e.stackKey,e.owned];}),ui.viewMode,ui.groupMode]);model=next;toolbar.render(model);
    if(mode!==ui.viewMode){if(reorder)reorder.cancel();mode=ui.viewMode;shelf.setActive(session&&mode==='shelf');grid.setActive(session&&mode==='grid');selectedTags.hidden=mode==='grid';C.events.emit('inventory:viewChanged',mode);}
    if(force||signature!==nextSignature){signature=nextSignature;cancel();if(detailId)deferredModel=true;if(!detailId){shelf.setModel(model.entries,selected);grid.setModel(model.entries,selected,model.groups);resizeViews();}}else {shelf.refreshModel(model.entries);grid.refreshModel(model.entries);}
    if(!selected||!model.entries.some(function(e){return e.stackKey===selected;}))selected=model.entries[0]?model.entries[0].stackKey:null;
    empty.hidden=!!model.entries.length;empty.textContent=ui.activeCollectionId!=='all'?'This collection is empty. Add cards from their detail view.':query?'No search results. Try another term.':Object.keys(filters).length?'No matches. Try removing a filter.':!ui.showUnowned?'Open your first pack.':'No cards in this catalog.';
    var peekEntry=base.entries.find(function(e){return e.stackKey===(selected||ui.lastSelectedStackKey)&&e.owned;})||base.entries.find(function(e){return e.owned;});
    if((peekEntry&&peekEntry.stackKey)!==(peekView&&C.stacks.of(peekView.instance))){if(peekView)peekView.destroy();peekView=null;while(peek.children.length)peek.children[0].remove();if(peekEntry){peekView=C.cardView.create(peekEntry.card,peekEntry.instances[0],{thumbnail:true,owned:true});peek.appendChild(peekView.el);}}
    dirty=true;C.fx.wake();C.events.emit('inventory:modelChanged',{shown:model.shown,total:model.total});
  }
  function resizeViews(){var height=detents[detent]||detents.normal,chrome=body.offsetTop||144+(toolbar.search.hidden?0:48)+(toolbar.chips.hidden?0:32);shelf.resize(height-(chrome-144));grid.resize(height-(chrome-144));body.style.height=Math.max(0,height-chrome)+'px';}
  function resize(){if(!sheet)return;cancel();var h=root.innerHeight;detents={peek:cfg.detents.peekPx,normal:h*cfg.detents.normalVh/100,expanded:h*cfg.detents.expandedVh/100,full:h-cfg.detents.fullMarginPx};sheet.style.height=detents.full+'px';spring.target=detents[detent];if(!session)spring.reset(detents.peek);resizeViews();dirty=true;C.fx.wake();}
  function cancel(){if(drag){var d=drag;drag=null;if(d.moved)suppressClick=true;if(d.capture.hasPointerCapture(d.id))d.capture.releasePointerCapture(d.id);}if(reorder)reorder.cancel();if(shelf)shelf.cancel();if(grid)grid.cancel();}
  function request(value){var next=typeof value==='string'?value:value===false?'peek':value===true?'normal':detent!=='peek'?'peek':'normal';if(!detents[next])return;
    if(!C.inventory.canRequest({phase:openingPhase,hidden:root.document.hidden,preferences:preferences,detail:!!detailId},next!=='peek'))return;
    if(detailId){pendingClose=next==='peek';if(pendingClose)C.events.emit('detail:requestClose');return;}
    cancel();detent=next;
    if(next!=='peek'&&!session){session=true;stats.opens++;sheet.inert=false;menuInert(true);root.document.body.classList.add('inventory-depth-active');C.accessibility.trap(sheet);C.events.emit('menu:visibilityHold',{reason:'inventory',active:true});C.events.emit('inventory:open');selected=C.inventoryModel.current.pendingFocusStackKey||C.inventoryModel.current.lastSelectedStackKey;if(C.inventoryModel.current.pendingFocusStackKey){query='';validQuery='';filters={};toolbar.clearSearch();C.inventoryModel.update({activeCollectionId:'all'});}refresh(true);}
    if(next==='peek'&&session){toolbar.reset();stats.closes++;C.events.emit('inventory:close');}
    toolbar.controls.inert=next==='peek';toolbar.tabs.inert=next==='peek';toolbar.search.inert=next==='peek';body.inert=next==='peek';sheet.classList.toggle('is-peek',next==='peek');sheet.classList.toggle('is-full',next==='full');spring.target=detents[next];resizeViews();shelf.setActive(session&&mode==='shelf');grid.setActive(session&&mode==='grid');dirty=true;context();C.fx.wake();
    if(next!=='peek'){if(C.inventoryModel.current.pendingFocusStackKey){var pending=C.inventoryModel.current.pendingFocusStackKey;view().focus(pending,true);view().update(root.performance.now(),0);var entry=model.entries.find(function(e){return e.stackKey===pending;});var tile=Array.from(view().tiles.values()).find(function(t){return t.entry.stackKey===pending;});if(tile)tile.el.classList.add('is-acquired');C.inventoryTransition.handoff(entry,(function(){var rect=view().rect(pending);if(rect)rect={left:rect.left,top:rect.top-(detents[next]-spring.value),width:rect.width,height:rect.height};return rect;})(),tile);}if(C.input.modality==='keyboard')focus(view().el);}
  }
  function finish(){session=false;toolbar.reset();shelf.setActive(false);grid.setActive(false);shelf.clear();grid.clear();C.inventoryTransition.clear();menuInert(false);root.document.body.classList.remove('inventory-depth-active');C.accessibility.release(sheet);C.events.emit('menu:visibilityHold',{reason:'inventory',active:false});C.events.emit('menu:activity');context();focus(arrow);}
  function beginDrag(event,capture){if(openingPhase!=='idle'||preferences||detailId||toolbar.modal||event.button!==0||event.isPrimary===false)return;cancel();suppressClick=false;drag={id:event.pointerId,capture:capture,y:event.clientY,x:event.clientX,start:spring.value,last:event.clientY,at:root.performance.now(),velocity:0,moved:false};capture.setPointerCapture(event.pointerId);C.fx.wake();}
  function moveDrag(event){if(!drag||event.pointerId!==drag.id)return;var d=drag,dy=event.clientY-d.y,now=root.performance.now();if(Math.hypot(event.clientX-d.x,dy)>=cfg.dragSlopPx)d.moved=true;if(!d.moved)return;event.preventDefault();var v=d.start-dy,low=detents.peek,high=detents.full;if(v<low||v>high){var edge=v<low?low:high,over=v-edge;v=C.motion.reduced?clamp(v,low,high):edge+Math.sign(over)*cfg.rubberBandPx*(1-1/(1+Math.abs(over)/cfg.rubberBandPx));}spring.value=v;d.velocity=clamp(-(event.clientY-d.last)*1000/Math.max(16,now-d.at),-cfg.maxFlickPxPerSecond,cfg.maxFlickPxPerSecond);d.last=event.clientY;d.at=now;dirty=true;C.fx.wake();}
  function releaseDrag(event,cancelled){if(!drag||event&&event.pointerId!==drag.id)return;var d=drag;drag=null;if(d.capture.hasPointerCapture(d.id))d.capture.releasePointerCapture(d.id);if(d.moved){suppressClick=true;var projected=spring.value+(cancelled||C.motion.reduced?0:d.velocity*Math.exp(-(root.performance.now()-d.at)/cfg.flickDecayMs)*cfg.flickProjectionMs/1000);var next=cancelled?detent:Object.keys(detents).reduce(function(best,key){return Math.abs(detents[key]-projected)<Math.abs(detents[best]-projected)?key:best;},'peek');request(next);}else spring.target=detents[detent];C.fx.wake();}
  function openDetail(tile){if(!session||detailId||toolbar.modal||drag||reorder.active||reorder.guarded)return;detailId=tile.entry.stackKey;shelf.cancel();C.inventoryTransition.clear();toolbar.close();body.inert=true;grip.inert=true;toolbar.el.inert=true;toolbar.tabs.inert=true;var payload=view().take(tile);payload.preview=!!fixture;C.events.emit('inventory:detailOpen',payload);context();if(tile.entry.owned&&C.collection.markSeen(detailId,fixture?fixture.instances:C.state.current.inventory)){if(!fixture)C.state.save();else refresh(false);}}
  function detailById(id){var entry=model.entries.find(function(e){return e.stackKey===id;});if(!entry)return;view().focus(id,true);view().update(root.performance.now(),0);var tile=Array.from(view().tiles.values()).find(function(t){return t.entry.stackKey===id;});if(tile)openDetail(tile);}
  function reorderCards(from,to,sourceRect){if(!model.entries[from]||!model.entries[to]||fixture)return;var before=C.inventoryTransition.capture(view().tiles);selected=model.entries[from].stackKey;if(sourceRect)before.set(selected,{rect:sourceRect,entry:model.entries[from]});C.inventoryModel.reorder(model.entries.map(function(e){return e.stackKey;}),from,to);view().update(root.performance.now(),0);C.inventoryTransition.morph(before,view().tiles);}
  function reset(){cancel();C.events.emit('detail:reset');detailId=null;pendingClose=false;body.inert=false;grip.inert=false;toolbar.el.inert=false;toolbar.tabs.inert=false;fixture=null;query='';validQuery='';filters={};toolbar.clearSearch();selected=null;detent='peek';if(session)finish();spring.reset(detents.peek);sheet.classList.add('is-peek');toolbar.controls.inert=true;toolbar.tabs.inert=true;toolbar.search.inert=true;body.inert=true;refresh(true);C.inventoryTransition.forget();}
  function update(now,dt){
    var moving=false;stats.updates++;if(!drag){if(C.motion.reduced){var delta=spring.target-spring.value;spring.value+=delta*Math.min(1,dt/65);spring.velocity=0;if(Math.abs(delta)<.1)spring.reset(spring.target);}else spring.step(dt,spring.target);}
    if(dirty||!spring.settled()||drag){dirty=false;sheet.style.transform='translate3d(0,'+(detents.full-spring.value)+'px,0)';var depth=clamp((spring.value-detents.peek)/(detents.normal-detents.peek),0,1);root.document.body.style.setProperty('--inventory-menu-scale',C.motion.reduced?1:1-(1-cfg.menuScale)*depth);root.document.body.style.setProperty('--inventory-menu-blur',(C.motion.reduced?0:cfg.menuBlurPx*depth)+'px');root.document.body.style.setProperty('--inventory-menu-opacity',1-cfg.menuDim*depth);}
    if(session&&detent==='peek'&&spring.settled())finish();
    if(session&&!detailId&&!preferences){moving=view().update(now,dt)||moving;moving=reorder.update(now,dt)||moving;selectionAge+=dt;if(selectionAge>250&&selected&&C.inventoryModel.current.lastSelectedStackKey!==selected&&!fixture&&!view().dragging&&(mode==='grid'||shelf.settled()))C.inventoryModel.update({lastSelectedStackKey:selected});}
    moving=toolbar.update(now,dt)||moving;moving=C.inventoryTransition.update(now,dt)||moving;stats.mounted=shelf.tiles.size+grid.tiles.size;stats.maxMounted=Math.max(stats.maxMounted,stats.mounted);
    if(profile){profile.elapsed+=dt;if(view().snap)view().snap(Math.round((.5+.5*Math.sin(profile.elapsed/500))*Math.min(model.entries.length-1,30)));if(profile.elapsed>=5000){lastProfile={valid:true,tiles:model.total,mounted:stats.mounted,fullCards:C.cardView.stats.fullCards};profile=null;}else moving=true;}
    return moving||!!drag||!spring.settled();
  }
  C.inventory={initialized:false,stats:stats,canRequest:function(ctx,next){return ctx.phase==='idle'&&!ctx.hidden&&!ctx.preferences&&!(ctx.detail&&next);},get open(){return session&&detent!=='peek';},get active(){return session;},get progress(){return spring?(spring.value-detents.peek)/(detents.normal-detents.peek):0;},get detent(){return detent;},get entries(){return model.entries;},get rendered(){return view()?view().tiles:new Map();},get center(){return view()?view().center:0;},get order(){return C.inventoryModel.current.sortMode;},get preview(){return !!fixture;},get gesturesActive(){return !!drag||!!(shelf&&shelf.dragging)||!!(reorder&&reorder.active);},get lastProfile(){return lastProfile;},request:request,refresh:refresh,
    init:function(){if(this.initialized)return;this.initialized=true;var params=new URLSearchParams(root.location.search);if(params.get('dev')==='1'&&params.get('gallery')==='1')return;cfg=C.config.inventoryMotion;openingPhase=C.opening.phase;
      sheet=node('section','inventory-sheet glass glass--sheet is-peek',root.document.body);sheet.id='inventory-sheet';sheet.setAttribute('aria-label','Inventory');root.document.body.style.setProperty('--detail-backdrop-dim',cfg.detailBackdropDim);root.document.body.style.setProperty('--sheet-detail-opacity',cfg.sheetDetailOpacity);
      grip=node('div','inventory-grip',sheet);grip.setAttribute('aria-label','Drag inventory handle');node('i','inventory-handle',grip);grip.addEventListener('pointerdown',function(event){beginDrag(event,grip);});grip.addEventListener('lostpointercapture',function(){releaseDrag(null,true);});
      toolbar=C.inventoryToolbar.create(sheet,{collapse:function(){request();},expand:function(){request(detent==='full'?'normal':'full');},layout:function(){resizeViews();},preference:preference,search:function(text){query=text;refresh(false);resizeViews();},filters:function(value){filters=value;refresh(false);resizeViews();},detail:detailById,move:function(id,delta){var at=model.entries.findIndex(function(e){return e.stackKey===id;});reorderCards(at,clamp(at+delta,0,model.entries.length-1));}});
      peek=node('div','inventory-peek-thumbnail',toolbar.el);peek.addEventListener('click',function(){request(true);});toolbar.el.addEventListener('click',function(event){if(detent==='peek'&&!event.target.closest('button,input'))request(true);});
      body=node('div','inventory-content',sheet);empty=node('p','inventory-empty',body);
      selectedTags=node('div','inventory-selected-tags',body);
      var callbacks={select:select,activate:openDetail,context:function(tile,event){if(reorder.active||reorder.guarded)return;toolbar.context(tile,event);},blocked:function(){return preferences||!!detailId||toolbar.modal||reorder&&reorder.active;}};
      shelf=C.inventoryShelf.create(body,callbacks);grid=C.inventoryGrid.create(body,callbacks);
      reorder=C.inventoryReorder.create(body,{blocked:function(){return preferences||!!detailId||toolbar.modal||!session;},tiles:function(){return view().tiles;},tile:function(target){return Array.from(view().tiles.values()).find(function(t){return t.el.contains(target);});},cancelScroll:function(){view().cancel();},viewMode:function(){return mode;},nearest:function(x,y){var best=null,distance=Infinity;view().tiles.forEach(function(t){var r=t.el.getBoundingClientRect(),d=Math.hypot(x-r.left-r.width/2,y-r.top-r.height/2);if(d<distance){distance=d;best=t.index;}});return best;},scroll:function(delta){if(mode==='grid')grid.scroll(delta);else shelf.move(delta);},drop:reorderCards});
      spring=C.springs.create(0,Object.assign({},cfg.sheetSpring,{epsilon:.05}));var arrowHome=root.document.getElementById('inventory-affordance');arrow=arrowHome.querySelector('button');arrow.removeAttribute('aria-disabled');arrow.setAttribute('aria-controls','inventory-sheet');arrow.addEventListener('click',function(){if(suppressClick){suppressClick=false;return;}request();});arrow.addEventListener('keydown',function(e){if(e.key===' ')e.preventDefault();else if(e.key==='Enter'&&!e.repeat){e.preventDefault();request();}});arrow.addEventListener('pointerdown',function(e){beginDrag(e,arrow);});
      root.document.addEventListener('pointermove',moveDrag);root.document.addEventListener('pointerup',function(e){releaseDrag(e,false);});root.document.addEventListener('pointercancel',function(e){releaseDrag(e,true);});root.addEventListener('blur',function(){releaseDrag(null,true);shelf.cancel();reorder.cancel();});
      root.document.addEventListener('keydown',function(e){if(e.inventoryReorderHandled||preferences||e.repeat||detailId)return;var editable=e.target&&(e.target.isContentEditable||e.target.closest('input,select,textarea,[contenteditable]'));if(session&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();toolbar.openSearch();return;}if(e.key==='Escape'&&session){e.preventDefault();if(reorder.active){reorder.cancel();return;}if(!toolbar.escape())request('peek');return;}if(editable)return;if((e.key.toLowerCase()==='i'||e.key==='ArrowUp')&&!session&&openingPhase==='idle'){e.preventDefault();request(true);}});
      C.events.on('inventory:handoffComplete',function(event){if(C.inventoryModel.current.pendingFocusStackKey===event.stackKey)C.inventoryModel.update({pendingFocusStackKey:null});});C.events.on('inventory:request',request);C.events.on('inventory:preferencesChanged',function(){refresh(false);});C.events.on('save:written',function(){refresh(false);});C.events.on('save:reset',reset);C.events.on('save:willReset',reset);
      C.events.on('inventory:detailReturned',function(event){detailId=null;body.inert=false;grip.inert=false;toolbar.el.inert=false;toolbar.tabs.inert=false;view().restore(event);context();refresh(deferredModel);deferredModel=false;if(pendingClose){pendingClose=false;request('peek');}C.fx.wake();});
      C.events.on('inventory:returnTarget',function(event){event.rect=view().rect(event.stackKey);});
      C.events.on('inventory:detailNavigate',function(event){var at=model.entries.findIndex(function(e){return e.stackKey===detailId;}),next=model.entries[clamp(at+event.delta,0,model.entries.length-1)];if(next&&next.stackKey!==detailId){detailId=next.stackKey;selected=detailId;view().reserve(detailId);view().focus(detailId,true);view().update(root.performance.now(),0);event.entry=next;event.preview=!!fixture;if(next.owned&&!fixture&&C.collection.markSeen(detailId,C.state.current.inventory))C.state.save();}});
      C.events.on('inventory:detailMembership',function(event){toolbar.membership(event.entry,event.anchor);});
      C.events.on('inventory:preview',function(value){if(detailId)return;fixture=value?C.collection.preview(typeof value==='number'?value:cfg.previewCount):null;selected=null;refresh(true);});
      C.events.on('opening:context',function(event){openingPhase=event.phase;if(event.active&&session)reset();sheet.hidden=event.active;});C.events.on('preferences:context',function(event){preferences=event.active;sheet.inert=preferences;if(preferences){releaseDrag(null,true);shelf.cancel();reorder.cancel();}else resizeViews();});C.events.on('fx:visibility',function(visible){if(!visible){releaseDrag(null,true);shelf.cancel();reorder.cancel();if(profile){lastProfile={valid:false};profile=null;}}});C.events.on('motion:changed',function(){dirty=true;refresh(true);});C.events.on('settings:rarityColorMode',function(){refresh(true);});root.addEventListener('resize',resize);
      C.inventory.el=sheet;C.inventory.grip=grip;C.inventory.shelf=shelf.el;C.inventory.grid=grid.el;C.inventory.arrow=arrow;C.inventory.toolbar=toolbar;C.inventory.count=toolbar.count;C.inventory.content=body;
      C.inventory.carousel={move:function(px){shelf.move(px/shelf.pitch-shelf.target);},snap:function(px){shelf.snap(px/shelf.pitch);},settled:shelf.settled,get position(){return shelf.position*shelf.pitch;},get target(){return shelf.target*shelf.pitch;}};
      if(params.get('dev')==='1'){var tools=node('div','inventory-dev-tools',sheet);[60,300,500,1000].forEach(function(n){var b=node('button','',tools,n+' tiles');b.addEventListener('click',function(){C.events.emit('inventory:preview',n);request(true);});});var real=node('button','',tools,'Use real collection');real.addEventListener('click',function(){C.events.emit('inventory:preview',false);});var measure=node('button','',tools,'Measure 5 s FPS');measure.addEventListener('click',function(){profile={elapsed:0};C.profiler.start('inventory · '+model.total+' cards');C.fx.wake();});}
      selected=C.inventoryModel.current.lastSelectedStackKey;resize();refresh(true);shelf.setActive(false);grid.setActive(false);toolbar.controls.inert=true;toolbar.tabs.inert=true;toolbar.search.inert=true;body.inert=true;C.fx.subscribe(update,'inventory');context();
    }
  };
})(window.Cardable,window);
