(function(C,root){'use strict';
  var sheet,backdrop,rail,content,search,origin,blocked=[],selected=0,query='',pending=false;
  function date(note){return note.date?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(note.date)):/Unreleased/.test(note.version)?'Unreleased':'Date not recorded';}
  function read(){try{return JSON.parse(root.localStorage.getItem('cardable.patchnotes.seen')||'{}');}catch(_){return {};}}
  function mark(version){var seen=read();seen[version]=true;try{root.localStorage.setItem('cardable.patchnotes.seen',JSON.stringify(seen));root.localStorage.setItem('cardable.patchnotes.version',C.config.version);root.localStorage.setItem('cardable.qol.versionSeen',C.config.version);}catch(_){}}
  function markdown(note){return note.markdown||'## '+note.version+'\n\n'+note.sections.map(function(s){return '### '+s.title+'\n\n'+s.items.map(function(i){return '- '+i.text;}).join('\n');}).join('\n\n');}
  function close(){if(!sheet)return;C.accessibility.release(sheet);backdrop.remove();sheet=null;blocked.forEach(function(r){if(r.el.isConnected)r.el.inert=r.before;});blocked=[];C.events.emit('qol:context',{active:false});C.events.emit('menu:visibilityHold',{reason:'patchnotes',active:false});if(origin&&origin.isConnected&&C.accessibility.available(origin))origin.focus({preventScroll:true});C.ui.emit('close',{component:'patchnotes'});}
  function go(target){close();if(target==='inventory')C.inventory.request('full');else if(target==='achievements')C.achievementView.show();else if(target==='studio'){if(C.detail.phase==='detail')C.studio.enter();else{C.inventory.request('full');C.ui.toast('Choose a collected card, then Inspect.');}}else if(target==='desktop'){if(C.native)C.native.window.toggleMini();else{C.openSettings('Desktop');C.ui.toast('Mini mode is available in the Windows app.');}}else if(target==='notes')show();else C.openSettings(target==='settings'?'Graphics':target);}
  function render(){var notes=C.data.patchNotes,seen=read(),note=notes[selected];rail.replaceChildren();notes.forEach(function(n,i){var b=C.ui.create('button',{label:n.version,variant:'ghost',onClick:function(){selected=i;mark(n.version);render();}});b.classList.add('cb-notes-version');b.setAttribute('aria-current',String(i===selected));b.appendChild(Object.assign(root.document.createElement('small'),{textContent:date(n)}));if(!seen[n.version])b.appendChild(C.ui.create('badge',{label:'Unread'}));rail.appendChild(b);});content.replaceChildren();
    var h=root.document.createElement('h2');h.className='cb-title';h.textContent=note.version;content.appendChild(h);content.appendChild(C.ui.create('chip',{label:date(note)}));if(note.highlight){var img=root.document.createElement('img');img.src=note.highlight;img.alt=note.highlightAlt||'Update preview';content.appendChild(img);}
    note.sections.forEach(function(section){var items=section.items.filter(function(i){return !query||(section.title+' '+i.text).toLowerCase().includes(query);});if(!items.length)return;var s=C.ui.create('panel',{className:'cb-notes-section'}),header=root.document.createElement('h3');header.appendChild(C.icons.create(section.title==='New'?'new':section.title==='Fixed'?'check':section.title==='Known issues'?'error':'notes'));header.append(root.document.createTextNode(section.title));s.appendChild(header);var list=root.document.createElement('ul');items.forEach(function(item){var li=root.document.createElement('li');li.textContent=item.text;if(item.target)li.appendChild(C.ui.create('button',{label:'Try it',variant:'ghost',onClick:function(){go(item.target);}}));list.appendChild(li);});s.appendChild(list);content.appendChild(s);});
    if(!content.querySelector('.cb-notes-section'))content.appendChild(C.ui.create('empty-state',{label:'No matching changes. Try another search.'}));content.scrollTop=0;
  }
  function show(version){if(sheet)return true;if(C.opening.phase!=='idle'||C.studio?.active||C.studio?.pending||C.tutorial.active||C.state.recovery?.pending)return false;
    if(C.commands.active)C.commands.close();if(C.preferences.open)C.preferences.close();selected=Math.max(0,C.data.patchNotes.findIndex(function(n){return n.version===version;}));query='';origin=root.document.activeElement;
    backdrop=C.ui.create('panel',{className:'cb-notes-backdrop'});backdrop.setAttribute('data-tool-surface','patchnotes');sheet=C.ui.create('sheet',{label:'Patch notes',className:'cb-notes-sheet'});backdrop.appendChild(sheet);
    var header=C.ui.create('section-header',{children:[C.ui.create('help',{help:'notes',label:'Patch notes help'}),C.ui.create('button',{label:'Copy Markdown',onClick:function(){C.ui.copyText(markdown(C.data.patchNotes[selected])).then(function(ok){C.ui.toast(ok?'Patch notes copied.':'Could not copy. Try exporting from the changelog file.');});}}),C.ui.create('button',{label:'Close',onClick:close})]});header.prepend(Object.assign(root.document.createElement('h1'),{className:'cb-heading',textContent:'Patch notes'}));sheet.appendChild(header);
    search=C.ui.create('search-field',{label:'Search patch notes',placeholder:'Search this version…',onChange:function(v){query=v.toLowerCase().trim();render();}});sheet.appendChild(search);var work=C.ui.create('panel',{className:'cb-notes-workspace'});rail=C.ui.create('scroll-area',{className:'cb-notes-rail'});rail.setAttribute('aria-label','Version timeline');content=C.ui.create('scroll-area',{className:'cb-notes-content'});work.append(rail,content);sheet.appendChild(work);
    var parent=C.viewport.parent(root.document.body);Array.from(parent.children).filter(function(e){return e!==backdrop&&!['SCRIPT','CANVAS'].includes(e.tagName)&&!e.classList.contains('cb-toast-stack');}).forEach(function(e){blocked.push({el:e,before:e.inert});e.inert=true;});parent.appendChild(backdrop);mark(C.data.patchNotes[selected].version);render();C.accessibility.trap(sheet);search.focus();backdrop.addEventListener('click',function(e){if(e.target===backdrop)close();});sheet.addEventListener('keydown',function(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}else if((e.key==='ArrowUp'||e.key==='ArrowDown')&&rail.contains(e.target)){e.preventDefault();selected=Math.max(0,Math.min(C.data.patchNotes.length-1,selected+(e.key==='ArrowDown'?1:-1)));mark(C.data.patchNotes[selected].version);render();rail.children[selected].focus();}});C.events.emit('qol:context',{active:true});C.events.emit('menu:visibilityHold',{reason:'patchnotes',active:true});C.ui.emit('open',{component:'patchnotes'});return true;
  }
  function pump(){if(!pending||sheet||root.document.hidden||C.friendly?.active||C.preferences.open||C.inventory.active||C.commands.active||C.tutorial.active||C.opening.phase!=='idle'||C.studio?.active||C.state.recovery)return;if(show())pending=false;}
  C.patchNotes={show:show,close:close,markdown:markdown,get open(){return !!sheet;}};
  C.events.on('app:ready',function(){C.commands.register({id:'patchnotes',label:'Patch notes',group:'Help',run:show});Object.keys(C.settingsSchema.entries).forEach(function(id){var d=C.settingsSchema.entries[id];if(d.group)C.commands.register({id:'setting:'+id,label:'Settings · '+d.label,group:d.group,run:function(){C.openSettings(id);}});});try{var last=root.localStorage.getItem('cardable.patchnotes.version')||root.localStorage.getItem('cardable.qol.versionSeen');pending=!!last&&last!==C.config.version;if(!last)root.localStorage.setItem('cardable.patchnotes.version',C.config.version);}catch(_){}pump();});
  ['opening:context','preferences:context','inventory:context','qol:context','tutorial:context','menu:activity','fx:visibility'].forEach(function(name){C.events.on(name,function(){root.queueMicrotask(pump);});});
})(window.Cardable,window);
