(function(C,root){'use strict';
  function speed(){var rate=C.settings.get('uiAnimationSpeed')||1;Object.entries({instant:80,fast:150,base:240,slow:400,sheet:500,exit:120}).forEach(function(p){root.document.documentElement.style.setProperty('--duration-'+p[0],p[1]/rate+'ms');});}
  C.formats={date:function(time,includeTime){var date=new Date(time),format=C.settings.get('dateFormat'),text=format==='iso'?date.toISOString().slice(0,10):date.toLocaleDateString(format==='dmy'?'en-GB':format==='mdy'?'en-US':undefined);return includeTime?text+' '+C.formats.time(time):text;},time:function(time){var value=C.settings.get('timeFormat'),opts={hour:'2-digit',minute:'2-digit'};if(value!=='system')opts.hour12=value==='12';return new Date(time).toLocaleTimeString(undefined,opts);},number:function(value,original){var style=C.settings.get('numberFormat');return style==='current'?original:style==='full'?Number(value).toLocaleString():new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:1}).format(value);}};
  C.controlOptions={cutscene:function(rarity){if(!rarity)return 'inherit';var route=C.settings.get('cutscene_'+rarity.id)||'inherit',seen=C.settings.get('cutscenesSeen')||{};if(C.settings.get('playCutscenesOnce')&&!seen[rarity.id])return 'play';return C.settings.get('skipAllCutscenes')?'skip':route;},seen:function(rarity){if(!rarity||!C.settings.get('playCutscenesOnce'))return;var seen=Object.assign({},C.settings.get('cutscenesSeen'));seen[rarity.id]=true;C.settings.set('cutscenesSeen',seen);},reset:function(){var next=Object.assign({},C.settings.snapshot,{keyBindings:{},controlsProfile:'Default'});C.data.visibilityKeys.forEach(function(k){next[k]=true;});C.settings.restore(next);}};
  C.events.on('app:ready',function(){Object.keys(C.settingsSchema.entries).forEach(function(id){var d=C.settingsSchema.entries[id];if(d.group)C.commands.register({id:'setting:'+id,label:'Settings · '+d.label,group:d.group,run:function(){C.openSettings(id);}});});speed();var info=C.desktop&&C.desktop.info;if(new URLSearchParams(root.location.search).has('reset-controls')||info&&info.resetControls)C.controlOptions.reset();if(C.settings.get('startupScreen')==='last'){var screen=C.settings.get('lastScreen');if(screen==='inventory')C.inventory.request(true);else if(screen==='achievements')C.achievementView.show();}
    var ui=C.inventoryModel.current,sort=C.settings.get('defaultSort'),view=C.settings.get('defaultView');if(sort!=='current'||view!=='current')C.inventoryModel.update({sortMode:sort==='current'?ui.sortMode:sort,viewMode:view==='current'?ui.viewMode:view});
  });
  C.events.on('inventory:context',function(e){if(C.settings.get('startupScreen')==='last')C.settings.set('lastScreen',e.active?'inventory':'menu');});C.events.on('achievements:open',function(){if(C.settings.get('startupScreen')==='last')C.settings.set('lastScreen','achievements');});
  C.events.on('settings:changed',function(e){if(e.key==='fpsLimit'&&C.native&&C.native.app.setGraphics)C.native.app.setGraphics(e.value==='unlimited').catch(function(){C.qol.toast('Could not save the desktop frame-limit preference.');});if(e.key==='uiAnimationSpeed')speed();if(e.key==='keyBindings')C.events.emit('controls:changed');});
})(window.Cardable,window);
