(function(C,root){'use strict';
  var entries=new Map(),listeners=[],held=new Map(),capture=null,sequence=0,props=new WeakMap();
  var reserved=['Escape','Mod+Comma','Tab','Shift+Tab','Mod+KeyQ','Alt+F4','Mod+Space','Mod+Tab','Alt+Tab','Mod+KeyW'];
  var punctuation={' ':'Space','?':'Shift+Slash','/':'Slash',',':'Comma','.':'Period','[':'BracketLeft',']':'BracketRight','+':'Shift+Equal','=':'Equal','-':'Minus','_':'Shift+Minus','`':'Backquote'};
  function canonical(value){if(typeof value!=='string')return '';var parts=value.replace(/Ctrl\/Cmd|Ctrl|Cmd|Control|Meta/g,'Mod').split('+'),last=parts.pop();if(last==='')last='Plus';last=last==='Plus'?'Equal':punctuation[last]||last;if(/^[a-z]$/i.test(last))last='Key'+last.toUpperCase();if(/^\d$/.test(last))last='Digit'+last;var mods=['Mod','Alt','Shift'].filter(function(m){return parts.includes(m)||last.indexOf(m+'+')===0;});last=last.replace(/^(?:Mod|Alt|Shift)\+/,'');return mods.concat(last).join('+');}
  function valid(value){return /^(?:(?:Mod|Alt|Shift)\+)*(?:Key[A-Z]|Digit[0-9]|F(?:[1-9]|1[0-2])|Arrow(?:Left|Right|Up|Down)|Space|Enter|Escape|Tab|Home|End|PageUp|PageDown|Delete|Backspace|Comma|Period|Slash|Backquote|BracketLeft|BracketRight|Equal|Minus|Backslash|Numpad(?:[0-9]|Add|Subtract|Enter|Decimal))$/.test(value);}
  function normalize(input){var out={};if(!input||typeof input!=='object'||Array.isArray(input))return out;Object.keys(input).slice(0,400).forEach(function(id){if(!/^[\w.:-]{1,100}$/.test(id)||!Array.isArray(input[id]))return;out[id]=Array.from(new Set(input[id].map(canonical).filter(valid))).slice(0,2);});return out;}
  function bindings(item,map){map=map||C.settings&&C.settings.get('keyBindings')||{};return Object.prototype.hasOwnProperty.call(map,item.id)?map[item.id]:item.id==='opening.hold'&&C.settings?[canonical(C.settings.holdKey)]:item.id==='opening.tear'&&C.settings?[canonical(C.settings.actionKey)]:item.defaults;}
  function chord(e){var code=e.code||canonical(e.key).split('+').pop();return [(e.ctrlKey||e.metaKey)?'Mod':'',e.altKey?'Alt':'',e.shiftKey?'Shift':'',code].filter(Boolean).join('+');}
  function editable(target){return target&&target.closest&&target.closest('input,select,textarea,[contenteditable]:not([contenteditable="false"])');}
  function context(){if(C.preferences&&C.preferences.open)return 'settings';if(C.ui&&C.ui.modal||C.commands&&C.commands.active||C.patchNotes&&C.patchNotes.open||C.friendly&&C.friendly.active||C.journalView&&C.journalView.open)return 'dialogs';if(C.studio&&C.studio.active){var t=root.document.activeElement;return t&&t.closest('.studio-timeline,.director2-dock,.director-dock,[data-timeline-focus]')?'studio.timeline':t&&t.closest('.studio-library')?'studio.library':t&&t.closest('.studio-viewport')?'studio.viewport':'studio';}if(C.achievementView&&C.achievementView.open)return 'achievements';if(C.detail&&C.detail.phase!=='closed')return 'detail';if(C.inventory&&C.inventory.active)return 'inventory';if(C.opening&&C.opening.phase==='rarityIntro')return 'cutscene';if(C.opening&&C.opening.phase!=='idle')return 'opening';return 'menu';}
  function active(item){var ctx=context();return (item.context==='global'||item.context===ctx||item.context==='studio'&&ctx.startsWith('studio.')||item.context==='opening'&&ctx==='menu')&&(!item.when||item.when());}
  function overlap(a,b){return a==='global'||b==='global'||a===b||a==='studio'&&b.startsWith('studio.')||b==='studio'&&a.startsWith('studio.')||a==='menu'&&b==='opening'||b==='menu'&&a==='opening';}
  function canOverlap(a,b){var aa=a.contexts||[a.context],bb=b.contexts||[b.context];return aa.some(function(x){return bb.some(function(y){return overlap(x,y);});});}
  function conflicts(id,value,map){var item=entries.get(id);if(!item)return [];return Array.from(entries.values()).filter(function(other){return other.id!==id&&!(item.exclusive&&item.exclusive===other.exclusive)&&canOverlap(item,other)&&bindings(other,map).includes(value);});}
  function set(id,slot,value,resolution){var item=entries.get(id);value=canonical(value);if(!item||slot<0||slot>1||value&&(!valid(value)||reserved.includes(value)))return {ok:false,error:'This key is reserved for navigation or the system.'};var map=normalize(C.settings.get('keyBindings')),before=bindings(item,map).slice(),found=value?conflicts(id,value,map):[];
    if(found.length&&!resolution)return {ok:false,conflicts:found};
    found.forEach(function(other){var list=bindings(other,map).slice(),at=list.indexOf(value);if(resolution==='swap'&&before[slot]&&!conflicts(other.id,before[slot],map).some(function(x){return x.id!==id;}))list[at]=before[slot];else list.splice(at,1);map[other.id]=list;});
    before[slot]=value;map[id]=before.filter(Boolean);C.settings.set('keyBindings',map);return {ok:true};}
  function label(id){var item=entries.get(id)||Array.from(entries.values()).filter(active).find(function(e){return e.defaults.includes(canonical(id));})||Array.from(entries.values()).find(function(e){return e.defaults.includes(canonical(id));});var text=item?bindings(item).join(' / '):canonical(id);return text.replace(/Mod/g,root.navigator.platform.indexOf('Mac')>=0?'Cmd':'Ctrl').replace(/Key|Digit/g,'').replace(/Comma/g,',').replace(/Period/g,'.').replace(/Slash/g,'/').replace(/Equal/g,'+').replace(/Minus/g,'−');}
  function origin(item){return typeof item.origin==='function'?item.origin():item.origin||item.defaults[0];}
  function virtual(event,binding){var bits=canonical(binding).split('+'),code=bits.pop(),key=/^Key/.test(code)?code.slice(3).toLowerCase():code.replace(/^Digit/,'');var names={Space:' ',Comma:',',Period:'.',Slash:bits.includes('Shift')?'?':'/',Equal:bits.includes('Shift')?'+':'=',Minus:bits.includes('Shift')?'_':'-',BracketLeft:'[',BracketRight:']',Backslash:'\\',Backquote:'`'};key=names[code]||key;var extra=props.get(event)||{};props.set(event,extra);return new Proxy(event,{get:function(t,p){if(p in extra)return extra[p];if(p==='key')return bits.includes('Shift')&&/^Key/.test(code)?key.toUpperCase():key;if(p==='code')return code;if(p==='ctrlKey')return bits.includes('Mod');if(p==='metaKey')return false;if(p==='shiftKey')return bits.includes('Shift');if(p==='altKey')return bits.includes('Alt');var v=t[p];return typeof v==='function'?v.bind(t):v;},set:function(t,p,v){extra[p]=v;return true;}});}
  function route(event,binding,action){if(action){var extra=props.get(event)||{};extra.cbKeyAction=action.id;props.set(event,extra);}var path=event.composedPath?event.composedPath():[event.target,root.document,root],stop=false,immediate=false;var ordered=listeners.filter(function(r){var host=r.ref.deref();return host&&r.type===event.type&&path.includes(host)&&host._cbKeyListeners&&host._cbKeyListeners.has(r.id);}).sort(function(a,b){var ai=path.indexOf(a.ref.deref()),bi=path.indexOf(b.ref.deref());return a.capture!==b.capture?(a.capture?-1:1):a.capture?bi-ai||a.order-b.order:ai-bi||a.order-b.order;});var lastHost=null;
    for(var r of ordered){var host=r.ref.deref();if(immediate||stop&&host!==lastHost)break;var raw=host._cbKeyListeners.get(r.id);if(!raw)continue;var e=binding?virtual(event,binding):virtual(event,chord(event));var proxy=new Proxy(e,{get:function(t,p){if(p==='currentTarget')return host;if(p==='stopPropagation')return function(){stop=true;event.stopPropagation();};if(p==='stopImmediatePropagation')return function(){stop=immediate=true;event.stopImmediatePropagation();};return t[p];},set:function(t,p,v){t[p]=v;return true;}});raw.call(host,proxy);lastHost=host;if(event.key==='Escape'&&event.defaultPrevented)break;}
    if(listeners.length>400)listeners=listeners.filter(function(r){var h=r.ref.deref();return h&&(h===root||h===root.document||h.isConnected);});}
  function dispatch(e){if(e.code==='Space')C.keys.spacePressed=e.type==='keydown';if(e.isComposing||e.key==='Process'||root.document.hidden)return;var value=chord(e);if(capture){if(e.type==='keydown'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){var cancel=capture;capture=null;cancel(null);}else if(!/^(Control|Meta|Shift|Alt)/.test(e.code||'')){var cb=capture;capture=null;cb(value);}}return;}
    if(e.type==='keydown'&&value==='Mod+Comma'){if(C.keys.emergency){e.preventDefault();e.stopImmediatePropagation();C.keys.emergency();return;}e.preventDefault();e.stopImmediatePropagation();if(C.events)C.events.emit('input:cancel',{reason:'emergency-settings'});if(C.commands&&C.commands.active)C.commands.close();if(C.contextMenu&&C.contextMenu.open)C.contextMenu.close();if(C.preferences)C.preferences.show(null,true);return;}
    if(e.key==='Escape'||e.key==='Tab'){route(e);return;}
    var item=e.type==='keyup'?held.get(e.code):Array.from(entries.values()).filter(active).sort(function(a,b){var ctx=context();return (a.context===ctx?-2:a.context==='global'?1:0)-(b.context===ctx?-2:b.context==='global'?1:0);}).find(function(a){return bindings(a).includes(value)&&(!editable(e.target)||a.allowInput||/Mod\+|^F\d/.test(value));});
    if(item){if(e.type==='keydown'){if(e.repeat&&!item.repeat){e.preventDefault();return;}held.set(e.code,item);}else held.delete(e.code);if(item.run&&(!item.bridge)){if(e.type==='keydown'){e.preventDefault();item.run(e);}else if(item.release)item.release(e);return;}var original=origin(item);route(e,original,item);return;}
    // Navigation/activation stays native, but removed game shortcuts cannot leak
    // into the old action callbacks. Local controls may still use Enter/arrows.
    var removed=Array.from(entries.values()).some(function(a){return active(a)&&a.defaults.includes(value)&&!bindings(a).includes(value);});if(!removed)route(e);
  }
  C.keys={entries:entries,normalize:normalize,canonical:canonical,chord:chord,label:label,bindings:function(id){var e=entries.get(id);return e?bindings(e).slice():[];},context:context,overlap:overlap,conflicts:conflicts,set:set,
    register:function(item){if(!item||!item.id||!item.label||!item.context)throw Error('Invalid key action');item=Object.assign({group:item.context,defaults:[],bridge:false},item);item.defaults=Array.from(new Set(item.defaults.map(canonical).filter(valid))).slice(0,2);if(item.bridge&&!item.run)item.run=function(event){if(event)return route(event,origin(item),item);var target=root.document.activeElement||root.document.body,path=[];for(var at=target;at;at=at.parentNode)path.push(at);path.push(root);var generated=new KeyboardEvent('keydown',{bubbles:true,cancelable:true});route(new Proxy(generated,{get:function(t,p){if(p==='target')return target;if(p==='composedPath')return function(){return path;};var v=t[p];return typeof v==='function'?v.bind(t):v;}}),origin(item),item);};entries.set(item.id,item);return function(){entries.delete(item.id);};},
    listen:function(host,type,id,fn,options){if(!host._cbKeyListeners)host._cbKeyListeners=new Map();var key=id+':'+type+':'+(++sequence);host._cbKeyListeners.set(key,fn);listeners.push({ref:new WeakRef(host),id:key,type:type,capture:options===true||!!(options&&options.capture),order:sequence});return function(){host._cbKeyListeners.delete(key);};},
    remove:function(host,type,fn){if(host._cbKeyListeners)for(var pair of host._cbKeyListeners)if(pair[0].includes(':'+type+':')&&pair[1]===fn)host._cbKeyListeners.delete(pair[0]);},
    capture:function(fn){capture=fn;return function(){capture=null;};},get capturing(){return !!capture;},
    reset:function(id){var map=normalize(C.settings.get('keyBindings'));if(id)delete map[id];else map={};C.settings.set('keyBindings',map);},
    validateImport:function(input){if(!input||input.format!=='cardable-controls'||input.version!==1)throw Error('Choose a Cardable controls export.');if(!input.bindings||typeof input.bindings!=='object'||Array.isArray(input.bindings))throw Error('Bindings must be an object.');Object.keys(input.bindings).forEach(function(id){var values=input.bindings[id];if(!Array.isArray(values)||values.length>2||values.some(function(v){return typeof v!=='string'||!valid(canonical(v));}))throw Error('Invalid binding for '+id);});var map=normalize(input.bindings);for(var id of Object.keys(map)){if(!entries.has(id))throw Error('Unknown action: '+id);if(map[id].some(function(v){return reserved.includes(v);}))throw Error('Reserved keys cannot be imported.');}var collisions=[];for(var id of Object.keys(map))for(var v of map[id])if(conflicts(id,v,map).some(function(o){return !entries.get(id).defaults.includes(v)||!o.defaults.includes(v);}))collisions.push(id);if(collisions.length)throw Error('Resolve conflicts before importing: '+collisions.slice(0,3).join(', '));return map;},
    import:function(input){C.settings.set('keyBindings',C.keys.validateImport(input));},
    export:function(){return {format:'cardable-controls',version:1,bindings:normalize(C.settings.get('keyBindings'))};},
    invoke:function(id,e){var a=entries.get(id);if(a&&active(a)&&a.run)a.run(e);},
    refresh:function(){if(!root.document)return;root.document.querySelectorAll('[data-key-action]').forEach(function(el){var text=label(el.dataset.keyAction);var a=entries.get(el.dataset.keyAction);if(a)el.setAttribute('aria-keyshortcuts',bindings(a).map(function(v){return v.replace(/Mod/g,'Control').replace(/Key|Digit/g,'');}).join(' '));if(el.tagName==='KBD')el.textContent=text||'Unbound';else el.dataset.tooltip=(el.dataset.keyLabel||el.getAttribute('aria-label')||'')+(text?' · '+text:'');});}
  };
  root.addEventListener('keydown',dispatch,true);root.addEventListener('keyup',dispatch,true);
  root.addEventListener('blur',function(){held.clear();capture=null;C.keys.spacePressed=false;});if(C.events)C.events.on('settings:changed',function(e){if(e.key==='keyBindings')C.keys.refresh();});
})(window.Cardable,window);
