(function(C,root){'use strict';
  C.ui.gallery=function(){
    var gallery=C.ui.create('sheet',{label:'Cardable UI gallery',className:'cb-gallery'}),held=[],presentation,status=C.ui.create('panel',{label:'Component events appear here.'});gallery.dataset.toolSurface='gallery';gallery.dataset.density='comfortable';gallery.dataset.galleryQuality='medium';
    var header=C.ui.create('section-header',{children:[C.ui.create('help',{help:'developer',label:'Gallery help'}),C.ui.create('button',{label:'Close gallery',onClick:function(){held.forEach(function(h){h.destroy();});if(unsubscribe)unsubscribe();if(offPress)offPress();if(presentation)presentation.close();else gallery.remove();if(origin&&origin.isConnected)origin.focus({preventScroll:true});}})]});
    header.prepend(Object.assign(root.document.createElement('h1'),{textContent:'One Cardable'}));gallery.appendChild(header);
    function previewState(value){gallery.dataset.galleryState=value;gallery.querySelectorAll('.cb-gallery-section button,.cb-gallery-section input,.cb-gallery-section select').forEach(function(e){if(!e.dataset.previewOriginalDisabled)e.dataset.previewOriginalDisabled=String(e.disabled);e.disabled=value==='disabled'||e.dataset.previewOriginalDisabled==='true';e.setAttribute('aria-busy',String(value==='loading'));if(e.matches('input,select'))e.setAttribute('aria-invalid',String(value==='error'));});}
    var tools=C.ui.create('row',{children:[C.ui.create('select',{label:'Gallery interaction state',options:['idle','hover','pressed','focus','disabled','loading','empty','error'],onChange:previewState}),C.ui.create('select',{label:'Gallery quality',options:['very-low','low','medium','high'],value:'medium',onChange:function(v){gallery.dataset.galleryQuality=v;}}),C.ui.create('select',{label:'Gallery density',options:['comfortable','compact'],onChange:function(v){gallery.dataset.density=v;}}),C.ui.create('switch',{label:'Gallery reduced motion',onChange:function(v){gallery.classList.toggle('reduced-motion',v);}})]});gallery.appendChild(tools);
    gallery.appendChild(C.ui.create('empty-state',{label:'Every state belongs to the same family.',children:[C.ui.create('chip',{label:'Idle · Hover · Pressed · Focus · Disabled · Loading · Empty · Error'})]}));
    function section(title){var e=C.ui.create('panel',{className:'cb-gallery-section'}),h=root.document.createElement('h2');h.textContent=title;e.appendChild(h);gallery.appendChild(e);return e;}
    function add(parent,type,p){var e=C.ui.create(type,p);parent.appendChild(e);return e;}
    var buttons=section('Buttons and confirmation');['primary','secondary','ghost','danger','hold-confirm','click-again'].forEach(function(v){var b=add(buttons,'button',{label:v.replace(/-/g,' '),variant:v,onConfirm:function(){C.ui.toast('Confirmation complete.');}});if(b.update)held.push(b);});add(buttons,'button',{label:'Unavailable',disabled:true,title:'Disabled controls explain their state.'});add(buttons,'icon-button',{label:'Close',icon:'close'});add(buttons,'button',{label:'Loading…',disabled:true});
    var fields=section('Fields and choices');['text-field','search-field','number-field','slider','checkbox','radio','switch','select'].forEach(function(type){var label=root.document.createElement('label');label.className='cb-gallery-field';label.appendChild(Object.assign(root.document.createElement('span'),{textContent:type.replace(/-/g,' ')}));label.appendChild(C.ui.create(type,{label:type,value:type==='number-field'?42:type==='slider'?60:undefined,min:0,max:100,options:['First option','Second option'],placeholder:'A labelled field…'}));fields.appendChild(label);});add(fields,'segmented-control',{label:'Segmented options',options:['First','Second','Third']});add(fields,'tabs',{label:'Tab navigation',options:['Set','Light','Camera']});
    var identity=section('Identity and progress');['keycap','chip','badge'].forEach(function(type){add(identity,type,{label:type==='keycap'?'Ctrl + K':type});});['compact','semi-open','open'].forEach(function(state){add(identity,'tag',{label:'Variant',detail:'Rainbow Holo · collected',state:state});});add(identity,'progress',{label:'Loading progress',value:.6});add(identity,'ring-progress',{label:'Collection progress',value:.72});add(identity,'skeleton',{label:'Skeleton'});add(identity,'loader',{label:'Loading card',loaded:2,total:3});
    var surfaces=section('Surfaces, rows and feedback');['panel','card','sheet','drawer','dialog','row','tree-row','stat-tile','section-header','scroll-area','tooltip','popover','context-menu','command-palette'].forEach(function(type){var sample=add(surfaces,type,{label:type.replace(/-/g,' ')});sample.classList.add('cb-gallery-sample');if(!sample.textContent)sample.textContent=type.replace(/-/g,' ');if(type==='tree-row'){sample.setAttribute('role','treeitem');sample.tabIndex=0;}sample.dataset.hover='glow-edge';});add(surfaces,'divider',{});add(surfaces,'button',{label:'Open dialog',onClick:function(){var presentation,dialog=C.ui.create('dialog',{label:'Local progress',children:[Object.assign(root.document.createElement('h2'),{textContent:'Progress stays on this computer'}),Object.assign(root.document.createElement('p'),{textContent:'Export your collection from Data when you want a backup.'}),C.ui.create('button',{label:'Close dialog',onClick:function(){presentation.close();}})]});presentation=C.ui.present(dialog);}});add(surfaces,'empty-state',{label:'No saved scenes yet',children:[C.ui.create('button',{label:'Create a scene'})]});add(surfaces,'button',{label:'Show toast',onClick:function(){C.ui.toast('Saved for this session.',{label:'Undo',run:function(){C.ui.toast('Previous choice restored.');}});}});add(surfaces,'button',{label:'Show error',onClick:function(){C.ui.toast('Could not read this file. Choose a complete save export.',null,'error');}});add(surfaces,'help',{help:'developer',label:'Help'});
    var controls=section('Controls and reversible profiles'),binding=add(controls,'row',{className:'cb-binding-row'});var copy=document.createElement('div');copy.innerHTML='<strong>Open inventory</strong><small class="cb-small">menu · primary and secondary</small>';binding.appendChild(copy);add(binding,'button',{label:C.keys.label('menu.inventory')});add(binding,'button',{label:'Assign…'});add(binding,'icon-button',{label:'Reset Open inventory',icon:'reset'});add(binding,'icon-button',{label:'Clear Open inventory bindings',icon:'close'});add(controls,'button',{label:'Preview a profile',onClick:function(){C.openSettings('Profiles');presentation.close();}});add(controls,'button',{label:'View release showcase',onClick:function(){presentation.close();C.patchNotes.show();}});
    var stateNote=C.ui.create('row',{className:'cb-gallery-state-note',label:'Preview states with the state selector. Keyboard focus, pointer hover and presses remain interactive.'});gallery.appendChild(stateNote);
    var hover=section('Six hover behaviors');['lift','glow-edge','reveal','magnet','tilt','press'].forEach(function(v){var b=add(hover,'button',{label:v});b.dataset.hover=v;if(v==='reveal')b.appendChild(Object.assign(root.document.createElement('span'),{className:'cb-reveal',textContent:'Extra information'}));});gallery.appendChild(status);
    gallery.dataset.galleryState='idle';var unsubscribe=C.fx.subscribe(function(now,dt){if(!gallery.isConnected)return false;var active=false;held.forEach(function(h){active=h.update(now,dt)||active;});return active;},'ui-gallery');
    var offPress=C.events.on('ui:press',function(p){if(gallery.isConnected)status.textContent='Pressed '+p.label;});
    var origin=root.document.activeElement;C.keys.listen(gallery, 'keydown', 'src.ui.kit.gallery.js.1', function(event){if(event.key==='Escape'){event.preventDefault();header.querySelector('button:last-child').click();}if(event.key==='Tab'){var focusables=Array.from(gallery.querySelectorAll('button,input,select,[tabindex="0"]')).filter(function(e){return !e.disabled&&e.getClientRects().length;}),first=focusables[0],last=focusables[focusables.length-1];if(event.shiftKey&&root.document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&root.document.activeElement===last){event.preventDefault();first.focus();}}});
    presentation=C.ui.present(gallery,{onClose:function(){held.forEach(function(h){h.destroy();});if(unsubscribe)unsubscribe();if(offPress)offPress();}});C.ui.mount(gallery);return gallery;
  };
  C.events.on('app:ready',function(){if(new URLSearchParams(root.location.search).get('dev')==='1'&&new URLSearchParams(root.location.search).get('gallery')==='ui')C.ui.gallery();});
})(window.Cardable,window);
