(function(C,root){'use strict';
  var upgraded=new WeakSet(),observer,toastHost,popup,tipTimer,helpActive=false,tooltip;
  function el(tag,cls,text){var e=root.document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;}
  function emit(name,data){if(C.events)C.events.emit('ui:'+name,data||{});}
  function closePopup(){if(popup){popup.remove();popup=null;emit('close',{component:'popover'});}}
  function position(p,anchor){var r=anchor.getBoundingClientRect();p.style.left=Math.max(8,Math.min(root.innerWidth-p.offsetWidth-8,r.left))+'px';p.style.top=Math.max(8,Math.min(root.innerHeight-p.offsetHeight-8,r.bottom+8))+'px';}
  function showHelp(anchor,id){var data=C.data.help[id]||{title:anchor.getAttribute('aria-label')||anchor.textContent.trim(),body:'Use this control to '+(anchor.getAttribute('aria-label')||anchor.textContent.trim()).toLowerCase()+'.'};closePopup();popup=el('aside','cb-popover cb-ui');popup.setAttribute('role','note');popup.appendChild(el('strong','',data.title));popup.appendChild(el('p','',data.body));
    var keys=data.shortcuts||[];if(keys.length)popup.appendChild(el('p','cb-small',keys.map(function(k){return C.keybindings&&C.keybindings.label?C.keybindings.label(k):k;}).join(' · ')));root.document.body.appendChild(popup);position(popup,anchor);emit('open',{component:'help',id:id});}
  function stopTooltip(){root.clearTimeout(tipTimer);if(tooltip){tooltip.remove();tooltip=null;}}
  function enhance(e){if(!e||e.nodeType!==1||upgraded.has(e)||e.closest('.card,.card-thumbnail,.pack-unit,.gpu-art,.wordmark'))return;
    var tag=e.tagName,classes=e.className&&typeof e.className==='string'?e.className:'';
    if(tag==='BUTTON'){e.classList.add('cb-button');if(!e.hasAttribute('data-hover'))e.dataset.hover='lift';if(!e.getAttribute('type'))e.type='button';}
    if(tag==='INPUT'||tag==='TEXTAREA')e.classList.add('cb-field');if(tag==='SELECT')e.classList.add('cb-select');if(tag==='KBD')e.classList.add('cb-keycap');
    if(/(?:toast|undo-notice)$/.test(classes)){e.dataset.cbToast='true';}
    if(tag==='BUTTON'||tag==='INPUT'||tag==='SELECT'||tag==='TEXTAREA'){upgraded.add(e);if(e.disabled&&!e.title)e.title='Unavailable in this context';}
    if(/(?:panel|sheet|toolbar|dialog|overlay|surface|inspector|friendly|timeline|library)(?:\s|$)/.test(classes)){
      e.classList.add('cb-ui');var id=/achievement/.test(classes)?'achievements':/preferences|settings/.test(classes)?'settings':/timeline/.test(classes)?'timeline':/library/.test(classes)?'library':/studio/.test(classes)?'studio':/detail/.test(classes)?'detail':/inventory/.test(classes)?'inventory':/tutorial/.test(classes)?'tutorial':/dev-/.test(classes)?'developer':/palette/.test(classes)?'commands':/performance/.test(classes)?'performance':/qol-/.test(classes)?'welcome':/opening/.test(classes)?'opening':'menu';
      if(!e.dataset.help)e.dataset.help=id;
      if(!/overlay|toolbar|surface/.test(classes)&&e.querySelector('h2,h3')&&!e.querySelector(':scope > .cb-help-button')){var b=C.ui.create('help',{help:id,label:'Help with '+C.data.help[id].title});e.insertBefore(b,e.firstChild);}
    }
    if(tag==='BUTTON'&&!e.dataset.help){var text=e.getAttribute('aria-label')||e.textContent.trim();if(text)e.dataset.help='control:'+text;}
  }
  function mount(host){if(!host)return;enhance(host);host.querySelectorAll('button,input,select,textarea,kbd,section,aside,header,div,article').forEach(enhance);}
  function progress(value,label,ring){var e;if(ring){e=root.document.createElementNS('http://www.w3.org/2000/svg','svg');e.setAttribute('viewBox','0 0 48 48');e.classList.add('cb-ring');for(var i=0;i<2;i++){var c=root.document.createElementNS(e.namespaceURI,'circle');c.setAttribute('cx',24);c.setAttribute('cy',24);c.setAttribute('r',20);e.appendChild(c);}}else{e=el('div','cb-progress');e.appendChild(el('i'));}e.setAttribute('role','progressbar');e.setAttribute('aria-label',label||'Progress');e.setAttribute('aria-valuemin',0);e.setAttribute('aria-valuemax',100);e.update=function(v){v=Math.max(0,Math.min(1,Number(v)||0));e.setAttribute('aria-valuenow',Math.round(v*100));if(ring)e.style.setProperty('--progress',v);else e.firstChild.style.transform='scaleX('+v+')';};e.update(value);return e;}
  var types={button:'button','icon-button':'button',switch:'button',checkbox:'input',radio:'input',slider:'input','number-field':'input','text-field':'input','search-field':'input',select:'select',keycap:'kbd',chip:'span',badge:'span',tag:'button',panel:'section',card:'article',sheet:'section',drawer:'aside',dialog:'section',row:'div',list:'div','tree-row':'div','section-header':'header','stat-tile':'div',divider:'hr','scroll-area':'div',skeleton:'div','empty-state':'div',help:'button',tooltip:'aside',popover:'aside','context-menu':'div','command-palette':'section',loader:'div'};
  C.ui={mount:mount,enhance:enhance,progress:progress,emit:emit,
    create:function(type,p){p=p||{};if(type==='progress'||type==='ring-progress')return progress(p.value,p.label,type==='ring-progress');
      if(type==='tabs'||type==='segmented-control'){var group=el('div',type==='tabs'?'cb-tabs':'cb-segments');group.setAttribute('role',type==='tabs'?'tablist':'radiogroup');group.setAttribute('aria-label',p.label||'Choose an option');var values=p.options||[],buttons=[];
        function choose(i){buttons.forEach(function(b,j){b.setAttribute(type==='tabs'?'aria-selected':'aria-checked',String(i===j));b.tabIndex=i===j?0:-1;});if(p.onChange)p.onChange(typeof values[i]==='object'?values[i].value:values[i]);emit('toggle',{component:type,value:i});}
        values.forEach(function(v,i){var label=typeof v==='object'?v.label:v,b=C.ui.create('button',{label:label,variant:'ghost',onClick:function(){choose(i);}});b.setAttribute('role',type==='tabs'?'tab':'radio');b.addEventListener('keydown',function(e){if(['ArrowLeft','ArrowRight','Home','End'].indexOf(e.key)<0)return;e.preventDefault();var n=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;choose(n);buttons[n].focus();});group.appendChild(b);buttons.push(b);});buttons.forEach(function(b,i){b.setAttribute(type==='tabs'?'aria-selected':'aria-checked',String((p.value==null?0:p.value)===i));b.tabIndex=(p.value==null?0:p.value)===i?0:-1;});return group;}
      var e=el(types[type]||'div','cb-'+({'text-field':'field','search-field':'field','number-field':'field',checkbox:'field',radio:'field',slider:'field','stat-tile':'stat','empty-state':'empty','scroll-area':'scroll',help:'icon-button cb-help-button',card:'panel','tree-row':'row',loader:'loader'}[type]||type));e.classList.add('cb-ui');
      if(p.label){if(e.tagName==='INPUT'||e.tagName==='SELECT')e.setAttribute('aria-label',p.label);else e.textContent=p.label;}
      if(p.variant)e.dataset.variant=p.variant;if(p.id)e.id=p.id;if(p.className)e.classList.add.apply(e.classList,p.className.split(' '));if(p.title)e.title=p.title;
      if(e.tagName==='BUTTON')e.type='button';if(p.icon){if(type==='icon-button'||type==='help')e.textContent='';e.prepend(C.icons.create(p.icon));e.setAttribute('aria-label',p.label||p.icon);}
      if(type==='help'){e.textContent='?';e.dataset.help=p.help||'menu';e.addEventListener('click',function(){showHelp(e,e.dataset.help);});}
      if(type==='switch'){e.textContent='';e.setAttribute('role','switch');e.setAttribute('aria-label',p.label||'Toggle');e.setAttribute('aria-checked',String(!!p.value));e.addEventListener('click',function(){var next=e.getAttribute('aria-checked')!=='true';e.setAttribute('aria-checked',String(next));if(p.onChange)p.onChange(next);emit('toggle',{value:next});});}
      if(e.tagName==='INPUT'){e.type={slider:'range','number-field':'number','search-field':'search',checkbox:'checkbox',radio:'radio'}[type]||'text';if(p.min!=null)e.min=p.min;if(p.max!=null)e.max=p.max;if(p.step!=null)e.step=p.step;if(p.value!=null)e.value=p.value;if(p.placeholder)e.placeholder=p.placeholder;if(p.name)e.name=p.name;if(type==='checkbox'||type==='radio')e.checked=!!p.value;e.addEventListener('input',function(){if(p.onChange)p.onChange(e.type==='checkbox'||e.type==='radio'?e.checked:e.type==='range'||e.type==='number'?Number(e.value):e.value);});
        if(type==='number-field'){var start=null;e.addEventListener('pointerdown',function(event){if(!event.altKey)return;event.preventDefault();start={x:event.clientX,value:Number(e.value)||0};e.setPointerCapture(event.pointerId);});e.addEventListener('pointermove',function(event){if(!start)return;var step=Number(e.step)||1,v=start.value+Math.round((event.clientX-start.x)/4)*step;e.value=Math.max(p.min==null?-Infinity:p.min,Math.min(p.max==null?Infinity:p.max,v));e.dispatchEvent(new Event('input',{bubbles:true}));});e.addEventListener('pointerup',function(){start=null;});e.addEventListener('pointercancel',function(){start=null;});}
      }
      if(type==='select'){(p.options||[]).forEach(function(v){var o=el('option','',typeof v==='object'?v.label:v);o.value=typeof v==='object'?v.value:v;e.appendChild(o);});if(p.value!=null)e.value=p.value;e.addEventListener('change',function(){if(p.onChange)p.onChange(e.value);});}
      if(type==='dialog'||type==='sheet'||type==='drawer'){e.setAttribute('role','dialog');e.setAttribute('aria-modal','true');e.setAttribute('aria-label',p.label||'Dialog');}
      if(type==='tag'){e.dataset.state=p.state||'compact';e.appendChild(el('span','cb-tag-detail',p.detail||''));e.addEventListener('pointerenter',function(){if(e.dataset.pinned!=='true')e.dataset.state='semi-open';});e.addEventListener('pointerleave',function(){if(e.dataset.pinned!=='true')e.dataset.state='compact';});e.addEventListener('focus',function(){if(e.dataset.pinned!=='true')e.dataset.state='semi-open';});e.addEventListener('blur',function(){if(e.dataset.pinned!=='true')e.dataset.state='compact';});e.addEventListener('click',function(){e.dataset.pinned=String(e.dataset.pinned!=='true');e.dataset.state=e.dataset.pinned==='true'?'open':'semi-open';});}
      if(type==='loader'){e.textContent='';var outline=el('div','cb-loader-outline');outline.appendChild(el('i'));e.appendChild(outline);e.appendChild(el('span','',p.label||'Loading card…'));e.setAttribute('role','status');e.update=function(loaded,total){var ratio=total?loaded/total:0;outline.firstChild.style.transform='scaleY('+Math.max(.05,Math.min(1,ratio))+')';e.lastChild.textContent=(p.label||'Loading')+' · '+loaded+' / '+total;};e.update(p.loaded||0,p.total||1);}
      if(p.disabled)e.disabled=true;if(p.onClick)e.addEventListener('click',p.onClick);if(p.children)p.children.forEach(function(child){e.appendChild(child);});
      if(p.variant==='hold-confirm'||p.variant==='click-again'){var confirmation;Promise.resolve().then(function(){if(!C.settingsControls)return;confirmation=C.settingsControls.confirmation(e,p.onConfirm||function(){},{mode:p.variant==='hold-confirm'?'hold':'click',holdMs:p.holdMs||1500,announce:p.announce});e.confirmation=confirmation;});e.update=function(now,dt){return confirmation?confirmation.update(now,dt):false;};e.destroy=function(){if(confirmation)confirmation.destroy();};}
      enhance(e);return e;
    },
    toast:function(text,action,variant){if(!toastHost){toastHost=el('div','cb-toast-stack cb-ui');toastHost.setAttribute('aria-live','polite');(C.viewport?C.viewport.parent(root.document.body):root.document.body).appendChild(toastHost);}while(toastHost.children.length>=3){var old=toastHost.firstChild;if(old.dismiss)old.dismiss();else old.remove();}var t=el('div','cb-toast cb-enter');t.dataset.variant=variant||'info';t.setAttribute('role',variant==='error'?'alert':'status');t.appendChild(C.icons.create(variant==='error'?'error':variant==='achievement'?'star':'check'));t.appendChild(el('span','',text));var timer;
      function dismiss(){root.clearTimeout(timer);t.remove();emit('close',{component:'toast'});}t.dismiss=dismiss;if(action)t.appendChild(C.ui.create('button',{label:action.label,onClick:function(){dismiss();action.run();}}));if(variant==='error')t.appendChild(C.ui.create('icon-button',{label:'Dismiss message',icon:'close',onClick:dismiss}));else timer=root.setTimeout(dismiss,4000);toastHost.appendChild(t);emit(variant==='error'?'error':'success',{component:'toast'});return t;
    },
    loader:function(host,promise,label){var l=C.ui.create('loader',{label:label||'Loading card',total:1});host.appendChild(l);var timer=root.setTimeout(function(){l.remove();},8000);Promise.resolve(promise).then(function(){l.update(1,1);l.remove();root.clearTimeout(timer);},function(){l.remove();root.clearTimeout(timer);});return l;}
  };
  C.help={attach:function(e,id){e.dataset.help=id;return e;},show:showHelp,toggle:function(value){helpActive=value==null?!helpActive:!!value;root.document.body.classList.toggle('cb-help-active',helpActive);if(!helpActive)closePopup();return helpActive;},get active(){return helpActive;}};
  root.document.addEventListener('click',function(event){if(helpActive){var target=event.target.closest('[data-help]');if(target){event.preventDefault();event.stopImmediatePropagation();showHelp(target,target.dataset.help);return;}}if(popup&&!popup.contains(event.target)&&!event.target.closest('.cb-help-button'))closePopup();var b=event.target.closest('button');if(b&&!b.disabled)emit('press',{label:b.getAttribute('aria-label')||b.textContent.trim()});},true);
  root.document.addEventListener('change',function(event){if(event.target.closest('input,select'))emit('toggle',{value:event.target.value});});
  root.document.addEventListener('keydown',function(event){if(event.key==='Escape'&&(popup||helpActive)){event.preventDefault();event.stopImmediatePropagation();closePopup();C.help.toggle(false);}else if((event.key==='F1'||event.key==='?')&&!event.repeat&&!event.target.closest('input,textarea,select,[contenteditable]')){event.preventDefault();C.help.toggle();}},true);
  root.document.addEventListener('pointerover',function(event){var e=event.target.closest('[data-tooltip],button[title]');if(!e||e.disabled||tooltip)return;stopTooltip();tipTimer=root.setTimeout(function(){if(!e.isConnected)return;tooltip=el('aside','cb-tooltip cb-ui',e.dataset.tooltip||e.title);tooltip.setAttribute('role','tooltip');root.document.body.appendChild(tooltip);position(tooltip,e);emit('hover',{label:e.getAttribute('aria-label')||e.textContent});},400);});
  root.document.addEventListener('pointerout',stopTooltip);root.document.addEventListener('focusout',stopTooltip);root.document.addEventListener('visibilitychange',stopTooltip);
  root.document.addEventListener('pointermove',function(event){var e=event.target.closest('[data-hover]');if(!e||C.motion&&C.motion.reduced||C.settings&&C.settings.policy.animation<2)return;var r=e.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top;if(e.dataset.hover==='glow-edge'&&C.settings.policy.blur){e.style.setProperty('--pointer-x',x+'px');e.style.setProperty('--pointer-y',y+'px');}if(e.dataset.hover==='magnet')e.style.transform='translate('+Math.max(-4,Math.min(4,(x-r.width/2)*.04))+'px,'+Math.max(-4,Math.min(4,(y-r.height/2)*.04))+'px)';if(e.dataset.hover==='tilt')e.style.transform='perspective(700px) rotateX('+Math.max(-4,Math.min(4,-(y-r.height/2)*.03))+'deg) rotateY('+Math.max(-4,Math.min(4,(x-r.width/2)*.03))+'deg)';});
  root.document.addEventListener('pointerout',function(event){var e=event.target.closest('[data-hover="magnet"],[data-hover="tilt"]');if(e&&!e.contains(event.relatedTarget))e.style.transform='';});
  function init(){root.document.body.classList.add('cb-ui');mount(root.document.body);observer=new MutationObserver(function(records){records.forEach(function(record){record.addedNodes.forEach(function(e){if(e.nodeType===1)mount(e);});});});observer.observe(root.document.body,{childList:true,subtree:true});}
  if(C.events)C.events.on('app:ready',init);else init();
})(window.Cardable,window);
