(function(C,root){
  'use strict';var D=C.dev,frenzyCount=10,frenzy=null,frenzyResult=null,roulette=null,roulettePick=null,immersive=null;
  function stopFrenzy(reason){if(!frenzy)return;C.presentation.openingRate=1;frenzyResult={opened:frenzy.opened,requested:frenzy.requested,reason:reason,bestPull:frenzy.best?{card:C.card(frenzy.best.cardId).name,tier:C.rarity(C.card(frenzy.best.cardId).rarity).name,finish:(C.variant(frenzy.best.variantId)||{name:'Normal'}).name}:null,variants:frenzy.variants,rarities:frenzy.rarities};D.frames.delete(frenzy.frame);frenzy=null;D.message('Frenzy stopped · '+reason);D.changed();}
  D.frenzy=function(){if(frenzy)throw new Error('A frenzy is already running.');if(D.disposePreview)D.disposePreview();if(C.opening.phase!=='idle'||C.inventory.active||C.preferences.open)throw new Error('Close game dialogs and finish the current pack first.');if(!C.state.current.packs.ready)throw new Error('No available stock. Grant packs first.');
    var run={requested:frenzyCount,opened:0,best:null,rarities:{},variants:{},frame:function(){
      if(!frenzy)return false;
      if(C.opening.phase==='idle'){if(run.opened>=run.requested){stopFrenzy('Requested packs opened');return false;}if(!C.state.current.packs.ready){stopFrenzy('Stock exhausted');return false;}if(!C.opening.openNow(D.pack().id)){stopFrenzy('Opening unavailable or durable write failed');return false;}}
      if(C.opening.phase==='cutting')C.opening.finishCut();
      if(C.opening.phase==='revealed'&&!C.opening.keepButton.hidden)C.opening.keepCurrent();
      return true;
    }};frenzy=run;C.presentation.openingRate=16;D.frames.add(run.frame);C.fx.wake();D.message('Frenzy running · shortened real openings');
  };
  C.events.on('opening:committed',function(e){if(!frenzy)return;frenzy.opened++;e.cards.forEach(function(i){var card=C.card(i.cardId),rank=C.rarity(card.rarity).tier;frenzy.rarities[C.rarity(card.rarity).name]=(frenzy.rarities[C.rarity(card.rarity).name]||0)+1;if(i.variantId)frenzy.variants[C.variant(i.variantId).name]=(frenzy.variants[C.variant(i.variantId).name]||0)+1;if(!frenzy.best||rank>C.rarity(C.card(frenzy.best.cardId).rarity).tier||rank===C.rarity(C.card(frenzy.best.cardId).rarity).tier&&i.variantId&&!frenzy.best.variantId)frenzy.best=i;});});
  D.exitImmersive=function(){if(!immersive)return;var mode=immersive;immersive=null;D.immersive=false;D.frames.delete(mode.frame);mode.cleanups.forEach(function(fn){fn();});mode.views.forEach(function(v){v.destroy();});C.accessibility.release(mode.host);mode.host.remove();root.document.body.classList.remove('dev-immersive');C.events.emit('preferences:context',{active:!!C.preferences.open});C.events.emit('menu:visibilityHold',{reason:'dev-showcase',active:false});if(mode.previous&&!mode.previous.destroyed)mode.previous.setMode('full');if(mode.focus&&mode.focus.isConnected)mode.focus.focus();D.ensureDriver();C.fx.wake();};
  function beginImmersive(title,cls){if(C.opening.phase!=='idle')throw new Error('Finish the active opening first.');if(D.disposePreview)D.disposePreview();D.exitImmersive();var host=D.node('section','dev-stage '+cls,root.document.body);host.dataset.toolSurface='';host.setAttribute('role','dialog');host.setAttribute('aria-label',title);host.tabIndex=-1;var mode={host:host,views:[],cleanups:[],focus:root.document.activeElement,previous:C.cardView.active,frame:null};if(mode.previous)mode.previous.setMode('lite');immersive=mode;D.immersive=true;D.ensureDriver();root.document.body.classList.add('dev-immersive');C.events.emit('preferences:context',{active:true,preview:true});C.events.emit('menu:visibilityHold',{reason:'dev-showcase',active:true});C.accessibility.trap(host);host.focus();return mode;}
  function listen(mode,target,type,fn,options){target.addEventListener(type,fn,options);mode.cleanups.push(function(){target.removeEventListener(type,fn,options);});}
  D.showcase=function(){var owned=C.state.current.inventory;if(!owned.length)throw new Error('Grant or keep a card before starting showcase.');var mode=beginImmersive('Owned-card showcase','dev-showcase'),track=D.node('div','dev-showcase-track',mode.host),caption=D.node('p','dev-stage-title',mode.host,'Any input exits'),age=0,randomOrder=owned.slice().sort(function(){return Math.random()-.5;}),index=0;
    function cycle(){mode.views.forEach(function(v){v.destroy();});mode.views=[];track.replaceChildren();for(var j=-1;j<=1;j++){var item=randomOrder[(index+j+randomOrder.length)%randomOrder.length],wrap=D.node('div',j?'dev-showcase-side':'',track),view=D.previewCard(wrap,C.card(item.cardId),item.variantId,{instance:item,lite:j!==0});view.setTiltLock({x:0,y:j?j*-16:0});mode.views.push(view);}var center=randomOrder[index];caption.textContent=C.card(center.cardId).name+' / '+(C.variant(center.variantId)||{name:'Normal'}).name+' · Any input exits';index=(index+1)%randomOrder.length;}
    cycle();mode.frame=function(now,dt){age+=dt*D.visualRate;if(age>=4500){age=0;cycle();}var moving=false;mode.views.forEach(function(v){if(v.mode==='full')moving=v.update(now,dt*D.visualRate)||moving;});return true;};D.frames.add(mode.frame);
    ['keydown','pointerdown','wheel','pointermove','touchstart'].forEach(function(type){listen(mode,root.document,type,function(e){if(type==='keydown'){e.preventDefault();e.stopImmediatePropagation();}D.exitImmersive();},{capture:true,once:true});});C.fx.wake();
  };
  D.photo=function(){var mode=beginImmersive('Card photo mode','dev-photo'),view=D.previewCard(mode.host,D.card(),D.selectedVariant),caption=D.node('p','dev-stage-title',mode.host,'Drag outside the card to rotate the lamp · Escape exits'),lamp=53.13,drag=null;
    mode.views.push(view);view.setTiltLock(null);function light(){var angle=lamp*Math.PI/180;view.setLamp(Math.cos(angle),Math.sin(angle));caption.textContent='Lamp '+Math.round(lamp)+'° · Free card tilt · Escape exits';}
    var controls=D.node('div','dev-stage-actions',mode.host);var input=D.node('input','',controls);input.type='range';input.min=0;input.max=360;input.value=lamp;input.setAttribute('aria-label','Photo lamp angle');listen(mode,input,'input',function(){lamp=Number(input.value);light();});D.button('Exit photo',controls,D.exitImmersive);
    listen(mode,mode.host,'pointerdown',function(e){if(e.target.closest('.collectible-card,button,input'))return;drag=e.clientX;mode.host.setPointerCapture(e.pointerId);});listen(mode,mode.host,'pointermove',function(e){if(drag==null)return;lamp=(lamp+(e.clientX-drag)*.6+360)%360;drag=e.clientX;input.value=lamp;light();});listen(mode,mode.host,'pointerup',function(){drag=null;});listen(mode,mode.host,'pointercancel',function(){drag=null;});
    listen(mode,root.document,'keydown',function(e){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();D.exitImmersive();}},{capture:true});mode.frame=function(now,dt){return view.update(now,dt*D.visualRate);};D.frames.add(mode.frame);light();C.fx.wake();
  };
  D.spinRoulette=function(){if(roulette)throw new Error('Roulette is already spinning.');roulettePick=null;var sampler=C.pull.createSampler(D.pack(),{luck:D.luck}),final=sampler.draw(),elapsed=0,lastStep=-1,result='Spinning…';roulette={get label(){return result;},frame:function(now,dt){elapsed+=dt;var step=Math.floor(elapsed/(50+elapsed*.06));if(step!==lastStep){lastStep=step;var draw=elapsed>=2400?final:sampler.draw();result=C.card(draw.cardId).name+' / '+(C.variant(draw.variantId)||{name:'Normal'}).name;D.message(result);}if(C.motion.reduced||elapsed>=2400){roulettePick=final;D.frames.delete(roulette.frame);roulette=null;D.message('Selected '+C.card(final.cardId).name+' · choose Grant roulette result');D.changed();return false;}return true;}};D.frames.add(roulette.frame);C.fx.wake();};
  D.closeHandlers.add(function(){stopFrenzy('Panel closed; any reserved reveal remains recoverable');if(roulette){D.frames.delete(roulette.frame);roulette=null;}D.exitImmersive();});
  D.startups.push(function(){var group='Fun';
    D.register({id:'fun.frenzy-count',group:group,label:'Frenzy pack count',helper:'Consumes available stock; stops automatically when stock is exhausted.',type:'input',inputType:'number',min:1,max:99,get:function(){return frenzyCount;},set:function(v){if(!Number.isSafeInteger(v)||v<1||v>99)throw new Error('Choose 1–99 packs.');frenzyCount=v;}});
    D.register({id:'fun.frenzy',group:group,label:'Start pack frenzy',aliases:['montage','rapid open'],helper:'Shortened real reveals, automatic Keep, normal serials/rewards/recovery. No duplicate awards.',type:'button',run:D.frenzy});
    D.register({id:'fun.frenzy-stop',group:group,label:'Stop pack frenzy',helper:'Stop after the current reservation; Keep/Delete remain available.',type:'button',run:function(){stopFrenzy('Stopped manually');}});
    D.register({id:'fun.frenzy-result',group:group,label:'Frenzy summary',helper:'Best pull, finishes found, rarity counts and the reason the run stopped.',type:'readout',get:function(){return frenzyResult||'No frenzy completed.';}});
    D.register({id:'fun.showcase',group:group,label:'Owned-card coverflow showcase',helper:'Attract screen cycles actual owned finishes. Any input exits and restores focus.',type:'button',run:D.showcase});
    D.register({id:'fun.photo',group:group,label:'Photo mode',helper:'Selected card enlarged, free tilt, draggable lamp, Escape exit.',type:'button',run:D.photo});
    D.register({id:'fun.roulette',group:group,label:'Spin card roulette',helper:'Animated weighted selection, with reduced-motion result. It grants nothing automatically.',type:'button',run:D.spinRoulette});
    D.register({id:'fun.roulette-result',group:group,label:'Roulette result',helper:'Finish selection follows current one-slot rules.',type:'readout',get:function(){return roulette?roulette.label:roulettePick?C.card(roulettePick.cardId).name+' / '+(C.variant(roulettePick.variantId)||{name:'Normal'}).name:'No result yet.';}});
    D.register({id:'fun.roulette-grant',group:group,label:'Grant roulette result',helper:'Explicit atomic grant after the spin finishes.',type:'button',available:function(){return !!roulettePick&&!roulette;},run:function(){if(!roulettePick)throw new Error('Spin first.');D.grant([roulettePick],'Roulette result granted');roulettePick=null;}});
  });
})(window.Cardable,window);
