(function(C){
  'use strict';
  C.dev.registerCheck('inventory preferences migrate without losing owned instances',function(){var old=C.state.fresh();old.schemaVersion=1;delete old.inventoryUi;var next=C.state.migrate(old);return next.schemaVersion===C.config.storage.schemaVersion&&next.inventory.length===old.inventory.length&&next.inventoryUi.viewMode==='shelf';});
  C.dev.registerCheck('invalid inventory tags are reported',function(){return C.inventoryQuery.parse('vram:nope owned:maybe unknown:yes').errors.length===3;});
  C.dev.registerCheck('VRAM normalization preserves shared memory',function(){return C.inventoryQuery.memory({vram:{amount:1024,unit:'MB'}})===1&&C.inventoryQuery.memory({vram:{amount:null,shared:true}})===null;});
  C.dev.registerCheck('inventory preferences deduplicate collection references',function(){var ui=C.inventoryModel.normalize({favorites:['a','a'],collections:[{id:'test',name:'Test',stackKeys:['a','a']},{id:'test'}]});return ui.favorites.length===1&&ui.collections.length===1&&ui.collections[0].stackKeys.length===1;});
  C.dev.registerCheck('unknown cards cannot disclose their name in search',function(){var card=C.data.cards.find(function(c){return !c.retired;});var e={card:card,owned:false,rarity:C.rarity(card.rarity),generation:C.data.generations.find(function(g){return g.id===card.generation;})};return !C.inventoryQuery.matches(e,{key:'name',value:card.name.toLowerCase()});});
  C.dev.registerCheck('combined inventory facets and rarity sorting use registries',function(){var base=C.collection.project(C.data.cards,[],'all'),ui=C.inventoryModel.defaults();ui.sortMode='rarity-desc';var result=C.inventoryQuery.run(base,ui,'',{});return result.entries.every(function(e,i,a){return !i||a[i-1].rarity.tier>=e.rarity.tier;})&&result.shown===base.total;});
  C.dev.registerCheck('inventory windows stay bounded at the first and last of 1000 cards',function(){return [0,1,2,5,20,60,200,500,1000].every(function(n){return [0,n/2,n-1].every(function(p){var r=C.inventoryShelf.range(p,n);return r.min>=0&&r.max<n&&r.max-r.min+1<=13&&Number.isFinite(r.center);});});});
  C.dev.registerCheck('stale and unowned favorites never enter a collection result',function(){var base=C.collection.project(C.data.cards,[],'all'),ui=C.inventoryModel.defaults();ui.activeCollectionId='favorites';ui.favorites=base.entries.map(function(e){return e.card.id;}).concat(['stale']);var result=C.inventoryQuery.run(base,ui,'',{});return result.shown===0&&result.collectionCounts.favorites===0;});
  C.dev.registerCheck('schema migration preserves pending acquisition focus',function(){var state=C.state.fresh();state.inventoryUi.pendingFocusStackKey=C.stacks.key('test-card',null);return C.state.migrate(state).inventoryUi.pendingFocusStackKey===C.stacks.key('test-card',null);});
  C.dev.registerCheck('reorder Escape is claimed before sheet dismissal',function(){var event={key:'Escape'};return C.inventoryReorder.claimEscape(event,true)&&event.inventoryReorderHandled&&!C.inventoryReorder.claimEscape({key:'Enter'},true);});
})(window.Cardable);
