(function(C,root){
  'use strict';var D=C.dev,lab={quality:'high',mono:false,locked:false,x:-8,y:12,lamp:53.13,solo:'all',outlines:false},demo=null,labHost=null,evolve=0,stage=null,previous=null,playback=null,tagAge=0,tagPrint=0,stageCleanups=[],stageFocus=null;
  var phases=['idle','charging','draining','dissolving','cutting','tearing','rising','preFlip','flipping','settling','variantReveal','revealed','collecting','discarding'];
  D.field=function(host,label,value,set,options){options=options||{};var id='field-'+(++D.counter),control=C.uiKit.create({key:id,prefix:'dev-',label:label,helper:'',control:options.choices?'select':'input',choices:options.choices,inputType:options.type||'text',min:options.min,max:options.max,step:options.step},host,{get:function(){return value;},set:function(key,next){D.safe(function(){set(next);D.changed();})();},subscribe:function(){return function(){};}});control.el.classList.add('dev-input');return control.el;};
  D.cardPicker=function(host,set,selected){var input=D.field(host,'Search GPU card',selected?C.card(selected).name:'',function(v){var match=C.data.cards.find(function(c){return c.id===v||c.name.toLowerCase()===v.toLowerCase();});if(!match)throw new Error('Select a card from the catalog suggestions.');set(match.id);});var list=D.node('datalist','',host);list.id='dev-card-list-'+(++D.counter);input.setAttribute('list',list.id);C.data.cards.forEach(function(c){var o=D.node('option','',list,c.brand+' / '+(C.rarity(c.rarity)||{}).name+' / '+c.generation);o.value=c.name;});return input;};
  D.previewCard=function(host,card,variant,options){options=options||{};var wrap=D.node('div','dev-preview-local',host);if(options.quality)C.settingsSchema.graphicsKeys.forEach(function(k){wrap.setAttribute('data-'+k.replace(/[A-Z]/g,function(c){return '-'+c.toLowerCase();}),options.quality);});
    var instance=Object.assign({instanceId:'dev-preview-'+(++D.counter),cardId:card.id,variantId:variant||null,serial:C.serial.format(C.state.current.playerCode,1),pulledAt:C.clock.now(),seen:true},options.instance||{});
    var view=C.cardView.create(card,instance,Object.assign({autoFocus:false,autoStamp:false,keyboardFlip:false,owned:true,independent:true,canFlip:true},options));wrap.appendChild(view.el);view.setMode(options.lite?'lite':'full');view.wrapper=wrap;return view;
  };
  function applyDemo(){if(!demo)return;demo.setTiltLock(lab.locked?{x:lab.x,y:lab.y}:null);var angle=lab.lamp*Math.PI/180;demo.setLamp(Math.cos(angle),Math.sin(angle));demo.setColorMode(lab.mono?'mono':'color');demo.wrapper.classList.toggle('dev-lab-outlines',lab.outlines);demo.el.querySelectorAll('[data-layer]').forEach(function(el){el.style.visibility=lab.solo==='all'||lab.solo===el.dataset.layer?'':'hidden';});C.fx.wake();}
  D.rebuildDemo=function(){if(!labHost)return;if(demo){demo.destroy();demo.wrapper.remove();}demo=D.previewCard(labHost,D.card(),D.selectedVariant,{quality:lab.quality});D.demo=demo;applyDemo();};
  function closeStage(){stageCleanups.splice(0).forEach(function(fn){fn();});if(stage){C.accessibility.release(stage);}if(playback){D.frames.delete(playback.frame);playback.view.destroy();playback=null;D.playback=null;}if(stage){stage.remove();stage=null;}C.events.emit('preferences:context',{active:!!(C.preferences&&C.preferences.open)});if(previous&&!previous.destroyed){previous.setMode('full');}previous=null;if(stageFocus&&stageFocus.isConnected)stageFocus.focus();stageFocus=null;}
  D.disposePreview=closeStage;D.closeHandlers.add(closeStage);
  D.stage=function(title){closeStage();stageFocus=root.document.activeElement;previous=C.cardView.active;if(previous)previous.setMode('lite');C.events.emit('preferences:context',{active:true,preview:true});stage=D.node('section','dev-stage',root.document.body);stage.dataset.toolSurface='';stage.setAttribute('role','dialog');stage.setAttribute('aria-label',title);D.node('h2','dev-gallery-title',stage,title);var close=D.button('Close preview',stage,closeStage);close.focus();close.style.position='absolute';close.style.top='20px';close.style.left='20px';return stage;};
  D.replay=function(){var host=D.stage('Opening study · no pack spent'),pack=D.pack(),card=D.card(),wrap=D.node('div','dev-playback-scene',host),unit=C.packMarkup.unit(wrap,false,pack);unit.el.style.width='180px';unit.el.style.height='266px';unit.el.style.position='absolute';unit.el.style.inset='0';
    var foil=C.packMarkup.foil(wrap,pack);foil.style.position='absolute';foil.style.inset='0';var halves=[C.packMarkup.foil(wrap,pack),C.packMarkup.foil(wrap,pack)];halves.forEach(function(h,i){h.style.position='absolute';h.style.inset='0';h.style.clipPath='inset('+(i?'10% 0 0 0':'0 0 90% 0')+')';});
    var view=D.previewCard(wrap,card,D.selectedVariant,{controlledReveal:true}),tags=D.node('div','card-tags',host),label=D.node('p','dev-stage-title',host);var rarity=C.rarity(card.rarity),timing=C.settings.revealTiming(rarity.reveal,rarity.tier,1);
    var durations={idle:150,charging:C.config.hold.chargeMs,draining:C.config.hold.drainMs,dissolving:C.config.openingMotion.dissolveMs,cutting:800,tearing:C.config.openingMotion.tearMs+C.config.openingMotion.splitMs+C.config.openingMotion.fallMs,rising:timing.riseMs,preFlip:timing.preFlipPauseMs,flipping:timing.flipMs,settling:C.config.revealMotion.settleMs,variantReveal:D.selectedVariant?C.config.variants.revealMs:0,revealed:1800,collecting:C.config.revealMotion.collectMs,discarding:C.config.revealMotion.discardMs};
    var sequence=['charging','dissolving','cutting','tearing','rising','preFlip','flipping','settling','variantReveal','revealed','collecting'],index=0,phase='charging',elapsed=0,paused=false;
    function paint(){var duration=Math.max(1,durations[phase]),p=Math.min(1,elapsed/duration),reduced=C.motion.reduced;label.textContent=phase+' · '+Math.round(p*100)+'%'+(paused?' · paused':'');unit.el.style.display=['idle','charging','draining','dissolving'].includes(phase)?'block':'none';unit.fluid.style.transform='translateY('+(1-(phase==='draining'?1-p:p))*100+'%)';unit.el.style.opacity=phase==='dissolving'?1-p:1;foil.style.display=['dissolving','cutting'].includes(phase)?'block':'none';foil.style.opacity=phase==='dissolving'?p:1;
      halves.forEach(function(h,i){h.style.display=phase==='tearing'?'block':'none';h.style.opacity=1-p;h.style.transform=reduced?'none':'translateY('+((i?-1:1)*p*90)+'px) rotate('+(i?-1:1)*p*3+'deg)';});var show=['rising','preFlip','flipping','settling','variantReveal','revealed','collecting','discarding'].includes(phase);view.wrapper.style.visibility=show?'visible':'hidden';view.wrapper.style.opacity=['collecting','discarding'].includes(phase)?1-p:1;
      var angle=['rising','preFlip'].includes(phase)?180:phase==='flipping'?180*(1-p):0;view.setRevealFrame({pose:{y:phase==='rising'&&!reduced?(1-p)*100:0,scale:phase==='rising'&&!reduced?.88+.12*p:1,turn:0},angle:angle,frontOpacity:angle<=90?1:0,infoMs:['settling','variantReveal','revealed','collecting'].includes(phase)?(phase==='settling'?p*2400:10000):-1,shine:phase==='settling'?p:0});
      view.setVariantProgress(phase==='variantReveal'?p:['revealed','collecting','discarding'].includes(phase)?1:0,phase==='variantReveal'&&!reduced?Math.sin(p*60)*3*(1-p):0);
      var entry={card:card,rarity:rarity,owned:true,variantId:view.instance.variantId,stackKey:C.stacks.of(view.instance),isNew:true};C.cardTags.render(tags,entry,view.instance,'selected');tags.style.opacity=['variantReveal','revealed','collecting'].includes(phase)?1:0;
    }
    function seek(next){if(!phases.includes(next))return;phase=next;index=Math.max(0,sequence.indexOf(next));elapsed=0;paint();C.events.emit('dev:playbackPhase',next);C.fx.wake();}
    var controller={view:view,get phase(){return phase;},get paused(){return paused;},seek:seek,pause:function(v){paused=v;host.getAnimations().forEach(function(a){if(v)a.pause();else a.play();});paint();C.fx.wake();},step:function(){elapsed+=1000/60*D.visualRate;paint();view.update(root.performance.now(),1000/60);},skipEvolve:function(){seek('revealed');},replayTags:function(){seek('settling');},frame:function(now,dt){if(!paused){elapsed+=dt*D.visualRate;if(elapsed>=durations[phase]){if(index<sequence.length-1){index++;phase=sequence[index];elapsed=0;}else paused=true;}paint();view.update(now,dt*D.visualRate);}return !paused;}};
    playback=controller;D.playback=controller;D.frames.add(controller.frame);var actions=D.node('div','dev-stage-actions',host);D.button('Pause / resume',actions,function(){controller.pause(!controller.paused);});D.button('Step frame',actions,function(){controller.pause(true);controller.step();});D.button('Replay',actions,function(){seek('charging');controller.pause(false);});D.button('Replay tags',actions,controller.replayTags);paint();C.fx.wake();
  };
  D.tagGallery=function(host,scope){var card=D.card(),list=[['Fresh',0],['Today',3*3600000],['Old',90*86400000],['First pull',0],['First variant',0],['Low serial',0]];var grid=D.node('div','dev-tag-gallery',host);function render(){grid.replaceChildren();list.forEach(function(item,i){var entry={card:card,rarity:C.rarity(card.rarity),owned:true,variantId:D.selectedVariant,stackKey:C.stacks.key(card.id,D.selectedVariant),isNew:i===0};var instance={cardId:card.id,variantId:D.selectedVariant,serial:C.serial.format(C.state.current.playerCode,item[0]==='Low serial'?1:120),pulledAt:C.clock.now()-item[1]-tagAge*86400000,seen:i!==0};var group=D.node('div','dev-tag-case',grid);D.node('p','dev-helper',group,item[0]);C.cardTags.render(group,entry,instance,'detail');if(item[0]==='First pull'||item[0]==='First variant')D.node('span','card-tag',group,item[0]+' · preview');});['Combo','Multi-variant'].forEach(function(label){D.node('p','dev-empty',grid,label+': no compatible definitions in this catalog.');});}render();var stop=C.events.on('dev:changed',render);scope.cleanup(stop);scope.frame(function(now,dt){if(!tagPrint)return false;tagPrint=Math.max(0,tagPrint-dt*D.visualRate);grid.querySelectorAll('.card-tag').forEach(function(t,i){t.style.opacity=C.motion.reduced?1:Math.max(0,Math.min(1,1-tagPrint/1200-i*.04));});return tagPrint>0;});return grid;};
  D.openGallery=function(kind){kind=kind==='1'?'tiers':kind;if(!['cards','variants','tags','tiers'].includes(kind))kind='tiers';var host=D.stage(kind.charAt(0).toUpperCase()+kind.slice(1)+' gallery'),grid=D.node('div','dev-gallery-grid',host),views=[];
    if(kind==='tags'){var scope={cleanup:function(fn){stageCleanups.push(fn);},frame:function(fn){D.frames.add(fn);stageCleanups.push(function(){D.frames.delete(fn);});}};D.tagGallery(grid,scope);return;}
    var rows=[];if(kind==='cards')C.data.cards.filter(function(c){return !c.retired;}).forEach(function(c){rows.push({card:c,label:c.name});});
    if(kind==='variants')[{id:null,name:'Normal'}].concat(C.data.variants).forEach(function(v){rows.push({card:D.card(),variant:v.id,label:v.name});});
    if(kind==='tiers')C.data.rarities.filter(function(t){return C.finishes.registry[t.finish];}).forEach(function(t){var card=C.data.cards.find(function(c){return c.rarity===t.id&&!c.retired;});if(!card)card=Object.assign({},D.card(),{rarity:t.id,name:t.name+' GPU study'});C.finishes.previewStates(t.finish).forEach(function(state){['color','mono'].forEach(function(mode){rows.push({card:card,state:state,mode:mode,label:t.name+' / '+mode+(state?' / '+state:'')});});});});
    rows.forEach(function(row){var item=D.node('div','',grid),v=D.previewCard(item,row.card,row.variant,{lite:true,colorMode:row.mode,finishState:row.state});views.push(v);D.node('p','dev-gallery-caption',item,row.label);v.el.addEventListener('pointerenter',function(){views.forEach(function(other){other.setMode(other===v?'full':'lite');});});v.el.addEventListener('focus',function(){views.forEach(function(other){other.setMode(other===v?'full':'lite');});});});
    var frame=function(now,dt){var moving=false;views.forEach(function(v){if(v.mode==='full'&&v.visible)moving=v.update(now,dt*D.visualRate)||moving;});return moving;};D.frames.add(frame);stageCleanups.push(function(){D.frames.delete(frame);views.forEach(function(v){v.destroy();});});
  };
  D.startups.push(function(){var group='Variants lab';
    D.register({id:'lab.card',group:group,label:'Demo card picker',helper:'Search cards and generations from the live catalog.',type:'custom',render:function(host){D.cardPicker(host,function(id){D.selectedCard=id;D.selectGroup('Variants lab');},D.card().id);}});
    D.register({id:'lab.grid',group:group,label:'Finish comparison grid',helper:'All registered finishes. The current save supports one surface finish; selecting another replaces it.',type:'custom',render:function(host,scope){labHost=D.node('div','dev-lab-demo',host);D.rebuildDemo();var grid=D.node('div','dev-grid',host),views=[];[{id:null,name:'Normal'}].concat(C.data.variants).forEach(function(v){var tile=D.node('button','dev-study',grid);tile.type='button';tile.setAttribute('aria-label','Preview '+v.name);tile.classList.toggle('is-selected',D.selectedVariant===v.id);var view=D.previewCard(tile,D.card(),v.id,{quality:'high'});view.el.setAttribute('tabindex','-1');views.push(view);D.node('span','',tile,v.name);tile.addEventListener('click',function(){D.selectedVariant=D.selectedVariant===v.id?null:v.id;grid.querySelectorAll('button').forEach(function(t){t.classList.remove('is-selected');});tile.classList.toggle('is-selected',D.selectedVariant===v.id);D.rebuildDemo();D.message('One surface slot · '+(D.selectedVariant?C.variant(D.selectedVariant).name:'Normal'));D.changed();});});scope.frame(function(now,dt){var moving=false;views.forEach(function(v){if(v.visible)moving=v.update(now,dt*D.visualRate)||moving;});if(demo){if(evolve>0){evolve=Math.max(0,evolve-dt);var p=1-evolve/C.config.variants.revealMs;demo.setVariantProgress(p,C.motion.reduced?0:Math.sin(p*60)*3*(1-p));moving=evolve>0||moving;}moving=demo.update(now,dt*D.visualRate)||moving;}return moving;});scope.cleanup(function(){views.forEach(function(v){v.destroy();});if(demo){demo.destroy();demo=null;D.demo=null;}labHost=null;evolve=0;});}});
    D.register({id:'lab.resolved',group:group,label:'Resolved finish identity',helper:'Identity comes from the current stack helpers. Missing game rules are not invented.',type:'readout',get:function(){return {variantKey:D.selectedVariant||'normal',stackKey:C.stacks.key(D.card().id,D.selectedVariant),combo:'No compatible combo resolver',score:'Not defined by the catalog',surfaceSlots:1};}});
    D.register({id:'lab.lock',group:group,label:'Lock tilt',helper:'Use the fixed angles below for consistent comparisons.',type:'toggle',get:function(){return lab.locked;},set:function(v){lab.locked=v;applyDemo();}});
    ['x','y'].forEach(function(axis){D.register({id:'lab.tilt-'+axis,group:group,label:'Tilt '+axis.toUpperCase(),helper:'Fixed card angle in degrees.',type:'slider',min:-18,max:18,step:1,get:function(){return lab[axis];},set:function(v){lab[axis]=v;applyDemo();}});});
    D.register({id:'lab.lamp',group:group,label:'Lamp angle',helper:'One local light source; other cards retain their lamp.',type:'slider',min:0,max:360,step:1,get:function(){return lab.lamp;},set:function(v){lab.lamp=v;applyDemo();}});
    D.register({id:'lab.quality',group:group,label:'Demo quality',helper:'Local rendering policy, independent of saved graphics settings.',type:'input',choices:function(){return C.settingsSchema.tiers;},get:function(){return lab.quality;},set:function(v){lab.quality=v;D.rebuildDemo();}});
    D.register({id:'lab.mono',group:group,label:'Demo monochrome',helper:'Remove card-face color for material comparison.',type:'toggle',get:function(){return lab.mono;},set:function(v){lab.mono=v;applyDemo();}});
    D.register({id:'lab.solo',group:group,label:'Solo layer',helper:'Layer names are discovered from the renderer.',type:'input',choices:function(){return ['all'].concat(demo?Array.from(new Set(Array.from(demo.el.querySelectorAll('[data-layer]')).map(function(e){return e.dataset.layer;}))):[]);},get:function(){return lab.solo;},set:function(v){lab.solo=v;applyDemo();}});
    D.register({id:'lab.outlines',group:group,label:'Demo layer outlines',helper:'Outline only this comparison card.',type:'toggle',get:function(){return lab.outlines;},set:function(v){lab.outlines=v;applyDemo();}});
    D.register({id:'lab.evolve',group:group,label:'Replay evolve animation',helper:'Replay optical coating alignment without changing ownership.',type:'button',available:function(){return !!D.selectedVariant;},run:function(){evolve=C.config.variants.revealMs;if(demo)demo.setVariantProgress(0);C.fx.wake();}});
    D.register({id:'lab.grant',group:group,label:'Grant this demo card',helper:'Add one instance with the selected permanent finish.',type:'button',run:function(){D.grant([{cardId:D.card().id,variantId:D.selectedVariant}]);}});
    D.register({id:'lab.combos',group:group,label:'Combo finder',aliases:['pair','triple','missing variants'],helper:'Combo definitions appear here when added to the catalog.',type:'custom',render:function(host){var combos=C.data.combos||[];if(!combos.length){D.node('p','dev-empty',host,'No combos or multi-slot rules are defined. Current cards support one finish.');return;}combos.forEach(function(combo){var ids=combo.variantIds||combo.variants||[];D.node('p','dev-helper',host,(combo.name||combo.id)+' · '+ids.join(' + ')+' · Missing: '+ids.filter(function(id){return id!==D.selectedVariant;}).join(', '));});}});
    group='Opening and reveal';D.register({id:'opening.card',group:group,label:'Replay card picker',helper:'Choose a catalog card without granting or spending anything.',type:'custom',render:function(host){D.cardPicker(host,function(id){D.selectedCard=id;},D.card().id);D.field(host,'Finish',D.selectedVariant||'',function(v){D.selectedVariant=v||null;},{choices:[{value:'',label:'Normal'}].concat(C.data.variants.map(function(v){return {value:v.id,label:v.name};}))});}});
    D.register({id:'opening.replay',group:group,label:'Replay full opening',aliases:['cinematic','reveal'],helper:'Presentation only: no pack, serial, reward or collection writes.',type:'button',run:D.replay});
    D.register({id:'opening.phase',group:group,label:'Jump to phase',helper:'Seek any opening phase in the isolated playback.',type:'input',choices:phases,get:function(){return D.playback?D.playback.phase:'idle';},set:function(v){if(!D.playback)D.replay();D.playback.seek(v);}});
    D.register({id:'opening.pause',group:group,label:'Pause playback',helper:'Freeze presentation and CSS animation; save clocks keep their own policy.',type:'toggle',get:function(){return !!(D.playback&&D.playback.paused);},set:function(v){if(!D.playback)D.replay();D.playback.pause(v);}});
    D.register({id:'opening.step',group:group,label:'Step one frame',helper:'Advance a paused preview by 1/60 s.',type:'button',run:function(){if(!D.playback)D.replay();D.playback.pause(true);D.playback.step();}});
    D.register({id:'opening.scale',group:group,label:'Global visual time scale',helper:'0.1×–4× for the shared animation loop, CSS and Web Animations. Holds use real time.',type:'slider',min:.1,max:4,step:.1,get:function(){return D.visualRate;},set:D.setVisualRate});
    D.register({id:'opening.skip-evolve',group:group,label:'Skip evolve',helper:'Seek directly to the finished preview.',type:'button',run:function(){if(!D.playback)D.replay();D.playback.skipEvolve();}});
    D.register({id:'opening.tags-replay',group:group,label:'Replay tag printing',helper:'Replay engraving/info presentation and the tag-gallery fade.',type:'button',run:function(){tagPrint=1200;if(D.playback)D.playback.replayTags();C.fx.wake();}});
    D.register({id:'opening.tag-time',group:group,label:'Tag age travel',helper:'Age preview tags by 0–365 days without editing stored timestamps.',type:'slider',min:0,max:365,step:1,get:function(){return tagAge;},set:function(v){tagAge=v;}});
    D.register({id:'opening.tag-gallery',group:group,label:'Tag state gallery',helper:'Fresh, today, old, first-pull preview, low serial, and capability states.',type:'custom',render:D.tagGallery});
  });
})(window.Cardable,window);
