(function(C,root){
  'use strict';var D=C.dev,key='cardable.dev.snapshots',slot=0,name='Snapshot 1',raw='',importText='';
  function slots(){var list=D.read(key,[]);return Array.from({length:5},function(_,i){return list[i]||null;});}
  function write(list){D.write(key,list);D.changed();}
  function currentSlot(){return slots()[slot];}
  function requireSlot(){var s=currentSlot();if(!s)throw new Error('This snapshot slot is empty.');return s;}
  function replaceSave(save,label,workspaceBefore){var next=C.state.validate(D.clone(save),true);D.mutate(label,function(s){Object.keys(s).forEach(function(k){delete s[k];});Object.assign(s,next);},workspaceBefore);}
  function tree(value,parent,label){
    if(!value||typeof value!=='object'){D.node('p','dev-tree-value',parent,label+': '+JSON.stringify(value));return;}
    var detail=D.node('details','',parent),summary=D.node('summary','',detail,label+' · '+(Array.isArray(value)?value.length+' items':Object.keys(value).length+' fields'));var mounted=false;
    detail.addEventListener('toggle',function(){if(!detail.open||mounted)return;mounted=true;var host=D.node('div','dev-tree',detail),keys=Object.keys(value),index=0;function more(){var stop=Math.min(keys.length,index+50);while(index<stop){var k=keys[index++];tree(value[k],host,k);}if(index<keys.length){var b=D.button('Show next 50',host,function(){b.remove();more();});}}more();});
    return summary;
  }
  D.startups.push(function(){
    var group='Save';
    D.register({id:'save.sandbox',group:group,label:'Sandbox mode',helper:'First use starts fresh. Each context keeps its own save and backups.',type:'toggle',get:function(){return D.sandbox;},set:D.switchSandbox});
    D.register({id:'save.slot',group:group,label:'Snapshot slot',helper:'Five independent slots, separate from collection storage.',type:'input',choices:function(){return slots().map(function(s,i){return {value:String(i),label:(i+1)+' · '+(s?s.name:'Empty')};});},get:function(){return String(slot);},set:function(v){slot=Number(v);name=currentSlot()?currentSlot().name:'Snapshot '+(slot+1);D.selectGroup(group);}});
    D.register({id:'save.name',group:group,label:'Snapshot name',helper:'Use a name that explains the state you are testing.',type:'input',get:function(){return name;},set:function(v){name=String(v).trim().slice(0,64)||'Snapshot '+(slot+1);}});
    D.register({id:'save.snapshot',group:group,label:'Save snapshot',aliases:['backup','checkpoint'],helper:'Empty slots save instantly. Hold to replace an occupied slot.',type:'custom',render:function(host,scope){scope.action(currentSlot()?'Hold · Replace snapshot':'Save snapshot',host,function(){var list=slots();list[slot]={name:name,at:Date.now(),context:D.sandbox?'sandbox':'real',save:D.clone(C.state.current),cap:D.cap,workspace:D.workspace()};write(list);D.message('Saved '+name);D.selectGroup(group);},!!currentSlot());}});
    D.register({id:'save.load',group:group,label:'Load snapshot',helper:'Hold 3 s to replace the active collection. Undo is available.',type:'button',danger:true,available:function(){return !!currentSlot();},run:function(){var s=requireSlot();var oldCap=D.cap;D.cap=Math.max(D.cap,s.cap||4);C.config.packs.maxStored=D.cap;var priorWorkspace=D.workspace();try{D.applySnapshotWorkspace(s.workspace);replaceSave(s.save,'Snapshot loaded',priorWorkspace);}catch(e){D.applySnapshotWorkspace(priorWorkspace);D.cap=oldCap;C.config.packs.maxStored=oldCap;throw e;}}});
    D.register({id:'save.rename',group:group,label:'Rename snapshot',helper:'Apply the name above to this slot.',type:'button',available:function(){return !!currentSlot();},run:function(){var list=slots();list[slot].name=name;write(list);D.message('Snapshot renamed');D.selectGroup(group);}});
    D.register({id:'save.delete',group:group,label:'Delete snapshot',helper:'Hold 3 s to empty this slot.',type:'button',danger:true,available:function(){return !!currentSlot();},run:function(){var list=slots();list[slot]=null;write(list);D.selectGroup(group);}});
    D.register({id:'save.diff',group:group,label:'Snapshot vs current',helper:'Counts and changed top-level fields, without expanding the whole collection.',type:'readout',get:function(){var s=currentSlot();if(!s)return 'Select a populated slot.';var a=C.saveTools.summary(s.save),b=C.saveTools.summary(C.state.current);var fields=Object.keys(C.state.current).filter(function(k){return JSON.stringify(s.save[k])!==JSON.stringify(C.state.current[k]);});return {snapshot:a,current:b,changed:fields};}});
    D.register({id:'save.viewer',group:group,label:'Save viewer',helper:'Expand on demand; arrays load 50 entries at a time.',type:'custom',render:function(host){tree(C.state.current,host,'Active save');D.button('Copy JSON',host,function(){D.copy(JSON.stringify(C.state.current,null,2));});}});
    D.register({id:'save.raw',group:group,label:'Raw save editor',helper:'Schema, references, serials and size are checked before a held apply.',type:'custom',render:function(host,scope){
      var area=D.node('textarea','dev-input',host);area.setAttribute('aria-label','Raw save JSON');area.spellcheck=false;area.value=raw||JSON.stringify(C.state.current,null,2);var status=D.node('p','dev-helper',host,'No changes applied.');
      area.addEventListener('input',function(){raw=area.value;});scope.action('Validate JSON',host,function(){var candidate=C.state.validate(JSON.parse(area.value),true);if(area.value.length>C.config.polish.maxSaveBytes)throw new Error('Save exceeds the size limit');status.textContent='Valid · '+candidate.inventory.length+' instances';});
      scope.action('Hold · Apply JSON',host,function(){if(area.value.length>C.config.polish.maxSaveBytes)throw new Error('Save exceeds the size limit');replaceSave(JSON.parse(area.value),'Raw save applied');raw='';D.selectGroup(group);},true);
    }});
    D.register({id:'save.export',group:group,label:'Export save',helper:'Download the existing checked Cardable envelope as a local JSON file.',type:'button',run:function(){var text=D.sandbox?C.saveTools.exportText():JSON.stringify(C.saveTools.envelope(JSON.parse(C.state.encode(C.state.current)),Date.now()),null,2);C.saveFiles.download(text,'cardable-'+(D.sandbox?'sandbox':'save')+'-'+new Date().toISOString().slice(0,10)+'.json');D.message('Save exported');}});
    D.register({id:'save.import',group:group,label:'Import save',helper:'Choose a local export, review it, then hold to replace the active save.',type:'custom',render:function(host,scope){var file=D.node('input','dev-input',host);file.type='file';file.accept='.json,application/json';file.setAttribute('aria-label','Import Cardable save');var status=D.node('p','dev-helper',host,'No file selected.');file.addEventListener('change',D.safe(async function(){if(!file.files[0])return;importText=await file.files[0].text();var parsed=C.saveTools.parse(importText);status.textContent=JSON.stringify(C.saveTools.summary(parsed.save));}));scope.action('Hold · Import save',host,function(){if(!importText)throw new Error('Choose a save file first.');D.backup();C.saveTools.importText(importText);importText='';D.message('Save imported · Restore and Undo are available in Settings / Data.');D.selectGroup(group);},true);}});
    D.register({id:'save.real-backup',group:group,label:'Restore dev session backup',helper:'Hold to restore the real save captured before its first developer change.',type:'button',danger:true,available:function(){return !D.sandbox&&!!D.read('cardable.save.dev-session-backup',null);},run:function(){replaceSave(D.read('cardable.save.dev-session-backup',null).save,'Session backup restored');}});
  });
})(window.Cardable,window);
