(function(C,root){
  'use strict';var D=C.dev,controls=[],cleanups=[],readouts=[],activeGroup='Packs and time',tabFrame=null,shellFrame=null,driver=null;
  var prefs=D.read('cardable.dev.ui',{width:420,opacity:.96,pinned:false,stars:[],recent:[]}),focusReturn=null,paletteIndex=0,paletteMatches=[];
  var iconPaths=['M4 4h16v16H4M8 8h8v8H8','M4 6h16v14H4M8 3v6m8-6v6','M4 12h16m-7-6 6 6-6 6','M5 3h14v18H5m4-13h6m-6 4h6','M12 2 3 7v10l9 5 9-5V7ZM3 7l9 5 9-5','m9 5 10 7-10 7Z','M3 17 7 9l4 5 4-10 6 7','M4 8h16M4 12h16M4 16h16','m5 12 4 4 10-10','M12 3 3 20h18Zm0 6v5'];
  function icon(parent,index){var s=root.document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');var p=root.document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',iconPaths[index%iconPaths.length]);s.appendChild(p);parent.appendChild(s);}
  function persist(){try{D.write('cardable.dev.ui',prefs);}catch(_){}}
  function disposeTab(){controls.forEach(function(c){if(c.destroy)c.destroy();});cleanups.forEach(function(fn){fn();});controls=[];cleanups=[];readouts=[];if(tabFrame){D.frames.delete(tabFrame);tabFrame=null;}}
  D.scope=function(){return {control:function(c){controls.push(c);return c;},cleanup:function(fn){cleanups.push(fn);},frame:function(fn){D.frames.add(fn);cleanups.push(function(){D.frames.delete(fn);});},action:function(label,parent,fn,danger){var b=D.node('button','quiet-button',parent,label);b.type='button';if(danger){controls.push(C.uiKit.confirmation(b,D.safe(fn),{mode:'hold',announce:D.message}));}else b.addEventListener('click',D.safe(fn));return b;}};};
  function remember(id){prefs.recent=[id].concat(prefs.recent.filter(function(x){return x!==id;})).slice(0,12);persist();}
  function starButton(t,parent){var b=D.node('button','dev-star',parent,prefs.stars.includes(t.id)?'●':'○');b.type='button';b.setAttribute('aria-label','Star '+t.label);b.setAttribute('aria-pressed',prefs.stars.includes(t.id));b.addEventListener('click',function(){if(prefs.stars.includes(t.id))prefs.stars=prefs.stars.filter(function(x){return x!==t.id;});else prefs.stars.push(t.id);persist();b.textContent=prefs.stars.includes(t.id)?'●':'○';b.setAttribute('aria-pressed',prefs.stars.includes(t.id));});return b;}
  D.run=function(id){var t=D.tools.get(id);if(!t)return;if(!D.available(t)){D.message(t.unavailable||'Unavailable in the current catalog.');return;}remember(id);D.show(true);if(t.type!=='button'||t.danger){D.selectGroup(t.group);var row=D.ui.body.querySelector('[data-tool-id="'+t.id+'"]');if(row){row.scrollIntoView({block:'center'});var focus=row.querySelector('.is-hold-confirm')||row.querySelector('input,select,textarea,summary')||row.querySelector('button:not(.dev-star)');if(focus)focus.focus();else{row.tabIndex=-1;row.focus();}}return;}D.safe(t.run)();D.changed();};
  D.refresh=function(){readouts.forEach(function(item){try{var v=item.tool.get();item.el.textContent=typeof v==='object'?JSON.stringify(v,null,2):String(v==null?'—':v);}catch(e){item.el.textContent=e.message;}});if(D.ui.body)D.ui.body.querySelectorAll('[data-tool-id]').forEach(function(row){var tool=D.tools.get(row.dataset.toolId);if(!tool||!tool.available)return;var available=D.available(tool);row.querySelectorAll('button:not(.dev-star),input,select,textarea').forEach(function(el){el.disabled=!available;if(!available&&tool.unavailable)el.title=tool.unavailable;});});D.status();};
  D.selectGroup=function(group){if(!D.groups.has(group))return;activeGroup=group;disposeTab();D.ui.body.replaceChildren();D.ui.heading.textContent=group;D.ui.rail.querySelectorAll('button').forEach(function(b){b.classList.toggle('is-selected',b.dataset.group===group);b.setAttribute('aria-selected',b.dataset.group===group);});
    var scope=D.scope();D.groups.get(group).forEach(function(id){var t=D.tools.get(id);if(!t||t.hidden)return;
      var section=D.node('section','dev-tool',D.ui.body);section.dataset.toolId=id;
      if(t.type==='custom'){var title=D.node('div','dev-tool-title',section);D.node('h3','',title,t.label);starButton(t,title);D.node('p','dev-helper',section,t.helper||'');if(D.available(t)){var cleanup=t.render(section,scope);if(typeof cleanup==='function')scope.cleanup(cleanup);}else D.node('p','dev-empty',section,t.unavailable||'No compatible definitions in this catalog.');return;}
      if(['toggle','segment','slider'].includes(t.type)){
        var type={toggle:'switch',segment:'segments',slider:'slider'}[t.type];
        var desc={key:id,prefix:'dev-setting-',label:t.label,helper:t.helper||'',control:type,choices:typeof t.choices==='function'?t.choices():t.choices,min:t.min,max:t.max,step:t.step,format:t.format};
        var binding={get:function(){return t.get();},set:D.safe(function(key,value){remember(id);t.set(value);D.changed();}),subscribe:function(key,fn){return C.events.on('dev:changed',function(){fn(t.get());});}};
        var control=C.uiKit.create(desc,section,binding);scope.control(control);if(!D.available(t)){control.el.disabled=true;control.el.querySelectorAll('button,input').forEach(function(b){b.disabled=true;});}starButton(t,control.row);return;
      }
      var title=D.node('div','dev-tool-title',section);var label=D.node('h3','',title,t.label);label.id='dev-label-'+id;starButton(t,title);D.node('p','dev-helper',section,t.helper||'');
      if(t.type==='button'){var b=scope.action(t.danger?'Hold · '+t.label:t.label,section,function(){remember(id);t.run();D.changed();},t.danger);b.disabled=!D.available(t);if(t.hotkey)b.setAttribute('aria-keyshortcuts',t.hotkey);}
      else if(t.type==='input'){
        var descriptor={key:id,prefix:'dev-input-',label:t.label,helper:'',control:t.choices?'select':'input',choices:typeof t.choices==='function'?t.choices():t.choices,inputType:t.inputType||'text',min:t.min,max:t.max,step:t.step,format:t.format};
        var shared=C.uiKit.create(descriptor,section,{get:function(){return t.get();},set:D.safe(function(key,value){t.set(value);remember(id);D.changed();}),subscribe:function(){return function(){};}});scope.control(shared);shared.el.classList.add('dev-input');shared.el.disabled=!D.available(t);title.removeChild(label);

      }else{var output=D.node('pre','dev-readout',section);readouts.push({tool:t,el:output});}
    });
    tabFrame=function(now,dt){var moving=false;controls.forEach(function(c){moving=c.update(now,dt)||moving;});return moving;};D.frames.add(tabFrame);D.refresh();C.fx.wake();
  };
  D.rebuildRail=function(){if(!D.ui.rail)return;D.ui.rail.replaceChildren();var groups=Array.from(D.groups.keys());groups.forEach(function(group,i){var b=D.node('button','dev-tab',D.ui.rail);b.type='button';b.dataset.group=group;b.title=group+' · Alt+'+(i===9?'0':i+1);b.setAttribute('aria-label',group);b.setAttribute('role','tab');b.setAttribute('aria-selected',group===activeGroup);b.classList.toggle('is-selected',group===activeGroup);icon(b,i);b.addEventListener('click',function(){D.selectGroup(group);});});};
  D.status=function(){if(!D.ui.chip)return;D.ui.chip.textContent='DEV - '+(D.sandbox?'sandbox':'real save')+' · '+(D.fpsEnabled?(D.fps?D.fps+' FPS':'idle'):'FPS off')+' · '+C.settings.get('quality');D.ui.chip.setAttribute('aria-expanded',D.opened);};
  D.ensureDriver=function(){if((D.opened||D.immersive)&&!driver)driver=C.fx.subscribe(function(now,dt){var moving=false;D.frames.forEach(function(fn){moving=fn(now,dt/(C.fx.presentationRate||1))||moving;});return moving;},'developer tools');else if(!D.opened&&!D.immersive&&driver){driver();driver=null;}};
  D.show=function(value){if(!D.ui.panel)return;if(value===D.opened)return;D.opened=!!value;D.ensureDriver();D.ui.panel.inert=!value;D.ui.panel.setAttribute('aria-hidden',!value);D.ui.panel.classList.toggle('is-open',value);D.ui.panel.hidden=false;
    if(value){D.selectGroup(activeGroup);C.events.emit('menu:visibilityHold',{reason:'developer',active:true});}
    else{D.closePalette();D.cancelJobs();D.closeHandlers.forEach(function(fn){fn();});disposeTab();C.events.emit('menu:visibilityHold',{reason:'developer',active:false});}
    if(shellFrame)shellFrame();var spring=C.springs.create(value?1:0,{stiffness:220,damping:26});
    shellFrame=C.fx.subscribe(function(now,dt){if(C.motion.reduced)spring.reset(value?0:1);else spring.step(dt/(C.fx.presentationRate||1),value?0:1);D.ui.panel.style.transform='translate3d('+spring.value*110+'%,0,0)';if(spring.settled()){if(!value)D.ui.panel.hidden=true;var stop=shellFrame;shellFrame=null;if(stop)stop();return false;}return true;},'developer sheet');D.status();
  };
  function score(query,text){query=query.toLowerCase().replace(/\s/g,'');text=text.toLowerCase();if(!query)return 1;var index=-1,value=0;for(var i=0;i<query.length;i++){var next=text.indexOf(query[i],index+1);if(next<0)return 0;value+=next===index+1?5:1;index=next;}return value+100/(1+text.length);}
  function search(){var query=D.ui.search.value;paletteMatches=Array.from(D.tools.values()).map(function(t){var match=score(query,[t.label,t.group].concat(t.aliases||[]).join(' '));return {tool:t,score:match+(prefs.stars.includes(t.id)?1000:prefs.recent.includes(t.id)?500:0)};}).filter(function(r){return score(query,[r.tool.label,r.tool.group].concat(r.tool.aliases||[]).join(' '))>0;}).sort(function(a,b){return b.score-a.score;});paletteIndex=0;renderMatches();}
  function renderMatches(){D.ui.matches.replaceChildren();paletteMatches.forEach(function(r,i){var t=r.tool,b=D.node('button','dev-palette-result',D.ui.matches);b.type='button';b.id='dev-result-'+i;b.setAttribute('role','option');b.setAttribute('aria-selected',i===paletteIndex);b.classList.toggle('is-selected',i===paletteIndex);b.tabIndex=-1;D.node('span','',b,(prefs.stars.includes(t.id)?'● ':prefs.recent.includes(t.id)?'◦ ':'')+t.label);D.node('small','',b,t.group+(t.hotkey?' · '+t.hotkey:''));if(!D.available(t))b.classList.add('is-unavailable');b.addEventListener('click',function(){D.closePalette();D.run(t.id);});});D.ui.search.setAttribute('aria-activedescendant',paletteMatches.length?'dev-result-'+paletteIndex:'');if(!paletteMatches.length)D.node('p','dev-empty',D.ui.matches,'No matching tools');}
  D.openPalette=function(){D.show(true);focusReturn=root.document.activeElement;D.ui.palette.hidden=false;D.ui.search.value='';search();D.ui.search.focus();};
  D.closePalette=function(){if(!D.ui.palette||D.ui.palette.hidden)return;D.ui.palette.hidden=true;if(focusReturn&&focusReturn.isConnected)focusReturn.focus();};
  D.mountShell=function(){
    var panel=D.node('aside','dev-workspace glass glass--sheet',root.document.body);panel.dataset.toolSurface='';panel.setAttribute('aria-label','Developer workspace');panel.style.width=Math.min(prefs.width||420,root.innerWidth-32)+'px';panel.style.opacity=prefs.opacity;
    var resize=D.node('div','dev-resize',panel);resize.setAttribute('role','separator');resize.setAttribute('tabindex','0');resize.setAttribute('aria-label','Resize developer panel');resize.setAttribute('aria-orientation','vertical');var drag=null;
    resize.addEventListener('pointerdown',function(e){drag={x:e.clientX,width:panel.offsetWidth};resize.setPointerCapture(e.pointerId);});resize.addEventListener('pointermove',function(e){if(drag){prefs.width=Math.max(Math.min(320,root.innerWidth-32),Math.min(720,root.innerWidth-32,drag.width+drag.x-e.clientX));panel.style.width=prefs.width+'px';}});resize.addEventListener('pointerup',function(){drag=null;persist();});resize.addEventListener('pointercancel',function(){drag=null;});
    resize.addEventListener('keydown',function(e){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();prefs.width=Math.max(320,Math.min(720,root.innerWidth-32,panel.offsetWidth+(e.key==='ArrowLeft'?16:-16)));panel.style.width=prefs.width+'px';persist();}});
    var header=D.node('header','dev-header',panel),brand=D.node('div','',header);D.node('small','dev-kicker',brand,'CARDABLE / WORKSPACE');D.node('span','dev-version',brand,C.config.version);
    var toolbar=D.node('div','dev-toolbar',header);D.button('⌕',toolbar,D.openPalette).setAttribute('aria-label','Command palette');
    var pin=D.button(prefs.pinned?'●':'○',toolbar,function(){prefs.pinned=!prefs.pinned;pin.textContent=prefs.pinned?'●':'○';pin.setAttribute('aria-pressed',prefs.pinned);persist();});pin.setAttribute('aria-label','Pin developer panel');pin.setAttribute('aria-pressed',prefs.pinned);
    D.button('×',toolbar,function(){D.show(false);}).setAttribute('aria-label','Close developer panel');
    var frame=D.node('div','dev-layout',panel),rail=D.node('nav','dev-rail',frame);rail.setAttribute('role','tablist');rail.setAttribute('aria-label','Developer groups');rail.setAttribute('aria-orientation','vertical');
    var content=D.node('div','dev-content',frame),heading=D.node('h2','dev-group-title',content),body=D.node('div','dev-tools',content);var footer=D.node('footer','dev-footer',panel);
    var notice=D.node('p','dev-notice',footer,'All visual overrides are temporary.');notice.setAttribute('role','status');var actions=D.node('div','dev-footer-actions',footer);D.button('Undo',actions,D.undo);var opacity=D.node('input','',actions);opacity.type='range';opacity.min=.65;opacity.max=1;opacity.step=.01;opacity.value=prefs.opacity;opacity.setAttribute('aria-label','Panel opacity');opacity.addEventListener('input',function(){prefs.opacity=Number(opacity.value);panel.style.opacity=prefs.opacity;persist();});var jobStatus=D.node('span','dev-job',footer);
    var chip=D.node('button','dev-status glass',root.document.body);chip.type='button';chip.dataset.toolSurface='';chip.addEventListener('click',function(){D.show(!D.opened);});
    var palette=D.node('div','dev-palette-backdrop',root.document.body);palette.hidden=true;palette.dataset.toolSurface='';var dialog=D.node('section','dev-palette glass glass--sheet',palette);dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label','Developer command palette');var searchInput=D.node('input','dev-search',dialog);searchInput.type='search';searchInput.placeholder='Find a tool, group, or alias…';searchInput.setAttribute('role','combobox');searchInput.setAttribute('aria-label','Search every developer tool');searchInput.setAttribute('aria-expanded','true');searchInput.setAttribute('aria-controls','dev-matches');var matches=D.node('div','dev-matches',dialog);matches.id='dev-matches';matches.setAttribute('role','listbox');D.node('p','dev-palette-hint',dialog,'↑ ↓ Navigate   ↵ Run or focus   Esc Close');searchInput.addEventListener('input',search);
    D.ui={panel:panel,rail:rail,body:body,heading:heading,notice:notice,chip:chip,palette:palette,search:searchInput,matches:matches,jobStatus:jobStatus};D.panel=panel;D.output=D.node('pre','dev-check-output');
    D.rebuildRail();D.show(true);
    root.document.addEventListener('pointerdown',function(e){if(!palette.hidden){if(e.target===palette)D.closePalette();return;}if(D.opened&&!prefs.pinned&&!D.immersive&&!e.target.closest('[data-tool-surface]'))D.show(false);});
    root.document.addEventListener('keydown',function(e){var editable=e.target&&(e.target.isContentEditable||e.target.closest('input,textarea,select,[contenteditable]'));
      if(!palette.hidden){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();D.closePalette();}else if(e.key==='Tab'){e.preventDefault();searchInput.focus();e.stopImmediatePropagation();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();paletteIndex=(paletteIndex+(e.key==='ArrowDown'?1:-1)+paletteMatches.length)%Math.max(1,paletteMatches.length);renderMatches();var match=root.document.getElementById('dev-result-'+paletteIndex);if(match)match.scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&paletteMatches[paletteIndex]){e.preventDefault();e.stopImmediatePropagation();var id=paletteMatches[paletteIndex].tool.id;D.closePalette();D.run(id);}return;}
      if(C.preferences.open||C.inventory.active)return;
      if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();D.openPalette();return;}if(editable||e.repeat)return;
      if(e.key==='`'&&!e.altKey&&!e.ctrlKey&&!e.metaKey){e.preventDefault();D.show(!D.opened);return;}
      if(e.altKey&&!e.ctrlKey&&!e.metaKey){var digit='1234567890'.indexOf(e.key),groups=Array.from(D.groups.keys());if(digit>=0&&groups[digit]){e.preventDefault();D.show(true);D.selectGroup(groups[digit]);return;}var tool=Array.from(D.tools.values()).find(function(t){return t.hotkey&&t.hotkey.toLowerCase()==='alt+'+e.key.toLowerCase();});if(tool){e.preventDefault();D.run(tool.id);}}
    },true);
    var age=0,count=0,lastRefresh=0;C.events.on('fx:frame',function(e){if(!D.fpsEnabled&&!D.opened&&!D.immersive)return;if(D.fpsEnabled||D.opened){age+=e.realDt;count++;if(D.opened){D.gaps.push(e.realDt);if(D.gaps.length>600)D.gaps.shift();}if(age>=250){D.fps=Math.round(count*1000/age);age=count=0;D.status();}}if(D.opened&&e.now-lastRefresh>500){lastRefresh=e.now;D.refresh();}});
    C.events.on('preferences:context',function(e){if(!D.ui.chip)return;var owned=!!C.preferences.open;D.ui.chip.setAttribute('aria-disabled',owned);if(owned)D.closePalette();});C.events.on('inventory:context',function(e){D.ui.panel.inert=e.active||!D.opened;});
    C.events.on('fx:sleep',function(){D.fps=0;D.status();});C.events.on('settings:changed',D.status);C.events.on('dev:changed',D.status);
    D.ensureDriver();
    root.document.addEventListener('visibilitychange',function(){if(root.document.hidden){D.cancelJobs();if(D.disposePreview)D.disposePreview();if(D.exitImmersive)D.exitImmersive();}});
  };
})(window.Cardable,window);
