(function(C,root){
  'use strict';var D=C.dev,bulkN=1000,addResults=false,last=null,completion=null,luck={count:0,sum:0,expected:0,variance:0};
  function pct(n){return (n*100).toFixed(n<.001?5:3)+'%';}
  function bars(host,rows,total){var container=D.node('div','dev-bars',host);rows.forEach(function(r){var row=D.node('div','dev-bar',container);D.node('span','',row,r.name+' · '+r.count+' / expected '+r.expected.toFixed(2)+' · Δ '+(r.count-r.expected).toFixed(2));var bar=D.node('i','',row);bar.style.width=Math.max(0,Math.min(100,100*r.count/Math.max(1,total)))+'%';});}
  D.odds=function(){var pack=D.pack(),base=C.pull.probabilities(pack),effective=C.pull.probabilities(pack,{luck:D.luck}),card=D.card();return {pack:pack,base:base,effective:effective,card:card};};
  D.bulk=function(){
    var n=Math.round(bulkN);if(n<100||n>100000)throw new Error('Choose 100 to 100,000 packs.');var pack=D.pack(),sampler=C.pull.createSampler(pack,{luck:D.luck}),table=sampler.table,total=n*pack.cardsPerPack,index=0,tiers={},variants={},brands={},draws=addResults?[]:null;
    D.chunk('Bulk simulation',function(job){var draw=sampler.draw(),card=C.card(draw.cardId);tiers[card.rarity]=(tiers[card.rarity]||0)+1;variants[draw.variantId||'normal']=(variants[draw.variantId||'normal']||0)+1;brands[card.brand||'Unknown']=(brands[card.brand||'Unknown']||0)+1;if(draws)draws.push(draw);index++;job.progress=index/total;return index>=total;},function(){var expectedBrands={};table.cards.forEach(function(r){var b=r.card.brand||'Unknown';expectedBrands[b]=(expectedBrands[b]||0)+r.chance;});last={packs:n,pulls:total,tiers:table.tiers.map(function(r){return {name:r.tier.name,count:tiers[r.tier.id]||0,expected:r.chance*total};}),variants:table.variants.map(function(r){return {name:r.name,count:variants[r.id||'normal']||0,expected:r.chance*total};}),brands:Object.keys(expectedBrands).map(function(b){return {name:b,count:brands[b]||0,expected:expectedBrands[b]*total};}),added:false};if(draws){try{D.grant(draws,'Simulation results added');last.added=true;}catch(e){last.addError=e.message;D.message('Simulation complete; inventory unchanged: '+e.message,true);}}D.selectGroup('Pulls');D.message('Simulated '+n.toLocaleString()+' packs'+(last.added?' · results added':''));});
  };
  // Weighted coupon collection skips repeats with a geometric waiting time.
  function coupon(probabilities){var remaining=probabilities.filter(function(p){return p>0;}),sum=remaining.reduce(function(a,b){return a+b;},0),draws=0;while(remaining.length){sum=Math.min(1,Math.max(Number.EPSILON,sum));draws+=sum>=1?1:Math.floor(Math.log1p(-Math.random())/Math.log1p(-sum))+1;var needle=Math.random()*sum,i=0;while(i<remaining.length-1&&needle>=remaining[i])needle-=remaining[i++];sum-=remaining[i];remaining.splice(i,1);}return draws;}
  D.complete=function(){var pack=D.pack(),table=C.pull.probabilities(pack,{luck:D.luck}),cardP=table.cards.filter(function(r){return r.chance>0;}).map(function(r){return r.chance;}),variantP=table.variants.filter(function(r){return r.id&&r.chance>0;}).map(function(r){return r.chance;}),cards=[],variants=[],trials=0;
    if(!cardP.length||!variantP.length)throw new Error('No reachable card or finish set under these odds.');
    var reachable=new Set(table.cards.filter(function(r){return r.chance>0;}).map(function(r){return r.card.id;}));
    D.chunk('Completion estimate',function(job){cards.push(Math.ceil(coupon(cardP)/pack.cardsPerPack));variants.push(Math.ceil(coupon(variantP)/pack.cardsPerPack));trials++;job.progress=trials/2000;return trials===2000;},function(){cards.sort(function(a,b){return a-b;});variants.sort(function(a,b){return a-b;});completion={trials:2000,start:'Empty collection',pack:pack.name,luck:D.luck,cards:{median:cards[999],p90:cards[1799]},finishesOnAnyCard:{median:variants[999],p90:variants[1799]},unreachableCards:C.data.cards.filter(function(c){return !c.retired&&!reachable.has(c.id);}).map(function(c){return c.name;}),unreachableVariants:table.variants.filter(function(r){return r.id&&!r.chance;}).map(function(r){return r.name;})};D.message('Completion estimate ready');D.selectGroup('Fun');});
  };
  function cdf(x){var sign=x<0?-1:1,z=Math.abs(x)/Math.sqrt(2),t=1/(1+.3275911*z);var erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-z*z);return .5*(1+sign*erf);}
  D.trackLuck=function(event){var o=event.options;if(o.forcedTier||o.forcedCard||o.forcedVariant!==undefined)return;var table=C.pull.probabilities(event.pack,{luck:o.luck}),values=[];table.tiers.filter(function(r){return r.chance>0;}).forEach(function(t){table.variants.filter(function(v){return v.chance>0;}).forEach(function(v){var p=t.chance*v.chance;values.push({p:p,score:-Math.log2(p)});});});var mean=values.reduce(function(n,r){return n+r.p*r.score;},0),variance=values.reduce(function(n,r){return n+r.p*Math.pow(r.score-mean,2);},0);event.cards.forEach(function(i){var card=C.card(i.cardId),t=table.tiers.find(function(r){return r.tier.id===card.rarity;}),v=table.variants.find(function(r){return r.id===i.variantId;});if(!t||!v||!t.chance||!v.chance)return;luck.count++;luck.sum-=Math.log2(t.chance*v.chance);luck.expected+=mean;luck.variance+=variance;});D.changed();};
  D.luckSummary=function(){return luck.count?{eligiblePulls:luck.count,observedRarityScore:luck.sum.toFixed(2),expected:luck.expected.toFixed(2),estimatedPercentile:luck.variance?(cdf((luck.sum-luck.expected)/Math.sqrt(luck.variance))*100).toFixed(1)+'%':'Unavailable',method:'Normal approximation of accumulated rarity/finish surprise. Forced, granted and preview cards excluded.'}:'Open an unforced pack to start this session’s luck gauge.';};
  D.startups.push(function(){
    D.register({id:'pull.odds',group:'Pulls',label:'Odds explorer',helper:'Normalized pack weights, empty-tier policy, independent finish odds, and the selected card.',type:'custom',render:function(host,scope){var o=D.odds(),p=o.effective.cards.find(function(r){return r.card.id===o.card.id;}),output=D.node('pre','dev-readout',host);output.textContent='Card: '+o.card.name+'\nPer pull: '+pct(p?p.chance:0)+'\n\nTier                   Base → Effective\n'+o.base.tiers.map(function(r){var effective=o.effective.tiers.find(function(t){return t.tier.id===r.tier.id;});return r.tier.name+': '+pct(r.chance)+' → '+pct(effective.chance);}).join('\n')+'\n\nFinish                  Any card / Selected card\n'+o.effective.variants.map(function(v){return v.name+': '+pct(v.chance)+' / '+pct(v.chance*(p?p.chance:0));}).join('\n')+'\n\nCombos: '+((C.data.combos||[]).length?'Requires a compatible runtime resolver':'No combo definitions in this catalog.');D.button('Copy odds',host,function(){D.copy(output.textContent);});var last=0;scope.frame(function(now){if(now-last<500)return false;last=now;var updated=D.odds(),selected=updated.effective.cards.find(function(r){return r.card.id===updated.card.id;});output.textContent='Card: '+updated.card.name+'\nPer pull: '+pct(selected?selected.chance:0)+'\n\nTier                   Base → Effective\n'+updated.base.tiers.map(function(r){var e=updated.effective.tiers.find(function(t){return t.tier.id===r.tier.id;});return r.tier.name+': '+pct(r.chance)+' → '+pct(e.chance);}).join('\n')+'\n\nFinish / Selected card\n'+updated.effective.variants.map(function(v){return v.name+': '+pct(v.chance)+' / '+pct(v.chance*(selected?selected.chance:0));}).join('\n')+'\n\nCombos: No compatible catalog/runtime model';return false;});}});
    D.register({id:'pull.sim-count',group:'Pulls',label:'Simulation pack count',helper:'100–100,000 packs; work yields every 8 ms.',type:'input',inputType:'number',min:100,max:100000,get:function(){return bulkN;},set:function(v){bulkN=v;}});
    D.register({id:'pull.sim-add',group:'Pulls',label:'Add simulation results',helper:'Off keeps the experiment pure. On validates and commits all results atomically.',type:'toggle',get:function(){return addResults;},set:function(v){addResults=v;}});
    D.register({id:'pull.simulate',group:'Pulls',label:'Run bulk simulator',aliases:['distribution','100000','monte carlo'],helper:'Samples the same probability model as real pulls; does not spend packs.',type:'button',run:D.bulk});
    D.register({id:'pull.distribution',group:'Pulls',label:'Simulation distribution',helper:'Observed counts compared with exact expected counts under the selected odds.',type:'custom',render:function(host){if(!last){D.node('p','dev-empty',host,'Run a simulation to compare tier, finish and brand results.');return;}D.node('p','dev-helper',host,last.packs.toLocaleString()+' packs / '+last.pulls.toLocaleString()+' pulls');['tiers','variants','brands'].forEach(function(k){D.node('h3','',host,k);bars(host,last[k],last.pulls);});D.node('p','dev-helper',host,'Combos: no compatible combo probability model is registered.'+(last.addError?'\nInventory addition failed: '+last.addError:''));D.button('Copy distribution',host,function(){D.copy(last);});}});
    D.register({id:'fun.completion',group:'Fun',label:'Estimate completion',helper:'2,000 trials from empty: every reachable GPU, and every finish on any GPU.',type:'button',run:D.complete});
    D.register({id:'fun.completion-result',group:'Fun',label:'Completion estimate',helper:'Median and 90th percentile packs. Unreachable designs are reported separately.',type:'readout',get:function(){return completion||'No estimate yet.';}});
    D.register({id:'fun.luck',group:'Fun',label:'Session luck meter',helper:'An estimated percentile against the actual odds of eligible session openings.',type:'custom',render:function(host,scope){var output=D.node('pre','dev-readout',host),meter=D.node('progress','dev-luck-meter',host);meter.max=100;meter.setAttribute('aria-label','Estimated session luck percentile');function render(){var summary=D.luckSummary();output.textContent=typeof summary==='string'?summary:JSON.stringify(summary,null,2);meter.value=typeof summary==='object'?parseFloat(summary.estimatedPercentile)||50:50;}render();scope.cleanup(C.events.on('dev:changed',render));}});
    D.register({id:'fun.luck-reset',group:'Fun',label:'Reset luck meter',helper:'Starts a new measurement window without changing your collection.',type:'button',run:function(){luck={count:0,sum:0,expected:0,variance:0};D.changed();}});
    D.register({id:'debug.cancel-jobs',group:'View and debug',label:'Cancel running jobs',helper:'Cancel simulation, recording and CPU stress work immediately.',type:'button',run:D.cancelJobs});
  });
})(window.Cardable,window);
