(function(C,root){
  'use strict';
  var D=C.dev,packQuantity=1,customHours=2,randomCount=10,instanceId='',currencyAmount=500,logFilter='',recordResult=null,telemetry=null,redrawRate=0;
  function register(id,group,label,type,extra){return D.register(Object.assign({id:id,group:group,label:label,type:type},extra));}
  function integer(value,min,max){if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error('Enter a whole number from '+min+' to '+max+'.');return value;}
  function currentInstance(){var item=C.state.current.inventory.find(function(i){return i.instanceId===instanceId;});if(!item)throw new Error('Select an owned instance first.');return item;}
  function randomDraws(count){var sampler=C.pull.createSampler(D.pack(),{luck:D.luck}),draws=[];for(var i=0;i<count;i++)draws.push(sampler.draw());return draws;}
  function editInstance(label,fn){var id=currentInstance().instanceId;D.mutate(label,function(s){fn(s.inventory.find(function(i){return i.instanceId===id;}),s);});}
  function money(label,fn){var before=C.state.current.currency;D.mutate(label,function(s){var value=fn(s.currency);integer(value,0,Number.MAX_SAFE_INTEGER);s.currency=value;});var after=C.state.current.currency;C.events.emit('currency:changed',{before:before,value:after,amount:Math.abs(after-before),direction:after>=before?1:-1});}
  function percentile(values,p){if(!values.length)return null;var sorted=values.slice().sort(function(a,b){return a-b;});return sorted[Math.min(sorted.length-1,Math.ceil(sorted.length*p)-1)];}
  function frameSummary(values){if(!values.length)return 'Unavailable · no active animation frames';return {frames:values.length,averageMs:Number((values.reduce(function(a,b){return a+b;},0)/values.length).toFixed(2)),p95Ms:Number(percentile(values,.95).toFixed(2)),worstMs:Number(Math.max.apply(null,values).toFixed(2))};}
  function metrics(){var heap=root.performance.memory;return {fps:D.fps||'Idle',p95Ms:D.gaps.length?percentile(D.gaps,.95).toFixed(2):'Unavailable',domNodes:root.document.getElementsByTagName('*').length,runningAnimations:root.document.getAnimations().filter(function(a){return a.playState==='running';}).length,sharedRAF:C.fx.stats.running?1:0,otherRAF:'Unavailable',sharedSubscribers:C.fx.stats.subscribers,canvasRedrawsPerSecond:redrawRate,heapBytes:heap?heap.usedJSHeapSize:'Unavailable',quality:C.settings.get('quality')};}
  D.startups.push(function(){
    var group='Packs and time';
    register('packs.type',group,'Pack selection','input',{helper:'Preview and odds selection only. Actual openings follow the queue or Force next.',choices:function(){return C.data.packs.map(function(p){return {value:p.id,label:p.name+(p.enabled?'':' · Unavailable'),disabled:!p.enabled};});},get:function(){return D.pack().id;},set:function(v){if(!C.pack(v)||!C.pack(v).enabled)throw new Error('This pack is disabled by the catalog.');D.selectedPack=v;}});
    register('packs.force-next',group,'Force next pack type','input',{helper:'One successful opening only; cancellation keeps this override. Lifetime cadence resumes afterwards.',choices:function(){return [{value:'',label:'Follow schedule'}].concat(C.data.packs.filter(function(p){return p.enabled;}).map(function(p){return {value:p.id,label:p.name};}));},get:function(){return C.packs.forced||'';},set:function(v){C.packs.forceNext(v);}});
    register('packs.opened-count',group,'Schedule opened count','input',{helper:'Change the lifetime schedule position; historical opening statistics stay intact.',inputType:'number',min:0,max:Number.MAX_SAFE_INTEGER-100,get:function(){return C.state.current.packs.openedCount;},set:function(v){integer(v,0,Number.MAX_SAFE_INTEGER-100);D.mutate('Pack schedule changed',function(s){s.packs.openedCount=v;});}});
    register('packs.queue',group,'Upcoming pack schedule','readout',{get:function(){return C.packs.upcoming(4).map(function(p,i){return (i+1)+': '+p.name;}).join(' · ');}});
    register('packs.classic-modern-weight',group,'Classic: modern card weight','input',{helper:'Session tuning. Classic cards stay ×3 within their tier; Secret stays ×4. Zero excludes modern cards before resolving empty tiers.',inputType:'number',min:0,max:100,step:.25,get:function(){return C.config.classicPack.modernCardWeight;},set:function(v){if(!Number.isFinite(v)||v<0||v>100)throw new Error('Choose a weight from 0 to 100');C.config.classicPack.modernCardWeight=v;}});
    register('packs.quantity',group,'Pack grant quantity','input',{helper:'Added to the selected stock model, up to the active cap.',inputType:'number',min:1,max:99,get:function(){return packQuantity;},set:function(v){packQuantity=integer(v,1,99);}});
    register('packs.grant',group,'Grant selected packs','button',{aliases:['refill','stock'],helper:'Validated durable grant; current rules share one stock count across enabled packs.',run:function(){D.mutate('Packs granted',function(s){s.packs.ready=Math.min(D.cap,s.packs.ready+packQuantity);if(s.packs.ready>=D.cap)s.packs.timerStartedAt=null;});}});
    register('packs.stock',group,'Stored pack count','input',{helper:'Explicit stock edit. Over-cap real-save stock exists only during this session.',inputType:'number',min:0,max:99,get:function(){return C.state.current.packs.ready;},set:function(v){integer(v,0,D.cap);D.mutate('Stock changed',function(s){s.packs.ready=v;s.packs.timerStartedAt=v>=D.cap?null:C.clock.now();});}});
    register('packs.cap',group,'Stored pack cap','input',{helper:'1–99. Normal saves serialize with the ordinary four-pack cap.',inputType:'number',min:1,max:99,get:function(){return D.cap;},set:D.setCap});
    register('packs.pause',group,'Pause regeneration','toggle',{helper:'Freeze pack progress independently of visual playback.',get:function(){return D.paused;},set:D.pauseTimer});
    register('packs.speed',group,'Regeneration speed','segment',{helper:'Virtual timer policy; ordinary saved settings remain unchanged.',choices:['1','10','100','instant'],format:function(v){return v==='instant'?'Instant':'×'+v;},get:function(){return D.regen;},set:D.setRegen});
    [['1h',1],['8h',8],['24h',24],['7d',168]].forEach(function(skip){register('packs.skip-'+skip[0],group,'Skip +'+skip[0],'button',{helper:'Advance virtual wall time, pack regeneration and tag age.',run:function(){D.skip(skip[1]*3600000);}});});
    register('packs.custom-hours',group,'Custom skip hours','input',{helper:'Hours may include fractions. Your system clock is untouched.',inputType:'number',min:0,max:87600,step:.25,get:function(){return customHours;},set:function(v){if(!Number.isFinite(v)||v<0||v>87600)throw new Error('Choose 0–87,600 hours.');customHours=v;}});
    register('packs.skip-custom',group,'Apply custom time skip','button',{helper:'Advance by the duration entered above.',run:function(){D.skip(customHours*3600000);}});
    register('packs.instant',group,'Open next pack instantly','button',{hotkey:'Alt+O',helper:'Skip charging; reserve, reward, reveal, Keep and Delete follow the actual opening flow.',run:function(){if(D.disposePreview)D.disposePreview();if(!C.opening.openNow())throw new Error('Close other game dialogs and ensure at least one pack is ready.');}});
    group='Pulls';
    register('pull.force-tier',group,'Force tier','input',{helper:'One-shot until a successful opening commit, or sticky when enabled below.',choices:function(){return [{value:'',label:'Random tier'}].concat(C.data.rarities.map(function(t){return {value:t.id,label:t.name,disabled:!t.pullable||!C.data.cards.some(function(c){return c.rarity===t.id&&c.pullable!==false;})};}));},get:function(){return D.force.tier;},set:function(v){D.force.tier=v;D.force.card='';}});
    register('pull.force-card',group,'Force specific card','custom',{helper:'Search the live catalog. A chosen card takes precedence over the tier.',render:function(host){D.cardPicker(host,function(id){D.force.card=id;D.selectedCard=id;},D.force.card||D.card().id);D.button('Clear forced card',host,function(){D.force.card='';D.changed();});}});
    register('pull.force-variant',group,'Force finish','input',{helper:'Single permanent finish under current rules. Normal bypasses the variant roll.',choices:function(){return [{value:'random',label:'Random finish'},{value:'',label:'Normal'}].concat(C.data.variants.map(function(v){return {value:v.id,label:v.name};}));},get:function(){return D.force.variant;},set:function(v){D.force.variant=v;D.selectedVariant=v==='random'?null:v||null;}});
    register('pull.sticky',group,'Sticky forcing','toggle',{helper:'Keep forced selections after each successful opening. Off consumes them once.',get:function(){return D.force.sticky;},set:function(v){D.force.sticky=v;}});
    register('pull.force-combo',group,'Force combo / multiple finishes','button',{helper:'Requires compatible catalog definitions and a runtime multi-finish resolver.',available:function(){return typeof C.pull.forceCombination==='function'&&(C.data.combos||[]).length>0;},unavailable:'Unavailable · cards currently have one finish slot and no combo definitions.',run:function(){C.pull.forceCombination(D);}});
    register('pull.luck',group,'Luck multiplier','slider',{helper:'×1–×50: rank-scaled tier weights and finish chance capped at 100%.',min:1,max:50,step:1,get:function(){return D.luck;},set:function(v){D.luck=v;}});
    register('pull.odds-card',group,'Odds card picker','custom',{helper:'The odds explorer uses this card, selected pack and luck multiplier.',render:function(host){D.cardPicker(host,function(id){D.selectedCard=id;D.selectGroup('Pulls');},D.card().id);}});
    group='Cards and inventory';
    register('cards.selection',group,'Card grant selection','custom',{helper:'Catalog card, one permanent finish, and quantity.',render:function(host){D.cardPicker(host,function(id){D.selectedCard=id;},D.card().id);D.field(host,'Permanent finish',D.selectedVariant||'',function(v){D.selectedVariant=v||null;},{choices:[{value:'',label:'Normal'}].concat(C.data.variants.map(function(v){return {value:v.id,label:v.name};}))});D.field(host,'Quantity',D.quantity,function(v){D.quantity=integer(v,1,5000);},{type:'number',min:1,max:5000});}});
    register('cards.grant',group,'Grant selected card','button',{helper:'Fresh unique serials; clone, validate and commit the whole grant atomically.',run:function(){D.grant(Array.from({length:D.quantity},function(){return {cardId:D.card().id,variantId:D.selectedVariant};}));}});
    register('cards.every',group,'Grant every card','button',{helper:'One copy of each catalog design, including populated unpullable tiers.',run:function(){D.grant(C.data.cards.map(function(c){return {cardId:c.id,variantId:null};}),'Every catalog card granted');}});
    register('cards.tiers',group,'Grant every populated tier','button',{helper:'One representative design from each populated rarity.',run:function(){D.grant(C.data.rarities.map(function(t){return C.data.cards.find(function(c){return c.rarity===t.id;});}).filter(Boolean).map(function(c){return {cardId:c.id,variantId:null};}));}});
    register('cards.random-count',group,'Random grant count','input',{helper:'Sample the actual selected-pack odds, without spending stock.',inputType:'number',min:1,max:5000,get:function(){return randomCount;},set:function(v){randomCount=integer(v,1,5000);}});
    register('cards.random',group,'Grant random cards','button',{helper:'Uses the same tier and finish sampler as real openings; excluded from luck meter.',run:function(){D.grant(randomDraws(randomCount));}});
    register('cards.variants',group,'Grant every finish on demo card','button',{helper:'One instance per registered finish, plus Normal. No multi-finish cards are invented.',run:function(){D.grant([{cardId:D.card().id,variantId:null}].concat(C.data.variants.map(function(v){return {cardId:D.card().id,variantId:v.id};})));}});
    [100,500,1000,5000].forEach(function(n){register('cards.stress-'+n,group,'Add '+n.toLocaleString()+' stress cards','button',{helper:'Add a diverse scroll fixture with unique instance IDs and serials. Undo available.',run:function(){D.grant(randomDraws(n),'Stress fixture added');}});});
    register('cards.instance',group,'Owned instance editor','custom',{helper:'Acquisition date uses the game’s pulledAt field. Favorites apply to the whole finish stack.',render:function(host,scope){
      var items=C.state.current.inventory;if(!items.length){D.node('p','dev-empty',host,'Grant a card to edit an owned instance.');return;}if(!items.some(function(i){return i.instanceId===instanceId;}))instanceId=items[items.length-1].instanceId;
      var search=D.field(host,'Filter owned instances','',function(value){populate(value);});var select=D.node('select','dev-input',host);select.setAttribute('aria-label','Select an owned card instance');function populate(filter){select.replaceChildren();items.filter(function(i){var card=C.card(i.cardId);return [card&&card.name,i.serial,i.variantId].join(' ').toLowerCase().includes((filter||'').toLowerCase());}).slice(-1000).reverse().forEach(function(i){var o=D.node('option','',select,C.card(i.cardId).name+' / '+(C.variant(i.variantId)||{name:'Normal'}).name+' / '+i.serial);o.value=i.instanceId;});select.value=instanceId;}populate('');select.addEventListener('change',function(){instanceId=select.value;D.selectGroup(group);});search.addEventListener('input',function(){populate(search.value);});
      var item=currentInstance();D.field(host,'Acquired at (ISO date)',new Date(item.pulledAt).toISOString(),function(v){var time=Date.parse(v);if(!Number.isFinite(time)||time<0)throw new Error('Enter a valid ISO timestamp.');D.editTimestamp(item.instanceId,time);});
      D.field(host,'Serial',item.serial,function(v){editInstance('Serial changed',function(i,s){i.serial=v;var parts=v.split('-');if(parts[1]===s.playerCode)s.serialCounter=Math.max(s.serialCounter,Number(parts[2])||0);});});
      function toggle(label,get,set){scope.control(C.uiKit.create({key:'instance-'+(++D.counter),label:label,helper:'',control:'switch',prefix:'dev-edit-'},host,{get:get,set:function(k,v){D.safe(set)(v);D.changed();},subscribe:function(){return function(){};}}));}
      toggle('Seen',function(){return currentInstance().seen;},function(v){editInstance('Seen state changed',function(i){i.seen=v;});});
      toggle('Favorite finish stack',function(){return C.inventoryModel.current.favorites.includes(C.stacks.of(currentInstance()));},function(v){editInstance('Favorite changed',function(i,s){var key=C.stacks.of(i);s.inventoryUi.favorites=s.inventoryUi.favorites.filter(function(k){return k!==key;});if(v)s.inventoryUi.favorites.push(key);});});
      ['firstPull','firstVariant'].forEach(function(flag){toggle(flag+' · preview metadata',function(){return !!(D.metadata[instanceId]||{})[flag];},function(v){D.metadata[instanceId]=D.metadata[instanceId]||{};D.metadata[instanceId][flag]=v;});});
      D.node('p','dev-helper',host,'First flags are preview metadata, saved only in the sandbox workspace. Showing the newest 1,000 matching instances.');
    }});
    register('cards.delete',group,'Delete selected instance','button',{helper:'Hold 3 s to remove the instance selected in the editor.',danger:true,available:function(){return C.state.current.inventory.length>0;},run:function(){var id=currentInstance().instanceId;D.mutate('Instance deleted',function(s){s.inventory=s.inventory.filter(function(i){return i.instanceId!==id;});});instanceId='';D.selectGroup(group);}});
    register('cards.clear',group,'Clear inventory','button',{helper:'Hold 3 s to remove owned instances and their stack favorites.',danger:true,run:function(){D.mutate('Inventory cleared',function(s){s.inventory=[];s.inventoryUi.favorites=[];});instanceId='';D.selectGroup(group);}});
    [true,false].forEach(function(seen){register('cards.mark-'+seen,group,'Mark all '+(seen?'seen':'unseen'),'button',{helper:'Apply to every owned instance in the active save context.',run:function(){D.mutate('All cards marked '+(seen?'seen':'unseen'),function(s){s.inventory.forEach(function(i){i.seen=seen;});});}});});
    register('cards.currency',group,'Currency amount','input',{helper:'Non-negative safe integer for Add and Set.',inputType:'number',min:0,max:Number.MAX_SAFE_INTEGER,get:function(){return currencyAmount;},set:function(v){currencyAmount=integer(v,0,Number.MAX_SAFE_INTEGER);}});
    register('cards.currency-add',group,'Add currency','button',{helper:'Atomic transaction with normal transaction feedback.',run:function(){money('Currency added',function(v){return v+currencyAmount;});}});
    register('cards.currency-set',group,'Set currency','button',{helper:'Explicit balance edit with Undo.',run:function(){money('Currency set',function(){return currencyAmount;});}});
    register('cards.currency-x10',group,'Multiply currency ×10','button',{helper:'Safe-integer validation prevents overflow.',run:function(){money('Currency multiplied',function(v){return v*10;});}});
    register('cards.currency-billion',group,'Set currency to 1,000,000,000','button',{helper:'A deliberate durable balance edit.',run:function(){money('Currency set',function(){return 1000000000;});}});
    group='Quality and performance';
    register('quality.preset',group,'Quality override','segment',{helper:'Every registered tier, including Very Low. Saved graphics settings are untouched.',choices:C.settingsSchema.tiers,get:function(){return C.settings.get('quality');},set:D.quality});
    register('quality.motion',group,'Reduced motion override','segment',{helper:'Auto uses your system preference; On uses reduced-motion equivalents.',choices:['auto','on','off'],get:function(){return C.settings.get('motion');},set:function(v){D.setSetting('motion',v);}});
    register('quality.mono',group,'Monochrome cards','toggle',{helper:'Session-wide card color policy.',get:function(){return C.settings.get('rarityColor')==='mono';},set:function(v){D.setSetting('rarityColor',v?'mono':'color');}});
    register('quality.dots',group,'Dot grid','segment',{helper:'Session override of the shared background effect.',choices:['on','subtle','off'],get:function(){return C.settings.get('dots');},set:function(v){D.setSetting('dots',v);}});
    register('quality.glow',group,'Cursor glow','toggle',{helper:'Keep the native cursor; only the decorative halo changes.',get:function(){return C.settings.get('cursorGlow');},set:function(v){D.setSetting('cursorGlow',v);}});
    register('quality.idle',group,'Force idle / hide game UI','toggle',{helper:'Developer panel remains accessible; reset overrides restores the view.',get:function(){return root.document.body.classList.contains('dev-force-idle');},set:function(v){root.document.body.classList.toggle('dev-force-idle',v);}});
    register('quality.fps',group,'Status chip FPS','toggle',{helper:'Uses existing frame events. Does not wake a sleeping game.',get:function(){return D.fpsEnabled;},set:function(v){D.fpsEnabled=v;}});
    register('quality.hud',group,'Performance HUD','custom',{helper:'500 ms refresh. rAF counts refer to the shared loop; unavailable browser metrics say so.',render:function(host,scope){telemetry=D.node('pre','dev-readout',host);var svg=root.document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 360 72');svg.setAttribute('class','dev-frame-graph');svg.setAttribute('role','img');svg.setAttribute('aria-label','Recent frame times, 0–50 milliseconds');var line=root.document.createElementNS(svg.namespaceURI,'polyline');svg.appendChild(line);host.appendChild(svg);function refresh(){telemetry.textContent=JSON.stringify(metrics(),null,2);line.setAttribute('points',D.gaps.slice(-90).map(function(ms,i){return i*4+','+(72-Math.min(50,ms)*1.44);}).join(' '));}refresh();var last=0;scope.frame(function(now){if(now-last>=500){last=now;refresh();}return false;});scope.cleanup(function(){telemetry=null;});}});
    register('quality.record',group,'Record 10 seconds','button',{helper:'Real-time active-frame summary. Stops on close. No recording runs automatically.',run:function(){D.recording={start:root.performance.now(),frames:[],quality:C.settings.get('quality')};D.message('Recording active frames for 10 real seconds');C.fx.wake();}});
    register('quality.record-result',group,'Recording result','readout',{helper:'Average, p95 and worst active-frame time; idle intervals are identified.',get:function(){return recordResult||'No recording yet.';}});
    register('quality.copy-record',group,'Copy recording','button',{helper:'Copy the ten-second summary as JSON.',run:function(){D.copy(recordResult||'No recording yet.');}});
    register('quality.cpu',group,'CPU stress per frame','segment',{helper:'Manual only: 0 / 5 / 10 / 20 ms. Real time, independent of visual speed. Stops on close.',choices:['0','5','10','20'],format:function(v){return v==='0'?'Off':v+' ms';},get:function(){return String(D.burn);},set:function(v){D.burn=Number(v);C.fx.wake();}});
    group='View and debug';
    register('debug.filter',group,'Event filter','input',{helper:'Match event names or serialized payload text.',get:function(){return logFilter;},set:function(v){logFilter=v.toLowerCase();}});
    register('debug.pause',group,'Pause event capture','toggle',{helper:'Preserve the bounded log without adding new entries.',get:function(){return D.logPaused;},set:function(v){D.logPaused=v;}});
    register('debug.log',group,'Cardable event log','custom',{helper:'Most recent 1,000 events; visible list shows the newest 60 matching entries.',render:function(host,scope){var output=D.node('pre','dev-readout dev-log',host);function render(){output.textContent=D.logs.filter(function(e){return (e.name+' '+JSON.stringify(e.payload)).toLowerCase().includes(logFilter);}).slice(-60).map(function(e){return new Date(e.at).toISOString()+' '+e.name+' '+JSON.stringify(e.payload);}).join('\n')||'No matching events.';}render();var last=0;scope.frame(function(now){if(now-last>500){last=now;render();}return false;});D.button('Copy matching events',host,function(){D.copy(D.logs.filter(function(e){return (e.name+' '+JSON.stringify(e.payload)).toLowerCase().includes(logFilter);}));});D.button('Clear event log',host,function(){D.logs=[];render();});}});
    register('debug.errors',group,'Warnings and errors','readout',{helper:'Console warnings/errors, uncaught exceptions and unhandled rejections.',get:function(){return D.errors.length?D.errors.slice(-60):'No warnings or errors.';}});
    register('debug.copy-errors',group,'Copy warnings and errors','button',{helper:'Copy the bounded diagnostic list.',run:function(){D.copy(D.errors);}});
    [['elements','dev-outlines'],['layers','dev-layers'],['hit areas','dev-hits']].forEach(function(pair){register('debug.'+pair[1],group,'Show '+pair[0],'toggle',{helper:'Monochrome outlines; no changes to card data.',get:function(){return root.document.body.classList.contains(pair[1]);},set:function(v){root.document.body.classList.toggle(pair[1],v);}});});
    register('debug.reset',group,'Reset all dev overrides','button',{hotkey:'Alt+X',helper:'Restore clocks, speed, forcing, graphics, preview scopes and the ordinary cap.',run:D.resetOverrides});
    ['cards','variants','tags','tiers'].forEach(function(kind){register('debug.gallery-'+kind,group,kind.charAt(0).toUpperCase()+kind.slice(1)+' gallery','button',{helper:'Isolated live catalog study. gallery=1 remains the tier-study alias.',run:function(){D.openGallery(kind);}});});
    group='Checks';
    register('checks.run',group,'Run logic checks','button',{helper:'Existing checks only. Isolated cache/context; overrides suspended and restored in finally.',run:function(){
      if(C.opening.phase!=='idle'||C.inventory.active||C.preferences.open)throw new Error('Close game dialogs and finish opening before running checks.');
      var state=C.state.current,key=C.config.storage.key,recovery=C.state.recovery,encode=C.state.encode,beforeWrite=C.state.beforeWrite,savedSettings=D.clone(D.settings),offset=D.offset,cap=D.cap,regen=D.regen,paused=D.paused,clock=C.clock.now,save=C.state.save,rate=D.visualRate;
      var passed=false;if(D.disposePreview)D.disposePreview();C.timers.stop();
      try{D.settings={};C.settings.clearOverrides();D.offset=0;D.cap=4;D.regen='1';D.paused=false;C.clock.now=Date.now;C.config.packs.maxStored=4;C.config.packs.regenMs=7200000;C.state.beforeWrite=null;C.state.encode=JSON.stringify;C.fx.presentationRate=1;D.output.textContent='';
        C.state.withIsolatedCache(function(){C.config.storage.key=key+'.logic-check';var validation=D.validateData();passed=D.runChecks()&&validation.errors.length===0;});
      }finally{C.state.current=state;C.config.storage.key=key;C.state.recovery=recovery;C.state.encode=encode;C.state.beforeWrite=beforeWrite;C.state.save=save;D.settings=savedSettings;D.offset=offset;D.cap=cap;D.regen=regen;D.paused=paused;C.clock.now=clock;C.config.packs.maxStored=cap;C.config.packs.regenMs=regen==='instant'?1:7200000/(Number(regen)||1);C.fx.presentationRate=rate;Object.keys(savedSettings).forEach(function(k){C.settings.override(k,savedSettings[k]);});if(!paused)C.timers.start();C.events.emit('save:written',state);}
      D.checkSummary=passed?'● Existing logic checks passed':'○ Existing logic checks reported a failure; inspect the check output.';D.message(D.checkSummary);D.changed();
    }});
    register('checks.summary',group,'Logic check summary','readout',{helper:'A single summary line from the existing logic suite.',get:function(){return D.checkSummary||'No checks run this session.';}});
    register('checks.copy',group,'Copy check details','button',{helper:'Copy the preserved report produced by existing checks.',run:function(){D.copy(D.output.textContent);}});
  });
  var lastDraws=0,lastSample=0;
  C.events.on('fx:frame',function(e){if(!D.opened)return;if(e.now-lastSample>=1000){var draws=C.dots&&C.dots.stats?C.dots.stats.draws:0;redrawRate=Math.round((draws-lastDraws)*1000/Math.max(1,e.now-lastSample));lastDraws=draws;lastSample=e.now;}if(D.recording)D.recording.frames.push(e.realDt);});
  D.frames.add(function(now){if(D.recording&&now-D.recording.start>=10000){recordResult={durationSeconds:10,quality:D.recording.quality,activeFrames:frameSummary(D.recording.frames),note:'Existing game frame events only; sleeping intervals produce no frames.'};D.recording=null;D.message('Ten-second recording complete');D.changed();}if(D.burn){var until=root.performance.now()+D.burn;while(root.performance.now()<until){}return true;}return !!D.recording;});
})(window.Cardable,window);
