(function(C,root){
  'use strict';
  var current=null;
  function node(tag,cls,parent,text){var el=root.document.createElement(tag);el.className=cls||'';if(text!=null)el.textContent=text;if(parent)parent.appendChild(el);return el;}
  function button(text,parent,run){var b=node('button','studio-button',parent,text);b.type='button';b.addEventListener('click',run);return b;}
  function usageText(info){var text=info.count+' / 100 photos · '+(info.bytes/1048576).toFixed(1)+' MB';if(info.estimate&&Number.isFinite(info.estimate.usage)&&Number.isFinite(info.estimate.quota))text+=' · browser '+(info.estimate.usage/1048576).toFixed(1)+' / '+(info.estimate.quota/1048576).toFixed(0)+' MB';return text;}
  function close(){
    var s=current;if(!s)return;current=null;s.batchCancelled=true;if(s.folder)C.studioFiles.release(s.folder).catch(function(){});if(s.compareURLs)s.compareURLs.forEach(URL.revokeObjectURL);s.revision++;s.refreshRevision++;s.urls.forEach(URL.revokeObjectURL);if(s.previewURL)URL.revokeObjectURL(s.previewURL);s.off.forEach(function(off){off();});C.accessibility.release(s.el);s.el.remove();root.document.body.classList.remove('studio-album-active');s.hidden.forEach(function(r){if(r.el.isConnected){r.el.inert=r.inert;r.el.style.visibility=r.visibility;}});s.releaseScope();s.releaseMenu();if(s.timers)C.timers.start();if(s.focus&&s.focus.isConnected)s.focus.focus({preventScroll:true});C.events.emit('studio:albumContext',{active:false});C.fx.wake();
  }
  async function selected(s,id){
    var revision=++s.revision;s.preview.replaceChildren();if(s.previewURL){URL.revokeObjectURL(s.previewURL);s.previewURL=null;}if(s.compareURLs){s.compareURLs.forEach(URL.revokeObjectURL);s.compareURLs=[];}
    try{var photo=await C.studioAlbum.get(id);if(current!==s||revision!==s.revision)return;if(!photo||!(photo.blob instanceof root.Blob)){s.notice.textContent='This photo was removed.';return;}
      s.selectedId=id;var img=node('img','studio-album-photo',s.preview);img.alt=photo.name;s.previewURL=URL.createObjectURL(photo.blob);img.src=s.previewURL;
      node('p','studio-copy',s.preview,photo.w+' × '+photo.h+' · '+new Date(photo.createdAt).toLocaleString());
      var row=node('label','studio-field',s.preview);node('span','',row,'Photo name');var name=node('input','',row);name.type='text';name.value=photo.name;name.maxLength=60;name.setAttribute('aria-label','Photo name');
      async function action(run){try{await run();}catch(error){if(current===s)s.notice.textContent=error.message;}}
      var tagRow=node('label','studio-field',s.preview);node('span','',tagRow,'Tags · comma separated');var tags=node('input','',tagRow);tags.value=(photo.tags||[]).join(', ');tags.maxLength=200;tags.setAttribute('aria-label','Photo tags');
      var actions=node('div','studio-presets-row',s.preview);
      button('Save tags',actions,function(){action(async function(){await C.studioAlbum.tags(photo.id,tags.value.split(','));if(current===s){s.notice.textContent='Tags saved.';C.events.emit('studio:albumChanged');await refresh(s,photo.id);}});});
      button('Rename',actions,function(){action(async function(){await C.studioAlbum.rename(photo.id,name.value);if(current===s){s.notice.textContent='Photo renamed.';C.events.emit('studio:albumChanged');await refresh(s,photo.id);}});});
      button('Download',actions,function(){action(function(){return C.studioPhoto.download(photo);});});
      button('Copy image',actions,function(){C.studioPhoto.copy(photo).then(function(){if(current===s)s.notice.textContent='Image copied.';},function(error){if(current===s)s.notice.textContent=error.message+' Download the photo instead.';});}).disabled=!C.studioPhoto.clipboard;
      var owned=C.state.current.inventory.some(function(i){return i.instanceId===photo.instanceId&&i.cardId===photo.cardId;});
      button('Reopen scene',actions,function(){if(!owned)return;close();C.studio.reopenPhoto(photo);}).disabled=!owned;
      if(!owned)node('p','studio-copy',s.preview,'This serial is no longer in your collection. Its photo remains available.');
      button('Delete photo',actions,function(){action(async function(){s.revision++;await C.studioAlbum.remove(photo.id);if(current===s){s.preview.replaceChildren();s.selectedId=null;s.notice.textContent='Photo deleted.';C.events.emit('studio:albumChanged');await refresh(s);}});});
    }catch(error){if(current===s)s.notice.textContent=error.message;}
  }
  function paint(s){
    s.urls.forEach(URL.revokeObjectURL);s.urls=[];s.grid.replaceChildren();s.strip.replaceChildren();var query=s.search.value.trim().toLowerCase(),list=s.list.filter(function(p){return [p.name,p.cardId].concat(p.tags||[]).join(' ').toLowerCase().indexOf(query)>=0;});
    if(!list.length)node('p','studio-copy',s.grid,s.list.length?'No photos match this search.':'Your album is empty. Capture a photo to begin.');
    function image(photo,host){var img=node('img','',host),url=photo.thumb?URL.createObjectURL(photo.thumb):'';if(url){s.urls.push(url);img.src=url;}img.alt='';img.loading='lazy';}
    list.forEach(function(photo){var tile=node('div','studio-album-tile studio-album-selectable',s.grid),b=button('',tile,function(){selected(s,photo.id);});b.setAttribute('aria-label','View photo: '+photo.name);image(photo,b);node('span','',b,photo.name);node('small','',b,(photo.tags||[]).join(' · ')||photo.w+' × '+photo.h);var check=node('input','studio-album-checkbox',tile);check.type='checkbox';check.checked=s.batch.has(photo.id);check.setAttribute('aria-label','Select photo: '+photo.name);check.addEventListener('change',function(){if(check.checked)s.batch.add(photo.id);else s.batch.delete(photo.id);s.batchText.textContent=s.batch.size+' selected';});var film=button('',s.strip,function(){selected(s,photo.id);});film.setAttribute('aria-label','View photo: '+photo.name);image(photo,film);});s.batchText.textContent=s.batch.size+' selected';
  }
  async function refresh(s,id){
    var revision=s.refreshRevision=(s.refreshRevision||0)+1;try{var list=await C.studioAlbum.list(),info=await C.studioAlbum.usage(list);if(current!==s||revision!==s.refreshRevision)return;s.list=list;s.batch.forEach(function(id){if(!list.some(function(p){return p.id===id;}))s.batch.delete(id);});s.usage.textContent=usageText(info);s.meter.max=info.estimate&&info.estimate.quota||100;s.meter.value=info.estimate&&info.estimate.usage||list.length;s.meter.setAttribute('aria-valuetext',s.usage.textContent);paint(s);if(id)await selected(s,id);
    }catch(error){if(current===s)s.notice.textContent=error.message;}
  }
  async function compare(s){var ids=Array.from(s.batch);if(ids.length!==2){s.notice.textContent='Select exactly two photos to compare.';return;}var revision=++s.revision;try{var photos=await Promise.all(ids.map(C.studioAlbum.get));if(current!==s||revision!==s.revision)return;if(s.previewURL){URL.revokeObjectURL(s.previewURL);s.previewURL=null;}if(s.compareURLs)s.compareURLs.forEach(URL.revokeObjectURL);s.compareURLs=[];s.preview.replaceChildren();var pair=node('div','studio-album-compare',s.preview);photos.filter(Boolean).forEach(function(p){var figure=node('figure','',pair),img=node('img','',figure),url=URL.createObjectURL(p.blob);s.compareURLs.push(url);img.src=url;img.alt=p.name;node('figcaption','studio-copy',figure,p.name+' · '+p.w+' × '+p.h);});s.notice.textContent='Comparing two photos.';}catch(e){if(current===s)s.notice.textContent=e.message;}}
  async function batch(s,all,folder){
    if(s.batchBusy)return;var ids=all?s.list.map(function(p){return p.id;}):Array.from(s.batch);if(!ids.length){s.notice.textContent='Select photos to download.';return;}s.batchBusy=true;s.batchCancelled=false;s.batchCancel.hidden=false;var chosen=null;
    try{if(folder){chosen=await C.studioFiles.choose();if(!chosen)return;s.folder=chosen;}for(var i=0;i<ids.length;i++){if(current!==s||s.batchCancelled)break;var photo=await C.studioAlbum.get(ids[i]);if(current!==s||s.batchCancelled)break;if(!photo)continue;s.notice.textContent='Saving '+(i+1)+' / '+ids.length;if(chosen)await C.studioFiles.write(chosen,photo.blob,String(i+1).padStart(3,'0')+'-'+photo.name+'-'+photo.id.slice(0,8));else if(!await C.studioPhoto.download(photo))break;}if(current===s)s.notice.textContent=s.batchCancelled?'Batch export stopped. Completed files remain in the folder.':'Batch export finished.';}catch(e){if(current===s)s.notice.textContent=e.message;}finally{await C.studioFiles.release(chosen).catch(function(){});s.folder=null;s.batchBusy=false;if(current===s)s.batchCancel.hidden=true;}
  }
  C.studioAlbumUI={get active(){return !!current;},usageText:usageText,close:close,
    open:async function(id){
      if(current){if(id)await selected(current,id);return;}if(C.studio.pending||C.preferences.open||C.opening.phase!=='idle')return;
      if(C.studioController&&C.studioController.capturing)return;
      if(C.contextMenu.open)C.contextMenu.close();if(C.inventory.toolbar)C.inventory.toolbar.close();
      var s=current={urls:[],hidden:[],off:[],revision:0,list:[],batch:new Set(),focus:root.document.activeElement};s.timers=C.timers.running;C.timers.stop();s.releaseMenu=C.menu.suspendActivity();s.releaseScope=C.fx.scope('studio-album');
      s.el=node('section','studio-album',root.document.body);s.el.setAttribute('role','dialog');s.el.setAttribute('aria-modal','true');s.el.setAttribute('aria-label','Photo album');s.el.setAttribute('data-tool-surface','album');
      var top=node('header','studio-album-top',s.el),heading=node('div','',top);node('p','studio-kicker',heading,'CARDABLE / PHOTO ALBUM');node('h1','',heading,'The collection, composed.');var exit=button('Close album',top,close);s.usage=node('p','studio-album-usage',s.el);s.meter=node('meter','studio-storage-meter',s.el);s.meter.min=0;s.meter.setAttribute('aria-label','Album storage usage');var tools=node('div','studio-album-tools',s.el);s.search=node('input','studio-album-search',tools);s.search.type='search';s.search.placeholder='Search names and tags';s.search.setAttribute('aria-label','Search album');s.search.addEventListener('input',function(){paint(s);});s.batchText=node('span','studio-copy',tools,'0 selected');button('Select all',tools,function(){s.list.forEach(function(p){s.batch.add(p.id);});paint(s);});button('Clear selection',tools,function(){s.batch.clear();paint(s);});button('Compare two',tools,function(){compare(s);});button('Download selected',tools,function(){batch(s,false,false);});button('Export all to folder',tools,function(){batch(s,true,true);}).disabled=!C.studioFiles.folders;s.batchCancel=button('Stop batch',tools,function(){s.batchCancelled=true;});s.batchCancel.hidden=true;s.notice=node('p','studio-copy',s.el);s.notice.setAttribute('role','status');var layout=node('div','studio-album-layout',s.el);s.grid=node('div','studio-album-grid',layout);s.preview=node('aside','studio-album-preview',layout);s.strip=node('nav','studio-album-filmstrip',s.el);s.strip.setAttribute('aria-label','Album filmstrip');node('p','studio-copy',s.preview,'Choose a photo to download it or reopen its scene.');
      C.viewport.layers().forEach(function(el){if(el===s.el||el.tagName==='SCRIPT')return;s.hidden.push({el:el,inert:el.inert,visibility:el.style.visibility});el.inert=true;el.style.visibility='hidden';});root.document.body.classList.add('studio-album-active');C.accessibility.trap(s.el);exit.focus({preventScroll:true});
      s.el.addEventListener('keydown',function(event){event.stopPropagation();if(event.key==='Escape'){event.preventDefault();close();}});
      ['click','contextmenu','pointerdown','pointerup','wheel','keyup'].forEach(function(name){s.el.addEventListener(name,function(event){event.stopPropagation();if(name==='contextmenu')event.preventDefault();});});
      s.off.push(C.events.on('save:willReplace',close),C.events.on('detail:reset',close));C.events.emit('studio:albumContext',{active:true});await refresh(s,id);
    }
  };
})(window.Cardable,window);
