(function(C,root){
  'use strict';
  var U=C.studioUI,S=C.studioScenes,presets={youtube:{name:'YouTube · 1080p60',w:1920,h:1080,fps:60},shorts:{name:'Shorts / Reels · 9:16',w:1080,h:1920,fps:60},square:{name:'Square · 1080',w:1080,h:1080,fps:30},loop:{name:'Loop · 1080p30',w:1920,h:1080,fps:30}};
  function frames(scene,fps){return Math.max(1,Math.ceil((scene.animation.workArea.out-scene.animation.workArea.in)/scene.animation.speed*fps-1e-8));}
  function frameTime(scene,index,fps){return Math.min(scene.animation.workArea.out,scene.animation.workArea.in+index/fps*scene.animation.speed);}
  function panel(s){
    if(!s.deliverOptions)s.deliverOptions={samples:Math.min(128,C.studioQuality.samples(s.tier)),preset:'youtube',fps:30,motionBlur:false};var o=s.deliverOptions;
    U.section(s,'Render still');U.node('p','studio-copy',s.panel,'Accumulate a frozen scene at your photo dimensions. Changing the image or leaving the studio cancels the job.');var row=U.node('label','studio-field',s.panel);U.node('span','',row,'Samples');var sel=U.node('select','studio-select',row);sel.setAttribute('aria-label','Render samples');[64,128,256,512].forEach(function(n){var opt=U.node('option','',sel,String(n));opt.value=n;opt.disabled=n>C.studioQuality.samples(s.tier);});o.samples=Math.min(o.samples,C.studioQuality.samples(s.tier));sel.value=o.samples;sel.addEventListener('change',function(){o.samples=Number(sel.value);});U.button('Render still',s.panel,function(){run(s,'still');}).disabled=s.renderer.kind==='Simple';
    U.section(s,'Clip');row=U.node('label','studio-field',s.panel);U.node('span','',row,'Delivery preset');sel=U.node('select','studio-select',row);sel.setAttribute('aria-label','Clip preset');Object.keys(presets).forEach(function(k){var opt=U.node('option','',sel,presets[k].name);opt.value=k;});sel.value=o.preset;sel.addEventListener('change',function(){o.preset=sel.value;});U.node('p','studio-copy',s.panel,'Work area · '+((s.scene.animation.workArea.out-s.scene.animation.workArea.in)/s.scene.animation.speed).toFixed(2)+' seconds. Loop uses matching first and last poses; choose Loop on Animate before capture.');U.button('Record real-time WebM',s.panel,function(){C.studioRecording.start(s,presets[o.preset]);}).disabled=!C.studioRecording.supported();U.button('Render frame-stepped WebM',s.panel,function(){run(s,'clip');}).disabled=!root.VideoEncoder||!root.VideoFrame||s.renderer.kind==='Simple';if(s.clip)U.button('Save latest clip',s.panel,function(){C.studioRecording.download(s);});
    U.section(s,'Image sequence');row=U.node('label','studio-field',s.panel);U.node('span','',row,'Sequence frame rate');sel=U.node('select','studio-select',row);sel.setAttribute('aria-label','Sequence frame rate');[24,30,60].forEach(function(n){var opt=U.node('option','',sel,n+' fps');opt.value=n;});sel.value=o.fps;sel.addEventListener('change',function(){o.fps=Number(sel.value);});row=U.node('label','studio-field',s.panel);U.node('span','',row,'Motion blur · Very High');var blur=U.node('input','',row);blur.type='checkbox';blur.checked=o.motionBlur;blur.disabled=s.tier!=='very-high'||C.motion.reduced;blur.setAttribute('aria-label','Export motion blur');blur.addEventListener('change',function(){o.motionBlur=blur.checked;});U.button('Export numbered PNGs',s.panel,function(){run(s,'sequence');}).disabled=!C.studioFiles.folders||s.renderer.kind==='Simple';if(!C.studioFiles.folders)U.node('p','studio-copy',s.panel,'Folder exports are available in the desktop app.');
  }
  function progress(s,job,title){var box=U.node('div','studio-render-progress',s.root),ring=U.node('div','studio-render-ring',box),text=U.node('p','',box,title),detail=U.node('p','studio-copy',box,'Preparing…');box.setAttribute('role','region');box.setAttribute('aria-label',title);ring.setAttribute('role','progressbar');ring.setAttribute('aria-label','Render progress');ring.setAttribute('aria-valuemin','0');ring.setAttribute('aria-valuemax','100');var cancel=U.button('Cancel',box,function(){job.cancel();});cancel.focus({preventScroll:true});return {update:function(value,message){var n=Math.round(value*100);ring.style.setProperty('--progress',n+'%');ring.textContent=n+'%';ring.setAttribute('aria-valuenow',n);detail.textContent=message;text.textContent=title;},destroy:function(){box.remove();}};}
  async function run(s,kind){
    if(s.photoBusy||s.recordJob||s.closing||!s.renderer)return;s.api.commit();s.gizmos.cancel();var job=s.photoJob=C.studioPhoto.createJob(),scene=S.parse(s.scene),start=s.lightTime,opts=Object.assign({},s.photoOptions),d=s.deliverOptions,folder=null,encoder=null,chunks=[],bytes=0,ui;
    if(kind==='clip'&&d.preset==='loop'){C.studioAnimation.loop(scene,[]);scene.director.repeat='loop';}
    scene.director.playhead=s.director.time;scene.director.preview=s.director.preview;scene.card.tilt[1]=((scene.card.tilt[1]+s.director.turn*360+180)%360+360)%360-180;C.studioPhotoPanel.lock(s,true);ui=progress(s,job,kind==='still'?'Render still':kind==='clip'?'Render clip':'Export sequence');job.keepAlive=true;
    function alive(){if(job.cancelled||s.closing||!s.root.isConnected)throw Error('Export cancelled.');}
    try{
      if(kind==='sequence'){folder=await C.studioFiles.choose();alive();if(!folder)return;}
      var video=presets[d.preset],fps=kind==='clip'?video.fps:d.fps,total=kind==='still'?1:frames(scene,fps),stem='cardable-'+String(s.view.instance.serial).replace(/[^\w-]/g,'-')+'-'+Date.now();opts.scene=scene;opts.motionBlur=d.motionBlur&&s.tier==='very-high'&&!C.motion.reduced;opts.samples=kind==='still'?d.samples:1;opts.store=kind==='still';if(kind==='clip'){opts.w=video.w;opts.h=video.h;opts.frame='none';opts.format='png';opts.raw=true;opts.store=false;var config={codec:'vp8',width:video.w,height:video.h,framerate:fps,bitrate:8000000,latencyMode:'quality'},support=await root.VideoEncoder.isConfigSupported(config);alive();if(!support.supported)throw Error('Frame-stepped VP8 encoding is unavailable. Use real-time WebM.');chunks.push(C.studioWebM.header(video.w,video.h,fps,total/fps,'vp8'));encoder=new root.VideoEncoder({output:function(chunk){var data=C.studioWebM.cluster(chunk);bytes+=data.length;if(bytes>128*1024*1024){job.cancel();return;}chunks.push(data);},error:function(error){job.encoderError=error;job.cancel();}});encoder.configure(config);}
      if(kind==='sequence'){opts.format='png';opts.samples=1;opts.store=false;}
      for(var i=0;i<total;i++){
        alive();opts.time=kind==='still'?scene.director.playhead:frameTime(scene,i,fps);opts.presentationTime=start+(kind==='still'?0:i/fps);job.progress=(function(index){return function(n,message){ui.update((index+n)/total,'Frame '+(index+1)+' / '+total+' · '+message);};})(i);
        var result=await C.studioPhoto.capture(s,opts,job);alive();
        if(kind==='still'){s.latestPhoto=result.record;ui.update(1,'Saving…');await C.studioFiles.save(result.record.blob,result.record.name);alive();await s.photoFilm.refresh();}
        else if(kind==='sequence'){await C.studioFiles.write(folder,result.record.blob,stem+'-'+String(i+1).padStart(5,'0'));}
        else {var frame=new root.VideoFrame(result.canvas,{timestamp:Math.round(i*1e6/fps),duration:Math.round(1e6/fps)});try{encoder.encode(frame,{keyFrame:i%(fps*2)===0});}finally{frame.close();}if(encoder.encodeQueueSize>=2)await encoder.flush();}
        ui.update((i+1)/total,'Frame '+(i+1)+' / '+total);
      }
      if(encoder){await encoder.flush();alive();s.clip=new root.Blob(chunks,{type:'video/webm'});await C.studioFiles.save(s.clip,stem+'-director');alive();C.events.emit('studio:clip',{cardId:s.view.card.id,instanceId:s.view.instance.instanceId,duration:total/fps,fps:fps,frames:total,bytes:s.clip.size,stepped:true,at:Date.now()});}
      if(kind==='sequence')C.events.emit('studio:render',{cardId:s.view.card.id,instanceId:s.view.instance.instanceId,kind:'sequence',frames:total,fps:fps,w:opts.w,h:opts.h,at:Date.now()});s.api.status(kind==='sequence'?'Image sequence saved.':kind==='clip'?'Frame-stepped clip ready.':'Rendered still ready in your album.');
    }catch(e){if(!s.closing)s.api.status(job.encoderError?job.encoderError.message:e.message);}
    finally{if(encoder&&encoder.state!=='closed')encoder.close();chunks.length=0;C.studioPhoto.release(job);await C.studioFiles.release(folder).catch(function(){});if(ui)ui.destroy();if(s.photoJob===job)s.photoJob=null;if(!s.closing&&s.root.isConnected){C.studioPhotoPanel.lock(s,false);s.api.select('photo');}}
  }
  C.studioDeliver={panel:panel,run:run,frames:frames,frameTime:frameTime,presets:presets};
})(window.Cardable,window);
