(function(C,root){
  'use strict';
  var U=C.studioUI,S=C.studioScenes,A=C.studioAnimation;
  function name(o){return o.name||(o.text?o.text.slice(0,24):o.id);}
  C.studioDirectorPanel=function(s){
    var ui=s.timelineState||(s.timelineState={selected:[],zoom:1,scroll:0,view:'dope',snap:true,paths:false,target:'card',property:'position',component:0,folded:{},clipboard:[]}),focused=root.document.activeElement,focus=focused&&focused.dataset.timelineFocus;
    ui.openSections=ui.openSections||{};s.panel.querySelectorAll('details.director-section').forEach(function(el){ui.openSections[el.querySelector('summary').textContent]=el.open;});s.keepTimeline=false;U.closeDirector(s);s.root.classList.add('is-director');s.panel.replaceChildren();
    var a=s.scene.animation,d=s.scene.director,r=s.director,dead=false,gesture=null,heads=[],keys=new Map(),pathUI=null;
    ui.selected=ui.selected.filter(function(id){return A.refs(s.scene,[id]).length;});
    function refresh(){if(!dead){s.api.dirty();C.studioDirectorPanel(s);}}
    function mark(el,key){el.dataset.timelineFocus=key;return el;}
    function edit(label,fn){s.timelineEditing=true;try{s.api.mutate(fn,label);r.preview=true;}finally{s.timelineEditing=false;}refresh();}
    function action(label,host,fn){return mark(U.button(label,host,fn),label);}
    function inside(host,fn){var old=s.panel;s.panel=host;try{return fn();}finally{s.panel=old;}}
    function field(host,label,type,value,min,max,step,fn,disabled){var input=inside(host,function(){return U.field(s,label,type,value,min,max,step,function(v){try{fn(v);}catch(error){s.api.status(error.message);}},disabled);});mark(input,label);input.parentElement.addEventListener('pointerdown',function(){s.timelineEditing=true;},true);input.parentElement.addEventListener('keydown',function(){s.timelineEditing=true;},true);['change','blur','pointerup','pointercancel','lostpointercapture'].forEach(function(e){input.parentElement.addEventListener(e,function(){s.api.commit();s.timelineEditing=false;});});input.addEventListener('change',refresh);return input;}
    function choice(host,label,value,options,fn,temporary){var wrap=U.node('label','studio-field',host);U.node('span','',wrap,label);var input=mark(U.node('select','studio-select',wrap),label);input.setAttribute('aria-label',label);options.forEach(function(o){var p=Array.isArray(o)?o:[o,o],option=U.node('option','',input,p[1]);option.value=p[0];});input.value=value;input.addEventListener('change',function(){if(temporary){fn(input.value);refresh();}else edit('Change '+label,function(){fn(input.value);});});return input;}
    function section(label,open){var box=U.node('details','director-section',s.panel);box.open=Object.prototype.hasOwnProperty.call(ui.openSections,label)?ui.openSections[label]:!!open;U.node('summary','',box,label);return U.node('div','director-section-body',box);}
    function snapped(time){var v=ui.snap?S.snap(time,1/a.fps):time;if(ui.snap){var candidates=a.markers.map(function(m){return m.time;}).concat(a.workArea.in,a.workArea.out,r.time);a.tracks.forEach(function(t){t.keys.forEach(function(k){if(ui.selected.indexOf(k.id)<0)candidates.push(k.time);});});var threshold=d.duration/(Math.max(600,s.directorDock.clientWidth)*ui.zoom)*7;candidates.forEach(function(t){if(Math.abs(time-t)<threshold)v=t;});}return Math.max(0,Math.min(d.duration,v));}
    function selected(){return A.refs(s.scene,ui.selected).filter(function(ref){return A.editable(s.scene,ref.track);});}
    function select(ref,add){ui.selected=add?(ui.selected.indexOf(ref.key.id)>=0?ui.selected.filter(function(id){return id!==ref.key.id;}):ui.selected.concat(ref.key.id)):[ref.key.id];ui.target=ref.track.target;ui.property=ref.track.property;r.seek(ref.key.time);}
    function key(){var shown=r.scene(),object=A.object(shown,ui.target);if(!object)return;edit('Key '+ui.property,function(){A.upsert(s.scene,ui.target,ui.property,r.time,A.baseValue(shown,object,ui.property));});}
    function remove(){if(!selected().length)return;edit('Delete selected keys',function(){a.tracks.forEach(function(t){if(A.editable(s.scene,t))t.keys=t.keys.filter(function(k){return ui.selected.indexOf(k.id)<0;});});ui.selected=[];});}
    function copy(){var refs=selected();if(!refs.length)return;var start=Math.min.apply(Math,refs.map(function(ref){return ref.key.time;}));ui.clipboard=refs.map(function(ref){return {target:ref.track.target,property:ref.track.property,key:S.clone(ref.key),offset:ref.key.time-start};});var text=JSON.stringify({cardableStudioKeys:1,keys:ui.clipboard});if(C.native&&C.native.system&&C.native.system.copyText)Promise.resolve(C.native.system.copyText(text)).catch(function(){});else if(root.navigator.clipboard)root.navigator.clipboard.writeText(text).catch(function(){});s.api.status(refs.length+' keys copied. Paste at the playhead.');}
    function paste(){if(!ui.clipboard.length)return;edit('Paste keys',function(){ui.selected=[];ui.clipboard.forEach(function(ref){if(r.time+ref.offset>d.duration||!A.object(s.scene,ref.target))return;var result=A.upsert(s.scene,ref.target,ref.property,r.time+ref.offset,ref.key.value);result.key.easing=ref.key.easing;result.key.bezier=S.clone(ref.key.bezier||[.25,.1,.25,1]);ui.selected.push(result.key.id);});});}
    U.node('p','studio-kicker',s.panel,'ANIMATE / DIRECTOR');U.node('h2','studio-panel-title',s.panel,'Shape the moment.');U.node('p','director-intro',s.panel,'Key a property, refine its curve, then cut between cameras.');
    var dock=s.directorDock=U.node('section','director-dock director2-dock',null);dock.setAttribute('aria-label','Animation timeline');s.bottom.prepend(dock);
    var transport=U.node('div','director-transport',dock),identity=U.node('div','director-timeline-identity',transport);U.icon(identity,'film');U.node('span','',identity,'Timeline');U.node('span','director-key-count',identity,A.keyCount(s.scene)+' KEYS');
    var playback=U.node('div','director-playback',transport);
    function step(sign){var times=a.tracks.flatMap(function(t){return t.keys.map(function(k){return k.time;});}).concat(s.scene.keyframes.map(function(k){return k.time;}));var next=times.filter(function(t){return sign<0?t<r.time-.001:t>r.time+.001;}).sort(function(x,y){return sign*(x-y);})[0];if(next!==undefined){r.seek(next);r.sync();}}
    action('Previous',playback,function(){step(-1);});var play=action('Preview',playback,function(){r.play();r.sync();});var time=U.node('output','director-timecode',playback);time.setAttribute('aria-label','Playhead time');action('Next',playback,function(){step(1);});
    var options=U.node('div','director-play-options',transport);choice(options,'Repeat',d.repeat,[['once','Once'],['loop','Loop'],['ping-pong','Ping-pong']],function(v){d.repeat=v;});choice(options,'Speed',a.speed,[['.25','0.25×'],['.5','0.5×'],['1','1×'],['1.5','1.5×'],['2','2×']],function(v){a.speed=Number(v);});choice(options,'FPS',a.fps,['24','30','60'],function(v){a.fps=Number(v);});
    var tools=U.node('div','director2-tools',dock),auto=action('Auto-key',tools,function(){edit('Toggle auto-key',function(){a.autoKey=!a.autoKey;});});auto.setAttribute('aria-pressed',String(a.autoKey));action('Key · K',tools,key);action('Copy',tools,copy);action('Paste',tools,paste);action('Delete',tools,remove);action('Loopable',tools,function(){edit('Match loop endpoints',function(){A.loop(s.scene,ui.selected);d.repeat='loop';});});var snap=action('Snap',tools,function(){ui.snap=!ui.snap;refresh();});snap.setAttribute('aria-pressed',String(ui.snap));['dope','graph'].forEach(function(view){var b=action(view==='dope'?'Dope sheet':'Graph',tools,function(){ui.view=view;refresh();});b.setAttribute('aria-pressed',String(ui.view===view));});var paths=action('Motion path',tools,function(){ui.paths=!ui.paths;refresh();});paths.setAttribute('aria-pressed',String(ui.paths));action('−',tools,function(){ui.zoom=Math.max(1,ui.zoom/1.5);refresh();}).setAttribute('aria-label','Zoom timeline out');action('+',tools,function(){ui.zoom=Math.min(12,ui.zoom*1.5);refresh();}).setAttribute('aria-label','Zoom timeline in');
    var scroll=U.node('div','director2-scroll',dock),content=U.node('div','director2-content',scroll);content.style.width=Math.max(600,Math.max(300,dock.parentElement.clientWidth-32)*ui.zoom)+'px';scroll.scrollLeft=ui.scroll;scroll.addEventListener('scroll',function(){ui.scroll=scroll.scrollLeft;});
    function row(label,cls){var el=U.node('div','director-track '+(cls||''),content);U.node('div','director-track-label',el,label);return U.node('div','director-track-rail',el);}
    function head(rail){heads.push(U.node('div','director2-playhead',rail));}
    var ruler=row('TIME / FRAMES','director2-ruler'),work=U.node('div','director2-workarea',ruler);work.style.left=a.workArea.in/d.duration*100+'%';work.style.width=(a.workArea.out-a.workArea.in)/d.duration*100+'%';
    for(var i=0;i<=Math.min(60,Math.ceil(d.duration*ui.zoom));i++){var t=d.duration*i/Math.min(60,Math.ceil(d.duration*ui.zoom)),tick=U.node('span','director2-tick',ruler,t.toFixed(t%1?1:0)+'s');tick.style.left=t/d.duration*100+'%';}
    var scrub=mark(U.node('input','director-scrub',ruler),'Playhead');scrub.type='range';scrub.min=0;scrub.max=d.duration;scrub.step=1/a.fps;scrub.value=r.time;scrub.setAttribute('aria-label','Timeline playhead');scrub.addEventListener('input',function(){r.seek(Number(scrub.value));r.sync();});head(ruler);
    var markerRail=row('MARKERS');a.markers.forEach(function(m){var b=action('◆ '+m.name,markerRail,function(){ui.marker=m.id;r.seek(m.time);refresh();});b.className='director2-marker';b.style.left=m.time/d.duration*100+'%';b.title=m.name+' · '+m.time.toFixed(2)+'s';b.style.setProperty('--marker-color','rgb('+m.color.map(function(v){return Math.round(v*255);}).join(',')+')');});head(markerRail);
    var shotRail=row('SHOTS');a.shots.forEach(function(shot){var b=action(shot.name||'Shot',shotRail,function(){ui.shot=shot.id;r.seek(shot.start);refresh();});b.className='director2-shot';b.style.left=shot.start/d.duration*100+'%';b.style.width=shot.duration/d.duration*100+'%';b.title=(shot.name||'Shot')+' · '+shot.transition;b.setAttribute('aria-pressed',String(ui.shot===shot.id));});head(shotRail);
    if(s.scene.keyframes.length){var legacy=U.node('div','director2-legacy',content);U.node('span','',legacy,s.scene.keyframes.length+' legacy pose keys · preserved');action('Expand into property tracks',legacy,function(){edit('Expand legacy poses',function(){A.migratePoses(s.scene);});});}
    ['Camera','Card','Lights','Props','Look','FX','Titles'].forEach(function(group){var groupRow=U.node('div','director2-group',content),groupButton=action((ui.folded[group]?'▸':'▾')+' '+group,groupRow,function(){ui.folded[group]=!ui.folded[group];refresh();});groupButton.setAttribute('aria-expanded',String(!ui.folded[group]));if(ui.folded[group])return;var tracks=a.tracks.filter(function(track){return A.group(s.scene,track.target)===group;});if(!tracks.length)U.node('span','director2-group-empty',groupRow,'Choose a property to start');tracks.forEach(function(track){var object=A.object(s.scene,track.target),rail=row((object?name(object):track.target)+' / '+track.property,'director2-property');rail.parentElement.dataset.track=track.id;var mute=action(track.enabled?'●':'○',rail.parentElement.firstChild,function(){edit('Toggle track',function(){track.enabled=!track.enabled;});});mute.setAttribute('aria-label',(track.enabled?'Mute ':'Enable ')+track.property);track.keys.forEach(function(k){var ref={track:track,key:k},b=action('',rail,function(e){if(b.dataset.dragged)return;select(ref,e.shiftKey||e.ctrlKey||e.metaKey);refresh();});b.className='director-key';b.dataset.key=k.id;b.style.left=k.time/d.duration*100+'%';b.setAttribute('aria-label',name(object||{id:track.target})+' '+track.property+' at '+k.time.toFixed(3)+' seconds');b.setAttribute('aria-pressed',String(ui.selected.indexOf(k.id)>=0));b.disabled=!A.editable(s.scene,track);U.node('span','director-diamond',b);keys.set(k.id,b);b.addEventListener('pointerdown',function(e){if(e.button!==0||b.disabled)return;e.preventDefault();e.stopPropagation();if(ui.selected.indexOf(k.id)<0)select(ref,e.shiftKey||e.ctrlKey||e.metaKey);s.api.commit();s.timelineEditing=true;s.api.begin('Move keyframes');gesture={kind:'keys',el:b,id:e.pointerId,x:e.clientX,original:selected().map(function(ref){return {ref:ref,time:ref.key.time};}),width:rail.clientWidth,time:k.time};b.setPointerCapture(e.pointerId);keys.forEach(function(button,id){button.setAttribute('aria-pressed',String(ui.selected.indexOf(id)>=0));});});});head(rail);rail.addEventListener('pointerdown',function(e){if(e.target!==rail||e.button!==0)return;e.preventDefault();r.pause();var rect=content.getBoundingClientRect(),box=U.node('div','director2-selection',content);gesture={kind:'box',el:rail,id:e.pointerId,x:e.clientX,y:e.clientY,rect:rect,box:box,original:e.shiftKey?ui.selected.slice():[]};rail.setPointerCapture(e.pointerId);});});});
    function move(e){if(!gesture||gesture.id!==e.pointerId)return;var g=gesture;if(g.kind==='keys'){var delta=snapped(g.time+(e.clientX-g.x)/g.width*d.duration)-g.time,lo=Math.min.apply(Math,g.original.map(function(o){return o.time;})),hi=Math.max.apply(Math,g.original.map(function(o){return o.time;}));delta=Math.max(-lo,Math.min(d.duration-hi,delta));g.original.forEach(function(o){o.ref.key.time=ui.snap?S.snap(o.time+delta,1/a.fps):o.time+delta;var b=keys.get(o.ref.key.id);if(b)b.style.left=o.ref.key.time/d.duration*100+'%';});if(Math.abs(e.clientX-g.x)>3)g.el.dataset.dragged='true';r.preview=true;s.api.dirty();}else{var left=Math.min(g.x,e.clientX),top=Math.min(g.y,e.clientY),right=Math.max(g.x,e.clientX),bottom=Math.max(g.y,e.clientY);Object.assign(g.box.style,{left:left-g.rect.left+'px',top:top-g.rect.top+'px',width:right-left+'px',height:bottom-top+'px'});ui.selected=g.original.slice();keys.forEach(function(b,id){var rect=b.getBoundingClientRect(),x=rect.left+rect.width/2,y=rect.top+rect.height/2;if(x>=left&&x<=right&&y>=top&&y<=bottom)ui.selected.push(id);b.setAttribute('aria-pressed',String(ui.selected.indexOf(id)>=0));});}}
    function finish(e){if(!gesture||e&&e.pointerId!==gesture.id)return;var g=gesture;gesture=null;if(g.box)g.box.remove();if(g.el.hasPointerCapture(g.id))g.el.releasePointerCapture(g.id);if(g.kind==='keys'){a.tracks.forEach(function(t){t.keys.sort(function(x,y){return x.time-y.time;});var unique=new Map();t.keys.forEach(function(k){unique.set(k.time,k);});t.keys=Array.from(unique.values());});if(e&&e.type==='pointercancel')s.api.cancel();else s.api.commit();}s.timelineEditing=false;if(!dead)refresh();}
    dock.addEventListener('pointermove',move);['pointerup','pointercancel','lostpointercapture'].forEach(function(event){dock.addEventListener(event,finish);});
    var pose=section('Property & pose',true),objects=S.objects(s.scene).concat(a.cameras,a.titles);if(!A.object(s.scene,ui.target))ui.target='card';var object=A.object(s.scene,ui.target),properties=A.properties(s.scene,object).filter(function(p){return A.baseValue(s.scene,object,p)!==undefined;});if(properties.indexOf(ui.property)<0)ui.property=properties[0];
    choice(pose,'Animated object',ui.target,objects.map(function(o){return [o.id,name(o)];}),function(v){ui.target=v;},true);choice(pose,'Property',ui.property,properties,function(v){ui.property=v;ui.component=0;},true);
    var shown=r.scene(),shownValue=A.baseValue(shown,A.object(shown,ui.target),ui.property);
    function poseValue(v){A.upsert(s.scene,ui.target,ui.property,r.time,v);r.preview=true;}
    if(Array.isArray(shownValue))shownValue.forEach(function(v,i){field(pose,'Pose '+['X','Y','Z','W'][i],'number',v,-10000,10000,.01,function(v){var scene=r.scene(),next=S.clone(A.baseValue(scene,A.object(scene,ui.target),ui.property));next[i]=v;poseValue(next);},S.locked(s.scene,object));});else if(typeof shownValue==='boolean')field(pose,'Pose value','checkbox',shownValue,null,null,null,poseValue,S.locked(s.scene,object));else if(typeof shownValue==='string')choice(pose,'Pose side',shownValue,['front','back'],poseValue);else field(pose,'Pose value','number',shownValue,-10000,10000,.01,poseValue,S.locked(s.scene,object));
    if(ui.paths&&!a.tracks.some(function(t){return t.target===ui.target&&t.property==='position';})&&A.properties(s.scene,object).indexOf('position')>=0)action('Create editable motion path',pose,function(){edit('Sample editable motion path',function(){var poses=[];for(var i=0;i<=8;i++){var time=d.duration*i/8,shown=C.studioDirector.sample(s.scene,time,0,true),o=A.object(shown,ui.target),value=A.baseValue(shown,o,'position');if(value)poses.push({time:time,value:value});}poses.forEach(function(p){A.upsert(s.scene,ui.target,'position',p.time,p.value);});if(ui.target==='camera'||a.cameras.some(function(c){return c.id===ui.target;})){a.tracks.forEach(function(t){if(t.target===ui.target&&['rotation','yaw','pitch','distance'].indexOf(t.property)>=0)t.enabled=false;});var c=A.object(s.scene,ui.target);c.position=c.rotation=null;c.autoFrame=false;}ui.property='position';});});
    action('Key this property',pose,key).disabled=S.locked(s.scene,object);action('Key object pose',pose,function(){r.capture(ui.target);refresh();}).disabled=S.locked(s.scene,object);
    if(A.group(s.scene,ui.target)==='Lights')U.node('p','director-help',pose,'Light playback uses soft ramps and the active strobing profile, including speed and loop closure.');var selection=section('Selected keys',ui.selected.length>0),refs=selected();U.node('p','studio-copy',selection,refs.length+' selected · Shift-click or drag a box');if(refs.length){var first=refs[0];field(selection,'Key time','number',first.key.time,0,d.duration,1/a.fps,function(v){var lo=Math.min.apply(Math,refs.map(function(ref){return ref.key.time;})),hi=Math.max.apply(Math,refs.map(function(ref){return ref.key.time;})),delta=Math.max(-lo,Math.min(d.duration-hi,v-first.key.time));A.retime(s.scene,ui.selected,delta,1);});choice(selection,'Easing',first.key.easing,A.easings,function(v){refs.forEach(function(ref){ref.key.easing=v;});});var value=first.key.value;if(typeof value==='boolean')field(selection,'Key value','checkbox',value,null,null,null,function(v){first.key.value=v;});else if(typeof value==='string')field(selection,'Key value','text',value,null,null,null,function(v){first.key.value=v.slice(0,120);});else (Array.isArray(value)?value:[value]).forEach(function(v,i){field(selection,'Key value '+['X','Y','Z','W'][i],'number',v,-10000,10000,.01,function(v){if(Array.isArray(first.key.value))first.key.value[i]=v;else first.key.value=v;});});var wrap=U.node('label','studio-field',selection);U.node('span','',wrap,'Time scale');var scaleInput=U.node('input','',wrap);scaleInput.type='number';scaleInput.min=.1;scaleInput.max=10;scaleInput.step=.1;scaleInput.value=1;scaleInput.setAttribute('aria-label','Selected key time scale');action('Scale selected time',selection,function(){edit('Scale key timing',function(){A.retime(s.scene,ui.selected,0,Number(scaleInput.value)||1);});});}
    // The inspector tools share the same transaction and refresh boundary as keys.
    C.studioTimelineTools(s,ui,{section:section,field:field,choice:choice,action:action,edit:edit,inside:inside,refresh:refresh});
    if(ui.view==='graph')C.studioTimelineGraph(s,ui,content,edit,refresh);if(ui.paths)pathUI=C.studioMotionPath(s,ui,edit);
    U.node('p','director-help',s.panel,C.motion.reduced?'Reduced motion pauses playback. Scrub to inspect each frame.':'Space preview · K key · M marker · I/O range · Ctrl/Cmd+C/V keys · Delete selected keys');
    s.timelineUI={update:function(state){var p=state.time/d.duration*100;heads.forEach(function(h){h.style.left=p+'%';});scrub.value=state.time;var value=String(Math.floor(state.time)).padStart(2,'0')+':'+String(Math.floor(state.time%1*a.fps)).padStart(2,'0')+' / '+d.duration.toFixed(1)+'s';if(time.textContent!==value)time.textContent=value;play.textContent=state.playing?'Pause':'Preview';play.disabled=C.motion.reduced||s.renderer.kind==='Simple'||!state.hasAnimation();if(pathUI)pathUI.update();},key:function(e){if(e.target.closest('input,select,textarea,[contenteditable]'))return false;var k=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey,inTimeline=dock.contains(e.target)||s.panel.contains(e.target);if(s.photoBusy||s.recordJob)return false;if(k==='escape'&&ui.selected.length){ui.selected=[];e.preventDefault();refresh();return true;}if(ctrl&&inTimeline&&k==='c'){copy();e.preventDefault();return true;}if(ctrl&&inTimeline&&k==='v'){paste();e.preventDefault();return true;}if(ctrl&&inTimeline&&k==='a'){ui.selected=a.tracks.flatMap(function(t){return t.keys.map(function(k){return k.id;});});e.preventDefault();refresh();return true;}if(inTimeline&&(k==='delete'||k==='backspace')){remove();e.preventDefault();return true;}if(!ctrl&&k==='k'){if(r.playing)r.pause();else key();e.preventDefault();return true;}if(!ctrl&&(k==='i'||k==='o')){edit('Set work range',function(){if(k==='i')a.workArea.in=Math.min(r.time,a.workArea.out-1/a.fps);else a.workArea.out=Math.max(r.time,a.workArea.in+1/a.fps);});e.preventDefault();return true;}if(!ctrl&&k==='m'){var b=s.panel.querySelector('[data-timeline-focus="Add marker · M"]');if(b)b.click();e.preventDefault();return true;}return false;},destroy:function(){dead=true;finish();s.timelineEditing=false;s.focusKeyTarget=null;if(pathUI)pathUI.destroy();}};
    r.sync();if(s.workspace&&!s.inspecting&&!s.workspaceBuildingTimeline)s.workspace.inspected('director');if(focus){var next=Array.from(s.root.querySelectorAll('[data-timeline-focus]')).find(function(el){return el.dataset.timelineFocus===focus;});if(next&&!next.disabled)next.focus({preventScroll:true});}
  };
})(window.Cardable,window);
