(function(C){
  'use strict';
  C.studioDirectorPanel=function(s){
    var ui=C.studioUI,d=s.scene.director,r=s.director;s.panel.replaceChildren();s.timelineUI=null;ui.node('p','studio-kicker',s.panel,'DIRECTOR');ui.node('h2','studio-panel-title',s.panel,'Make the card move.');ui.node('p','studio-copy',s.panel,'Scrub to a moment. Load its pose into Camera and Lights, edit, then capture a keyframe. Space toggles only the turntable.');
    var timeline=ui.node('div','studio-timeline',s.panel),label=ui.node('label','studio-field',timeline),scrub=ui.node('input','',label);ui.node('span','',label,'Timeline');scrub.type='range';scrub.min=0;scrub.max=d.duration;scrub.step=.01;scrub.value=r.time;scrub.setAttribute('aria-label','Timeline playhead');scrub.addEventListener('input',function(){r.seek(Number(scrub.value));r.sync();});var time=ui.node('output','studio-timecode',timeline);
    var marks=ui.node('div','studio-keyframe-marks',timeline);s.scene.keyframes.forEach(function(f){var b=ui.button(f.time.toFixed(2)+'s '+(f.track==='camera'?'Camera':(s.scene.lights.find(function(l){return l.id===f.target;})||{}).name||f.target),marks,function(){r.seek(f.time);C.studioDirectorPanel(s);});b.title='Seek to '+f.time.toFixed(2)+' seconds';});
    var actions=ui.node('div','studio-presets-row',s.panel),play=ui.button(r.playing?'Pause preview':'Preview',actions,function(){r.play();r.sync();}),turn=ui.button('Turntable',actions,function(){r.toggleTurntable();},'Turntable · Space');play.disabled=turn.disabled=C.motion.reduced||!s.renderer||s.renderer.kind==='Simple';turn.setAttribute('aria-pressed',String(r.turntable));s.timelineUI={scrub:scrub,time:time,play:play,turn:turn};
    ui.field(s,'Shot duration · seconds','range',d.duration,1,15,.5,function(v){r.pause();d.duration=v;r.time=Math.min(r.time,v);s.scene.keyframes.forEach(function(f){f.time=Math.min(f.time,v);});}).addEventListener('change',function(){C.studioDirectorPanel(s);});
    ui.select(s,'Repeat',d.repeat,[['once','Once'],['loop','Loop'],['ping-pong','Ping-pong']],function(v){d.repeat=v;});ui.field(s,'Title card','checkbox',d.title,null,null,null,function(v){d.title=v;});
    ui.button('Load pose for editing',s.panel,function(){r.editPose();});var target=s.directorTarget&&s.scene.lights.some(function(l){return l.id===s.directorTarget;})?s.directorTarget:'camera';s.directorTarget=target;ui.select(s,'Keyframe track',target,[['camera','Camera']].concat(s.scene.lights.map(function(l){return [l.id,l.name];})),function(v){s.directorTarget=v;C.studioDirectorPanel(s);});ui.button('Capture keyframe',s.panel,function(){r.capture(s.directorTarget||'camera');});
    ui.section(s,'Keyframes · '+s.scene.keyframes.length+' / 96');if(!s.scene.keyframes.length)ui.node('p','studio-copy',s.panel,'No keyframes yet. Auto-director provides an editable starting shot.');
    s.scene.keyframes.forEach(function(f){var row=ui.node('div','studio-keyframe',s.panel),old=s.panel;s.panel=row;ui.node('p','studio-copy',row,(f.track==='camera'?'Camera':f.target)+' · '+f.time.toFixed(2)+' s');ui.field(s,'Time · seconds','number',f.time,0,d.duration,.05,function(v){f.time=Math.max(0,Math.min(d.duration,v));r.pause();});ui.select(s,'Easing',f.easing,[['linear','Linear'],['ease-in','Ease in'],['ease-out','Ease out'],['ease-in-out','Ease in / out']],function(v){r.pause();f.easing=v;});ui.button('Delete keyframe',row,function(){s.api.mutate(function(){s.scene.keyframes=s.scene.keyframes.filter(function(v){return v.id!==f.id;});});C.studioDirectorPanel(s);});s.panel=old;});
    ui.section(s,'Auto-director');ui.select(s,'Director light rig',s.directorRig||'Studio',C.studioPresets.rigs,function(v){s.directorRig=v;});ui.button('Build cinematic orbit',s.panel,function(){r.auto(s.directorRig||'Studio');});ui.node('p','studio-copy',s.panel,C.motion.reduced?'Reduced motion keeps playback and animated lights off. Scrubbing selects still frames.':'Light keyframes use soft ramps. Closely spaced light keys merge for Safe / Full playback.');
    C.studioRecording.controls(s);r.sync();
  };
})(window.Cardable);
