(function (C, root) {
  'use strict';
  function svg(tag, attributes, parent) { var el = root.document.createElementNS('http://www.w3.org/2000/svg', tag); Object.keys(attributes || {}).forEach(function (key) { el.setAttribute(key, attributes[key]); }); if (parent) parent.appendChild(el); return el; }
  function matrices(s) { var r = s.viewport.getBoundingClientRect(), scene = C.studioScenes.clone(s.scene); if (scene.camera.autoFrame) C.studioCamera.frame(scene, r.width / Math.max(1, r.height)); return C.studioCamera.matrices(scene.camera, r.width / Math.max(1, r.height), scene.card); }
  function normalized(s, event) { var r = s.viewport.getBoundingClientRect(); return [(event.clientX - r.left) / r.width, (event.clientY - r.top) / r.height]; }
  function snap(value, shift, amount) { return shift ? Math.round(value / amount) * amount : value; }
  function shapePath(light, m, width, height, center) {
    if(light.scale){var model=C.studioProps.model(light.position,light.rotation,light.scale),path='';[[-.4,-.4,0],[.4,-.4,0],[.4,.4,0],[-.4,.4,0]].forEach(function(v,i){var q=C.studioCamera.project(m,C.studioCamera.transform(model,v).slice(0,3));path+=(i?'L':'M')+Math.max(-160,Math.min(160,(q.x-center.x)*width))+' '+Math.max(-160,Math.min(160,(q.y-center.y)*height));});return path+'Z';}
    if (!center.front || light.type === 'point' || light.type === 'ambient') return light.type === 'ambient' ? 'M-16 0A16 16 0 0 1 16 0M-16 4H16' : 'M-11 0A11 11 0 1 0 11 0A11 11 0 1 0-11 0';
    var d = C.studioLights.direction(light), up = Math.abs(d[1]) > .95 ? [1, 0, 0] : [0, 1, 0], right = C.studioCamera.unit([up[1] * d[2] - up[2] * d[1], up[2] * d[0] - up[0] * d[2], up[0] * d[1] - up[1] * d[0]]); up = [d[1] * right[2] - d[2] * right[1], d[2] * right[0] - d[0] * right[2], d[0] * right[1] - d[1] * right[0]];
    var angle = light.rotation[2] * Math.PI / 180, r = right.map(function (n, i) { return n * Math.cos(angle) + up[i] * Math.sin(angle); }), u = up.map(function (n, i) { return n * Math.cos(angle) - right[i] * Math.sin(angle); });
    function point(x, y, z) { var position = light.position.map(function (n, i) { return n + r[i] * x + u[i] * y + d[i] * z; }), p = C.studioCamera.project(m, position); return [Math.max(-160, Math.min(160, (p.x - center.x) * width)), Math.max(-160, Math.min(160, (p.y - center.y) * height))].join(' '); }
    if (light.type === 'spot') { var radius = Math.tan(light.angle * Math.PI / 360) * .8; return 'M0 0L' + point(-radius, 0, .8) + 'L' + point(0, radius, .8) + 'L' + point(radius, 0, .8) + 'L' + point(0, -radius, .8) + 'Z M0 0L' + point(radius, 0, .8); }
    if (light.type === 'directional') return 'M0 0L' + point(0, 0, .8) + ' M' + point(-.08, .08, .65) + 'L' + point(0, 0, .8) + 'L' + point(.08, .08, .65);
    var half = light.size / 2, h = half * (light.type === 'strip' ? .12 : .6); return 'M' + point(-half, -h, 0) + 'L' + point(half, -h, 0) + 'L' + point(half, h, 0) + 'L' + point(-half, h, 0) + 'Z';
  }
  C.studioGizmos = {
    create: function (s) { var layer = svg('svg', { 'class': 'studio-gizmos', 'aria-label': 'Scene object transform handles' }, s.viewport), drag = null, records = new Map();
      function objects(){return s.scene.lights.concat(s.scene.props);}function kind(o){return o.scale?'prop':'light';}function current(o){return objects().find(function(v){return v.id===o.id;})||o;}
      function end() { if (!drag) return; var target = drag.target, id = drag.pointerId; drag = null; if (target.hasPointerCapture(id)) target.releasePointerCapture(id); s.api.commit(); if (!s.closing && (s.selected === 'light'||s.selected==='prop')) s.api.select(s.selected, s.selectedId); }
      function handle(group, label, mode, light) { var target = svg('g', { role: 'button', tabindex: '0', 'aria-label': label + ': ' + light.name, 'data-studio-handle': mode, 'class': 'studio-gizmo-handle' }, group); svg('title', {}, target).textContent = label + ' · drag; Shift snaps; arrows adjust'; target.addEventListener('click', function (e) { e.stopPropagation(); });
        target.addEventListener('pointerdown', function (event) { event.preventDefault(); event.stopPropagation(); light = current(light); if (event.button !== 0 || light.locked || s.closing) return; s.api.select(kind(light), light.id); var m = matrices(s), p = normalized(s, event), point = C.studioCamera.plane(C.studioCamera.ray(m, p[0], p[1]), light.position, m.basis.back); s.api.begin(); drag = { pointerId: event.pointerId, target: target, light: light, mode: mode, x: event.clientX, y: event.clientY, position: light.position.slice(), rotation: light.rotation.slice(), size: light.size, scale:light.scale&&light.scale.slice(), point: point, matrices: m }; target.setPointerCapture(event.pointerId); target.focus({ preventScroll: true }); });
        target.addEventListener('focus', function () { if (s.selectedId !== light.id) s.api.select(kind(light),light.id); }); target.addEventListener('keydown', function (event) { light=current(light); if (light.locked || !/^Arrow/.test(event.key)) return; event.preventDefault(); event.stopPropagation(); s.api.mutate(function () { var amount = event.shiftKey ? .1 : .05, delta = event.key === 'ArrowLeft' || event.key === 'ArrowDown' ? -1 : 1; if (mode === 'move') light.position[event.key === 'ArrowUp' || event.key === 'ArrowDown' ? 1 : 0] = Math.max(-20, Math.min(20, light.position[event.key === 'ArrowUp' || event.key === 'ArrowDown' ? 1 : 0] + amount * delta)); else if (mode === 'depth') light.position[2] = Math.max(-20, Math.min(20, light.position[2] + amount * delta)); else if (mode === 'rotate') { var i = event.key === 'ArrowUp' || event.key === 'ArrowDown' ? 0 : 1; light.rotation[i] = Math.max(-180, Math.min(180, light.rotation[i] + (event.shiftKey ? 15 : 2) * delta)); } else if(light.scale)light.scale=light.scale.map(function(v){return Math.max(.05,Math.min(6,v+amount*delta));});else light.size = Math.max(.02, Math.min(4, light.size + amount * delta)); }); }); return target;
      }
      layer.addEventListener('pointermove', function (event) { if (!drag || event.pointerId !== drag.pointerId) return; event.preventDefault(); event.stopPropagation(); var d = drag, dx = event.clientX - d.x, dy = event.clientY - d.y, light = d.light;
        if (d.mode === 'move') { var p = normalized(s, event), point = C.studioCamera.plane(C.studioCamera.ray(d.matrices, p[0], p[1]), d.position, d.matrices.basis.back); if (point && d.point) light.position = d.position.map(function (n, i) { return Math.max(-20, Math.min(20, snap(n + point[i] - d.point[i], event.shiftKey, .1))); }); }
        else if (d.mode === 'depth') light.position = d.position.map(function (n, i) { return Math.max(-20, Math.min(20, snap(n - dy * .015 * d.matrices.basis.back[i], event.shiftKey, .1))); });
        else if (d.mode === 'rotate') light.rotation = [snap(d.rotation[0] - dy * .5, event.shiftKey, 15), snap(d.rotation[1] + dx * .5, event.shiftKey, 15), d.rotation[2]].map(function (n) { return Math.max(-180, Math.min(180, n)); });
        else if(light.scale)light.scale=d.scale.map(function(v){return Math.max(.05,Math.min(6,snap(v+(dx-dy)*.01,event.shiftKey,.1)));});else light.size = Math.max(.02, Math.min(4, snap(d.size + (dx - dy) * .01, event.shiftKey, .1))); s.api.dirty();
      }); layer.addEventListener('pointerup', end); layer.addEventListener('pointercancel', end); layer.addEventListener('lostpointercapture', end);
      function select(id) { records.forEach(function (r, key) { var chosen = key === id; r.group.classList.toggle('is-selected', chosen); r.handles.forEach(function (h, i) { h.style.display = i && !chosen ? 'none' : ''; h.setAttribute('tabindex', r.light.locked || i && !chosen ? '-1' : '0'); }); }); var selected = records.get(id); if (selected && layer.lastElementChild !== selected.group) layer.appendChild(selected.group); }
      return { cancel: end, select: select,
        draw: function (scene, width, height) { var focusedHandle = root.document.activeElement.closest('[data-studio-handle]'), focusId = focusedHandle && layer.contains(focusedHandle) ? focusedHandle.parentElement.getAttribute('data-light-id') : null, focusMode = focusedHandle && focusedHandle.getAttribute('data-studio-handle'); var simple = s.renderer && s.renderer.kind === 'Simple'; var hidden = simple || !s.root.classList.contains('is-ready'); layer.style.display = hidden ? 'none' : ''; layer.setAttribute('aria-hidden', String(hidden));  if (simple) return; layer.setAttribute('viewBox', '0 0 ' + width + ' ' + height); var ids = new Set(objects().map(function (l) { return l.id; })); records.forEach(function (record, id) { if (!ids.has(id)) { record.group.remove(); records.delete(id); } }); var m = C.studioCamera.matrices(scene.camera, width / Math.max(1, height), scene.card);
          objects().forEach(function (light) { var record = records.get(light.id); if (record && record.light !== light) { record.group.remove(); records.delete(light.id); record = null; } if (!record) { var group = svg('g', { 'class': 'studio-light-gizmo', 'data-light-id': light.id, 'data-object-kind':kind(light) }, layer), shape = svg('path', { 'class': 'studio-light-shape' }, group), move = handle(group, 'Move on camera plane', 'move', light), rotate = handle(group, 'Rotate light', 'rotate', light), depth = handle(group, 'Move in depth', 'depth', light), scale = handle(group, 'Scale / softness', 'scale', light); svg('circle', { cx: 0, cy: 0, r: 16, 'class': 'studio-gizmo-hit' }, move); svg('circle', { cx: 0, cy: 0, r: 5, 'class': 'studio-light-dot' }, move); svg('path', { d: 'M-23 0A23 23 0 0 1 23 0', fill: 'none' }, rotate); svg('circle', { cx: 0, cy: -23, r: 6, 'class': 'studio-gizmo-hit' }, rotate); svg('path', { d: 'M0 10V35M-5 29L0 35L5 29', fill: 'none' }, depth); svg('circle', { cx: 0, cy: 35, r: 8, 'class': 'studio-gizmo-hit' }, depth); svg('rect', { x: 25, y: -4, width: 9, height: 9, fill: 'none' }, scale); svg('rect', { x: 20, y: -10, width: 20, height: 20, 'class': 'studio-gizmo-hit' }, scale); record = { group: group, shape: shape, move: move, handles: [move, rotate, depth, scale], light: light }; records.set(light.id, record); }
            // History/presets replace object references: rebuild handlers safely.
            var sample = scene.lights.find(function (l) { return l.id === light.id; }) || light, projected = C.studioCamera.project(m, sample.position), x = Math.max(42, Math.min(width - 42, Number.isFinite(projected.x) ? projected.x * width : width / 2)), y = Math.max(42, Math.min(height - 45, Number.isFinite(projected.y) ? projected.y * height : height / 2)), selected = s.selectedId === light.id; record.group.setAttribute('transform', 'translate(' + x + ' ' + y + ')'); record.group.style.opacity = light.visible ? selected ? '1' : '.55' : '.25'; record.group.classList.toggle('is-selected', selected); record.group.style.display = light.type === 'ambient'||(!light.visible&&!selected)?'none':''; record.group.setAttribute('aria-hidden', String(light.type === 'ambient'||(!light.visible&&!selected))); record.move.querySelector('.studio-light-dot').style.fill = 'rgb(' + light.color.map(function (n) { return Math.round(n * 255); }).join(',') + ')'; record.shape.setAttribute('d', shapePath(sample, m, width, height, projected)); record.handles.forEach(function (h, i) { h.style.display = i && !selected ? 'none' : ''; h.setAttribute('tabindex', light.locked || i && !selected ? '-1' : '0'); h.setAttribute('aria-disabled', String(light.locked)); });
          }); select(s.selectedId); if (focusId && !focusedHandle.isConnected) { var focusedRecord = records.get(focusId), nextHandle = focusedRecord && focusedRecord.handles.find(function (h) { return h.getAttribute('data-studio-handle') === focusMode; }); (nextHandle || s.viewport).focus({ preventScroll: true }); }
        }, destroy: function () { end(); records.clear(); layer.remove(); } };
    }
  };
})(window.Cardable, window);
