(function(C,root){
  'use strict';
  var U=C.studioUI,S=C.studioScenes;
  function curve(value,x){var n=Math.min(3,Math.floor(Math.max(0,Math.min(1,x))*4)),t=Math.max(0,Math.min(1,x))*4-n;return value[n]*(1-t)+value[n+1]*t;}
  function create(s){
    var overlay=U.node('div','studio-look-overlay',s.viewport),line=U.node('div','studio-look-split',overlay),caption=U.node('span','studio-look-label',line,'BEFORE / AFTER'),scope=U.node('canvas','studio-look-scope',overlay),scratch=root.document.createElement('canvas'),g=scope.getContext('2d'),small=scratch.getContext('2d',{willReadFrequently:true}),showing=false,enabled=false,split=false,kind='histogram',last=-Infinity;
    scope.width=256;scope.height=104;scratch.width=96;scratch.height=54;scope.setAttribute('aria-label','Luminance scope');scope.setAttribute('role','img');line.hidden=scope.hidden=overlay.hidden=true;
    function changed(){line.hidden=!split;scope.hidden=!enabled;s.api.dirty();}
    function toggle(){split=!split;changed();}
    function draw(now){if(!showing||!enabled||now-last<250||!s.canvas.width)return;last=now;try{small.drawImage(s.canvas,0,0,96,54);var data=small.getImageData(0,0,96,54).data,bins=new Uint16Array(64);g.fillStyle='#0b0b0eec';g.fillRect(0,0,256,104);g.strokeStyle='#ffffff18';g.lineWidth=1;[26,52,78].forEach(function(y){g.beginPath();g.moveTo(0,y);g.lineTo(256,y);g.stroke();});g.fillStyle='#d8d8e3';for(var i=0;i<data.length;i+=4){var l=Math.round((data[i]*.213+data[i+1]*.715+data[i+2]*.072)/4);bins[Math.min(63,l)]++;if(kind==='waveform'){g.globalAlpha=.09;g.fillRect((i/4%96)*256/96,96-l/63*86,2,2);}}g.globalAlpha=1;if(kind==='histogram'){var peak=Math.max.apply(Math,bins)||1;bins.forEach(function(n,i){g.fillRect(i*4,96-n/peak*82,3,n/peak*82);});}g.fillStyle='#a5a5b0';g.font='9px monospace';g.fillText(kind.toUpperCase(),8,13);}catch(e){enabled=false;scope.hidden=true;s.api.status('Scopes unavailable: '+e.message);}}
    return {show:function(v){showing=v;overlay.hidden=!v;if(!v)s.api.dirty();},split:function(){return showing&&split?.5:0;},toggle:toggle,draw:draw,scope:function(v){enabled=v!=='off';kind=v;changed();},get scopeMode(){return enabled?kind:'off';},get comparing(){return split;},destroy:function(){overlay.remove();scratch.width=scratch.height=scope.width=scope.height=1;}};
  }
  function wheel(s,key,title){
    var post=s.scene.post,locked=S.locked(s.scene,post),row=U.node('div','studio-grade-wheel',s.panel),disk=U.node('div','studio-color-wheel',row),pin=U.node('span','studio-wheel-pin',disk),base=key==='lift'?0:1,range=key==='lift'?.2:.5;
    disk.tabIndex=locked?-1:0;disk.setAttribute('role','slider');disk.setAttribute('aria-label',title+' color balance');disk.setAttribute('aria-valuemin','-1');disk.setAttribute('aria-valuemax','1');U.node('strong','',row,title);
    function sync(){var v=post[key],x=(v[0]-v[2])/(range*2),y=(v[1]-(v[0]+v[2])/2)/range;pin.style.left=(50+x*40)+'%';pin.style.top=(50-y*40)+'%';disk.setAttribute('aria-valuenow',x.toFixed(2));disk.setAttribute('aria-valuetext',v.map(function(n){return n.toFixed(2);}).join(', '));}sync();
    function balance(x,y){var mean=post[key].reduce(function(a,b){return a+b;},0)/3,offset=[x-y*.5,y,-x-y*.5];post[key]=offset.map(function(n){return Math.max(key==='lift'?-.2:.5,Math.min(key==='lift'?.2:2,mean+n*range));});sync();s.api.dirty();}
    var drag=null;disk.addEventListener('pointerdown',function(e){if(locked||s.photoBusy||s.recordJob)return;e.preventDefault();s.api.begin('Balance '+title);drag=e.pointerId;disk.setPointerCapture(e.pointerId);move(e);});function move(e){if(drag!==e.pointerId)return;var r=disk.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.4),y=-(e.clientY-r.top-r.height/2)/(r.height*.4),length=Math.max(1,Math.hypot(x,y));balance(x/length,y/length);}disk.addEventListener('pointermove',move);function end(){if(drag===null)return;drag=null;s.api.commit();}disk.addEventListener('pointerup',end);disk.addEventListener('lostpointercapture',end);disk.addEventListener('pointercancel',function(){if(drag!==null){drag=null;s.api.cancel();}});disk.addEventListener('keydown',function(e){if(locked||!/^Arrow/.test(e.key))return;e.preventDefault();s.api.mutate(function(){var v=post[key],x=(v[0]-v[2])/(range*2),y=(v[1]-(v[0]+v[2])/2)/range;balance(x+(e.key==='ArrowRight'?.025:e.key==='ArrowLeft'?-.025:0),y+(e.key==='ArrowUp'?.025:e.key==='ArrowDown'?-.025:0));},'Balance '+title);});
    U.field(s,title+' level','range',post[key].reduce(function(a,b){return a+b;},0)/3,key==='lift'?-.2:.5,key==='lift'?.2:2,.01,function(v){var mean=post[key].reduce(function(a,b){return a+b;},0)/3;post[key]=post[key].map(function(n){return Math.max(key==='lift'?-.2:.5,Math.min(key==='lift'?.2:2,n+v-mean));});sync();},locked);
    U.button('Reset '+title,row,function(){s.api.mutate(function(){post[key]=[base,base,base];sync();},'Reset '+title);}).disabled=locked;
  }
  function panel(s){if(!s.lookUI)s.lookUI=create(s);s.panel.replaceChildren();U.node('p','studio-kicker',s.panel,'LOOK / COLOR & LENS');U.node('h2','studio-panel-title',s.panel,'Finish the image.');var locked=S.locked(s.scene,s.scene.post),simple=s.renderer.kind==='Simple';
    U.section(s,'Compare & scopes');var row=U.node('div','studio-presets-row',s.panel),compare=U.button('Before / after · \\',row,function(){s.lookUI.toggle();compare.setAttribute('aria-pressed',String(s.lookUI.comparing));});compare.setAttribute('aria-pressed',String(s.lookUI.comparing));compare.disabled=simple;var select=U.node('select','studio-select',row);select.setAttribute('aria-label','Image scope');[['off','Scopes off'],['histogram','Histogram'],['waveform','Waveform']].forEach(function(v){var o=U.node('option','',select,v[1]);o.value=v[0];});select.value=s.lookUI.scopeMode;select.addEventListener('change',function(){s.lookUI.scope(select.value);});
    U.button('Browse looks',row,function(){if(s.workspace)s.workspace.openPresets('look');else s.api.select('presets');}).dataset.lookPresets='true';
    U.section(s,'Primary grade');[['Exposure','exposure',-2,2,.05],['Contrast','contrast',.25,2,.01],['Saturation','saturation',0,2,.01],['Temperature','temperature',-1,1,.01],['Tint','tint',-1,1,.01],['Highlights','highlights',-1,1,.01],['Shadows','shadows',-1,1,.01],['Vibrance','vibrance',-1,1,.01]].forEach(function(p){U.field(s,p[0],'range',s.scene.post[p[1]],p[2],p[3],p[4],function(v){s.scene.post[p[1]]=v;},locked||simple&&['exposure','contrast','saturation'].indexOf(p[1])<0);});
    U.section(s,'Color balance');['lift','gamma','gain'].forEach(function(k){if(!simple)wheel(s,k,k.charAt(0).toUpperCase()+k.slice(1));});
    U.section(s,'Tone curve');var graph=U.node('canvas','studio-tone-curve',s.panel);graph.width=240;graph.height=132;graph.setAttribute('role','img');graph.setAttribute('aria-label','Tone curve. Adjust the five input levels below.');function draw(){var g=graph.getContext('2d');g.fillStyle='#101014';g.fillRect(0,0,240,132);g.strokeStyle='#ffffff20';g.beginPath();for(var i=0;i<5;i++){g.moveTo(10+i*55,10);g.lineTo(10+i*55,120);g.moveTo(10,10+i*27.5);g.lineTo(230,10+i*27.5);}g.stroke();g.strokeStyle='#e9e9ef';g.beginPath();s.scene.post.curve.forEach(function(y,i){if(i)g.lineTo(10+i*55,120-y*110);else g.moveTo(10,120-y*110);});g.stroke();}draw();['Black','Shadows','Midtones','Highlights','White'].forEach(function(name,i){U.field(s,name+' output','range',s.scene.post.curve[i],0,1,.01,function(v){s.scene.post.curve[i]=v;draw();},locked||simple);});
    U.section(s,'Lens & texture');[['Bloom','bloom',0,1,.01],['Halation','halation',0,1,.01],['Vignette','vignette',0,1,.01],['Grain','grain',0,.3,.005],['Chromatic aberration','aberration',0,1,.01],['Lens flare','flare',0,1,.01],['Sharpen','sharpen',0,1,.01],['Tilt-shift','tiltShift',0,1,.01]].forEach(function(p){U.field(s,p[0],'range',s.scene.post[p[1]],p[2],p[3],p[4],function(v){s.scene.post[p[1]]=v;},locked||simple||p[1]==='tiltShift'&&s.tier!=='high'&&s.tier!=='very-high');});if(simple)U.node('p','studio-copy',s.panel,'Very Low uses a light 2D preview. Advanced grades stay in your scene for higher tiers.');
  }
  C.studioLook={panel:panel,curve:curve};
})(window.Cardable,window);
