(function (C, root) {
  'use strict';
  function node(tag, name, parent, value) { var el = root.document.createElement(tag); el.className = name || ''; if (value != null) el.textContent = value; if (parent) parent.appendChild(el); return el; }
  function button(label, parent, run, title) { var el = node('button', 'studio-button', parent, label); el.type = 'button'; el.title = title || label; if (run) el.addEventListener('click', run); else el.disabled = true; return el; }
  function section(s, label) { node('h3', 'studio-section-title', s.panel, label); }
  function field(s, label, type, value, min, max, step, changed, disabled) { var wrapper = node('label', 'studio-field', s.panel), caption = node('span', '', wrapper, label), input = node('input', '', wrapper), output;
    input.type = type; input.disabled = !!disabled; input.setAttribute('aria-label', label); if (type === 'checkbox') input.checked = value; else { input.min = min; input.max = max; input.step = step; input.value = value; if (type === 'range') { output = node('output', 'studio-value', wrapper, Number(value).toFixed(step < 1 ? 2 : 0)); wrapper.insertBefore(output, input); } }
    function begin() { s.api.begin(); } input.addEventListener('pointerdown', begin); input.addEventListener('keydown', begin); input.addEventListener('input', function () { begin(); var v = type === 'checkbox' ? input.checked : type === 'text' ? input.value : Number(input.value); changed(v); if (output) output.value = Number(v).toFixed(step < 1 ? 2 : 0); s.api.dirty(); }); input.addEventListener('change', function () { s.api.commit(); }); input.addEventListener('blur', function () { s.api.commit(); }); return input;
  }
  function select(s, label, value, choices, changed, disabled) { var wrapper = node('label', 'studio-field', s.panel), input = node('select', 'studio-select', wrapper); node('span', '', wrapper, label); wrapper.insertBefore(wrapper.lastChild, input); input.setAttribute('aria-label', label); input.disabled = !!disabled; choices.forEach(function (entry) { var pair = Array.isArray(entry) ? entry : [entry, entry], option = node('option', '', input, pair[1]); option.value = pair[0]; }); input.value = value; input.addEventListener('change', function () { s.api.mutate(function () { changed(input.value); }); }); return input; }
  function vector(s, label, value, low, high, step, changed, disabled) { section(s, label); ['X', 'Y', 'Z'].forEach(function (axis, i) { field(s, label + ' ' + axis, 'range', value[i], low, high, step, function (v) { value[i] = v; changed(); }, disabled); }); }
  function color(s, light, property, caption) {
    section(s, caption); var hsv = C.studioLights.toHSV(light[property]);
    function apply() { light[property] = C.studioLights.hsv(hsv[0], hsv[1], hsv[2]); if (property === 'color') light.temperature = null; }
    // Hue is a neutral control ring: colored swatches live on the viewport only.
    var ring = node('div', 'studio-hue-ring', s.panel), hue = field(s, caption + ' hue', 'range', hsv[0], 0, 360, 1, function (v) { hsv[0] = v; apply(); }, light.locked), dial = button('', ring, function () {}, caption + ' hue ring · drag to choose hue'); dial.className = 'studio-hue-dial'; dial.disabled = light.locked; dial.setAttribute('aria-label', caption + ' hue ring'); ring.appendChild(hue.parentElement); ring.style.setProperty('--hue-angle', hsv[0] + 'deg'); hue.addEventListener('input', function () { ring.style.setProperty('--hue-angle', hue.value + 'deg'); });
    var dragging = false; function dialValue(event) { var r = dial.getBoundingClientRect(), angle = (Math.atan2(event.clientY - r.top - r.height / 2, event.clientX - r.left - r.width / 2) * 180 / Math.PI + 450) % 360; hue.value = Math.round(angle); hue.dispatchEvent(new root.Event('input', { bubbles: true })); }
    dial.addEventListener('pointerdown', function (event) { event.preventDefault(); dragging = true; s.api.commit(); s.api.begin(); dial.setPointerCapture(event.pointerId); dialValue(event); }); dial.addEventListener('pointermove', function (event) { if (dragging) dialValue(event); }); function finishDial() { if (dragging) { dragging = false; hue.dispatchEvent(new root.Event('change', { bubbles: true })); } } dial.addEventListener('pointerup', finishDial); dial.addEventListener('pointercancel', finishDial); dial.addEventListener('lostpointercapture', finishDial); dial.addEventListener('keydown', function (event) { if (/^Arrow/.test(event.key)) { event.preventDefault(); hue.value = (Number(hue.value) + (/Left|Down/.test(event.key) ? -1 : 1) * (event.shiftKey ? 15 : 3) + 360) % 360; hue.dispatchEvent(new root.Event('input', { bubbles: true })); hue.dispatchEvent(new root.Event('change', { bubbles: true })); } });
    field(s, caption + ' saturation', 'range', hsv[1], 0, 1, .01, function (v) { hsv[1] = v; apply(); }, light.locked); field(s, caption + ' value', 'range', hsv[2], 0, 1, .01, function (v) { hsv[2] = v; apply(); }, light.locked);
    if (property === 'color') { var row = node('div', 'studio-presets-row', s.panel); Object.keys(C.studioLights.colorPresets).forEach(function (name) { var b = button(name, row, function () { s.api.mutate(function () { light.color = C.studioLights.colorPresets[name].slice(); light.temperature = null; }); inspect(s, 'light', light.id); }); b.disabled = light.locked; }); field(s, 'Temperature · Kelvin', 'range', light.temperature || 6500, 1000, 12000, 100, function (v) { light.temperature = v; light.color = C.studioLights.kelvin(v); }, light.locked).addEventListener('change', function () { inspect(s, 'light', light.id); }); }
  }
  function camera(s) { var c = s.scene.camera, simple = s.renderer && s.renderer.kind === 'Simple', high = s.tier === 'high' && !simple;
    node('p', 'studio-copy', s.panel, simple ? 'Simple preview supports distance, roll and framing. Spatial camera tools require WebGL2.' : 'Drag to orbit. Right-drag or Shift-drag to pan. Scroll to dolly. Pick focus, then click the card or stage.');
    field(s, 'Distance', 'range', c.distance, 1.3, 9, .05, function (v) { c.distance = v; c.autoFrame = false; }); field(s, 'Field of view', 'range', c.fov, 15, 90, 1, function (v) { c.fov = v; }, simple); field(s, 'Roll', 'range', c.roll * 180 / Math.PI, -180, 180, 1, function (v) { c.roll = v * Math.PI / 180; });
    if (!simple) { field(s, 'Orbit yaw', 'range', c.yaw * 180 / Math.PI, -180, 180, 1, function (v) { c.yaw = v * Math.PI / 180; c.autoFrame = false; }); field(s, 'Orbit pitch', 'range', c.pitch * 180 / Math.PI, -77, 77, 1, function (v) { c.pitch = v * Math.PI / 180; c.autoFrame = false; }); vector(s, 'Pan target', c.target, -3, 3, .05, function () { c.autoFrame = false; }, c.lockToCard); }
    select(s, 'Aspect guide', c.aspect, [['free', 'Free'], ['1:1', '1:1'], ['4:5', '4:5'], ['16:9', '16:9'], ['9:16', '9:16'], ['card', 'Card only']], function (v) { c.aspect = v; });
    field(s, 'Auto-frame', 'checkbox', c.autoFrame, null, null, null, function (v) { c.autoFrame = v; }); field(s, 'Lock to card', 'checkbox', c.lockToCard, null, null, null, function (v) { c.lockToCard = v; }, simple); button('Frame card', s.panel, function () { s.api.mutate(function () { s.api.frame(); }); inspect(s, 'camera'); }, 'Frame card · F');
    section(s, 'Depth of field'); field(s, 'Aperture / blur', 'range', c.aperture, 0, 10, .1, function (v) { c.aperture = v; }, !high); var pick = button('Pick focus point', s.panel, function () { s.focusPick = true; s.api.status('Click the card or stage to focus.'); }, 'Click to focus · High only'); pick.disabled = !high; if (high) vector(s, 'Focus point', c.focus, -3, 3, .05, function () {}); else node('p', 'studio-copy', s.panel, 'Depth of field and tilt-shift render on High. Stored settings survive lower tiers.');
    section(s, 'Lens'); [['Exposure', 'exposure', -2, 2, .05], ['Bloom', 'bloom', 0, 1, .01], ['Vignette', 'vignette', 0, 1, .01], ['Grain', 'grain', 0, .3, .005], ['Chromatic aberration', 'aberration', 0, 1, .01], ['Lens flare', 'flare', 0, 1, .01], ['Tilt-shift', 'tiltShift', 0, 1, .01]].forEach(function (p) { field(s, p[0], 'range', s.scene.post[p[1]], p[2], p[3], p[4], function (v) { s.scene.post[p[1]] = v; }, p[1] === 'tiltShift' ? !high : p[1] === 'bloom' ? simple || s.tier === 'low' || s.tier === 'very-low' : simple && p[1] !== 'exposure'); });
  }
  function lightPanel(s, light) {
    field(s, 'Name', 'text', light.name, null, null, null, function (v) { light.name = v.slice(0, 60); }, light.locked); select(s, 'Type', light.type, C.studioLights.types.map(function (t) { return [t, { point: 'Point', spot: 'Spot', directional: 'Directional / sun', area: 'Area softbox', strip: 'Strip', ambient: 'Ambient / sky' }[t]]; }), function (v) { light.type = v; inspect(s, 'light', light.id); }, light.locked || s.renderer && s.renderer.kind === 'Simple');
    field(s, 'Locked', 'checkbox', light.locked, null, null, null, function (v) { light.locked = v; }, false).addEventListener('change', function () { inspect(s, 'light', light.id); }); field(s, 'Visible', 'checkbox', light.visible, null, null, null, function (v) { light.visible = v; }, light.locked);
    field(s, 'Intensity', 'range', light.intensity, 0, 20, .05, function (v) { light.intensity = v; }, light.locked); color(s, light, 'color', light.type === 'ambient' ? 'Sky top color' : 'Color'); if (light.type === 'ambient') color(s, light, 'bottom', 'Sky bottom color');
    if (light.type !== 'ambient' && !(s.renderer && s.renderer.kind === 'Simple')) { vector(s, 'Position', light.position, -8, 8, .05, function () {}, light.locked); vector(s, 'Rotation', light.rotation, -180, 180, 1, function () {}, light.locked); field(s, 'Size / softness', 'range', light.size, .02, 4, .02, function (v) { light.size = v; }, light.locked); field(s, 'Falloff', 'range', light.falloff, 0, 4, .05, function (v) { light.falloff = v; }, light.locked || light.type === 'directional');
      if (light.type === 'spot') { field(s, 'Cone angle', 'range', light.angle, 5, 120, 1, function (v) { light.angle = v; }, light.locked); field(s, 'Cone softness', 'range', light.softness, 0, 1, .01, function (v) { light.softness = v; }, light.locked); select(s, 'Gobo', light.gobo, ['none', 'blinds', 'grid', 'leaves', 'stars'], function (v) { light.gobo = v; }, light.locked); }
      field(s, 'Cast shadow', 'checkbox', light.shadows, null, null, null, function (v) { light.shadows = v; }, light.locked); field(s, 'Shadow softness', 'range', light.shadowSoftness, 0, 1, .01, function (v) { light.shadowSoftness = v; }, light.locked || s.tier !== 'high');
      select(s, 'Animation', light.animation, ['none', 'pulse', 'flicker', 'sweep', 'orbit'], function (v) { light.animation = v; }, light.locked || s.tier === 'very-low' || C.motion.reduced); field(s, 'Animation speed', 'range', light.speed, .1, 5, .1, function (v) { light.speed = v; }, light.locked || s.tier === 'very-low' || C.motion.reduced);
      node('p', 'studio-copy', s.panel, C.motion.reduced ? 'Reduced motion pauses all light animation.' : 'Soft animation · Safe caps intensity cycles at 1.8 Hz; Full at 5 Hz. Ambient sky stays static.'); }
    var actions = node('div', 'studio-presets-row', s.panel); button('Duplicate', actions, function () { s.api.duplicate(); }, 'Duplicate · Ctrl/Cmd+D').disabled = light.locked; button('Delete', actions, function () { s.api.remove(); }, 'Delete selected light · Del').disabled = light.locked;
  }
  function inspect(s, kind, id) {
    if(s.recordJob)return;if(s.director&&kind==='scenes'){s.scene.director.playhead=s.director.time;s.scene.presentationTime=s.lightTime;}s.timelineUI=null;if(s.director&&(kind==='camera'||kind==='light'))s.director.pause(true);var previousFocus = root.document.activeElement, panelHadFocus = s.panel.contains(previousFocus); s.api.commit(); s.selected = kind; s.selectedId = id || null; s.panel.replaceChildren(); s.root.querySelectorAll('[data-studio-tool]').forEach(function (tool) { tool.setAttribute('aria-pressed', String(tool.dataset.studioTool === (kind === 'light' ? 'lights' : kind === 'prop' ? 'props' : kind))); });
    var selectedLight = kind === 'light' && s.scene.lights.find(function (l) { return l.id === id; }); if (kind === 'light' && !selectedLight) { kind = s.selected = 'lights'; s.selectedId = null; }
    var selectedProp=kind==='prop'&&s.scene.props.find(function(p){return p.id===id;});if(kind==='prop'&&!selectedProp){kind=s.selected='props';s.selectedId=null;}
    node('p', 'studio-kicker', s.panel, kind==='photo'?'PHOTO STUDIO':kind==='objects'?'SCENE OBJECTS':kind==='props'?'PROP CATALOG':kind==='prop'?'SELECTED PROP':kind==='scenes'?'SAVED SCENES':kind === 'camera' ? 'CAMERA & LENS' : kind === 'backdrop' ? 'BACKDROP' : kind === 'lights' ? 'LIGHT RIG' : kind === 'light' ? 'SELECTED LIGHT' : kind === 'presets' ? 'SCENE PRESETS' : 'SELECTED CARD');
    node('h2', 'studio-panel-title', s.panel, kind==='photo'?'Keep this moment.':kind==='objects'?'Choose an object.':kind==='props'?'Build the stage.':kind==='prop'?selectedProp.name:kind==='scenes'?'Keep a composition.':kind === 'camera' ? 'Find the angle.' : kind === 'backdrop' ? 'A quiet stage.' : kind === 'lights' ? 'Shape the light.' : kind === 'light' ? selectedLight.name : kind === 'presets' ? 'Choose a scene.' : s.view.card.name);
    if(kind==='director')C.studioDirectorPanel(s);else if(kind==='photo')C.studioPhotoPanel(s);else if(kind==='objects'){var list=node('div','studio-mobile-objects',s.panel);outliner(s,list);}
    else if(kind==='props'||kind==='prop') C.studioPropPanel(s,selectedProp);
    else if(kind==='scenes') C.studioScenePanel(s);
    else if (kind === 'camera') camera(s);
    else if (kind === 'light') lightPanel(s, selectedLight);
    else if (kind === 'lights') { node('p', 'studio-copy', s.panel, s.scene.lights.length + ' / ' + C.studioScenes.limits(s.tier).lights + ' lights · ' + (s.tier === 'high' ? 'soft shadows' : s.tier === 'medium' ? 'basic shadows' : 'no shadows')); var types = node('div', 'studio-presets-grid', s.panel); C.studioLights.types.forEach(function (type) { button('Add ' + { point: 'point', spot: 'spot', directional: 'sun', area: 'softbox', strip: 'strip', ambient: 'sky' }[type], types, function () { s.api.addLight(type); }); }); section(s, 'Light rigs'); C.studioPresets.rigs.forEach(function (name) { button(name, s.panel, function () { s.api.mutate(function () { s.scene.lights = C.studioPresets.lights(name, s.tier); }); inspect(s, 'lights'); }); }); }
    else if (kind === 'presets') { node('p', 'studio-copy', s.panel, 'Replace the light rig, camera, props and stage. Your card identity stays with the scene. Undo restores the previous setup.'); C.studioPresets.scenes.forEach(function (name) { button(name, s.panel, function () { s.api.mutate(function () { s.scene = C.studioPresets.apply(name, s.scene, s.tier); }); inspect(s, 'presets'); }); }); }
    else if (kind === 'backdrop') { color(s,s.scene.backdrop,'color','Backdrop color'); field(s, 'Brightness', 'range', s.scene.backdrop.color[0], 0, .3, .005, function (v) { s.scene.backdrop.color = [v, v, v * 1.08]; }); }
    else { field(s,'Locked','checkbox',s.scene.card.locked,null,null,null,function(v){s.scene.card.locked=v;}).addEventListener('change',function(){inspect(s,'card');}); field(s,'Visible','checkbox',s.scene.card.visible,null,null,null,function(v){s.scene.card.visible=v;},s.scene.card.locked); var identity = node('dl', 'studio-identity', s.panel); [['Serial', s.view.instance.serial], ['Rarity', C.rarity(s.view.card.rarity).name], ['Finish', C.variant(s.view.instance.variantId)?.name || 'Normal'], ['Skin', C.cardSkin(s.view.instance.cardSkinId)?.name || 'Standard']].forEach(function (p) { node('dt', '', identity, p[0]); node('dd', '', identity, p[1]); }); var sides = node('div', 'studio-segment', s.panel); ['front', 'back'].forEach(function (side) { var b = button(side === 'front' ? 'Front' : 'Back', sides, function () { s.api.mutate(function () { s.scene.card.side = side; }); inspect(s, 'card'); }); b.setAttribute('aria-pressed', String(s.scene.card.side === side));b.disabled=s.scene.card.locked; }); field(s, 'Info plate', 'checkbox', s.scene.card.plate, null, null, null, function (v) { s.scene.card.plate = v; s.api.repaint(); },s.scene.card.locked); field(s, 'Card tilt X', 'range', s.scene.card.tilt[0], -45, 45, 1, function (v) { s.scene.card.tilt[0] = v; },s.scene.card.locked); field(s, 'Card tilt Y', 'range', s.scene.card.tilt[1], -180, 180, 1, function (v) { s.scene.card.tilt[1] = v; },s.scene.card.locked); if (s.view.instance.variantId && (!C.variant(s.view.instance.variantId)?.studio || s.renderer?.kind==='Simple')) node('p', 'studio-limited', s.panel, 'Studio preview limited · this coating requires a studio port and WebGL2.'); node('p', 'studio-copy', s.panel, 'Last scene saves for this exact instance on exit.'); }
    outliner(s); if (s.gizmos) s.gizmos.select(s.selectedId); if (panelHadFocus && !previousFocus.isConnected) { var nextFocus = C.accessibility.focusables(s.panel)[0]; if (nextFocus) nextFocus.focus({ preventScroll: true }); } s.api.dirty();
  }
  function outliner(s,host) {
    host=host||s.objects;var ownedFocus=host.contains(root.document.activeElement);host.replaceChildren();
    function row(object,kind,index){var el=node('div','studio-object-row',host),name=object.name||'Card',choose=button(name,el,function(){inspect(s,kind,object.id);});choose.classList.add('studio-object');choose.setAttribute('aria-pressed',String(kind==='card'?s.selected==='card':s.selectedId===object.id));
      button(object.visible?'Hide':'Show',el,function(){s.api.mutate(function(){object.visible=!object.visible;});if(s.selected==='objects')inspect(s,'objects');},'Toggle visibility: '+name).disabled=object.locked;
      button(object.locked?'Unlock':'Lock',el,function(){s.api.mutate(function(){object.locked=!object.locked;});inspect(s,kind,object.id);},'Toggle lock: '+name);
      button('Delete',el,function(){s.api.remove(object.id,kind);},kind==='card'?'Hide primary card; Undo restores it':'Delete: '+name).disabled=object.locked;
      node('span','studio-object-note',el,kind==='card'?'Primary subject':object.type+(kind==='light'&&index===0?' · key':'')+(index>=C.studioScenes.limits(s.tier)[kind==='light'?'lights':'props']?' · tier limit':''));}
    row(s.scene.card,'card',0);s.scene.lights.forEach(function(l,i){row(l,'light',i);});s.scene.props.forEach(function(p,i){row(p,'prop',i);});
    if(ownedFocus){var focus=host.querySelector('[aria-pressed=true]')||host.querySelector('button');if(focus)focus.focus({preventScroll:true});}
  }
  C.studioUI = { node: node, button: button, field:field,select:select,vector:vector,color:color,section:section, inspect: inspect, outliner: outliner,
    history: function (s) { s.undo.disabled = !s.history.canUndo; s.redo.disabled = !s.history.canRedo; },
    build: function (s, api) { s.api = api; var el = s.root = node('section', 'studio-shell', root.document.body); el.setAttribute('role', 'dialog'); el.setAttribute('aria-modal', 'true'); el.setAttribute('aria-label', 'Card studio'); el.setAttribute('data-tool-surface', 'studio'); var top = node('header', 'studio-topbar', el), identity = node('div', 'studio-topbar-identity', top); node('span', 'studio-kicker', identity, 'INSPECT / STUDIO'); node('h1', '', identity, s.view.card.name); var actions = node('div', 'studio-topbar-actions', top); s.undo = button('Undo', actions, function () { api.restore(false); }, 'Undo · Ctrl/Cmd+Z'); s.redo = button('Redo', actions, function () { api.restore(true); }, 'Redo · Ctrl/Cmd+Shift+Z'); button('Presets', actions, function () { inspect(s, 'presets'); }); button('Director',actions,function(){inspect(s,'director');});button('Scenes',actions,function(){inspect(s,'scenes');});button('Objects',actions,function(){inspect(s,'objects');});button('Reset', actions, function () { api.mutate(function () { s.scene = C.studioScenes.defaults(s.view.instance, s.pose); }); inspect(s, 'card'); }); node('span', 'studio-quality', actions, s.tier === 'very-low' ? 'VERY LOW / SIMPLE' : s.tier.toUpperCase()); s.exit = button('Exit', actions, function () { C.studioController.exit(); }, 'Return to card detail · Esc');
      var layout = node('div', 'studio-layout', el), left = node('aside', 'studio-outliner glass', layout); node('p', 'studio-kicker', left, 'SCENE'); s.objects = node('div', '', left); s.viewport = node('div', 'studio-viewport', layout); s.viewport.tabIndex = 0; s.viewport.setAttribute('role', 'group'); s.viewport.setAttribute('aria-label', 'Card stage. Drag to orbit; Shift-drag or right-drag to pan; scroll to dolly.'); s.canvas = node('canvas', 'studio-canvas', s.viewport); s.canvas.setAttribute('aria-hidden', 'true'); s.titleOverlay=node('div','studio-title-overlay',s.viewport);node('strong','',s.titleOverlay,s.view.card.name);node('span','',s.titleOverlay,C.rarity(s.view.card.rarity).name+' · '+s.view.instance.serial);s.titleOverlay.hidden=true;s.titleOverlay.setAttribute('aria-hidden','true');s.loading = node('div', 'studio-loading', s.viewport, 'Preparing your card…'); s.guide = node('div', 'studio-aspect-guide', s.viewport); s.guide.setAttribute('aria-hidden', 'true'); var right = node('aside', 'studio-inspector glass', layout); s.panel = node('div', '', right); var bottom = node('footer', 'studio-bottom', el), tools = node('nav', 'studio-tools glass', bottom); tools.setAttribute('aria-label', 'Studio tools'); [['Select', 'card'], ['Lights', 'lights'], ['Props', 'props'], ['Camera', 'camera'], ['Backdrop', 'backdrop'], ['Card', 'card'], ['Photo', 'photo']].forEach(function (pair) { var b = button(pair[0], tools, pair[1] ? function () { inspect(s, pair[1]); } : null, pair[1] ? pair[0] : pair[0] + ' begins in milestone ' + (pair[0] === 'Props' ? 'C' : 'D')); if (pair[1]) b.dataset.studioTool = pair[1]; }); s.photoFilm=C.studioFilmstrip.create(s,bottom);s.status = node('p', 'studio-status', bottom); s.status.setAttribute('role', 'status'); node('span', 'studio-hint', bottom, 'DRAG ORBIT · SHIFT-DRAG PAN · L LIGHT · F FRAME · CTRL/CMD+Z UNDO · ESC RETURN'); this.history(s);
    },
    guide: function (s, width, height) { var ratio = C.studioCamera.aspect(s.scene.camera.aspect);if(s.selected==='photo'&&s.photoOptions){var area=C.studioPhoto.area(s.photoOptions);if(area.w>0&&area.h>0)ratio=area.w/area.h;} s.guide.hidden = !ratio; if (!ratio) return; var w = Math.min(width, height * ratio) * .9, h = w / ratio; s.guide.style.width = w + 'px'; s.guide.style.height = h + 'px'; }
  };
})(window.Cardable, window);
