(function(C,root){
  'use strict';
  var U=C.studioUI,S=C.studioScenes,P=C.studioPresets;
  function create(s,hooks){
    var store=C.state.current.studio,defaults=S.normalize();['presets','presetRecents','presetFavorites','presetSeed'].forEach(function(k){if(store[k]==null)store[k]=defaults[k];});
    var browser=null,grid=null,kind='scene',search='',tag='all',filter='all',last=null,dead=false,pendingGallery=null,galleryFaces=new Map(),galleryRevision=0,inertRecords=[];
    function save(){C.state.save();}function starred(id){return store.presetFavorites.indexOf(id)>=0;}function favorite(id){var n=store.presetFavorites.indexOf(id);if(n>=0)store.presetFavorites.splice(n,1);else if(store.presetFavorites.length<128)store.presetFavorites.push(id);save();render();}
    function contain(){inertRecords=Array.from(s.root.children).filter(function(el){return el!==browser;}).map(function(el){var rec={el:el,inert:el.inert};el.inert=true;return rec;});C.keys.listen(browser, 'keydown', 'src.studio.ui.presets.js.1', function(e){if(e.key!=='Tab')e.stopPropagation();});}
    function close(){inertRecords.forEach(function(r){if(r.el.isConnected)r.el.inert=r.inert;});inertRecords=[];galleryRevision++;pendingGallery=null;if(browser){C.accessibility.release(browser);browser.remove();browser=null;grid=null;s.viewport.focus({preventScroll:true});}galleryFaces.forEach(function(f){f.destroy();});galleryFaces.clear();}
    function applied(entry,add,override){if(dead||s.closing||s.photoBusy||s.recordJob)return;var from=S.clone(s.api.presented().scene),success=false;try{var next=override||P.build(entry,s.scene,P.profile(s.view.card,s.view.instance,s.faces),store.presetSeed),result=P.combine(s.scene,entry,next,add,s.tier);s.api.mutate(function(){s.scene=result;success=true;},(add?'Add ':'Replace ')+entry.kind+': '+entry.name);if(!success)return;last=entry;store.presetRecents=[entry.id].concat(store.presetRecents.filter(function(id){return id!==entry.id;})).slice(0,24);save();hooks.applied(entry);hooks.tween(from);if(entry.kind==='move'||entry.kind==='animation'){s.director.seek(0);if(s.root.dataset.mode==='pro')s.workspace.page('Animate');}C.events.emit('studio:preset',{id:entry.id,kind:entry.kind,seed:store.presetSeed});s.api.status(entry.name+' applied. Undo restores your composition.');render();}catch(error){s.api.status(error.message);}}
    function request(entry,override){if(typeof entry==='string')entry=P.find(entry);if(!entry)return;if(s.photoBusy||s.recordJob||s.closing)return;s.root.querySelectorAll('.studio-preset-confirm').forEach(function(e){e.remove();});if(s.history.steps||s.scene.props.length||s.scene.keyframes.length||s.scene.animation.tracks.length){if(!s.presetPreference){var box=U.node('div','studio-inline-confirm studio-preset-confirm',browser||s.root.querySelector('.studio-simple-controls'));box.setAttribute('role','group');box.setAttribute('aria-label','Apply preset');U.node('span','',box,'Replace the affected part, or add its objects and motion to your scene?');U.button('Replace scene',box,function(){s.presetPreference='replace';box.remove();applied(entry,false,override);});var add=U.button('Add to scene',box,function(){s.presetPreference='add';box.remove();applied(entry,true,override);});add.disabled=entry.kind==='look';U.button('Cancel',box,function(){box.remove();});return;}}applied(entry,s.presetPreference==='add'&&entry.kind!=='look',override);}
    function all(){return P.catalog.concat(store.presets);}function currentList(){var list=all().filter(function(e){return e.kind===kind;});if(filter==='recent')list=store.presetRecents.map(function(id){return list.find(function(e){return e.id===id;});}).filter(Boolean);return list.filter(function(e){return (!search||(e.name+' '+e.tags.join(' ')).toLowerCase().includes(search))&&(tag==='all'||e.tags.indexOf(tag)>=0)&&(filter!=='favorites'||starred(e.id))&&(filter!=='user'||!!e.scene)&&(filter!=='similar'||!last||e.tags.some(function(t){return last.tags.indexOf(t)>=0;}));});}
    function render(){if(!browser||!grid||browser.dataset.gallery==='true')return;grid.replaceChildren();var list=currentList();list.forEach(function(e){var tile=U.node('article','studio-preset-tile',grid),apply=U.button('',tile,function(){request(e);}),canvas=U.node('canvas','',apply);canvas.width=160;canvas.height=100;canvas.setAttribute('aria-hidden','true');apply.setAttribute('aria-label','Apply '+e.name);U.node('strong','',apply,e.name);U.node('small','',apply,e.tags.join(' · '));hooks.queue(e,canvas);var tools=U.node('div','studio-preset-tile-tools',tile),star=U.button(starred(e.id)?'★':'☆',tools,function(){favorite(e.id);});star.setAttribute('aria-label','Favorite '+e.name);star.setAttribute('aria-pressed',String(starred(e.id)));if(e.scene){U.button('Edit',tools,function(){manage(e);});U.button('Export',tools,function(){exportPreset(e);});U.button('Copy',tools,function(){copyPreset(e);});}});if(!list.length)U.node('p','studio-copy',grid,'No presets match. Clear the filters or save your own.');browser.querySelector('.studio-preset-count').textContent=list.length+' presets · previews use this card';s.api.dirty();}
    function nameForm(title,value,run){browser.querySelectorAll('.studio-preset-form').forEach(function(e){e.remove();});var form=U.node('form','studio-preset-form studio-inline-confirm',browser),label=U.node('label','',form,title),input=U.node('input','studio-library-search',label);input.value=value;input.maxLength=60;input.setAttribute('aria-label',title);var submit=U.button('Save',form,function(){});submit.type='submit';U.button('Cancel',form,function(){form.remove();});form.addEventListener('submit',function(e){e.preventDefault();try{run(input.value.trim()||'Untitled preset');form.remove();save();render();}catch(error){s.api.status(error.message);}});input.focus();input.select();return form;}
    function savePreset(){nameForm('Preset name','My '+kind,function(name){if(store.presets.length>=32)throw Error('User preset limit reached: 32.');var snapshot=P.snapshot(kind,name,s.scene,'user-'+root.crypto.randomUUID());store.presets.push(snapshot);filter='user';hooks.invalidate();});}
    function manage(e){var form=nameForm('Rename preset',e.name,function(name){e.name=name;hooks.invalidate();});U.button('Duplicate',form,function(){if(store.presets.length>=32)return s.api.status('User preset limit reached: 32.');var p=S.clone(e);p.id='user-'+root.crypto.randomUUID();p.name=(e.name+' copy').slice(0,60);store.presets.push(p);hooks.invalidate();form.remove();save();render();});U.button('Delete',form,function(){store.presets=store.presets.filter(function(p){return p!==e;});store.presetFavorites=store.presetFavorites.filter(function(id){return id!==e.id;});store.presetRecents=store.presetRecents.filter(function(id){return id!==e.id;});form.remove();save();render();});}
    async function copyPreset(e){try{var text=P.serialize(e);if(C.native&&C.native.system&&C.native.system.copyText)await C.native.system.copyText(text);else await root.navigator.clipboard.writeText(text);if(!dead)s.api.status('Preset JSON copied.');}catch(error){if(!dead)s.api.status('Clipboard unavailable. Export the preset instead.');}}
    async function exportPreset(e){var text=P.serialize(e),name=P.find(e.id).name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.cardable-preset.json';var blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=root.document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);s.api.status('Preset exported.');}
    function importText(text){if(dead||s.closing)return;try{if(store.presets.length>=32)throw Error('User preset limit reached: 32.');var p=P.parse(text);p.id='user-'+root.crypto.randomUUID();p.tags=Array.from(new Set(['User'].concat(p.tags)));store.presets.push(p);hooks.invalidate();kind=p.kind;filter='user';save();open(kind);s.api.status('Preset imported. Applying it stays undoable.');}catch(error){s.api.status(error.message);}}
    function importPreset(){var input=root.document.createElement('input');input.type='file';input.accept='.cardable-preset.json,application/json';input.addEventListener('change',async function(){var f=input.files[0];if(!f)return;if(f.size>262144)return s.api.status('Preset file exceeds 256 KB.');try{importText(await f.text());}catch(error){s.api.status(error.message);}});input.click();}
    function seedTools(parent){var row=U.node('div','studio-preset-seed',parent),seed=U.node('input','studio-library-search',row);seed.maxLength=80;seed.value=store.presetSeed;seed.setAttribute('aria-label','Preset seed');seed.addEventListener('change',function(){store.presetSeed=seed.value||'cardable';save();});U.button('Surprise me',row,function(){store.presetSeed=seed.value||'cardable';request(P.surprise(store.presetSeed));});U.button('Remix',row,function(){store.presetSeed=seed.value||'cardable';var e=last&&last.kind==='scene'&&!last.scene?last:P.surprise(store.presetSeed);request(e,P.remix(e,s.scene,P.profile(s.view.card,s.view.instance,s.faces),store.presetSeed));});}
    function open(value){close();kind=value||'scene';browser=U.node('section','studio-preset-browser glass',s.root);browser.setAttribute('role','dialog');browser.setAttribute('aria-modal','true');browser.setAttribute('aria-label','Preset browser');var head=U.node('header','studio-preset-heading',browser),title=U.node('div','',head);U.node('p','studio-kicker',title,'DIRECTOR / PRESETS');U.node('h2','',title,'Find your scene.');U.button('Close',head,close);var tools=U.node('div','studio-preset-browser-tools',browser),searchBox=U.node('input','studio-library-search',tools);searchBox.type='search';searchBox.placeholder='Search styles, mood or color';searchBox.value=search;searchBox.setAttribute('aria-label','Search presets');searchBox.addEventListener('input',function(){search=searchBox.value.toLowerCase();render();});var tabs=U.node('div','studio-preset-kinds',tools);[['scene','Styles'],['rig','Light rigs'],['move','Camera moves'],['look','Looks'],['props','Prop sets'],['animation','Animations']].forEach(function(x){var b=U.button(x[1],tabs,function(){kind=x[0];tag='all';open(kind);});b.setAttribute('aria-pressed',String(kind===x[0]));});var row=U.node('div','studio-preset-filters',tools),tags=U.node('select','studio-select',row);tags.setAttribute('aria-label','Preset tag');['all'].concat(Array.from(new Set(all().filter(function(e){return e.kind===kind;}).flatMap(function(e){return e.tags;})))).forEach(function(t){var o=U.node('option','',tags,t==='all'?'All families, moods and colors':t);o.value=t;});tags.value=tag;tags.addEventListener('change',function(){tag=tags.value;render();});var filters=U.node('select','studio-select',row);filters.setAttribute('aria-label','Preset collection');[['all','All presets'],['favorites','Favorites'],['recent','Recent'],['similar','Similar styles'],['user','Your presets']].forEach(function(x){var o=U.node('option','',filters,x[1]);o.value=x[0];});filters.value=filter;filters.addEventListener('change',function(){filter=filters.value;render();});seedTools(tools);var actions=U.node('div','studio-presets-row',tools);U.button('Save current '+{scene:'scene',rig:'rig',look:'look',move:'move',props:'prop set',animation:'animation'}[kind],actions,savePreset);U.button('Import preset',actions,importPreset);U.button('Choose Replace / Add',actions,function(){s.presetPreference=null;s.api.status('The next preset will ask how to apply it.');});if(C.dev)U.button('Preset gallery',actions,gallery);U.node('p','studio-preset-count studio-copy',tools);grid=U.node('div','studio-preset-browser-grid',browser);render();contain();C.accessibility.trap(browser);searchBox.focus();}
    function references(){var cards=C.data.cards,basic=cards.find(function(c){return C.rarity(c.rarity).tier===0;})||s.view.card,legend=cards.find(function(c){return C.rarity(c.rarity).id==='legendary'||c.rarity==='legendary';})||s.view.card;return [['Basic',basic,null,null],['Holographic',basic,'rainbow-holo',null],['Matte',basic,'matte',null],['Cosmic',basic,'galaxy-holo',null],['Gold Foil',basic,'gold-foil',null],['Classic',basic,null,'classic'],['Legendary',legend,null,null]].map(function(x){var variant=x[2]&&C.variant(x[2]),instance={cardId:x[1].id,instanceId:'gallery-'+x[0],serial:'REFERENCE',variantId:variant?variant.id:x[2]==='gold-foil'?'gold-foil':null,cardSkinId:x[3],packId:'standard',pulledAt:0};return {name:x[0],card:x[1],instance:instance,limited:!!x[2]&&x[2]!=='gold-foil'&&(!variant||!variant.studio)};});}
    function gallery(){close();browser=U.node('section','studio-preset-browser studio-preset-gallery glass',s.root);browser.dataset.gallery='true';browser.setAttribute('role','dialog');browser.setAttribute('aria-modal','true');browser.setAttribute('aria-label','Preset reference gallery');var head=U.node('header','studio-preset-heading',browser);U.node('h2','',head,'24 styles × 7 reference cards');U.button('Back to presets',head,function(){open('scene');});U.button('Close',head,close);U.node('p','studio-copy',browser,'Real renderer · reference cards only · no inventory changes. Unsupported coatings show a limited preview. Scroll to render visible tiles.');grid=U.node('div','studio-preset-gallery-grid',browser);var refs=references();P.catalog.filter(function(e){return e.kind==='scene';}).forEach(function(e){U.node('h3','studio-kicker studio-gallery-style',grid,e.name);refs.forEach(function(ref){var tile=U.node('article','studio-preset-tile',grid),canvas=U.node('canvas','',tile);canvas.width=160;canvas.height=100;canvas.setAttribute('aria-label',e.name+' · '+ref.name);U.node('strong','',tile,ref.name+(ref.limited?' · limited':''));hooks.queue({id:'gallery:'+e.id+':'+ref.name,name:e.name,kind:'scene',entry:e,reference:ref},canvas);});});contain();C.accessibility.trap(browser);head.querySelector('button').focus();s.api.dirty();}
    function thumbnail(entry){if(!entry.reference)return {scene:P.build(entry,s.scene,P.profile(s.view.card,s.view.instance,s.faces),store.presetSeed),faces:s.faces};var ref=entry.reference,faces=galleryFaces.get(ref.name);if(!faces){if(!pendingGallery){var revision=galleryRevision;pendingGallery=ref.name;var scene=S.defaults(ref.instance);C.studioFace.paint(ref.card,ref.instance,scene,'very-low',null,ref.name==='Gold Foil'?{studioReference:'gold-foil'}:null,function(){return !dead&&revision===galleryRevision;}).then(function(f){if(dead||revision!==galleryRevision){if(f)f.destroy();return;}pendingGallery=null;if(f){if(galleryFaces.size>=7){var key=galleryFaces.keys().next().value;galleryFaces.get(key).destroy();galleryFaces.delete(key);}galleryFaces.set(ref.name,f);}s.api.dirty();},function(error){if(dead||revision!==galleryRevision)return;pendingGallery=null;s.api.status('Reference preview unavailable: '+error.message);});}return null;}var base=S.defaults(ref.instance);return {scene:P.build(entry.entry,base,P.profile(ref.card,ref.instance,faces),store.presetSeed),faces:faces};}
    function key(e){if(browser&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}}C.keys.listen(s.root, 'keydown', 'src.studio.ui.presets.js.2', key,true);
    return {open:open,request:request,apply:applied,thumbnail:thumbnail,gallery:gallery,importText:importText,facesChanged:function(){if(browser&&browser.dataset.gallery!=='true')render();},destroy:function(){dead=true;close();C.keys.remove(s.root, 'keydown',key,true);},isOpen:function(){return !!browser;}};
  }
  C.studioPresetUI={create:create};
})(window.Cardable,window);
