(function(C,root){
  'use strict';
  var U=C.studioUI,E=C.studioEditing,S=C.studioScenes,K=C.studioCamera,P=C.studioProps;
  function create(s){
    var store=C.state.current.studio||(C.state.current.studio=S.normalize()),prefs=store.workspace||(store.workspace=S.normalize().workspace),selection=new Set(['card']),tool='select',space='global',shading='material',guide='none',grid=false,angle=false,magnet=false,isolated=false,drag=null,transition=null,menu=null,palette=null,autosave=null,dead=false,thumbnails=new Map(),thumbQueue=[],thumbRenderer=null,thumbCanvas=null,category='props',query='',tag='all',onlyFavorites=false,mood=1,lightAngle=0,moodBase=null,presetUI=null,thumbFaces=null,thumbObserver=null;
    s.root.classList.add('studio-2');s.root.dataset.mode=prefs.mode;s.root.style.setProperty('--studio-left',prefs.leftWidth+'px');s.root.style.setProperty('--studio-right',prefs.rightWidth+'px');
    var top=s.root.querySelector('.studio-topbar'),actions=s.root.querySelector('.studio-topbar-actions'),switcher=s.root.querySelector('.studio-mode-switch'),layout=s.root.querySelector('.studio-layout'),left=s.objects.parentElement,right=s.panel.parentElement;
    switcher.replaceChildren();var simpleButton=U.button('Simple',switcher,function(){mode('simple');}),proButton=U.button('Pro',switcher,function(){mode('pro');});simpleButton.dataset.workspace='simple';proButton.dataset.workspace='pro';
    Array.from(actions.children).forEach(function(el){if(el!==s.exit&&!el.classList.contains('cb-replay-action'))el.classList.add('studio-pro-only');});s.exit.setAttribute('aria-label','Exit studio');
    var presetsButton=U.button('Presets',actions,function(){presetUI.open('scene');});presetsButton.classList.add('studio-pro-only');actions.insertBefore(presetsButton,s.exit);
    var commandButton=U.button('Commands',actions,function(){commands();},'Commands · Ctrl/Cmd+K');commandButton.classList.add('studio-pro-only');actions.insertBefore(commandButton,s.exit);
    left.querySelector('.studio-kicker').textContent='LAYERS';var layersActions=U.node('div','studio-layer-tools',left);left.insertBefore(layersActions,s.objects);U.button('All',layersActions,function(){selectAll();});U.button('Invert',layersActions,function(){invert();});U.button('Arrange',layersActions,function(){arrangePanel();});
    var library=U.node('details','studio-library',left);library.open=true;U.node('summary','',library,'Library');var libraryBody=U.node('div','studio-library-body',library),search=U.node('input','studio-library-search',libraryBody);search.type='search';search.placeholder='Find something for the scene';search.setAttribute('aria-label','Search library');search.addEventListener('input',function(){query=search.value.toLowerCase();renderLibrary();});
    var categories=U.node('div','studio-library-tabs',libraryBody);['props','lights','styles','looks','cameras','sets','motion'].forEach(function(c){var b=U.button(c.charAt(0).toUpperCase()+c.slice(1),categories,function(){category=c;tag='all';renderLibrary();});b.dataset.category=c;});
    var filters=U.node('div','studio-library-filters',libraryBody),tags=U.node('select','studio-select',filters);tags.setAttribute('aria-label','Library tag');tags.addEventListener('change',function(){tag=tags.value;renderLibrary();});var favorites=U.button('Favorites',filters,function(){onlyFavorites=!onlyFavorites;renderLibrary();});var libraryItems=U.node('div','studio-library-items',libraryBody);
    var leftToggle=U.button('Layers',top,function(){prefs.leftClosed=!prefs.leftClosed;layoutState();savePreferences();}),rightToggle=U.button('Inspector',top,function(){prefs.rightClosed=!prefs.rightClosed;layoutState();savePreferences();});leftToggle.addEventListener('click',function(){if(root.innerWidth<=780){s.root.classList.toggle('studio-mobile-layers');prefs.leftClosed=false;layoutState();s.api.dirty();}});leftToggle.classList.add('studio-pro-only','studio-panel-toggle');rightToggle.classList.add('studio-pro-only','studio-panel-toggle');
    function resizeHandle(host,key){var handle=U.node('div','studio-panel-resize',host);handle.tabIndex=0;handle.setAttribute('role','separator');handle.setAttribute('aria-orientation','vertical');handle.setAttribute('aria-label','Resize '+(key==='leftWidth'?'Layers':'Inspector'));var start=null;function value(v){prefs[key]=Math.max(key==='leftWidth'?200:240,Math.min(key==='leftWidth'?360:380,v));s.root.style.setProperty(key==='leftWidth'?'--studio-left':'--studio-right',prefs[key]+'px');handle.setAttribute('aria-valuenow',prefs[key]);s.api.dirty();}handle.addEventListener('pointerdown',function(e){if(s.photoBusy||s.recordJob)return;e.preventDefault();start={x:e.clientX,width:prefs[key]};handle.setPointerCapture(e.pointerId);});handle.addEventListener('pointermove',function(e){if(start)value(start.width+(e.clientX-start.x)*(key==='leftWidth'?1:-1));});function end(){if(!start)return;start=null;savePreferences();}handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);handle.addEventListener('lostpointercapture',end);handle.addEventListener('keydown',function(e){if(!/^Arrow/.test(e.key))return;e.preventDefault();value(prefs[key]+(/Right|Up/.test(e.key)?10:-10));savePreferences();});value(prefs[key]);}
    resizeHandle(left,'leftWidth');resizeHandle(right,'rightWidth');
    var oldTools=s.root.querySelector('.studio-tools');oldTools.replaceChildren();['Set','Light','Camera','Animate','Look','Deliver'].forEach(function(p){var b=U.button(p,oldTools,function(){page(p);});b.dataset.page=p;});oldTools.setAttribute('aria-label','Pro pages');s.root.querySelector('.studio-hint').textContent='V SELECT · G / R / S TRANSFORM · F FRAME · SPACE PLAY · ? SHORTCUTS';
    var toolbar=U.node('nav','studio-viewport-toolbar',s.viewport);toolbar.setAttribute('aria-label','Viewport tools');[['select','Select · V'],['move','Move · G'],['rotate','Rotate · R'],['scale','Scale · S'],['camera','Camera navigation']].forEach(function(pair){var b=U.button(pair[0].charAt(0).toUpperCase()+pair[0].slice(1),toolbar,function(){setTool(pair[0]);},pair[1]);b.dataset.transformTool=pair[0];});
    function toggle(label,read,write){var b=U.button(label,toolbar,function(){write(!read());b.setAttribute('aria-pressed',String(read()));s.api.dirty();});b.setAttribute('aria-pressed',String(read()));return b;}
    toggle('Grid',function(){return grid;},function(v){grid=v;});toggle('Angle',function(){return angle;},function(v){angle=v;});toggle('Magnet',function(){return magnet;},function(v){magnet=v;});
    function choice(label,choices,read,write){var el=U.node('select','studio-select',toolbar);el.setAttribute('aria-label',label);choices.forEach(function(v){var p=Array.isArray(v)?v:[v,v],o=U.node('option','',el,p[1]);o.value=p[0];});el.value=read();el.addEventListener('change',function(){write(el.value);s.api.dirty();});return el;}
    toolbar.addEventListener('pointerdown',function(){closeMenu();});choice('Transform space',['global','local'],function(){return space;},function(v){space=v;});choice('Viewport shading',[['material','Material'],['preview','Preview'],['bounds','Bounds']],function(){return shading;},function(v){shading=v;});choice('Composition guides',[['none','No guides'],['thirds','Rule of thirds'],['golden','Golden ratio'],['center','Center cross'],['safe','Safe frames']],function(){return guide;},function(v){guide=v;});var crop=choice('Aspect crop',[['free','Free'],['1:1','Square'],['4:5','4:5'],['16:9','16:9'],['9:16','9:16'],['2.39:1','2.39:1'],['card','Card only']],function(){return s.scene.camera.aspect;},function(v){s.api.mutate(function(){s.scene.camera.aspect=v;},'Aspect crop');});
    var cube=U.node('div','studio-view-cube',s.viewport);['Front','Side','Top'].forEach(function(v){U.button(v,cube,function(){view(v);});});var projection=U.button('Perspective',cube,function(){s.api.mutate(function(){s.scene.camera.projection=s.scene.camera.projection==='ortho'?'perspective':'ortho';},'Toggle projection');projection.textContent=s.scene.camera.projection==='ortho'?'Ortho':'Perspective';});U.button('Frame',cube,function(){frameSelected();},'Frame selected · F');
    var svg=root.document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('studio-workspace-overlay');svg.setAttribute('aria-label','Transform axes, bounds and guides');s.viewport.appendChild(svg);
    var simple=U.node('section','studio-simple-controls',s.bottom),stylesRow=U.node('div','studio-style-row',simple);U.node('span','studio-kicker',stylesRow,'STYLE');var styles=U.node('div','studio-style-carousel',stylesRow);styles.setAttribute('aria-label','Scene styles');
    C.studioPresets.scenes.filter(function(name){return name!=='Surprise me';}).forEach(function(name){var b=U.button('',styles,function(){applyStyle(name);});b.dataset.style=name;b.setAttribute('aria-label','Style: '+name);var canvas=U.node('canvas','',b);canvas.width=160;canvas.height=100;canvas.setAttribute('aria-hidden','true');U.node('span','',b,name);queueThumbnail(name,canvas);});
    var simpleRow=U.node('div','studio-simple-row',simple),moodHolder=U.node('label','studio-simple-mood',simpleRow);U.node('span','',moodHolder,'Mood');var moodInput=U.node('input','',moodHolder);moodInput.type='range';moodInput.min=.25;moodInput.max=1.5;moodInput.step=.01;moodInput.value=1;moodInput.setAttribute('aria-label','Mood');moodInput.addEventListener('pointerdown',function(){rememberMood();s.api.begin('Adjust mood');});moodInput.addEventListener('input',function(){rememberMood();s.api.begin('Adjust mood');mood=Number(moodInput.value);s.scene.lights.forEach(function(l){var base=moodBase.lights.find(function(b){return b.id===l.id;});if(base)l.intensity=Math.min(20,base.intensity*mood);});['bloom','vignette','grain','aberration','flare','tiltShift'].forEach(function(k){s.scene.post[k]=Math.min(k==='grain'?.3:1,moodBase.post[k]*mood);});s.scene.post.contrast=Math.max(.25,Math.min(2,1+(moodBase.post.contrast-1)*mood));s.scene.post.saturation=Math.max(0,Math.min(2,1+(moodBase.post.saturation-1)*mood));['temperature','tint','halation'].forEach(function(k){s.scene.post[k]=Math.max(k==='halation'?0:-1,Math.min(1,moodBase.post[k]*mood));});['lift','gamma','gain'].forEach(function(k){var neutral=k==='lift'?0:1;s.scene.post[k]=moodBase.post[k].map(function(v){return Math.max(k==='lift'?-.2:.5,Math.min(k==='lift'?.2:2,neutral+(v-neutral)*mood));});});s.scene.post.exposure=Math.max(-2,Math.min(2,moodBase.post.exposure+(mood-1)*.3));s.api.dirty();});['change','blur'].forEach(function(name){moodInput.addEventListener(name,s.api.commit);});
    var dialHolder=U.node('label','studio-angle-dial',simpleRow);U.node('span','',dialHolder,'Light angle');var dial=U.node('input','',dialHolder);dial.type='range';dial.min=-180;dial.max=180;dial.step=1;dial.value=0;dial.setAttribute('aria-label','Light angle');dialHolder.style.setProperty('--light-angle','0deg');dial.addEventListener('input',function(){rememberMood();s.api.begin('Turn the lights');lightAngle=Number(dial.value);var a=lightAngle*Math.PI/180;dialHolder.style.setProperty('--light-angle',lightAngle+'deg');s.scene.lights.forEach(function(l){var base=moodBase.lights.find(function(b){return b.id===l.id;});if(!base||l.type==='ambient')return;var p=base.position;l.position=[p[0]*Math.cos(a)+p[2]*Math.sin(a),p[1],-p[0]*Math.sin(a)+p[2]*Math.cos(a)];l.rotation=base.rotation.slice();l.rotation[1]=((base.rotation[1]+lightAngle+180)%360+360)%360-180;});s.api.dirty();});['change','blur'].forEach(function(name){dial.addEventListener(name,s.api.commit);});
    var shotRow=U.node('div','studio-simple-shots',simpleRow);U.node('span','studio-kicker',shotRow,'SHOT');['Hero','Close-up','Reveal','Spin'].forEach(function(name){var b=U.button(name,shotRow,function(){shot(name);});b.dataset.shot=name;});
    var captures=U.node('div','studio-simple-captures',simple);U.button('Photo',captures,function(){if(!s.photoOptions){var old=s.panel;s.panel=root.document.createElement('div');C.studioPhotoPanel(s);s.panel=old;}s.api.capture();}).classList.add('studio-primary');var record=U.button('Record',captures,function(){if(s.recordJob)s.recordJob.stop(false);else C.studioRecording.start(s);});record.disabled=!C.studioRecording.supported();var clipDownload=U.button('Download clip',captures,function(){C.studioRecording.download(s);});clipDownload.hidden=true;
    var hint=U.node('div','studio-simple-tour',simple),hintStep=0,hints=['1 / 3 · Pick a style to set the scene.','2 / 3 · Mood softens or strengthens it. Turn Light angle to find the shine.','3 / 3 · Pick a shot. Photo keeps this moment; Record captures its movement.'];
    function tour(){hint.replaceChildren();hint.hidden=prefs.tourDone;if(hint.hidden)return;U.node('span','',hint,hints[hintStep]);U.button(hintStep===2?'Got it':'Next',hint,function(){if(++hintStep===3){prefs.tourDone=true;savePreferences();}tour();});U.button('Dismiss',hint,function(){prefs.tourDone=true;savePreferences();tour();});}tour();
    function rememberMood(){if(!moodBase)moodBase={lights:S.clone(s.scene.lights),post:S.clone(s.scene.post)};}
    function savePreferences(){if(!dead)C.state.save();}
    function layoutState(){left.hidden=prefs.mode==='simple'||prefs.leftClosed;right.hidden=prefs.mode==='simple'||prefs.rightClosed;leftToggle.hidden=prefs.mode==='simple';rightToggle.hidden=prefs.mode==='simple';s.root.classList.toggle('studio-left-closed',prefs.leftClosed);s.root.classList.toggle('studio-right-closed',prefs.rightClosed);leftToggle.setAttribute('aria-pressed',String(!prefs.leftClosed));rightToggle.setAttribute('aria-pressed',String(!prefs.rightClosed));}
    function mode(value){if(s.photoBusy||s.recordJob)return;cancel();s.api.commit();prefs.mode=value;if(s.lookUI)s.lookUI.show(value==='pro'&&prefs.page==='Look');s.keepTimeline=false;if(s.photoFilm)s.photoFilm.el.hidden=value==='simple'||prefs.page!=='Deliver';s.root.dataset.mode=value;s.root.querySelectorAll('.studio-pro-only,.studio-tools,.studio-viewport-toolbar,.studio-view-cube,.studio-hint,.studio-refine').forEach(function(el){el.hidden=value==='simple';});simple.hidden=value!=='simple';simpleButton.hidden=value==='simple';simpleButton.setAttribute('aria-pressed',String(value==='simple'));proButton.setAttribute('aria-pressed',String(value==='pro'));if(value==='simple')U.closeDirector(s);else page(prefs.page);layoutState();savePreferences();if(s.entered)s.viewport.focus({preventScroll:true});s.api.dirty();}
    function page(value){if(s.photoBusy||s.recordJob)return;prefs.page=value;s.root.dataset.page=value;if(s.photoFilm)s.photoFilm.el.hidden=prefs.mode==='simple'||value!=='Deliver';oldTools.querySelectorAll('button').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.page===value));});if(prefs.mode==='pro'){s.keepTimeline=false;U.closeDirector(s);s.api.select({Set:'card',Light:'lights',Camera:'camera',Animate:'director',Look:'look',Deliver:'photo'}[value]);}savePreferences();s.api.dirty();}
    function setTool(value){tool=value;toolbar.querySelectorAll('[data-transform-tool]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.transformTool===tool));});s.viewport.style.cursor=tool==='select'?'default':tool==='camera'?'grab':'crosshair';s.api.dirty();}
    function choose(ids,add){if(!add)selection.clear();ids.forEach(function(id){if(!E.get(s.scene,id))return;if(add&&selection.has(id))selection.delete(id);else selection.add(id);});var last=Array.from(selection).pop(),o=E.get(s.scene,last);if(o)s.api.select(E.kind(s.scene,o),o.id);else{s.selected=s.selectedId=null;s.panel.replaceChildren();U.node('p','studio-copy',s.panel,'Select an object in the stage or Layers.');layers();}s.api.dirty();}
    function selectAll(){choose(S.objects(s.scene).filter(function(o){return o.position&&!S.locked(s.scene,o);}).map(function(o){return o.id;}));}
    function invert(){choose(S.objects(s.scene).filter(function(o){return o.position&&!S.locked(s.scene,o)&&!selection.has(o.id);}).map(function(o){return o.id;}));}
    function edit(label,run){cancel();s.api.mutate(function(){run();},label);selection=new Set(Array.from(selection).filter(function(id){return !!E.get(s.scene,id);}));if(s.selected)s.api.select(s.selected,s.selectedId);layers();}
    function duplicate(){var next;edit('Duplicate selection',function(){next=E.duplicate(s.scene,Array.from(selection),s.renderer.kind==='Simple'?'very-low':s.tier);});if(next&&next.length)choose(next);}
    function remove(){edit('Delete selection',function(){E.remove(s.scene,Array.from(selection));});}
    function groupSelection(){var id;edit('Group selection',function(){id=E.group(s.scene,Array.from(selection));});if(id)choose([id]);}
    function ungroup(){var children=[];selection.forEach(function(id){var g=E.get(s.scene,id);if(g&&g.children)children=children.concat(g.children);});edit('Ungroup selection',function(){E.ungroup(s.scene,Array.from(selection));});choose(children);}
    function toggleObjects(property){edit((property==='visible'?'Show / hide':'Lock / unlock')+' selection',function(){selection.forEach(function(id){var o=E.get(s.scene,id);if(!o)return;if(property==='locked'){if(o.parentId&&S.locked(s.scene,E.get(s.scene,o.parentId)))return;o.locked=!o.locked;}else if(!S.locked(s.scene,o))o[property]=!o[property];});});}
    function arrange(method,axis){edit('Arrange: '+method,function(){E.arrange(s.scene,Array.from(selection),method,axis);});}
    function arrayPanel(method){closeMenu();var box=U.node('div','studio-inline-confirm',s.panel);box.setAttribute('aria-label',method+' array');U.node('span','',box,method==='circle'?'Circle array':'Grid array');var count=U.node('input','studio-array-number',box);count.type='number';count.min=2;count.max=16;count.value=4;count.setAttribute('aria-label','Array count');var spacing=U.node('input','studio-array-number',box);spacing.type='number';spacing.min=.1;spacing.max=5;spacing.step=.1;spacing.value=1.2;spacing.setAttribute('aria-label','Array spacing');U.button('Create',box,function(){var next;edit(method+' array',function(){next=E.array(s.scene,Array.from(selection),method,Number(count.value),Number(spacing.value),s.renderer.kind==='Simple'?'very-low':s.tier);});if(next)choose(next);});U.button('Cancel',box,function(){box.remove();});}
    function arrangePanel(){closeMenu();var menuItems=[['Grid array…',function(){arrayPanel('grid');}],['Circle array…',function(){arrayPanel('circle');}],['Align X',function(){arrange('align',0);}],['Align Y',function(){arrange('align',1);}],['Align Z',function(){arrange('align',2);}],['Distribute X',function(){arrange('distribute',0);}],['Distribute Y',function(){arrange('distribute',1);}],['Distribute Z',function(){arrange('distribute',2);}],['Grid arrangement',function(){arrange('grid');}],['Circle arrangement',function(){arrange('circle');}],['Mirror X',function(){arrange('mirror',0);}],['Snap to floor',function(){edit('Snap to floor',function(){E.snapFloor(s.scene,Array.from(selection));});}]];showMenu(menuItems,s.viewport.getBoundingClientRect().left+20,s.viewport.getBoundingClientRect().top+70);}
    function layerOrder(delta){edit(delta>0?'Raise layer':'Lower layer',function(){[s.scene.props,s.scene.lights,s.scene.groups].forEach(function(list){var order=delta>0?list.slice().reverse():list.slice();order.forEach(function(o){if(!selection.has(o.id)||S.locked(s.scene,o))return;var i=list.indexOf(o),j=i+delta;if(j<0||j>=list.length||selection.has(list[j].id))return;list.splice(i,1);list.splice(j,0,o);});});});}

    function layers(host){host=host||s.objects;var focusId=root.document.activeElement.dataset.layerId;host.replaceChildren();var byParent=new Map();S.objects(s.scene).forEach(function(o){var key=o.parentId||'';if(!byParent.has(key))byParent.set(key,[]);byParent.get(key).push(o);});function row(o,depth){var kind=E.kind(s.scene,o),el=U.node('div','studio-layer-row',host);el.style.setProperty('--depth',Math.min(8,depth));var b=U.button(o.name||{card:s.view.card.name,camera:'Camera',look:'Look',backdrop:'Backdrop'}[kind]||'Group',el,function(e){choose([o.id],e.shiftKey);});b.dataset.layerId=o.id;b.setAttribute('aria-pressed',String(selection.has(o.id)));U.icon(b,kind==='light'?'light':kind==='camera'||kind==='card'?'camera':kind==='look'?'palette':'props');var hide=U.button(o.visible===false?'○':'◉',el,function(){edit('Toggle visibility',function(){if(!S.locked(s.scene,o))o.visible=o.visible===false;});});hide.setAttribute('aria-label','Toggle visibility: '+(o.name||kind));hide.disabled=S.locked(s.scene,o);var lock=U.button(o.locked?'▣':'□',el,function(){edit('Toggle lock',function(){if(o.parentId&&S.locked(s.scene,E.get(s.scene,o.parentId)))return;o.locked=!o.locked;});});lock.setAttribute('aria-label','Toggle lock: '+(o.name||kind));(byParent.get(o.id)||[]).forEach(function(child){row(child,depth+1);});}(byParent.get('')||[]).forEach(function(o){row(o,0);});if(focusId){var b=Array.from(host.querySelectorAll('[data-layer-id]')).find(function(b){return b.dataset.layerId===focusId;});if(b)b.focus({preventScroll:true});}}
    function entries(){var out=[];if(category==='props')Object.keys(S.catalog).forEach(function(group){S.catalog[group].forEach(function(p){out.push({id:'prop:'+p[0],name:p[1],tag:group,kind:'prop',value:p[0]});});});else if(category==='lights'){C.studioLights.types.forEach(function(t){out.push({id:'light:'+t,name:t+' light',tag:'spatial',kind:'light',value:t});});C.studioPresets.catalog.filter(function(e){return e.kind==='rig';}).forEach(function(e){out.push({id:e.id,name:e.name,tag:'rig',kind:'preset',value:e});});}else{var kind={styles:'scene',looks:'look',cameras:'move',sets:'props',motion:'animation'}[category];C.studioPresets.catalog.filter(function(e){return e.kind===kind;}).forEach(function(e){out.push({id:e.id,name:e.name,tag:e.tags[0],kind:'preset',value:e});});}return out;}
    function renderLibrary(){var list=entries(),available=['all'].concat(Array.from(new Set(list.map(function(e){return e.tag;}))));tags.replaceChildren();available.forEach(function(t){var o=U.node('option','',tags,t==='all'?'All tags':t);o.value=t;});if(available.indexOf(tag)<0)tag='all';tags.value=tag;categories.querySelectorAll('button').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.category===category));});favorites.setAttribute('aria-pressed',String(onlyFavorites));libraryItems.replaceChildren();var shown=list.filter(function(e){return (!query||(e.name+' '+e.tag).toLowerCase().includes(query))&&(tag==='all'||tag===e.tag)&&(!onlyFavorites||prefs.favorites.indexOf(e.id)>=0);});shown.forEach(function(e){var row=U.node('div','studio-library-item',libraryItems),b=U.button(e.name,row,function(){insert(e);});b.draggable=true;b.dataset.libraryId=e.id;b.title=e.name+' · '+e.tag;b.addEventListener('dragstart',function(event){event.dataTransfer.setData('application/x-cardable-studio',e.id);event.dataTransfer.effectAllowed='copy';});if(e.kind==='preset'){var c=U.node('canvas','',b);c.width=160;c.height=100;b.insertBefore(c,b.firstChild);queueThumbnail(e.value,c);}var star=U.button(prefs.favorites.indexOf(e.id)>=0?'★':'☆',row,function(){var i=prefs.favorites.indexOf(e.id);if(i>=0)prefs.favorites.splice(i,1);else if(prefs.favorites.length<128)prefs.favorites.push(e.id);savePreferences();renderLibrary();});star.setAttribute('aria-label','Favorite '+e.name);star.setAttribute('aria-pressed',String(prefs.favorites.indexOf(e.id)>=0));});if(!shown.length)U.node('p','studio-copy',libraryItems,'No matches. Try another name or tag.');s.api.dirty();}
    function allEntries(){var current=category,list=[];['props','lights','styles','looks','cameras','sets','motion'].forEach(function(v){category=v;list=list.concat(entries());});category=current;return list;}
    function insert(entry,point){if(s.photoBusy||s.recordJob)return;if(entry.kind==='preset')return presetUI.request(entry.value);if(entry.kind==='camera')return view(entry.value);if(entry.kind==='look'){edit('Clean look',function(){if(!S.locked(s.scene,s.scene.post))Object.assign(s.scene.post,S.defaults().post);});return;}var count=s.scene.props.length+s.scene.lights.length;if(entry.kind==='prop')s.api.addProp(entry.value,point);else if(entry.kind==='light')s.api.addLight(entry.value,point);var o=E.get(s.scene,s.selectedId);if(count===s.scene.props.length+s.scene.lights.length)return;if(o)choose([o.id]);}
    s.viewport.addEventListener('dragover',function(e){if(Array.from(e.dataTransfer.types).indexOf('application/x-cardable-studio')>=0){e.preventDefault();e.dataTransfer.dropEffectAllowed='copy';}});s.viewport.addEventListener('drop',function(e){var id=e.dataTransfer.getData('application/x-cardable-studio'),entry=allEntries().find(function(x){return x.id===id;});if(!entry)return;e.preventDefault();var r=s.viewport.getBoundingClientRect(),display=s.api.presented().scene,m=K.matrices(display.camera,r.width/r.height,display.card),point=K.plane(K.ray(m,(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height),[0,0,0],m.basis.back);insert(entry,point&&point.map(function(v){return Math.max(-20,Math.min(20,grid?S.snap(v,.1):v));}));});
    function queueThumbnail(entry,canvas){if(typeof entry==='string')entry=C.studioPresets.find(entry);if(!entry||!canvas)return;var cached=thumbnails.get(entry.id);if(cached){canvas.getContext('2d').drawImage(cached,0,0,160,100);return;}thumbQueue=thumbQueue.filter(function(x){return x.canvas.isConnected;});var item={entry:entry,canvas:canvas,visible:false};thumbQueue.push(item);if(!thumbObserver&&root.IntersectionObserver)thumbObserver=new root.IntersectionObserver(function(records){records.forEach(function(r){var x=thumbQueue.find(function(x){return x.canvas===r.target;});if(x){x.visible=r.isIntersecting;if(x.visible)s.api.dirty();}else thumbObserver.unobserve(r.target);});});if(thumbObserver)thumbObserver.observe(canvas);else item.visible=true;s.api.dirty();}
    function releaseThumbnails(){if(thumbRenderer)thumbRenderer.destroy();thumbRenderer=thumbCanvas=thumbFaces=null;}
    function renderThumbnail(){if(!s.faces||!presetUI||s.photoBusy||s.recordJob)return false;thumbQueue=thumbQueue.filter(function(x){if(x.canvas.isConnected)return true;if(thumbObserver)thumbObserver.unobserve(x.canvas);return false;});var available=thumbQueue.filter(function(x){return x.visible&&x.canvas.checkVisibility();});if(!available.length){releaseThumbnails();return false;}var item=available[0],cached=thumbnails.get(item.entry.id);try{if(!cached){var preview=presetUI.thumbnail(item.entry);if(!preview)return false;if(thumbRenderer&&thumbFaces!==preview.faces){thumbRenderer.setFaces(preview.faces);thumbFaces=preview.faces;}if(!thumbRenderer){thumbFaces=preview.faces;thumbCanvas=root.document.createElement('canvas');thumbRenderer=s.renderer.kind==='Simple'?C.studioRenderer.simple(thumbCanvas,thumbFaces):C.studioRenderer.create(thumbCanvas,thumbFaces,'low');}var scene=preview.scene;scene.card.visible=true;scene.materialTime=0;thumbRenderer.draw(S.effective(scene,'low'),160,100,item.entry.reference?null:s.propAssets);cached=root.document.createElement('canvas');cached.width=160;cached.height=100;cached.getContext('2d').drawImage(thumbCanvas,0,0,160,100);thumbnails.set(item.entry.id,cached);if(thumbnails.size>72){var first=thumbnails.keys().next().value;thumbnails.get(first).width=thumbnails.get(first).height=1;thumbnails.delete(first);}}item.canvas.getContext('2d').drawImage(cached,0,0,160,100);}catch(error){item.canvas.getContext('2d').drawImage(s.faces.front,44,0,72,100);item.canvas.title='Limited preview: '+error.message;}if(thumbObserver)thumbObserver.unobserve(item.canvas);thumbQueue.splice(thumbQueue.indexOf(item),1);var pending=thumbQueue.some(function(x){return x.visible&&x.canvas.checkVisibility();});if(!pending)releaseThumbnails();return pending;}
    function tween(from){if(C.motion.reduced)return;transition={from:from,to:S.clone(s.scene),at:root.performance.now(),duration:400};s.api.dirty();}
    function applyStyle(name){closeMenu();presetUI.request(C.studioPresets.find(name));}
    function shot(name){presetUI.request(C.studioPresets.find(name==='Spin'?'Turntable':name));}
    function view(name){if(S.locked(s.scene,s.scene.camera))return s.api.status('Unlock the camera before navigating.');var from=S.clone(s.api.presented().scene);s.api.mutate(function(){s.scene.camera.autoFrame=false;s.scene.camera.yaw=name==='Side'?Math.PI/2:0;s.scene.camera.pitch=name==='Top'?Math.PI/2:0;s.scene.camera.roll=0;},name+' view');tween(from);}
    function frameSelected(cardOnly){if(S.locked(s.scene,s.scene.camera))return s.api.status('Unlock the camera before navigating.');var from=S.clone(s.api.presented().scene);edit(cardOnly?'Frame card':'Frame selected',function(){var b=E.bounds(s.scene,cardOnly?['card']:Array.from(selection));if(!b)return;s.scene.camera.target=b.center;s.scene.camera.lockToCard=false;s.scene.camera.autoFrame=false;var r=s.viewport.getBoundingClientRect(),size=Math.max(b.size[1],b.size[0]/Math.max(.1,r.width/r.height),b.size[2],.3)*1.3;s.scene.camera.orthoScale=Math.max(.2,Math.min(20,size));s.scene.camera.distance=Math.max(1.3,Math.min(9,size/(2*Math.tan(s.scene.camera.fov*Math.PI/360))+b.size[2]/2));});tween(from);}

    function inspectorReset(kind,id){if(kind==='quality'){s.api.quality('global');return;}if(kind==='history'){s.api.jumpHistory(0);return;}var o=E.get(s.scene,id||({card:'card',camera:'camera',look:'look',backdrop:'backdrop'}[kind]));edit('Reset '+kind,function(){var defaults=S.defaults(s.view.instance);if(o){if(S.locked(s.scene,o))throw Error('Unlock the object before resetting it.');var k=E.kind(s.scene,o),base=k==='light'?S.light({type:o.type}):k==='prop'?P.create(o.type):k==='group'?{visible:true,locked:false}:defaults[k==='look'?'post':k];if(base){var meta={id:o.id,parentId:o.parentId,name:o.name,visible:o.visible,locked:o.locked,source:o.source,instances:o.instances,packId:o.packId};Object.assign(o,base);Object.keys(meta).forEach(function(key){if(meta[key]!==undefined)o[key]=meta[key];});}}else if(kind==='lights'){if(s.scene.lights.some(function(l){return S.locked(s.scene,l);}))throw Error('Unlock the lights before resetting the rig.');s.scene.lights=C.studioPresets.lights('Studio',s.tier);}else if(kind==='director'){s.scene.keyframes=[];s.scene.animation=defaults.animation;s.scene.director=defaults.director;s.director=S.clone(defaults.director);s.director=C.studioDirector.create(s);}else if(kind==='props'){s.scene.props=s.scene.props.filter(function(p){return S.locked(s.scene,p);});}else if(kind==='group'&&o){o.visible=true;}else if(kind==='photo')s.photoOptions=null;else if(kind==='scenes')s.jsonDraft=null;});}
    function inspected(kind,id){if(id&&E.get(s.scene,id)&&!selection.has(id)){selection.clear();selection.add(id);}if(kind==='card'&&!id&&!selection.size)selection.add('card');s.keepTimeline=prefs.mode==='pro'&&prefs.page==='Animate';if(s.keepTimeline&&(!s.directorDock||s.dockScene!==s.scene)&&kind!=='director'){var panel=s.panel,selected=s.selected,selectedId=s.selectedId,staging=root.document.createElement('div');s.panel=staging;s.keepTimeline=false;s.workspaceBuildingTimeline=true;C.studioDirectorPanel(s);s.workspaceBuildingTimeline=false;s.dockScene=s.scene;s.keepTimeline=true;s.panel=panel;s.selected=selected;s.selectedId=selectedId;}
      if(kind==='look')C.studioLook.panel(s);
      if(s.lookUI)s.lookUI.show(kind==='look'&&prefs.mode==='pro');
      s.panel.querySelectorAll('.studio-panel-helper').forEach(function(el){el.remove();});if(kind==='director')s.dockScene=s.scene;var helper=U.node('div','studio-panel-helper',null),text={card:'Select, place and tilt the primary subject.',light:'Position and soften this light. Color stays in the scene.',lights:'Add a light or choose a rig, within the active tier.',prop:'Place, size and material the selected prop.',props:'Add procedural props from Library, or drag them onto the stage.',camera:'Right/middle drag orbits; Shift pans; wheel zooms.',look:'Lens controls affect the image, with tier-aware detail.',backdrop:'A quiet backdrop lets the card lead.',director:'Simple shots are editable here. Space plays the timeline.',photo:'Capture this composition, or keep it in your album.',scenes:'Save a composition; loading preserves your collected serial.',history:'Choose a named edit to return to that moment.',quality:'Override the studio quality without changing the game.',group:'Transforms apply to the unlocked descendants.'}[kind]||'Select scene objects and refine the composition.';U.node('p','',helper,text);var reset=U.button('Reset',helper,function(){inspectorReset(kind,id);});reset.disabled=kind==='presets'||kind==='objects';s.panel.insertBefore(helper,s.panel.querySelector('h2')&&s.panel.querySelector('h2').nextSibling||s.panel.firstChild);
      if(kind==='card'){U.vector(s,'Position',s.scene.card.position,-20,20,.01,function(){},S.locked(s.scene,s.scene.card));U.vector(s,'Scale',s.scene.card.scale,.05,6,.01,function(){},S.locked(s.scene,s.scene.card));U.field(s,'Rotation Z','number',s.scene.card.rotationZ,-180,180,1,function(v){s.scene.card.rotationZ=v;},S.locked(s.scene,s.scene.card));}
      if(kind==='camera'){U.select(s,'Projection',s.scene.camera.projection,[['perspective','Perspective'],['ortho','Orthographic']],function(v){s.scene.camera.projection=v;});U.field(s,'Orthographic height','number',s.scene.camera.orthoScale,.2,20,.05,function(v){s.scene.camera.orthoScale=v;});}
      var more=null;Array.from(s.panel.children).forEach(function(el){if(el.matches('.studio-kicker,.studio-panel-title,.studio-panel-helper'))return;if(el.matches('.studio-section-title')){more=U.node('details','studio-inspector-section',null);more.open=true;var summary=U.node('summary','',more,el.textContent),body=U.node('div','',more);el.replaceWith(more);more=body;}else{if(!more){var detail=U.node('details','studio-inspector-section',null);detail.open=true;U.node('summary','',detail,'Settings');more=U.node('div','',detail);el.before(detail);}more.appendChild(el);}});
      layers();crop.value=s.scene.camera.aspect;projection.textContent=s.scene.camera.projection==='ortho'?'Ortho':'Perspective';s.root.classList.toggle('is-director',s.keepTimeline);if(prefs.mode==='simple'){s.keepTimeline=false;U.closeDirector(s);}if(s.photoFilm)s.photoFilm.el.hidden=prefs.mode==='simple'||prefs.page!=='Deliver';s.api.dirty();}
    function closeMenu(){if(menu){menu.remove();menu=null;s.viewport.focus({preventScroll:true});}}
    function showMenu(items,x,y){closeMenu();menu=U.node('div','context-panel studio-context-menu glass',s.root);menu.setAttribute('role','menu');menu.setAttribute('aria-label','Studio commands');items.forEach(function(item){var b=U.button(item[0],menu,function(){closeMenu();item[1]();});b.classList.add('context-item');b.setAttribute('role','menuitem');});var r=s.root.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.width-230,x-r.left))+'px';menu.style.top=Math.max(8,Math.min(r.height-menu.offsetHeight-8,y-r.top))+'px';menu.querySelector('button').focus({preventScroll:true});}
    function context(event){if(s.closing||s.photoBusy||s.recordJob)return;event.preventDefault();event.stopImmediatePropagation();var rect=s.viewport.getBoundingClientRect();showMenu([['Frame selected',frameSelected],['Duplicate',duplicate],['Delete',remove],['Group',groupSelection],['Ungroup',ungroup],['Arrange…',arrangePanel],['Hide / show',function(){toggleObjects('visible');}],['Lock / unlock',function(){toggleObjects('locked');}],['Isolate / show all',function(){isolated=!isolated;s.api.dirty();}],['Commands…',commands]],Number.isFinite(event.clientX)?event.clientX:rect.left+rect.width/2,Number.isFinite(event.clientY)?event.clientY:rect.top+rect.height/2);}
    function commandList(){return [['Grid array','',function(){arrayPanel('grid');}],['Circle array','',function(){arrayPanel('circle');}],['Select all','Ctrl/Cmd+A',selectAll],['Invert selection','',invert],['Group selection','Ctrl/Cmd+G',groupSelection],['Ungroup','Ctrl/Cmd+Shift+G',ungroup],['Duplicate','Ctrl/Cmd+D · Shift+D',duplicate],['Delete','X',remove],['Hide / show','',function(){toggleObjects('visible');}],['Lock / unlock','',function(){toggleObjects('locked');}],['Isolate / show all','/',function(){isolated=!isolated;s.api.dirty();}],['Frame selected','F',frameSelected],['Frame card','Home',function(){frameSelected(true);}],['Align X','',function(){arrange('align',0);}],['Align Y','',function(){arrange('align',1);}],['Align Z','',function(){arrange('align',2);}],['Distribute X','',function(){arrange('distribute',0);}],['Distribute Y','',function(){arrange('distribute',1);}],['Distribute Z','',function(){arrange('distribute',2);}],['Grid arrangement','',function(){arrange('grid');}],['Circle arrangement','',function(){arrange('circle');}],['Mirror X','',function(){arrange('mirror',0);}],['Mirror Y','',function(){arrange('mirror',1);}],['Mirror Z','',function(){arrange('mirror',2);}],['Snap to floor','',function(){edit('Snap to floor',function(){E.snapFloor(s.scene,Array.from(selection));});}],['Snap to card','',function(){edit('Snap to card',function(){var p=s.scene.card.position;E.members(s.scene,Array.from(selection)).forEach(function(o){if(o!==s.scene.card&&!S.locked(s.scene,o)){o.position[0]=p[0];o.position[2]=p[2];}});});}],['Undo','Ctrl/Cmd+Z',function(){s.api.restore(false);}],['Redo','Ctrl/Cmd+Shift+Z',function(){s.api.restore(true);}],['History','',function(){s.api.select('history');}],['Scenes','',function(){s.api.select('scenes');}],['Quality','',function(){s.api.select('quality');}],['Simple / Pro','Tab',function(){mode(prefs.mode==='simple'?'pro':'simple');}]].concat(['Set','Light','Camera','Animate','Look','Deliver'].map(function(p){return ['Open '+p+' page','',function(){mode('pro');page(p);}];}));}
    function closePalette(){if(palette){C.accessibility.release(palette);palette.remove();palette=null;s.viewport.focus({preventScroll:true});}}
    function runShortcut(value){key({key:value,target:s.viewport,preventDefault:function(){}});}
    function commands(help){closeMenu();closePalette();palette=U.node('section','studio-command-palette glass',s.root);palette.setAttribute('role','dialog');palette.setAttribute('aria-label',help?'Studio shortcuts':'Studio command palette');var head=U.node('div','studio-palette-heading',palette);U.node('strong','',head,help?'Studio shortcuts':'Find a command');U.button('Close',head,closePalette);var input=U.node('input','studio-library-search',palette);input.type='search';input.placeholder=help?'Find a shortcut':'Type a command';input.setAttribute('aria-label','Search studio commands');var list=U.node('div','studio-command-results',palette);function render(){list.replaceChildren();var all=(C.commands?Array.from(C.commands.entries.values()).filter(function(c){return c.id.indexOf('studio2.command.')===0;}).map(function(c){return [c.label,c.hotkey,c.run];}):commandList()).concat([['Select','V',function(){setTool('select');}],['Move','G',function(){setTool('move');}],['Rotate','R',function(){setTool('rotate');}],['Scale','S',function(){setTool('scale');}],['Play / pause','Space',function(){s.director.play();}],['Shuttle reverse','J',function(){runShortcut('j');}],['Shuttle forward','L',function(){runShortcut('l');}],['Stop playback / capture key','K',function(){runShortcut('k');}],['Set work area in','I',function(){runShortcut('i');}],['Set work area out','O',function(){runShortcut('o');}],['Add marker','M',function(){runShortcut('m');}],['Lower layer','[',function(){layerOrder(-1);}],['Raise layer',']',function(){layerOrder(1);}]]);all.filter(function(c){return (c[0]+' '+c[1]).toLowerCase().includes(input.value.toLowerCase());}).forEach(function(c){var b=U.button('',list,function(){closePalette();c[2]();});U.node('span','',b,c[0]);U.node('kbd','',b,c[1]);});}input.addEventListener('input',render);input.addEventListener('keydown',function(e){if(e.key==='ArrowDown'){e.preventDefault();var b=list.querySelector('button');if(b)b.focus();}else if(e.key==='Enter'){e.preventDefault();var b=list.querySelector('button');if(b)b.click();}});render();C.accessibility.trap(palette);input.focus({preventScroll:true});}
    function key(event){var k=String(event.key).toLowerCase(),control=event.ctrlKey||event.metaKey,typing=event.target.closest('input,select,textarea,[contenteditable]');if(k==='escape'){if(palette){closePalette();event.preventDefault();return true;}if(menu){closeMenu();event.preventDefault();return true;}if(drag){cancel();event.preventDefault();return true;}if(isolated){isolated=false;s.api.dirty();event.preventDefault();return true;}}
      if(menu||palette){if(k==='tab'){var list=C.accessibility.focusables(menu||palette),i=list.indexOf(root.document.activeElement);event.preventDefault();if(list.length)list[(i+(event.shiftKey?-1:1)+list.length)%list.length].focus();return true;}if(k==='arrowdown'||k==='arrowup'){var host=menu||palette,list=Array.from(host.querySelectorAll('button')),i=list.indexOf(root.document.activeElement);event.preventDefault();list[(i+(k==='arrowdown'?1:-1)+list.length)%list.length].focus();}return true;}
      if(s.photoBusy||s.recordJob)return false;if(control&&k==='k'){event.preventDefault();commands();return true;}if(typing||event.target.closest('button,summary'))return false;
      var handled=true;if(k==='tab'&&!event.shiftKey)mode(prefs.mode==='simple'?'pro':'simple');else if(control&&k==='g'){if(event.shiftKey)ungroup();else groupSelection();}else if(control&&k==='a'){if(event.shiftKey)invert();else selectAll();}else if((control||event.shiftKey)&&k==='d')duplicate();else if(control)return false;else if(k==='?')commands(true);else if(k==='v')setTool('select');else if(k==='g')setTool('move');else if(k==='r')setTool('rotate');else if(k==='s')setTool('scale');else if(k==='x'||k==='delete'||k==='backspace')remove();else if(k==='f')frameSelected();else if(k==='home')frameSelected(true);else if(k==='/'){isolated=!isolated;s.api.dirty();}else if(k==='['||k===']')layerOrder(k===']'?1:-1);else if(k===' '){if(!event.repeat)s.director.play();}else if(k==='j'||k==='l'){if(C.motion.reduced||s.renderer.kind==='Simple')s.api.status('Motion is paused. Use the timeline to choose a still frame.');else{s.director.preview=true;s.director.playing=true;s.director.direction=k==='j'?-1:1;if(s.director.time<=s.scene.animation.workArea.in&&k==='j')s.director.time=s.scene.animation.workArea.out;s.api.dirty();}}else if(k==='k'){if(s.director.playing)s.director.pause();else if(!s.scene.animation.autoKey)s.director.capture(s.selected==='light'?s.selectedId:'camera');}else if(k==='i'||k==='o'){edit('Set work area '+(k==='i'?'in':'out'),function(){var a=s.scene.animation.workArea;a[k==='i'?'in':'out']=s.director.time;if(a.out<a.in)a[k==='i'?'out':'in']=s.director.time;});}else if(k==='m'){edit('Add marker',function(){if(s.scene.animation.markers.length>=96)throw Error('Marker limit reached: 96.');s.scene.animation.markers.push({id:'marker-'+root.crypto.randomUUID(),name:'Marker '+(s.scene.animation.markers.length+1),time:s.director.time,color:[.6,.6,.6]});});}else handled=false;if(handled)event.preventDefault();return handled;}

    function element(tag,attrs,parent){var el=root.document.createElementNS(svg.namespaceURI,tag);Object.keys(attrs||{}).forEach(function(k){el.setAttribute(k,attrs[k]);});if(parent)parent.appendChild(el);return el;}
    var guideLayer=element('g',{'class':'studio-composition-guides'},svg),boundsLayer=element('g',{'class':'studio-layout-bounds'},svg),gizmoLayer=element('g',{'class':'studio-transform-gizmo'},svg),marquee=element('rect',{'class':'studio-marquee',hidden:'',x:0,y:0,width:0,height:0},svg),distance=element('text',{'class':'studio-distance-label'},svg),handles=[];
    ['X','Y','Z','XY','XZ','YZ','XYZ'].forEach(function(name){var g=element('g',{'class':'studio-transform-handle','data-axis':name,role:'button',tabindex:0,'aria-label':'Transform '+name},gizmoLayer);element('title',{},g).textContent=name+' · drag; Shift fine; Ctrl snaps';var hit=element('path',{'class':'studio-axis-hit'},g),shape=element('path',{'class':'studio-axis-shape'},g),text=element('text',{},g);text.textContent=name;g.addEventListener('pointerdown',function(e){if(e.button!==0)return;e.stopPropagation();e.preventDefault();startTransform(e,name,g);});g.addEventListener('keydown',function(e){if(!/^Arrow/.test(e.key)||s.photoBusy||s.recordJob)return;e.preventDefault();e.stopPropagation();var ids=Array.from(selection),b=E.bounds(s.scene,ids),original=new Map(E.members(s.scene,ids).map(function(o){return [o.id,S.clone(o)];})),axis=axes()[['X','Y','Z'].indexOf(name)]||[1,1,1],sign=/Left|Down/.test(e.key)?-1:1;if(!b)return;edit('Nudge '+tool,function(){var delta=tool==='move'?axis.map(function(v){return v*sign*(e.shiftKey?.01:.1);}):tool==='rotate'?sign*(angle?15:e.shiftKey?1:5):1+sign*(e.shiftKey?.01:.1);E.transform(s.scene,ids,original,tool,delta,axis,b.center);});});handles.push({name:name,g:g,hit:hit,shape:shape,text:text});});
    function axes(){var o=E.members(s.scene,Array.from(selection))[0];if(space==='local'&&o){var m=E.model(s.scene,o);return [0,1,2].map(function(i){return K.unit([m[i*4],m[i*4+1],m[i*4+2]]);});}return [[1,0,0],[0,1,0],[0,0,1]];}
    function position(event,rect){return [(event.clientX-rect.left)/rect.width,(event.clientY-rect.top)/rect.height];}
    function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
    function startTransform(event,name,target){if(s.closing||s.photoBusy||s.recordJob||s.renderer.kind==='Simple')return;var ids=Array.from(selection),objects=E.members(s.scene,ids).filter(function(o){return !S.locked(s.scene,o);});if(!objects.length)return s.api.status('Select an unlocked object.');cancel();transition=null;s.api.commit();s.api.begin('Transform '+(ids.length>1?'selection':objects[0].name||'card'),true);var display=s.api.presented().scene;objects.forEach(function(o){var shown=display.props.concat(display.lights).find(function(p){return p.id===o.id;});if(shown){o.position=shown.position.slice();if(shown.rotation)o.rotation=shown.rotation.slice();}});if(event.altKey){var next;try{next=E.duplicate(s.scene,ids,s.tier);}catch(error){s.api.cancel();return s.api.status(error.message);}ids=next;selection=new Set(next);objects=E.members(s.scene,ids);}
      var b=E.bounds(s.scene,ids),rect=s.viewport.getBoundingClientRect(),m=K.matrices(display.camera,rect.width/rect.height,display.card),basis=axes(),indices=name==='XYZ'?[0,1,2]:name.split('').map(function(a){return ['X','Y','Z'].indexOf(a);}),axis=basis[indices[0]],normal=indices.length===2?K.unit(cross(basis[indices[0]],basis[indices[1]])):K.unit(cross(axis,cross(m.basis.back,axis))),p=position(event,rect),point=K.plane(K.ray(m,p[0],p[1]),b.center,normal),screen=K.project(m,b.center),end=K.project(m,b.center.map(function(v,i){return v+axis[i]*.6;})),original=new Map(objects.map(function(o){return [o.id,S.clone(o)];}));drag={type:'transform',id:event.pointerId,target:target,rect:rect,m:m,ids:ids,original:original,pivot:b.center,axis:axis,basis:basis,indices:indices,normal:normal,point:point,startX:event.clientX,startY:event.clientY,screen:[screen.x*rect.width+rect.left,screen.y*rect.height+rect.top],direction:[(end.x-screen.x)*rect.width,(end.y-screen.y)*rect.height],startAngle:Math.atan2(event.clientY-screen.y*rect.height-rect.top,event.clientX-screen.x*rect.width-rect.left)};target.setPointerCapture(event.pointerId);s.api.dirty();}
    function down(event){if(event.target.closest('button,input,select,summary,[data-axis]'))return true;if(s.closing||s.photoBusy||s.recordJob||!s.renderer)return true;if(event.button!==0&&event.button!==1&&event.button!==2)return true;closeMenu();transition=null;var rect=s.viewport.getBoundingClientRect();if(s.focusPick)return false;event.preventDefault();s.viewport.focus({preventScroll:true});if(event.button!==0||event.shiftKey&&tool!=='select'||tool==='camera'||prefs.mode==='simple'){if(S.locked(s.scene,s.scene.camera))return s.api.status('Unlock the camera before navigating.');s.api.commit();s.api.begin(event.shiftKey?'Pan camera':'Orbit camera',true);if(s.scene.camera.autoFrame)s.api.frame();drag={type:'camera',id:event.pointerId,target:s.viewport,pan:event.shiftKey,startX:event.clientX,startY:event.clientY,x:event.clientX,y:event.clientY,rect:rect,button:event.button};s.viewport.setPointerCapture(event.pointerId);return true;}
      var display=s.api.presented().scene,m=K.matrices(display.camera,rect.width/rect.height,display.card),p=position(event,rect),hits=E.pick(display,m,p[0],p[1]),id=hits[0];if(event.altKey&&hits.length){var current=hits.indexOf(s.selectedId||Array.from(selection).pop());id=hits[(current+1)%hits.length];}if(id){if(!selection.has(id)||event.shiftKey)choose([id],event.shiftKey);if(tool!=='select'&&!event.shiftKey){startTransform(event,'XY',s.viewport);return true;}}
      drag={type:'selection',id:event.pointerId,target:s.viewport,startX:event.clientX,startY:event.clientY,x:event.clientX,y:event.clientY,add:event.shiftKey,hit:id,rect:rect,m:m,display:display};s.viewport.setPointerCapture(event.pointerId);return true;}
    function move(event){if(!drag||event.pointerId!==drag.id)return;var d=drag,dx=event.clientX-d.startX,dy=event.clientY-d.startY;if(d.type==='camera'){if(d.pan)K.pan(s.scene.camera,event.clientX-d.x,event.clientY-d.y,d.rect.height);else K.orbit(s.scene.camera,event.clientX-d.x,event.clientY-d.y);d.x=event.clientX;d.y=event.clientY;}
      else if(d.type==='selection'){d.x=event.clientX;d.y=event.clientY;if(Math.hypot(dx,dy)>4){marquee.removeAttribute('hidden');marquee.setAttribute('x',Math.min(d.startX,d.x)-d.rect.left);marquee.setAttribute('y',Math.min(d.startY,d.y)-d.rect.top);marquee.setAttribute('width',Math.abs(dx));marquee.setAttribute('height',Math.abs(dy));}}
      else{var fine=event.shiftKey?.1:1,delta,axis=d.axis;if(tool==='move'){var p=position(event,d.rect),point=K.plane(K.ray(d.m,p[0],p[1]),d.pivot,d.normal),v=point&&d.point?point.map(function(n,i){return (n-d.point[i])*fine;}):axis.map(function(n){return n*(-dy)*.008*fine;});if(d.indices.length===1){var amount=K.dot(v,axis);if(grid||event.ctrlKey)amount=S.snap(amount,.1);delta=axis.map(function(n){return n*amount;});}else delta=v.map(function(n){return grid||event.ctrlKey?S.snap(n,.1):n;});if(magnet){var moving=E.members(s.scene,d.ids),others=E.members(s.scene,S.objects(s.scene).filter(function(o){return o.position&&moving.indexOf(o)<0;}).map(function(o){return o.id;}));for(var j=0;j<3;j++){if(space==='global'&&d.indices.indexOf(j)<0)continue;var value=d.pivot[j]+delta[j],nearest=others.map(function(o){return o.position[j];}).concat(j===1?[-.9+d.pivot[1]-E.bounds(s.scene,d.ids).min[1]]:[s.scene.card.position[j]]).sort(function(a,b){return Math.abs(a-value)-Math.abs(b-value);})[0];if(Math.abs(nearest-value)<.08)delta[j]=nearest-d.pivot[j];}}distance.textContent=delta.map(function(v){return v.toFixed(2);}).join(' · ')+' units';}
        else if(tool==='rotate'){var current=Math.atan2(event.clientY-d.screen[1],event.clientX-d.screen[0]),a=current-d.startAngle;a=((a+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;delta=a*180/Math.PI*fine*(K.dot(axis,d.m.basis.back)<0?-1:1);if(angle||event.ctrlKey)delta=S.snap(delta,15);distance.textContent=delta.toFixed(1)+'°';}
        else{var length=Math.hypot.apply(Math,d.direction),change=length>5?(dx*d.direction[0]+dy*d.direction[1])/length:(dx-dy),factor=Math.max(.05,Math.min(8,1+change*.01*fine));if(grid||event.ctrlKey)factor=S.snap(factor,.1);delta=d.indices.length===3?factor:[0,1,2].map(function(i){return d.indices.indexOf(i)>=0?factor:1;});distance.textContent=factor.toFixed(2)+' ×';}E.transform(s.scene,d.ids,d.original,tool,delta,axis,d.pivot);distance.setAttribute('x',event.clientX-d.rect.left+16);distance.setAttribute('y',event.clientY-d.rect.top-12);}
      s.api.dirty();}
    function up(event){if(!drag||event&&event.pointerId!==drag.id)return;var d=drag;drag=null;if(d.target.hasPointerCapture(d.id))d.target.releasePointerCapture(d.id);marquee.setAttribute('hidden','');distance.textContent='';if(d.type==='selection'){var dx=d.x-d.startX,dy=d.y-d.startY;if(Math.hypot(dx,dy)>4){var l=(Math.min(d.x,d.startX)-d.rect.left)/d.rect.width,r=(Math.max(d.x,d.startX)-d.rect.left)/d.rect.width,t=(Math.min(d.y,d.startY)-d.rect.top)/d.rect.height,b=(Math.max(d.y,d.startY)-d.rect.top)/d.rect.height,ids=E.members(d.display,S.objects(s.scene).map(function(o){return o.id;})).filter(function(o){var p=K.project(d.m,o.position);return p.front&&p.x>=l&&p.x<=r&&p.y>=t&&p.y<=b;}).map(function(o){return o.id;});choose(ids,d.add);}else if(!d.hit&&!d.add)choose([]);}else{s.api.commit();if(d.type==='transform'){layers();var last=Array.from(selection).pop(),o=E.get(s.scene,last);if(o)s.api.select(E.kind(s.scene,o),o.id);}if(d.type==='camera'&&d.button===2&&event&&Math.hypot(event.clientX-d.startX,event.clientY-d.startY)<4)context(event);}s.api.dirty();}
    function cancel(rollback){transition=null;if(!drag)return;var d=drag;drag=null;if(d.target.hasPointerCapture(d.id))d.target.releasePointerCapture(d.id);marquee.setAttribute('hidden','');distance.textContent='';if(d.type!=='selection'){if(rollback!==false)s.api.cancel();else s.api.commit();}s.api.dirty();}
    s.viewport.addEventListener('pointermove',move);s.viewport.addEventListener('pointerup',up);s.viewport.addEventListener('pointercancel',function(){cancel();});s.viewport.addEventListener('lostpointercapture',function(){if(drag)cancel();});svg.addEventListener('pointermove',move);svg.addEventListener('pointerup',up);svg.addEventListener('pointercancel',function(){cancel();});svg.addEventListener('lostpointercapture',function(){if(drag)cancel();});

    function draw(scene,width,height){svg.setAttribute('viewBox','0 0 '+width+' '+height);svg.style.display=prefs.mode==='pro'&&s.root.classList.contains('is-ready')?'':'none';guideLayer.replaceChildren();boundsLayer.replaceChildren();var camera=scene.camera,m=K.matrices(camera,width/Math.max(1,height),scene.card),ratio=K.aspect(camera.aspect),fw=ratio?Math.min(width,height*ratio)*.9:width*.9,fh=ratio?fw/ratio:height*.9,l=(width-fw)/2,t=(height-fh)/2;
      function line(a,b,host,cls){if(!a.front||!b.front||[a.x,a.y,b.x,b.y].some(function(v){return !Number.isFinite(v)||Math.abs(v)>8;}))return;element('path',{d:'M'+(a.x*width)+' '+(a.y*height)+'L'+(b.x*width)+' '+(b.y*height),'class':cls||''},host);}
      if(guide==='thirds'||guide==='golden'){var splits=guide==='thirds'?[1/3,2/3]:[.382,.618];splits.forEach(function(k){element('path',{d:'M'+(l+fw*k)+' '+t+'V'+(t+fh)+' M'+l+' '+(t+fh*k)+'H'+(l+fw)},guideLayer);});}else if(guide==='center')element('path',{d:'M'+(width/2-14)+' '+height/2+'h28M'+width/2+' '+(height/2-14)+'v28'},guideLayer);else if(guide==='safe')[.8,.9].forEach(function(k){element('rect',{x:l+fw*(1-k)/2,y:t+fh*(1-k)/2,width:fw*k,height:fh*k},guideLayer);});
      var selectedIds=new Set(E.members(s.scene,Array.from(selection)).map(function(o){return o.id;})),objects=[scene.card].concat(scene.lights,scene.props).filter(function(o){return o.visible!==false&&(shading==='bounds'||selectedIds.has(o.id));});objects.forEach(function(o){var corners=E.corners(scene,o).map(function(v){return K.project(m,v);});for(var offset=0;offset<corners.length;offset+=8)for(var i=0;i<8;i++)[1,2,4].forEach(function(bit){if(!(i&bit))line(corners[offset+i],corners[offset+(i|bit)],boundsLayer,selectedIds.has(o.id)?'is-selected':'');});if(magnet&&selectedIds.has(o.id)){var at=K.project(m,o.position),card=K.project(m,scene.card.position);line(at,card,boundsLayer,'studio-smart-guide');var label=element('text',{x:(at.x+card.x)*width/2,y:(at.y+card.y)*height/2-8},boundsLayer);label.textContent=Math.hypot.apply(Math,o.position.map(function(v,i){return v-scene.card.position[i];})).toFixed(2)+' units';}});
      var b=E.bounds(s.scene,Array.from(selection)),editable=E.members(s.scene,Array.from(selection)).some(function(o){return !S.locked(s.scene,o);});var gizmoVisible=!!(b&&editable&&['move','rotate','scale'].indexOf(tool)>=0&&s.renderer.kind!=='Simple');gizmoLayer.style.display=gizmoVisible?'':'none';gizmoLayer.setAttribute('aria-hidden',String(!gizmoVisible));if(!gizmoVisible){handles.forEach(function(h){h.g.setAttribute('tabindex','-1');});return;}var basis=axes(),at=K.project(m,b.center),span=(camera.projection==='ortho'?camera.orthoScale:2*camera.distance*Math.tan(camera.fov*Math.PI/360))*80/Math.max(1,height),ends=basis.map(function(axis){return K.project(m,b.center.map(function(v,i){return v+axis[i]*span;}));}),cx=at.x*width,cy=at.y*height;
      handles.forEach(function(h){var axisIndex=['X','Y','Z'].indexOf(h.name),plane=h.name.length===2,visible=at.front&&(tool==='move'||tool==='scale')?h.name!=='XYZ'||tool==='scale':at.front&&axisIndex>=0;h.g.style.display=visible?'':'none';h.g.setAttribute('tabindex',visible?'0':'-1');if(!visible)return;var path='',tx=cx,ty=cy;
        if(tool==='rotate'){var u=basis[(axisIndex+1)%3],v=basis[(axisIndex+2)%3];for(var i=0;i<=48;i++){var a=i/48*Math.PI*2,p=K.project(m,b.center.map(function(n,j){return n+(u[j]*Math.cos(a)+v[j]*Math.sin(a))*span*.8;}));path+=(i?'L':'M')+p.x*width+' '+p.y*height;if(i===6){tx=p.x*width;ty=p.y*height;}}}
        else if(axisIndex>=0){var ex=ends[axisIndex].x*width,ey=ends[axisIndex].y*height;if(Math.hypot(ex-cx,ey-cy)<18){ex=cx+(axisIndex===2?28:0);ey=cy+60;}path='M'+cx+' '+cy+'L'+ex+' '+ey;if(tool==='scale')path+='M'+(ex-4)+' '+(ey-4)+'h8v8h-8Z';else path+='M'+(ex-4)+' '+(ey-4)+'L'+ex+' '+ey+'L'+(ex+4)+' '+(ey+4);tx=ex+9;ty=ey-7;}
        else if(plane){var axesIndex=h.name.split('').map(function(n){return ['X','Y','Z'].indexOf(n);});[[.18,.18],[.38,.18],[.38,.38],[.18,.38]].forEach(function(pair,i){var p=K.project(m,b.center.map(function(n,j){return n+(basis[axesIndex[0]][j]*pair[0]+basis[axesIndex[1]][j]*pair[1])*span;}));path+=(i?'L':'M')+p.x*width+' '+p.y*height;tx=p.x*width;ty=p.y*height;});path+='Z';}
        else{path='M'+(cx-8)+' '+cy+'a8 8 0 1 0 16 0a8 8 0 1 0-16 0';tx=cx-12;ty=cy+24;}h.shape.setAttribute('d',path);h.hit.setAttribute('d',path);h.text.setAttribute('x',tx);h.text.setAttribute('y',ty);h.g.dataset.mode=tool;});
    }
    function presented(scene){if(transition){var k=Math.max(0,Math.min(1,(root.performance.now()-transition.at)/transition.duration)),p=C.studioDirector.ease(k,'ease-in-out'),from=transition.from,to=transition.to;['yaw','pitch','distance','fov','roll','orthoScale','aperture'].forEach(function(key){if(Number.isFinite(from.camera[key])&&Number.isFinite(to.camera[key])){var delta=to.camera[key]-from.camera[key];if(key==='yaw'||key==='roll')delta=((delta+Math.PI)%(2*Math.PI)+2*Math.PI)%(2*Math.PI)-Math.PI;scene.camera[key]=from.camera[key]+delta*p;}});['target','focus'].forEach(function(key){scene.camera[key]=from.camera[key].map(function(v,i){return v+(to.camera[key][i]-v)*p;});});scene.lights.forEach(function(light){var a=from.lights.find(function(l){return l.id===light.id;})||Object.assign({},light,{intensity:0});['position','color'].forEach(function(key){light[key]=a[key].map(function(v,i){return v+(light[key][i]-v)*p;});});light.intensity=a.intensity+(light.intensity-a.intensity)*p;});scene.backdrop.color=from.backdrop.color.map(function(v,i){return v+(to.backdrop.color[i]-v)*p;});['position','scale'].forEach(function(key){scene.card[key]=from.card[key].map(function(v,i){return v+(to.card[key][i]-v)*p;});});['exposure','contrast','saturation','temperature','tint','bloom','halation','vignette','grain','aberration','flare'].forEach(function(key){var a=from.post[key],b=to.post[key];if(Number.isFinite(a)&&Number.isFinite(b))scene.post[key]=a+(b-a)*p;});['lift','gamma','gain'].forEach(function(key){if(from.post[key]&&to.post[key])scene.post[key]=from.post[key].map(function(v,i){return v+(to.post[key][i]-v)*p;});});if(k===1)transition=null;}
      if(isolated){var keep=new Set(E.members(s.scene,Array.from(selection)).map(function(o){return o.id;}));scene.card.visible=scene.card.visible&&keep.has('card');scene.props=scene.props.filter(function(o){return keep.has(o.id);});}
      s.layoutScene=scene;if(shading==='preview'){scene=S.clone(scene);scene.materialTime=0;scene.camera.aperture=0;Object.keys(scene.post).forEach(function(key){if(typeof scene.post[key]==='number'&&key!=='exposure')scene.post[key]=['contrast','saturation'].indexOf(key)>=0?1:0;});scene.post.lift=[0,0,0];scene.post.gamma=scene.post.gain=[1,1,1];scene.props=scene.props.filter(function(p){return !P.isEffect(p);}).map(function(p){p.time=0;if(p.surface==='mirror')p.surface='matte';p.castShadow=false;return p;});scene.lights.forEach(function(l){l.shadows=false;});}else if(shading==='bounds'){scene=S.clone(scene);scene.card.visible=false;scene.props=[];scene.camera.aperture=0;scene.post.bloom=0;}return scene;
    }
    function changed(){if(autosave!==null)root.clearTimeout(autosave);autosave=root.setTimeout(function(){autosave=null;if(dead||s.closing)return;if(s.editing){changed();return;}var saved=S.clone(s.scene);saved.director.playhead=s.director.time;saved.director.preview=s.director.preview;saved.presentationTime=s.lightTime;try{S.saveLast(s.view.instance,saved);s.api.status('Working scene saved.');}catch(error){s.api.status('Working scene could not save: '+error.message);}},4000);}
    function tick(){if(dead||s.closing)return false;var active=!!transition;if(transition)s.dirty=true;var pending=renderThumbnail();record.textContent=s.recordJob?'Stop recording':'Record';record.disabled=!C.studioRecording.supported()||!!s.photoBusy;clipDownload.hidden=!s.clip;return active||pending;}
    function facesChanged(){releaseThumbnails();thumbnails.forEach(function(c){c.width=c.height=1;});thumbnails.clear();thumbQueue=[];s.root.querySelectorAll('[data-style]').forEach(function(b){queueThumbnail(b.dataset.style,b.querySelector('canvas'));});if(presetUI)presetUI.facesChanged();renderLibrary();if(s.galleryRequested&&presetUI){s.galleryRequested=false;presetUI.gallery();}}
    var api={page:page,mode:mode,key:key,down:down,draw:draw,presented:presented,tick:tick,layers:layers,inspected:inspected,changed:changed,facesChanged:facesChanged,context:context,cancel:cancel,select:choose,selection:function(){return Array.from(selection);},fast:function(){return shading!=='material';},resetMood:function(){moodBase=null;moodInput.value=1;dial.value=0;dialHolder.style.setProperty('--light-angle','0deg');},destroy:function(){dead=true;if(presetUI)presetUI.destroy();if(thumbObserver)thumbObserver.disconnect();transition=null;cancel(false);root.clearTimeout(autosave);autosave=null;releaseThumbnails();thumbnails.forEach(function(c){c.width=c.height=1;});thumbnails.clear();thumbQueue=[];if(menu)menu.remove();if(palette){C.accessibility.release(palette);palette.remove();}svg.remove();}};
    s.workspace=api;presetUI=C.studioPresetUI.create(s,{queue:queueThumbnail,tween:tween,invalidate:facesChanged,applied:function(e){api.resetMood();choose(['card']);styles.querySelectorAll('[data-style]').forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.style===e.name));});}});api.presets=presetUI;api.applyPreset=function(e){presetUI.request(e);};api.openPresets=function(kind){presetUI.open(kind);};U.button('Browse',stylesRow,function(){presetUI.open('scene');}).classList.add('studio-style-browse');if(C.dev&&new URLSearchParams(root.location.search).get('gallery')==='presets')s.galleryRequested=true;if(C.commands)commandList().forEach(function(cmd,i){s.cleanups.push(C.commands.register({id:'studio2.command.'+i,label:cmd[0],group:'Studio',hotkey:cmd[1],when:function(){return !dead&&!s.closing;},run:cmd[2]}));});s.cleanups.push(C.contextMenu.registerSurface(function(event){if(dead||s.closing||!s.root.contains(event.target))return false;if(event.target.closest('input,textarea,[contenteditable]')){event.stopImmediatePropagation();return true;}context(event);return true;}));renderLibrary();setTool('select');mode(prefs.mode);return api;
  }
  C.studioWorkspace={create:create};
})(window.Cardable,window);
